### ISSUE TITLE
I can’t select any of my characters for my timeline function.

### ISSUE THREAD

**Issue by PremiumRib** [coppolaemilio/dialogic#1005]
I can’t select any of my characters for my timeline function.

**Describe the bug**
To be honest I don’t know enough about coding to identify the bug. But everytime I can’t select any of my characters even when I can see them on the drop down menu. I’ve restarted the program and even started new projects. Please help!

**Comment by coppolaemilio** [comment]
What version of dialogic are you using?

**Comment by PremiumRib** [comment]
> What version of dialogic are you using?

I’m using v1.4.3

**Comment by coppolaemilio** [comment]
What version of Godot are you using? Not sure why you are having that issue, I need you to share more details.

**Comment by PremiumRib** [comment]
I’m using 3.4.4, 64-bit. This is my first time using this software so I honestly have no I fea what it could be.

**Comment by zaknafean** [comment]
Give us screen shots, examples, a code snippet. Right now we have no way of diagnosing anything.

**Comment by PremiumRib** [comment]
![image](https://user-images.githubusercontent.com/109224848/178753759-e4c6280a-8184-49bb-9d96-d59069803fd0.jpg)

**Comment by zaknafean** [comment]
Nearly positive if you change the name from "Sign Bot-1.png.png" to "Sign Bot-1.png" this will work.

**Comment by PremiumRib** [comment]
I did that and it still doesn’t work :(

I can’t select “User Sample” either and I just changed the name in the box and used the godot icon

**Comment by PremiumRib** [comment]
![image](https://user-images.githubusercontent.com/109224848/178755346-3006b9ca-2494-42c4-bc5a-f79a67cc7849.jpg)

**Comment by zaknafean** [comment]
And after having restarted the editor, and clicking the drop down to select the character, you got the same error again?

**Comment by coppolaemilio** [comment]
Try removing the sprite from your project, naming it something like `SignBot1.png` and use it like that. It might be an issue with the `-` or with the white space ` `

**Comment by PremiumRib** [comment]
No luck still

**Comment by PremiumRib** [comment]
![Uploading image.jpg…]()

**Comment by PremiumRib** [comment]
could it be the file im pulling it from?

**Comment by PremiumRib** [comment]
Did it and it didn’t work

**Comment by PremiumRib** [comment]
I ended up downloading version 3.3.3 and dialogue worked
