### ISSUE TITLE
Godot crashes when selecing a theme

### ISSUE THREAD

**Issue by TheLegendYT1** [coppolaemilio/dialogic#1011]
## The problem

**Describe the bug**
the problem when i click on theme the diolog theme to edit it, godot crashes

**To Reproduce**
1. Go to themes
2. Click on default theme
4. godot crashes

**System (please complete the following information):**
 - OS: windows 10
 - Godot Version: 3.4.4
 - Dialogic Version: 1.4.3

**Comment by zaknafean** [comment]
As of 1.5, default theme is no longer something you can click or interact with directly, which was unintentional technically, but overall a positive thing for the plugin. So this is fixed at this point.
