### ISSUE TITLE
Name Label Position Offset

### ISSUE THREAD

**Issue by LordEwans** [coppolaemilio/dialogic#1036]
The name label in centre mode is not positioned properly, the origin of the name label is 0x0 instead of 0.5x0.5 i.e the origin it's not at the centre of the text label

**Comment by zaknafean** [comment]
Is this in 2.0 or 1.4.x

**Comment by Ewanretor** [comment]
> Is this in 2.0 or 1.4.x

1.4

**Comment by zaknafean** [comment]
This was fixed in 1.5
