### ISSUE TITLE
Allow multiple characters with same name

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1058]
This is important for saving events (mainly character and text).

Also the picker should be improved so that they can be easily distinguished.

**Comment by thebardsrc** [comment]
also mentioned in #1055 while building the 1.x -> 2.0 converter. 

I'm sure im not the only one that currently or future wants to use multiple characters with the same name in different folders, but to copy and paste my specific reasons from the discord:
"so for my RPG its for organization, I got folders for each of the towns and each of the buildings for that town, and like as the game progresses some NPCs are gonna be found in multiple places so I had intended to have a corresponding character for that location. this is mainly for my integrity tester, so it can check each one of the maps and tick of that the timelines, characters, variables, and anythign else i attach to each NPC on that map all exist and have the same uniform path 

for my VN, i'm just using so many portraits that the portraits list was starting to get unweildly, so I broke them up into separate characters by bracnh of the VN, so there's duplicates of a few key characers in each branch's subfolder, with only the portraits for that specific branch assigned to it "

**Comment by MJacred** [comment]
A general rule of thumb is to use IDs in the form of integers and save it to the files. And maybe not stop at characters, but giving everything an ID.  
Also opens up the road to performance improvements.  
If that is desirable, then that would leave the question on whether one global ID counter, or one counter per type (like database tables do).

**Comment by thebardsrc** [comment]
im gonna leave a note here for later, with the get_name added in #1154, I think I actually have an idea on how to implement this.

**Comment by thebardsrc** [comment]
not actually implmeneted yet, #1161 was just preliminary change to make this one possible

**Comment by thebardsrc** [comment]
Oh whoops missed closing this one out with #1207
