### ISSUE TITLE
Rebase Documentation Source code to use less Scenes?

### ISSUE THREAD

**Issue by Sam2much96** [coppolaemilio/dialogic#1061]
**Is your feature request related to a problem? Please describe.**
Sincerest apologies for spamming but the Documentation's source file is convoluted with lots of scenes, singletons and scripts. A complete rebasing of the source code to use less Scenes would help others contribute to the code base more easily. In the mean time, a map of the source code can be useful so new devs aren't intimidated by how interconnected the entire project's source code is

**Describe the solution you'd like**
(1) A map of the source code
(2) A rebase of the documentation to use less Scenes
(3) In code Documentation of each parts of the source code

**Comment by Jowan-Spooner** [comment]
Hey. I was the one mainly making the documentation. But we have removed it from Dialogic 2.0 and will likely move either to the wiki here or an external online documentation because it was hard to keep up-to-date and most people missed it anyways. 

If you are interested in using the scripts and scenes for something else you can of course do that.
But it's very unlikely we will be improving the 1.x version.

**Comment by Sam2much96** [comment]
Do you have a fresh template for it?

**Comment by Sam2much96** [comment]
Again, my sincerest apologies for spamming. The code itself is genius.

**Comment by Sam2much96** [comment]
> Hey. I was the one mainly making the documentation. But we have removed it from Dialogic 2.0 and will likely move either to the wiki here or an external online documentation because it was hard to keep up-to-date and most people missed it anyways.
> 
> If you are interested in using the scripts and scenes for something else you can of course do that. But it's very unlikely we will be improving the 1.x version.

I didn't mean that the code is bad! Don't just remove a feature cuz of me! 😰 A built-in Documentation + wiki+ website is the best combination, it's how Good Documentation should be. I just wanted less Scenes and Singletons so there's less chances of broken dependencies and broken scenes. Not because the idea of a built-in Documentation is bad. Don't go to either extremes, a middle ground solution is best here !
