### ISSUE TITLE
Don't load sub-resources unless needed (store as file paths)

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1087]
The events usually keep direct references to characters or other timelines. This however can cause chain-reactions of loading many, many timelines, and significantly and unnecessarily increase load time.

Resources should only be referenced by path and loaded once needed.

**Comment by Jowan-Spooner** [comment]
@thebardsrc this was adressed in a RP, right? Would you consider it fixed?

**Comment by thebardsrc** [comment]
yeah a few different changes together should have this particular problem addressed. was multiple PR's and several different changes because it was multi-faceted, but should be good to consider this one fixed
