### ISSUE TITLE
Support for Godot Editor's theming system

### ISSUE THREAD

**Issue by Lunadyn** [coppolaemilio/dialogic#109]
**Is your feature request related to a problem? Please describe.**
The colours in Godot's editor can be completely customised.
Dialogic's Timeline and Character Editors don't adapt to this change in colour.

This is especially noticeable in light themes: 
![image](https://user-images.githubusercontent.com/59242420/112426514-2889f600-8d8c-11eb-8139-218895d876b1.png)

![image](https://user-images.githubusercontent.com/59242420/112426453-1740e980-8d8c-11eb-80e3-dadf12d9e618.png)

**Describe the solution you'd like**
Dialogic should use the base colour of the Godot editor.

**Describe alternatives you've considered**
For more customisability, perhaps there should be settings for a theme editor within Dialogic.

**Additional context**
(n/a)

**Comment by coppolaemilio** [comment]
@Lunadyn I made a commit to master with many fixes to support light themes. It is not all fixed but it is much better than before. If you find any particular part that is hard to read or that is not properly styled let me know. (Right now I believe most of the pending issues are icons)

**Comment by Lunadyn** [comment]
Looking good, thanks for the update!

Several things I noticed that may need fixing:

- The Dialogic logo is still white in the light theme:
![1](https://user-images.githubusercontent.com/59242420/112850834-18f50f00-90f6-11eb-818b-393bcbed6c07.png)

- The contrast on the 'Default' placeholder text in the Portraits/Expressions section of the Character editor is a bit too low:
![2](https://user-images.githubusercontent.com/59242420/112850916-3033fc80-90f6-11eb-839a-53c64ec2306f.png)

- Perhaps I'm missing something, but switching back to Godot's default dark editor theme results in this:
![3](https://user-images.githubusercontent.com/59242420/112850986-417d0900-90f6-11eb-9ad2-9c87f20dc35e.png)

**Comment by coppolaemilio** [comment]
The first 3 will be fixed, but the last one unfortunately isn't. When you change theme you have to reset your editor or the plugin for it to work properly, I don't think there is a way around it since it only gets initialized once and then is when the new settings are applied. Thanks for the screenshots!
