### ISSUE TITLE
Changing how TimelineEditor keeps data for suggestions

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1097]
With the change in #1096 killing the recursive checks, I believe this breaks how it checks for suggestions for the UI elements of the TimelineEditor. So Timelines, Labels, and maybe Characters will need to have their own separate lists kept for this.  I don't think we want to save them to the Project Settings, so we'll want to either save them to their own file or regenerate them at runtime, in a way that won't lock the main Godot thread and prevent it from loading the rest of the folder tree ( see #1093 ). 

My initial thought, before digging into how the editor's node builders work, is something like just a simple Dictionary with a key of an array of all of the timeline filenames, and values being any labels in that key as well as the beginning of the timeline. Then when saving the timeline, just rebuild that one timeline's key

**Comment by thebardsrc** [comment]
So I have Jump in the TimelineEditor turned to just a text field temporarily, while figuring out this fix. I don't have any more time tonight to try and code it up myself

![image](https://user-images.githubusercontent.com/2214793/183276545-290825f4-1382-4149-8fa9-27ea6d30a774.png)

The current get_timeline_suggestions() function looks solid to me. only problem I see - aside from the resource having to be loaded and holding up memory, adding to the pool of orphaned resources (which I have tried looking to see where I can reduce but its still massive in the dump when closing Godot) -  is that since this is part of the jump _event_, it was called every time one was created. So for my debug timeline in my VN, for example, where I have six different branches based on different choices, this function would run six times. having to re-index the entire project six times just to load that timeline into the editor, as it uses `DialogicUtil` to do it and that is a static class. since this is only actually needed in-editor, the list should be generated in the top EditorView level, and rebuilt only when a timeline is saved or deleted or moved

![image](https://user-images.githubusercontent.com/2214793/183276781-5a6f58bc-185d-4118-8a9c-0bfaee0be511.png)

This one's going to be rougher to deal with, since it's actually loading the timelines as Resources to find the list of labels. it _can_ be done that way, although that's rather overkill to make it load and process them every time you switch the timeline choice because of how intensive loading the resource and processing it is in general. as I put forh in my first post, ideally they would be stored together with the timelines in the master list and updated only if they're changed. that does require front-loading them too, though, to build that list. alternatively, we could 'lite' load the timeline to crawl it for labels,  opening it as just the file instead of as a resource and reading the text line-by-line checking against the shortcode regex to see if a label is in the line. I  believe that would be somewhat faster than loading the timeline as a Resource, and it would _definitely_ be much less memory intensive and not leaving a ton of Objects sitting in the memory pool, as the sheer number of Objects that the Dialogic plugin is creating during runtime seems to be - combined together with the general alpha nature of Godot 4 right now - causing a lot of crashes

**Comment by Jowan-Spooner** [comment]
> only problem I see [...] is that since this is part of the jump event, it was called every time one was created. So for my debug timeline in my VN, for example, where I have six different branches based on different choices, this function would run six times.
Actually I'm pretty sure this is only run if you click on the dropdown of the TimelinePicker on the Jump event.

**Comment by thebardsrc** [comment]
yeah i think i saw that the next day when i looekd back at it, it was late when I put that in lol

**Comment by Jowan-Spooner** [comment]
I will close this. The only picker that isn't working/existing now is the Label picker. It will be tricky to re-implement without hurting performance, but probably possible.
