### ISSUE TITLE
2.0 Empty Timeline / Timeline Erasing Bug

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1106]
Need some proper handling for if a timeline file loads successfully, but it is empty and so no Event nodes created. Right now it just sits there doing nothing, with no indication that anything happened.

I discovered this tied together with another, bigger issue. One of my timelines just completely got erased, replaced by an empty file.  I'm not sure what exactly had led to it, but I did have it open in Editor. Can't recreate it right now, will need to thoroughly go over the Editor and game Timeline loaders to make sure everything is robust.

**Comment by Jowan-Spooner** [comment]
It's pretty likely that the timeline erasing happened because of the weird two time saving of both timeline editors. It should not happen anymore now, but oc it could've been something else. Think this should be split into two or edited. 
A) is a UI/UX issue
B) is a bug

**Comment by coppolaemilio** [comment]
I got the timeline erasing bug while simply toggling the visual/text editor button. I don't remember exactly the steps I followed or if these were the errors that caused it, but I'll leave a screenshot of the output screen here:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/2206700/189458674-dab18810-52fc-4c90-8789-0be3298bf883.png">

**Comment by thebardsrc** [comment]
i saw that case a couple days ago too, and was trying to narrow it down to figure it out but didn't find it yet. something to do with whatever's triggering that first error, puts the object in memory in a state that then the editor can't read it, i might be able to try cheking it out in a bit 

that last error I added as a safety check so the actual file itself doesn't get overwritten like this, so if you were able to close and reopen Godot and it was fine then at least that works as intended

**Comment by Jowan-Spooner** [comment]
I'm going to close this. If this happens again, we can reopen this or create a new issue, both are fine. For now, this isn't a necessary problem to track imo.
