### ISSUE TITLE
Overlock.tres has bad reference to Overlock-Black.ttf

### ISSUE THREAD

**Issue by todd-koeck** [coppolaemilio/dialogic#1109]
## The problem

[addons/dialogic/Example Assets/Fonts/Overlock/Overlock.tres](https://github.com/coppolaemilio/dialogic/blob/28c5b9feeb1705abc64303e46de7b1c0e0a0d5a9/addons/dialogic/Example%20Assets/Fonts/Overlock/Overlock.tres) references res://Fonts/Overlock/Overlock-Black.ttf when it should reference res://addons/dialogic/Example Assets/Fonts/Overlock/Overlock-Black.ttf.

**To Reproduce**
Run a simple dialogue as described in the tutorial and you'll see:
```
ERROR: Cannot open font file 'res://Fonts/Overlock/Overlock-Black.ttf'.
   at: _load (scene/resources/dynamic_font.cpp:143)
```
in the output.

**Expected behavior**
No error messages, :-).

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.5
 - Dialogic Version: 1.4.4

## Solutions
Reference the Overlock-Black.ttf font in the correct directory.

**Workaround**

I didn't notice any problems caused by it, so no workaround is necessary.

**Possible fixes**

See solution.

**Comment by zaknafean** [comment]
Ya it doesn't crash it, but its an easy fix and makes things less sloppy. Making the fix as you pointed out. Fixed in #1128
