### ISSUE TITLE
2.x Registering User-Provided Text Processing Routines

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1112]
Thank you for the reply! Updating the contents of the timeline outside of it seems to be the way to go, then. Quick question: Is it possible to change the content of a timeline at runtime besides changing the value of variables/values? Could I for example at runtime from another script loop through all of my timelines and replace all words in text events enclosed with <<>>? Reason I'm asking is that making a value for every word which might need to be modified would be rather time consuming. I do recognize that it's kind of a niche and/or overkill thing to need a dialogue editor to do though ^^'

_Originally posted by @Lumina-0 in https://github.com/coppolaemilio/dialogic/discussions/1110#discussioncomment-3393861_

**Comment by thebardsrc** [comment]
Making this for a feature request for myself to look into later, for adding the ability for a user to register other functions that can run custom replacement rules on text events on timelines, in addition to the other replacement rules Dialogic already provides (variable value, random words, and such). Setting as 2.x because idk when I'll get to it, unless someone else wants to do it sooner

**Comment by Jowan-Spooner** [comment]
This is possible now with the modular text modifiers (which do exactly this: get the text, modify it, return it).
