### ISSUE TITLE
Not all the "label" appear in the "go to".

### ISSUE THREAD

**Issue by jtbarts2021** [coppolaemilio/dialogic#1119]
not all the "label" appear in the "go to".
![imagen](https://user-images.githubusercontent.com/111250151/184554802-c29ffa56-d050-441e-9b83-20e2f0dc942a.png)

**Comment by carlosfruitcup** [comment]
This is issue is still present in 1.5 by the way

**Comment by zaknafean** [comment]
Fixed in #1940 1940
