### ISSUE TITLE
Character Offset broken

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1120]
@thebardsrc I think this came from your changes. I'm getting an error in the Portraits subsystem change_portrait() method:
```
	$Portrait.position.x = character.portraits[portrait]['offset']['x'] * character.portraits[portrait].scale *character.scale
	$Portrait.position.y = character.portraits[portrait]['offset']['y'] * character.portraits[portrait].scale *character.scale
```
It says there is no offset. I think you should use `.get('offset', Vector2())`. Also the offset is stored as a vector not as two values if I'm not mistaken

Edit: Other values are also assumed to be in portrait dictionary when they are not: scale, mirror

Edit: Also this line seems to multiply the scale twice, not sure why:
![grafik](https://user-images.githubusercontent.com/42868150/184606489-04db430d-8f9f-4fc4-8f9c-b7888b92d768.png)

**Comment by thebardsrc** [comment]
Ok, yeah I suspected I screwed up a few things there getting the scale and offsets right, since theres both a global scale and individual scales and offsets per-portrait. I'll get these together with the other portrait things I'm working on right now.
