### ISSUE TITLE
Name alignment not properly centered in 1st line of dialogue

### ISSUE THREAD

**Issue by meyaoigames** [coppolaemilio/dialogic#1126]
When you use centered name alignment, in the1st dialogue line that is shown, the name label is not properly centered.

1st line:
![image](https://user-images.githubusercontent.com/58981156/185044171-3f107354-e9a4-4a34-8a68-419028b62b41.png)

2nd line:
![image](https://user-images.githubusercontent.com/58981156/185044223-610e9900-21b7-4b30-a40d-32dad367c94e.png)

EDIT: Managed to sort of fix this by just moving the name_label.visible = true at the end. 
![image](https://user-images.githubusercontent.com/58981156/185071116-9a9c65ca-92a2-45af-a27e-05109e8e27b4.png)

**Comment by zaknafean** [comment]
That simple? Want to make a PR for it if you're up to date? Otherwise I'll implement the fix

**Comment by meyaoigames** [comment]
Yup, it's only that. I honestly am pretty new to GitHub, so I don't really understand how to make a pull request. Please feel free to do so!

**Comment by zaknafean** [comment]
Gotta love when a fix is easy, effective, and easy to test. Tested it out fixing the problem in my game too. #1127
