### ISSUE TITLE
First emit signal is only signal fired in timeline

### ISSUE THREAD

**Issue by wcbx** [coppolaemilio/dialogic#1131]
## The problem

**Describe the bug**
Adding two "emit signals" to a timeline and online the first signal is fired.

**To Reproduce**
Make a timeline. Emit a signal. Call it "whatever A". then make a few dialog texts pop up. Then Emit another signal called "Whatever B". Create a node with a script as a child of the dialog node. Connect the dialogic event to that child node and print out the value from the events. When you run the game it will only fire "Whatever A." However, when you click "Play Timeline" the debug output will report both events are fired.

**Expected behavior**
You would expect both Whatever A and whatever B signals to be fired.

**System (please complete the following information):**
Windows 10, Godot 3.5, Dialogic v1.4.4

**Comment by wcbx** [comment]
It wasn't firing _process. That's why.

**Comment by Jowan-Spooner** [comment]
> It wasn't firing _process. That's why.

So is this fixed?

**Comment by wcbx** [comment]
yes
