### ISSUE TITLE
Russian letters are not displayed in the dialog box

### ISSUE THREAD

**Issue by Aegel5** [coppolaemilio/dialogic#1136]
## The problem

**Describe the bug**

**System (please complete the following information):**
 - OS: [Windows 11]
 - Godot Version: [3.5]
 - Dialogic Version: [1.4.4]

![1](https://user-images.githubusercontent.com/10333681/185594260-dec77037-3870-4d3e-acdb-dbbd26143d1e.png)
![1](https://user-images.githubusercontent.com/10333681/185594572-b4308efa-a5a1-4713-afd5-de77a422ca44.png)

**Comment by Aegel5** [comment]
I changed the font and it worked

But maybe this situation need add to the FAQ or change the default font.

**Comment by Jowan-Spooner** [comment]
In 2.0 we use the built-in font I believe. I think it supports most common letters, but I haven't tried yet.
