### ISSUE TITLE
Remove name property of character resource

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1137]
The name property is redundant. We always use the file name or display name now.

**Comment by thebardsrc** [comment]
For further reference, see the images in #1123. In converted characters at the moment, the name field has the converted 1.x name. The first image has the filename they were converted to, which works fine playing the timeline, but then the timeline editor is using the name field to save edited timelines, so it changed it in the second image to a way that doesn't work actually playing the timeline.
