### ISSUE TITLE
Errors that happen when using Dialogic 2.0 for the first time

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1155]
Right after you copy-paste the `/addons/dialogic` folder to your project (even before enabling the plugin)

<img width="898" alt="image" src="https://user-images.githubusercontent.com/2206700/186535290-36a4652e-e54f-47bd-a3f2-72a513d62866.png">

After enabling Dialogic from the plugin menu:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/2206700/186535429-a47debc4-0b04-4b1c-b254-e66824c332e3.png">

After rebooting the editor 

<img width="1420" alt="Screen Shot 2022-08-25 at 00 35 35" src="https://user-images.githubusercontent.com/2206700/186535561-bb4fd3d0-d5c7-42d5-aa84-09461a0a521b.png">

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/2206700/186535607-84d8ae51-07c0-4976-a006-767367226fdb.png">

They keep happening after any reboot.

**Comment by coppolaemilio** [comment]
When trying to run a simple timeline for the first time 
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/2206700/186536258-16a70b9e-02c7-47c8-bdba-f8d49943f279.png">

**Comment by coppolaemilio** [comment]
We can safely ignore this error:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2206700/186539238-e89f06a0-aff8-47a6-a0d7-ae490fc32e83.png">

It will be fixed in upcoming alphas: https://github.com/godotengine/godot/pull/64233

**Comment by coppolaemilio** [comment]
Most of the errors seem to be originating at a Godot level, so I will leave this here until they get fixed. Not sure the timeline on those, but hopefully during Beta.

**Comment by coppolaemilio** [comment]
As of alpha 2, the first time you enable dialogic:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/2206700/189459732-4bb6df02-4895-40c2-8c59-7f86bc0f8c0a.png">
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/2206700/189459738-55831c48-9ee6-45ae-974a-b97614222ea3.png">

Without touching anything, after a restart:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/2206700/189459784-66bd043a-0cf1-4100-9f86-4a146332fcb5.png">

These last ones persist no matter the amount of restarts.

**Comment by thebardsrc** [comment]
on that last one... since Godot has a SVG file now by default, that would be why it's getting that error... but why is AddEventButton.tscn trying to reference the icon.png to begin with...

**Comment by coppolaemilio** [comment]
Yeah, I don't know where we left that reference, but I'll probably be able to find it using a global search on the project.

**Comment by thebardsrc** [comment]
taking a look at the .tscn now, it looks like it's set as the default image on the TextureRect in the scene. the script to add it then overrides it. the scene will need to eb updated to use an image in the addons/Dialogic folder instead

**Comment by coppolaemilio** [comment]
No big issues on the latest version
