### ISSUE TITLE
Missing actions when loading the plugin [2.0 alpha 1]

### ISSUE THREAD

**Issue by delleloper** [coppolaemilio/dialogic#1158]
Only _background_ and _call node_ actions are visible when loading the plugin, and icons look huge

![image](https://user-images.githubusercontent.com/17836214/186675274-4408d0f5-c728-4344-8832-ec956b304ca1.png)

After reloading godot all appears, but icons remain giant
![image](https://user-images.githubusercontent.com/17836214/186674903-a9d43aa6-4c51-4407-9c1b-43fb433e2b79.png)

 - OS: Windows, Linux 10
 - Godot Version: 4 alpha 14
 - Dialogic Version: alpha1

**Comment by thebardsrc** [comment]
so the first part where it doesn't show up is unfortunately something that cant be avoided, Godot has to be reloaded to completely load the plugin after installing and enabling it

the icons being big thing, I don't remember offhand, but I believe I remmebred seeing something about that being a Godot bug that a fix was merged recently? so hopefully the next Godot alpha should have that resolved

**Comment by Jowan-Spooner** [comment]
Maybe we can close this? The icons are fixed I think, the reload cannot be worked around I think.
