### ISSUE TITLE
Improve Character Event "Leave All" option UI

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1169]
Currently to make all characters leave, you have to toggle a hard to find toggle and not select a character. ALL shoukd be an option on the dropdown.

**Comment by thebardsrc** [comment]
IIRC, "Leave -All-" is the actual text command for it. It sets the boolean of `_leave_all` on parsing the script, the boolean's not meant to be used directly. But I also couldn't get '-All-' to appear in the Charcater picker

**Comment by thebardsrc** [comment]
Adding the -All- is easy enough now I could do it, but I'm not gonna close this out yet because I still want to do some rework of ComplexPicker before release, so I'll wait to add that in along with that
