### ISSUE TITLE
Proposal: Rename theme event and node to "layer"

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1172]
The theme event and node currently don't work like they do in 1.x, *although they can be used to achieve a similar effect*. 

**How they currently work in 2.0 is more like this:**
Using Change Theme will show all nodes in "layers" (DialogicDisplay_Theme nodes that have that name configured and all they children). All other "layers" will hide. Nodes that aren't decendants of a layer node won't be effected. Themes are not involved in the node or event.

**Comment by Jowan-Spooner** [comment]
We decided to rename the concept to `Style`.
Meaning: `Change Style` Event a `DialogicNode_Style` node and `Subsystem_Style`

**Comment by thebardsrc** [comment]
Implemented in #1231
