### ISSUE TITLE
Add a button to edit the current character selected from character events.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1174]
When you are on a timeline and you want to quickly jump to edit a character you have selected in a Character event, there is no easy way to go there, you have to search for the file in the filesystem tab and open. There should be an easier way to start editing it from the timeline editor.

**Comment by thebardsrc** [comment]
I'll get this along with my changes to implement #1058, since I gotta make changes to the picker for that anyway
