### ISSUE TITLE
Event properties are not properly vertically aligned

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1175]
You can see here the `Hide text box` label being higher than the rest of the elements

<img width="447" alt="Screen Shot 2022-08-28 at 18 54 26" src="https://user-images.githubusercontent.com/2206700/187085586-019f923b-d134-4cc0-826f-0733e270f91d.png">

**Comment by Jowan-Spooner** [comment]
I think this is mostly fixed. If you find more instances of this, feel free to reopen or create another issue.
