### ISSUE TITLE
Condition with String fails I believe

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1178]
Note for me to investigate a situation like this 
![grafik](https://user-images.githubusercontent.com/42868150/187270154-90b19f2f-9e05-48a9-9c44-283707837c82.png)
resulting in 
![grafik](https://user-images.githubusercontent.com/42868150/187270338-574cc2b7-eeb5-4c92-9f79-55fa36994ead.png)

**Comment by coppolaemilio** [comment]
I've been trying some conditions and they are a bit broken. They also get transformed weird to text, but I'll try to report it better when I have a proper timeline to test against.
