### ISSUE TITLE
ComplexPicker only saves on Enter 

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1179]
The complex pickers saving behaviour is not optimal.

When you type in a complex picker and then just click away, it won't be registered as a change and thus not save.

**Comment by thebardsrc** [comment]
im not sure that this shouldnt be expected behavior, though. If you're clicking away from it without enter or clicking on one of the options, that's cancelling the action of using the picker, it should stay what it was at before

**Comment by Jowan-Spooner** [comment]
From what I can tell this is fixed. If someone wants some changes on the pickers behavior, just create another issue.
