### ISSUE TITLE
TextEdit mode: How to know all possible event parameters

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1182]
When writing in text edit mode, I often forget how a shortcode parameter is called. 
I find myself switching to the visual editor changing one setting and then going back. It would be cool if there either were some sort of suggestions/auto-completions or a easy way to see all possible parameters. 
Maybe have a sidebar with the events similar to the visual editor but selecting/hovering a event button just shows some small info on the parameters?

**Comment by coppolaemilio** [comment]
Autocomplete should be added, yes. It would be nice to read the data from the existing events for custom ones, but we can do a simple hardcoded lists at the moment and update it later

**Comment by Jowan-Spooner** [comment]
It should be "relatively" easy to get all the parameters and shortcode texts from the events with the `get_shortcode()` and `get_shortcode_parameters()` methods.
