### ISSUE TITLE
Reimplement History feature for 2.0

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1185]

**Comment by thebardsrc** [comment]
Leaving a note for here, when this gets implemented, it needs to be structured internally with data structure that allows for being able to use it for other functions as well as just the last text messages: for example actually adding rollback support for VN use, or can be quickly split per-character into separate histories the way Disco Elysium does (as requested by a Discord user). With which options needed, as well as the max size of the history, be settings

**Comment by thebardsrc** [comment]
Currently being worked on in  #1219
