### ISSUE TITLE
Do basic calculations on timeline

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#119]
**Is your feature request related to a problem? Please describe.**
When making a choice heavy game, I need to keep track of values representing the state of the player (representing for example a percent of goodness), which evolve depending on choices, and change dialogs depending on the value. Right now the only way to change variables is to set them to constant value. So to make computations, I must emit a signal, and get/set variables from an external script.

**Describe the solution you'd like**
A clean way to allow this would be to create a *computation* node, allowing to take one variable and a constant, or 2 variables, make a basic computation between the 2 (`+`, `-`, `*`, `/`) and to store the result in an other variable. Like with `if`, we could check if all values are valid number to convert them before the computation.

**Comment by coppolaemilio** [comment]
I would modify the `Set Value` event to allow adding, removing, etc.. instead of creating another event. 
So it would be something like
`Set value [goodness] [add] 10`
`Set value [goodness] [remove] 4`
`Set value [goodness] [multiply by] 5`
`Set value [goodness] [divide by] 2`
`Set value [goodness] [to be] 0`

**Comment by arnaudvergnet** [comment]
Yes that would be simpler, but how would you implement this without breaking current timelines?

**Comment by coppolaemilio** [comment]
I would check if the data has the key "operation". If it doesn't I would assume it is `=` and if it does then you can populate with the new options. Not 100% sure about adding two different variables but it could work similarly.
