### ISSUE TITLE
Dialogic 1.4.5 not working on my Android device (using Godot 3.5)

### ISSUE THREAD

**Issue by yohannes-jo** [coppolaemilio/dialogic#1193]
## The problem

Dialogues simply don't start at runtime, it works on Desktop releases though.

**To Reproduce**
- Create a new project.
- Add dialogic, a timeline, characters(if you want), and just let it load on runtime.

**Expected behavior**
It should start the dialogue as it opens immediately

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.5stable
 - Dialogic Version: 1.4.5

**Comment by zaknafean** [comment]
Going to need a bit more than that. I have a 1.4.5 project that is running well on android. Are you using the DialogNode, or starting it via script?

**Comment by yohannes-jo** [comment]
> Going to need a bit more than that. I have a 1.4.5 project that is running well on android. Are you using the DialogNode, or starting it via script?

I add the dialog node found in the add-ons folder, give it a simple timeline I made to test if it works (I do that in node options on right side of the viewport, not in script), then exported it to my device.

Keep in mind that it works PERFECTLY well on my desktop, no problems there. It just doesn't appear on my Android device.

**Comment by yohannes-jo** [comment]
> > Going to need a bit more than that. I have a 1.4.5 project that is running well on android. Are you using the DialogNode, or starting it via script?
> 
> I add the dialog node found in the add-ons folder, give it a simple timeline I made to test if it works (I do that in node options on right side of the viewport, not in script), then exported it to my device.
> 
> Keep in mind that it works PERFECTLY well on my desktop, no problems there. It just doesn't appear on my Android device.

I wanted to be sure that the dialog wasn't actually appearing but would be way to the sides as a result of screen resolution so I toggled the text sound to on, no sound from that too

**Comment by zaknafean** [comment]
Perfectly from the editor, or does it also work when you export to windows?

Did you also remember to add this to your android export?
![image](https://user-images.githubusercontent.com/7741797/187471861-d64968de-fef8-41d5-9cd2-aa9b17af30c5.png)

**Comment by yohannes-jo** [comment]
> Perfectly from the editor, or does it also work when you export to windows?
> 
> Did you also remember to add this to your android export?
> ![image](https://user-images.githubusercontent.com/7741797/187471861-d64968de-fef8-41d5-9cd2-aa9b17af30c5.png)
> 
> Android is very particular, and we can't automate the export file types effectively on that platform.
> 

This solved it! Thank you so much, didn't know .json and .cfg files should be added as an exception
