### ISSUE TITLE
Proposal: rename DialogicDisplay_* nodes to DialogicNode_*

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1196]
# Why
The use of the word Display, makes you think of visual nodes. However these nodes range from visual, audio, input to holding nodes. Thus this terminology can be quite misleading. 

# What
As written in #1184 I suggest renaming DefaultDialogNode to DefaultScene. After that is done, DialogicDisplay_***** could be changed to DialogicNode_***** . This should be done on the scene, script and class names. I'm open for other suggestions, this is what we could come up with so far.

We should decide this asap, before people start using these, as renaming them will break already built scenes.

**Comment by coppolaemilio** [comment]
Yes, it makes sense to call them DialogicNode now that we have many kinds of nodes.

**Comment by coppolaemilio** [comment]
Closed by https://github.com/coppolaemilio/dialogic/commit/a19d2c8d2a33dac1f1641bebc837fed7cb49582d
