### ISSUE TITLE
Documentation links are all broken

### ISSUE THREAD

**Issue by DethRaid** [coppolaemilio/dialogic#1197]
## The problem

**Describe the bug**
The links in the README and in the wiki don't go to any useful pages

**To Reproduce**
1. Go to 'https://godotengine.org/asset-library/asset/833'
2. Download the package
3. Unzip the package
4. Notice the README.md
5. Open the README
6. Observe a link to https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Documentation/Content/Tutorials/BeginnersGuideStepByStep.md
7. Click on that link
8. Observe a 404

***Alternate repro steps***
1. Go to the project wiki https://github.com/coppolaemilio/dialogic/wiki
2. Scroll down to the Tutorials
3. Notice Beginner's Guide
4. Click on the link https://github.com/coppolaemilio/dialogic/wiki/Tutorials/BeginnersGuideStepByStep.md
5. Observe that there's no page at that address so GitHup asks me to write the beginner's step-by-step guide?

**Expected behavior**
I expect that the links you provide in your README and your wiki will lead to pages that exist

**Screenshots**
N/A just click the above links and observe the issues

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.5
 - Dialogic Version: 1.4.5

## Solutions

**Workaround**

Idk??? I tried going to the wiki when the link in the README didn't work but was not able to find the documentation I needed. i guess I could scour the wiki and hope that I stumble upon the right page?

**Possible fixes**

You should either update the links to point to documentation pages that exist, or write documentation pages and put them in the place of the links

**Comment by Jowan-Spooner** [comment]
Hi, thanks for letting us know.

This is a result of us starting to update the wiki for dialogic 2. Also some links seem to be broken due to the 1.x branch not being main anymore. I will try to fix the broken links. 

You can find the old documentation both offline in the editor (at the bottom of the resource tree) or online [here](https://github.com/coppolaemilio/dialogic/tree/dialogic-1/addons/dialogic/Documentation/Content).

**Comment by Jowan-Spooner** [comment]
Alright I've updated the links in the readme. Also I've updated the welcome page of the wiki to mention that is not for the 1.x branch anymore.
