### ISSUE TITLE
Proposal: rename timeline._events to timeline.events

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1198]
The events property of timelines currently starts with a _. This seems to tell me, I should not access it from outside. This is done all the time though, both in editor, and probably by people who want to create timelins through code.

Either we need to change the way this is accessed, or I would consider renaming it.

**Comment by coppolaemilio** [comment]
Agreed 👍

**Comment by coppolaemilio** [comment]
Fixed as of https://github.com/coppolaemilio/dialogic/commit/e8328ec96619c1deeceed902b34dc2d61a0c63ef

Also renamed `_events_processed` for the same reason
