### ISSUE TITLE
Proposal: rename event custom saving methods

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1200]
The methods in question are 
- get_as_string_to_store(), 
- load_from_string_to_store(),
- is_valid_event_string()

They are very complicated, not very intuitive and so similar that you can mix them up. On the other hand, they will rarely be used by users as shortcodes work fine for most events.

**Comment by coppolaemilio** [comment]
Closed by https://github.com/coppolaemilio/dialogic/commit/3e6c8248875f57615ec79d839b0eb988ab161936
