### ISSUE TITLE
Both Editors Building Editor Events

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1206]
Both text and visual editors are building the event nodes, text editor doesn't need them and its extra resources that are going to be taking up memory, which lead to tons of orphaned resources on close, and seem to at least be in part stability issues with alpha versions of Godot 4

Should probably actually be implemented as a flag for whether you want them built or not, which then could also be used for #1101 to allow building a timeline editor at runtime as requested there.

**Comment by Jowan-Spooner** [comment]
`build_event_editor()` is called because we (for whatever reasong) decided to override `_get_property_list()` instead of creating our own method. I think that is called. 
I do not think that actual nodes are created on the text editor tho, but oc I could be wrong.

**Comment by coppolaemilio** [comment]
We can create our own method. We were using the `_get_property_list` one to show in the inspector, but we don't use the inspector for it any more.

**Comment by thebardsrc** [comment]
> I do not think that actual nodes are created on the text editor tho, but oc I could be wrong.

i found in debugging on #1207 that they were, and also on runtime as well (which I put in a check to disable). there not adding to anything, but they are being created by the event creation itself

**Comment by Jowan-Spooner** [comment]
huh? but how? only the EventNode.tscn actually adds any input field nodes. And that scene is only created by the VisualTimeline editor.
