### ISSUE TITLE
checkbox to "clear characters" on the jump event

### ISSUE THREAD

**Issue by exelia-antonov** [coppolaemilio/dialogic#1209]
add a checkbox to "clear characters" on the jump event. we don't want them always leaving because you may want to do a jump and preserve the character state, but optionally a cleanup step like that is handy

all the Leave actions are part of the Character event, rather than the Portrait Subsystem, so there's no direct way to call it there. but also because of that, would be super simple to implement, just needing a few lines at the beginning of Jump event's _execute():

- duplicate the Character event from the event cache
- set it to ActionType.Leave
- set _leave_all to true
- _execute() it 
- then proceed with the rest of the jump

**Comment by Jowan-Spooner** [comment]
Wouldn't it be cleaner to implement a leave_all method on the Portraits subsystem? Because then you could very easily call it from outside as well (e.g. Dialogic.Portraits.leave_all()) or remove_all() alternatively.

**Comment by coppolaemilio** [comment]
After considering it, maybe it is better that the user deals with clearing the screen if they want to.

**Comment by Jowan-Spooner** [comment]
Yeah, I think it's a nice thing to have but not very important as a simple `Leave --All--` before the jump or at the beginning of the next timeline does the same. Also if we add a clear option it should probably remove backgrounds, styling and music as well.

**Comment by coppolaemilio** [comment]
Yes! 
Reset the background, characters, swap to the default theme and... I can't think of anything else?

**Comment by Jowan-Spooner** [comment]
I think I'm against implementing this on the jump event. Because jumping does not at all need clearing most of the time. I'd rather consider a clear event that actually calls a version of Dialogic.clear() (without clearing timeline info and variables).

**Comment by coppolaemilio** [comment]
A clear event seems like the best solution. That way we keep each event as minimal as possible.

**Comment by Jowan-Spooner** [comment]
I'll close this in favor of #1699
