### ISSUE TITLE
Project Settings Saving

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1217]
None (or nearly none) of the Project Settings actually save currently, so they are never being changed when settings are changed. 

anywhere where there's a `ProjectSettings.set_setting()` call, a `ProjectSettings.save()` needs to come after it so it actually saves the changes to `project.godot`. They're not getting saved and changes aren't applying when running a project otherwise.

**Comment by coppolaemilio** [comment]
I made changes at https://github.com/coppolaemilio/dialogic/commit/04e789188c4906f618919a500f1373f75108dcc6 but I haven't tested properly. Let me know if that fixed the issues!
