### ISSUE TITLE
Can't seem to save timelines in Godot 4.0 A16, Dialogic 2.0 A1

### ISSUE THREAD

**Issue by assertchris** [coppolaemilio/dialogic#1220]
## The problem

**Describe the bug**
When I create a timeline, I cannot save it.

**To Reproduce**
1. Create a couple characters
2. Create a timeline
3. Try to save timeline (cmd + s?)
4. See error in console 
5. Switching to text editor and back erases visual editor contents6. 

**Expected behavior**
I expect the timeline to save

**Screenshots**
<img width="862" alt="Screenshot 2022-09-12 at 08 38 34" src="https://user-images.githubusercontent.com/200609/189589001-7425fc38-97a2-44b3-8904-4b8321489511.png">

**System (please complete the following information):**
 - OS: macOS 12.5.1
 - Godot Version: 4.0 alpha 16
 - Dialogic Version: 2.0 alpha 1

## Solutions

**Workaround**

I tried changing what was in the timeline, but the error seems to be the same no matter what I put in it.

**Comment by assertchris** [comment]
Yes, sorry that I didn't lead with that: https://github.com/assertchris/godot-experiments

**Comment by coppolaemilio** [comment]
I think it should be resolved if you use the latest version from `main` since Godot Alpha 16 broke/rename some things

**Comment by assertchris** [comment]
Sorry for the confusion. I downloaded alpha 2, but the internal version seems to read alpha 1. This is on the latest version of both that I could download; but I'll try main and let you know what I find :)

**Comment by coppolaemilio** [comment]
> would it be ok for me to mention Dialogic in a book about [procedural content generation with Godot 4](https://www.amazon.in/Procedural-Generation-Godot-Generate-Enjoyable/dp/1484287940)?

Of course! I hope that we can get it stable soon so that people can start using it without issues 😅

**Comment by thebardsrc** [comment]
alright, found your issue!

there's a variable set on the timeline to only go through saving if something's actually been changed. it was renamed at one point, and everywhere but two places got it updated

it'll be included in an update, but if you want to manually fix it in the mean time its this file, lines 110 and 112. remove the underscore before `events_processed`
![image](https://user-images.githubusercontent.com/2214793/190045867-225bba76-8920-4d8d-8a27-82a529a66247.png)

**Comment by thebardsrc** [comment]
Fixed by #1223
