### ISSUE TITLE
Allow the events sidebar in the Timeline editor to be resized manually or automatically

### ISSUE THREAD

**Issue by Lunadyn** [coppolaemilio/dialogic#123]
**Is your feature request related to a problem? Please describe.**
At the moment, the events sidebar in the Timeline editor cannot be resized.
This may be an issue with DPI scaling, but event names are cut off and require scrolling for me:
![0](https://user-images.githubusercontent.com/59242420/112851331-9d479200-90f6-11eb-941f-0a321367cfb4.png)

**Describe the solution you'd like**
The width of the events sidebar should automatically resize to fit the event names, or should allow for manual resizing by the user.

**Describe alternatives you've considered**
(as above)

**Additional context**
(n/a)

**Comment by Jowan-Spooner** [comment]
@coppolaemilio This seems to already been nearly implemented. The only thing I had to change for it to work was to remove the custom separation on the main node of the TimlineEditor. Is there a reason for this?

The separation disabled:
![grafik](https://user-images.githubusercontent.com/42868150/113864461-35a2de00-97ab-11eb-849b-790ef616b353.png)
