### ISSUE TITLE
Adding new timelines is unbelievably slow at scale

### ISSUE THREAD

**Issue by Tummyache** [coppolaemilio/dialogic#1239]
## The problem

**Describe the bug**
Adding or removing timelines gets excessively slow after a large number of timelines (over 250) have been added.  Currently it's taking over 10 seconds to add or rename a timeline.  When adding a new timeline, Godot completely freezes and my CPU spikes from <1% to over 10%.

**To Reproduce**
1. Create 5 Folders
2. Create 10 Folders inside of each of those folders
3. Create 5 Timelines in each of the subfolders

**Expected behavior**
Adding a new timeline should be nearly instant, at least under a second.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.4.2
 - Dialogic Version: 1.4

**Workaround**
I've just been cramming more dialog into each timeline and then using condition branches to separate the content.

**Possible fixes**
The problem appears to be tied to the plugin restructuring the entire project every time a file is added/renamed.  Oddly enough, deleting a timeline isn't slow at all.

**Comment by zaknafean** [comment]
VERY big issue in 1.4.x as I'm finding myself in my current project. It's mostly due to how lookups are handled during creation. I think @thebardsrc had some good insight into the problem and fixes for the problem.

**Comment by Tummyache** [comment]
I think in the meantime I'm just going to make a quick little separate application to create new empty timeline files and sync them with the folder_structure file.  Then disable timeline creation/renaming in the plugin code so I don't accidentally trigger the lookups.  That way I can at least close Godot, create all the files I need, and open Godot back up to generate the lookups or whatever is causing it.  One big load when I open the project is a lot better than a big load every time I accidentally double click a timeline.

Fixing it in the editor would be preferable, I just don't have the time to go digging around in the source.  So if there's any insight on where the problem is approximately, I could look at trying to help out.

**Comment by Tummyache** [comment]
Cool, I'll keep an eye out and just roll with my hacky workaround until then, no rush.

**Comment by zaknafean** [comment]
Honestly, if you get the work around going post it here. My team
mates would love to use it too.

**Comment by Tummyache** [comment]
@zaknafean just finished it, haven't had a ton of time to test it.

[DialogStopgap](https://github.com/Tummyache/DialogStopgap)

It's MEGA ULTRA hacky, but it's working so far.  You load the dialogic root folder (the folder where you folder_structure.json is), it will load up all the timelines into a tree, you can add, delete, move, and rename the files as you see fit.  Then when you're finally done, you click the Sync button and it will modify your Dialogic files.  I have a lot of very similar timelines, so I also added a code editor on the side so I can copy paste things or edit them on the fly, but it's raw JSON so your mileage may vary.

The big downside obviously is that it won't reload the project if it's already open.  At the very least though, it allows you to create all the timelines you'll need so you can fill the actual events out later.

If you want to disable renaming files in the Dialogic plugin, like I did because I always double click them on accident, here's the line to change.

[MasterTree.gd Line 802](https://github.com/coppolaemilio/dialogic/blob/6ba2d594aa984d517fe65ddf9c3d4593227f280a/addons/dialogic/Editor/MasterTree/MasterTree.gd#L802)

Just make it `item.set_editable(0, false)`

Hopefully it helps, but make sure you backup your files as I can make absolutely no guarantees it won't burn the whole thing down.

**Comment by zaknafean** [comment]
Just wanted to let you know I finally got to trying out your 'stop gap' project. Beautiful work and me and my team REALLY appreciate this.

**Comment by thebardsrc** [comment]
im just gonna add this here rather than another bug, when I get to actually doing the optimization to fix this, im gonna look at optimization to fix this as well when the timeline is actually populated

![image](https://user-images.githubusercontent.com/2214793/197263202-174adadd-1283-4cba-8ea0-9055c5d9d2f0.png)

**Comment by Jowan-Spooner** [comment]
Can this be considered fixed @zaknafean or @exelia-antonov?

**Comment by zaknafean** [comment]
Didn't realize it was still open. Yes this is fixed.
