### ISSUE TITLE
Padding around section headers could be increased and made more uniform

### ISSUE THREAD

**Issue by Lunadyn** [coppolaemilio/dialogic#124]
**Is your feature request related to a problem? Please describe.**
This is just a small visual preference, and could be a DPI scaling issue, but the padding around section headers seems a bit tight, especially noticeable with letters like the 'g' in 'Dialog' that hang underneath the section title box:
![1](https://user-images.githubusercontent.com/59242420/112852745-eea45100-90f7-11eb-8279-4265ec4bd1ea.png)

![2](https://user-images.githubusercontent.com/59242420/112852729-eba96080-90f7-11eb-912f-3db932818dfa.png)

**Describe the solution you'd like**
Padding around section headers could be increased and made more uniform.

**Describe alternatives you've considered**
(n/a)

**Additional context**
(n/a)

**Comment by coppolaemilio** [comment]
@Lunadyn are you on a 4k monitor?

**Comment by coppolaemilio** [comment]
There are no more section headers, so I'll close this one :)
