### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by stesproject** [coppolaemilio/dialogic#1241]
Is it possible to localize the messages in Dialogic?

A solution could be writing a key in the text box and then that key will be replaced by the correct message of the selected language. The file can be a json structured this way: 
{"en": 
 {
  "hello": "Hello!",
  "goodbye": "Goodbye!"
 }
},
{"it":
 {
  "hello": "Ciao!",
  "goodbye": "Addio!"
 }

**Comment by Jowan-Spooner** [comment]
Hi 1.x only allows to use the text as a key. 2.0has a more complex system where each event has a translation key, and you can auto-create the translation csv files. There won't be any big changes like this in 1.x, so I will close this.
