### ISSUE TITLE
Text event button missing

### ISSUE THREAD

**Issue by Chubbulus** [coppolaemilio/dialogic#1246]
I can't actually use the addon because theres no Text Event button in the Timeline editor? Can someone help? Using the version made for godot 3.5 (1.4.5 of Dialogic)
![image](https://user-images.githubusercontent.com/88031636/194299308-aafcf773-0d1e-44b6-b433-0fa62f885a89.png)

**Comment by Jowan-Spooner** [comment]
This is very strange. @zaknafean could you look into this?

In the meantime, are there any errors? What system are you using? Any other information you can provide?

**Comment by zaknafean** [comment]
We ended up just needing to reinstall and the problem was fixed.
