### ISSUE TITLE
Icon auto-size is not working properly

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1248]
@bitbrain reported that the plugin icon doesn't scale properly:

![image](https://user-images.githubusercontent.com/2206700/195986854-a338f54c-1f09-4d63-a8ee-cfe843f275c9.png)

He tested the icon in different resolutions and scales and he identified when it didn't work:

1920x1080 (100% scaling) -> icon looks correct
1920x1080 (175% scaling) -> icon looks correct
2560x1440 (100% scaling) -> icon looks correct
2560x1440 (150% scaling) -> icon looks correct
2560x1440 (200% scaling) -> TINY ICON!
3840x2160 (100% scaling) -> TINY ICON!
3840x2160 (150% scaling) -> TINY ICON!
3840x2160 (200% scaling) -> TINY ICON!

This is probably an issue with the Godot's code that resizes the icon. I'm not sure if @YuriSizov might have an insight here.

**Comment by YuriSizov** [comment]
No immediate insight, the new import options are supposed to simply pass your textures through the same hoops the editor has for its icons. Scale is applied as a numerical value to the image loader.

I might have missed some adjustment on top of using the editor scale, like adjusting for a different display dpi or system scale, but then the editor scale doesn't respect those values and that should affect a lot of other things.

How was this tested? Changing editor settings would trigger a reimport, but changing your system screen resolution wouldn't. Does the issue remain if you try to reimport the image manually? Simply selecting it in the filesystem dock and hitting Reimport in the Import tab should be enough.

**Comment by bitbrain** [comment]
> Does the issue remain if you try to reimport the image manually? Simply selecting it in the filesystem dock and hitting Reimport in the Import tab should be enough.

Let me test that!

**Comment by YuriSizov** [comment]
> unless I explicitly close Godot and re-open it.

Do you mean to say that something happens if you manually reimport and then restart?

**Comment by bitbrain** [comment]
> Then, if the reimport helps, it means that the cache wasn't properly invalidated for some reason.

Reimport after restart did not help, unfortunately. Tested this for any of the tiny icon cases listed in the description. 😕

**Comment by YuriSizov** [comment]
That's peculiar, would be interesting to figure out what fixed it, if it is indeed fixed.

**Comment by coppolaemilio** [comment]
It was my fault. I didn't commit the .import file which contained the information to scale with the editor. 
Happy it is working as intended now! Not sure how I missed such a simple thing for so long 😭
