### ISSUE TITLE
Support for multiple typing sound files per character

### ISSUE THREAD

**Issue by Harpeaux** [coppolaemilio/dialogic#1249]
So far I love the typing sound feature, however I think it'd be nice if each character could support multiple audio files that could _also_ be randomly pulled from.

This would allow even further stylized audio when a character is talking, as they could conjugate different audio clips to fake a language being spoken (rather than the same clip being repeated over and over).

**Comment by zaknafean** [comment]
I think 1.x already does this. You can select a folder full of sounds, no
just a single sound.

**Comment by Harpeaux** [comment]
Oh! Must've missed that in the documentation then, feel free to close this!
