### ISSUE TITLE
Error when trying to play not-saved timeline

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1252]
This is somewhat expected, but we should make a check before trying to play the timeline. Or the testing scene should display a label saying that no timeline was found. 

I think it would be best if the "Play Timeline" button couldn't be played if the current timeline isn't saved.

**Comment by thebardsrc** [comment]
doesnt it automatically right now run through the saving routine when hitting the Play Timeline button, the same way that the regular start project buttons do?

in connection to this then, we need an actual button to be able to manually save, probably in the toolbar. right now its just when you hit the Ctrl+S combo, or save the entire project, or actually run the project, or switch betwen visual and text editors for timelines

**Comment by Jowan-Spooner** [comment]
As you cannot create a timeline without a path, this is outdated
