### ISSUE TITLE
Timelines resetting .dtl file data randomly

### ISSUE THREAD

**Issue by Yotopihi-Dev** [coppolaemilio/dialogic#1260]
My dialogic timeline works and then the entire file resets on itself randomly

**Expected behavior**
Im expecting the dialogue prompt to play, but the screen shows nothing and every time I check the timeline, it's not empty, but when I check the .dtl file on notepad, it's all empty.

I also got the error: 'Timeline was not in ready state for saving!Timeline was not saved!' 

**Screenshots**

![Screenshot 2022-10-21 130526](https://user-images.githubusercontent.com/101610280/197159450-a3826828-ca07-4a85-810f-457a29ce8608.png)
![Screenshot 2022-10-21 122716](https://user-images.githubusercontent.com/101610280/197159457-41c4ff02-6694-47d6-8064-e2aaf45337f8.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0 beta 3

 - Dialogic Version: v2.0 alpha 4

**Workaround**

Re-enabling the plugin, adding the events in the file again, and restarting godot

**Possible fixes**

I didnt have this issue until the saving timeline issue got fixed, so possibly the file is getting overwritten each time I save

**Comment by Jowan-Spooner** [comment]
Thanks for reporting. @thebardsrc is working on it!
