### ISSUE TITLE
Crucial spelling error in README.md

### ISSUE THREAD

**Issue by ReddKarma** [coppolaemilio/dialogic#1261]
I might be completely wrong but I think it should be *.cfg instead of *.cgh  I had problems exporting and it fixed once I changed this.

![image](https://user-images.githubusercontent.com/83674795/197295250-ce59810c-8b9a-44e4-81da-7d3bc17027cc.png)

**Comment by Jowan-Spooner** [comment]
Thank you, I've changed it.
