### ISSUE TITLE
`DialogicGameHandler.jump_to_label` does not work at runtime

### ISSUE THREAD

**Issue by factubsio** [coppolaemilio/dialogic#1270]
## The problem

**Describe the bug**
Using a `Jump` node does not work at runtime, it never finds its label

**To Reproduce**
Add a `Label` node
Add a `Jump` node targeting the label

**Expected behavior**
Dialog should continue from `Label`

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: godot v4.0.beta3.official [01ae26d31]
 - Dialogic Version: dialogic-2.0-alpha-4 

## Solutions

Workaround: maybe `get_event()` isn't supposed to copy?

Use `events[idx]` instead of `get_event(idx)` and handle bounds manually.

```
func jump_to_label(label:String) -> void:
	var idx: int = -1
	while true:
		idx += 1
		
		# check bounds since we are not using get_event()
		if idx >= len(current_timeline.events):
			idx = current_event_idx
			break
		
		var event: Variant = current_timeline.events[idx]
		if not event:
			idx = current_event_idx
			break
		if event is DialogicLabelEvent and event.Name == label:
			break
	current_event_idx = idx

```

Reasoning:

`DialogicGameHandler.jump_to_label` uses `timline.get_event()` which calls `duplicate()` on the event instead of just returning it (possibly by design?). When duplicating an event it runs:

```
################################################################################
## 					BUILDING THE EDITOR LIST
################################################################################
func _get_property_list() -> Array:
	if Engine.is_editor_hint():
		if editor_list != null:
			editor_list.clear()
		else:
			editor_list = []
		
		build_event_editor()
		return editor_list
	else:
		return []
```

Which does not work at runtime since `Engine.is_editor_hint()` returns false.

**Comment by Jowan-Spooner** [comment]
@thebardsrc has been working on an improvement of the label event (#1267) . Maybe she can give some inside.
