### ISSUE TITLE
NamePlates changes alignment

### ISSUE THREAD

**Issue by MadServlet** [coppolaemilio/dialogic#1272]
## The problem

**Describe the bug**
Nameplates changes alignment after the first sequence. 

**To Reproduce**
Just downloaded the latest one from release and installed.
Nothing special, just added 2 characters and a dialogue.
First character has a short name, next character has a long name.
Setup a conversation and make the short name appear first.
No modifications.

**Expected behavior**
Names shouldn't change alignments

**Screenshots**
![godot windows opt tools 64_bxBeVFeZds](https://user-images.githubusercontent.com/31308819/198833166-e0fb11f5-d3e5-48e1-a3a6-9eac04ab433d.gif)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: v3.5.1.stable.official [6fed1ffa3]
 - Dialogic Version: 1.4.5

**Comment by zaknafean** [comment]
Hm thought we had this fixed, but I'll dig into it. Probably need another resize call to make the alignment work.

**Comment by zaknafean** [comment]
Issue seems fixed, though I'm unsure about some of the code. Feels like a bandaid more than the core issue, so we'll monitor this.
