### ISSUE TITLE
When I create dialogs, they overlap each other

### ISSUE THREAD

**Issue by tonymacx86PRO** [coppolaemilio/dialogic#1274]
## When I create dialogs, they overlap each other

**Describe the bug**
When I click the button next to an NPC, it brings up a dialog box
The problem is that if I click the button a lot of times, then there are a lot of dialogs on top of other

**To Reproduce**
(Using C#)
`
Node dialog = null;
dialog = DialogicSharp.Start("timeline");
AddChild(dialog);
`

**Expected behavior**
To start just one dialog not many of them

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: v3.5.1.stable.mono
 - Dialogic Version: v1.4.5

**Comment by Jowan-Spooner** [comment]
Well if you call the method multiple times then it will instance it multiple times. You can add a check `if Dialogic.has_current_dialog_node():`.
Hope this helps.
