### ISSUE TITLE
[Godot 3.5] Question on Default Character Sprite Position

### ISSUE THREAD

**Issue by eaganlai** [coppolaemilio/dialogic#1277]
I am using Dialogic for a vertical screen game. So I will be using the 2nd, 3rd, and 4th character positions a lot.

![image](https://user-images.githubusercontent.com/74284983/199794908-db0e1537-5de8-447e-96ee-f0b40117333e.png)

Let's say I have a character Alex who usually takes the 2nd position and a character Bob who usually takes the 4th.
By default, Alex will be half out of the screen on the left and Bob will be half out of the screen on the right. I have adjusted the character sprite offset (Alex X+200, Bob X-200) to fit them in. However, it won't work if I want Alex to take the 4th (right) position, and Bob to take the 2nd position.

Is there a way to edit the X and Y value of the default position?

**Comment by Jowan-Spooner** [comment]
Well in dialogic 1 that is unfortunately hard to do. This means you have to go into the Portrait.gd script and change the offset that is hardcoded in there.

**Comment by eaganlai** [comment]
Thanks! I find it in `res://addons/dialogic/Nodes/Portrait.gd`

```
func move_to_position(position_offset):
	var positions = {
		'left': Vector2(-400, 0),
		'right': Vector2(+400, 0),
		'center': Vector2(0, 0),
		'center_right': Vector2(200, 0),
		'center_left': Vector2(-200, 0)}
```

Is it possible to override it without changing this gd? So like in CSS we can append a CSS sheet to overwrite the original one. I am asking because I don't want to do it every time after updating the plugin.

Also, I am curious about how easy it is in Dialogic 2? I am totally new to game dev and this is my first project. I could always make the switch if it is beneficial! I only picked Dialogic 1 because I thought there will be more documentation for Godot 3.5.

**Comment by Jowan-Spooner** [comment]
Hi, unfortunately I don't know of a way to change this without changing the file (yes this is annoying when updating).
 
Dialogic 2 is still in alpha state as it is only for godot 4. Also many things changed compared to 1.x. The portrait positions for example are now referenced from the so called PortraitPosition node (custom dialogic node). You can just move these nodes (basically Marker2D nodes, or Position2D nodes) to adjust the positions of your portraits. Also this allows to add more then 5 positions. 
There is less documentation both for dialogic 2 and godot 4 so if you are completely new that might not be a good choice for now. If you are an experienced developer who can work with little docs you can oc try it out but yeah, it's still very WIP.

**Comment by Jowan-Spooner** [comment]
I will close this, as it's not an issue we intend to fix (already fixed in 2.x).
