### ISSUE TITLE
Reimplement [nw] command

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1280]

**Comment by thebardsrc** [comment]
to bring forward the notes from the overall reimplement task list on #966: 

> nw (would rename this tho, and make it a global setting)

im not sure what you mean about the make it a global setting instead part?

**Comment by Jowan-Spooner** [comment]
Well I meant it can be usefull to have no wait/autocontinue on all events with a setting.

Personally I find autocontinue a better name for this command (because no wait implies something instant even though it's not).
So maybe the command could be [auto=x] or [autocon=x] idk, what do you think?
