### ISSUE TITLE
Wait event: Hide text box setting doesn't save

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1303]
This seems to be a bigger issue with settings not saved as shortcode parameters if they are "false". This is because the default saving implementation of shortcode makes a check for the value before saving it.

**Comment by Jowan-Spooner** [comment]
So the problem here is that the shortcode saver should try to not save the setting when it's at it's default value. However I have not yet found a good way to modularly get the default value of a variable from a script.

**Comment by coppolaemilio** [comment]
What about a setget? (no idea, just thought it might help 😅 )

**Comment by Jowan-Spooner** [comment]
I will try again later with Script.get_property_default_value()
