### ISSUE TITLE
Dialogic dialog can be activated multiple times when hitting different activation buttons in quick succession, making variable count tracking for events difficult.  

### ISSUE THREAD

**Issue by metanoder** [coppolaemilio/dialogic#1322]
Godot 3.5.1 Dialogic 1.4.5

Dialogic dialog can be activated multiple times when hitting different activation buttons in quick succession, making variable count tracking for events within plug-in difficult.  

Scenario:
I have a godot scene with four different dialogic dialog conversations within.  You need to activate all four to move forward.
I count each conversation at the end of each dialogic dialog, with a variable counter to see how many times the conversation happens.  After a count of 4 conversations, it calls a custom function in my autoloader to clear the .tscn and jump into the next .tscn.

But players can hit the mouse button, then players can hit return or spacebar to speed up dialog, which is what I do when I have already read a scene.  But you can active a dialogic dialog multiple times if it is done before the dialog is finished launching... 

This particular situation, my scene skips all other dialogs if a player spams multiple activation buttons.

Dialogic Default Action has return, spacebar, x, left mouse, x, and controller as default activate button.  
One could just have one activate button to get around this problem, but the quality of experience will suffer.  

Players can inadvertently or intentionally spam this on second play throughs. 
The dialogic dialog should only fire once.

**Comment by Jowan-Spooner** [comment]
I'm a bit confused of what you want. If you don't want to spawn another dialog if one is already playing, then add a check before adding it. 
E.g.:
```gdscript

func _on_something_happened():
    if !Dialogic.has_current_dialog_node(): # make sure only one dialog can exist
        var dialog = Dialogic.start('mytimeline')
        add_child(dialog)
```
Does that help? Maybe I misunderstood. Also please, shorter titles :laughing:. Maybe "Quickly activating dialog multiple times makes counting hard" or something similar, but not a big problem, just for next time. Information can go in the initial comment.

**Comment by metanoder** [comment]
Yep, just what I needed.  **Thank you!**

Can do on shortening long titles.  👍🏼
Being concise will be a WIP. ;P 

Cheers!

**Comment by metanoder** [comment]
Worked like a charm.  

For prosterity if others look this up...

Had to "Extend Dialogic" on top of my script to have access to the function ( # I had "Extends Node" instead )

**Thanks again** Jowan!
