### ISSUE TITLE
Stuck in Settings

### ISSUE THREAD

**Issue by FeralBytes** [coppolaemilio/dialogic#1327]
## Stuck in Settings

**Describe the bug**
Dialogic current master for Godot 4.0 when you press Settings you can not then make Settings go away to get back to the editor. Pressing Setting again does not hide it. Only reloading the project allows you to get back to the timeline.

**To Reproduce**
1. Click Dialogic Tab
2. Click Settings Tab
3. Try to get out of Settings View.

**Expected behavior**
Click Settings to show Settings. Click Settings again to hide Settings.

**Screenshots**

**System (please complete the following information):**
OS: Linux Mint 20.3 Cinnamon 5.2.7
Kernel: 5.4.0-131-generic
CPU: AMD Ryzen 9 3900X 12-Core Processor × 12
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5700 XT]
v4.0.beta4.official [e6751549c] Vulkan AKA Forward+
V2.0-Alpha-4

## Solutions

**Workaround**

Reload the Project.

**Possible fixes**

Settings button in the EditorView.tscn does not seem to be connected, so I am not sure how you are responding to it and how you would adjust that code.

**Comment by Jowan-Spooner** [comment]
Hmmmm... Not sure why it doesn't work for you. 
For me pressing settings again does work (show the previously edited thing again).
You can alternatively open any timeline or character from the file system, picker or side bar (only on main).
Did you edited any resource before opening the settings?

**Comment by FeralBytes** [comment]
No I had not created a timeline or any kind of character. So perhaps that is why.

**Comment by Jowan-Spooner** [comment]
That is probably the case. However you should still be able to exit the settings by creating a new timeline or character from the two toolbar buttons. Or does that not work?

**Comment by FeralBytes** [comment]
I tested this and even though it allowed me to create a new timeline, it did not switch to the new timeline. I was still stuck in settings and could not get it to go to the new timeline for editing.

**Comment by viloz1** [comment]
I can confirm that this is affecting me as well. Have not created any timeline or character or done anything related to dialogic for that manner, and I can not leave the settings after entering. Fresh install

**Comment by viloz1** [comment]
Can confirm that this is happening to me as well.

**Comment by metanoder** [comment]
Just confirming this as well...

With a fresh Godot beta 5 download, and freshly added dialogic alpha 4 post your code cleanup.  I have the same problem when you hit setting before starting and saving a new timeline.  

After it gets stuck, you can add a timeline, but one time I messed with the window resizing tab, and it showed that the settings panel slightly shifted to the right that showed that the setting panel hover over the newly instantiated dialog editor or character editor.

**But what seems to break me out of this is double clicking a timeline from the FileSystem dialog box.**

**Comment by metanoder** [comment]
part 2 ad-hoc workaround until a proper fix.

if you don't copy over any timelines nor characters from the dialogic addon...

if you get stuck on settings window and have no timeline to double click to in FileSystem editor dialog window.  
Adding a new timeline, and clicking on the drop down menu and selecting the new timeline seems to skip having to reload.

<img width="1087" alt="Screenshot 2022-11-17 at 11 13 17 PM" src="https://user-images.githubusercontent.com/117393840/202644010-239f667f-339e-43ca-9a28-7a70148e2608.png">

**Comment by Jowan-Spooner** [comment]
I'm working on a full editor rewrite that will add tabs for the editors and settings. So nobody should get stuck in the future! Might take a couple more days until everything works again.

**Comment by Jowan-Spooner** [comment]
I consider this fixed on main. If someone still has problems in the future, let me know.
