### ISSUE TITLE
Unable to set default portrait

### ISSUE THREAD

**Issue by viloz1** [coppolaemilio/dialogic#1330]
## The problem

**Describe the bug**
It is not possible to change the default portrait. When "Select Resource" is pressed, the text dissapears and the following error is thrown:
`res://addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd:326 - Trying to call a function on a null value.`

**To Reproduce**
1. Create a new Character
2. Try to select a resource for the new character

**Expected behavior**
The expected behaviour is that I can select a sort of image resource to apply to the default portrait, or some sort of popup telling me I need to add a portrait first.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.0 alpha 4
 - Dialogic Version: 2.0 alpha 4

## Solutions

**Workaround**

Have found no workaround.

**Possible fixes**

There seems to be a null value in CharactorEditor.gd

**Comment by viloz1** [comment]
This seems to be fixed in main, closing

**Comment by AnnoyingB** [comment]
I still have the problem :\

**Comment by Jowan-Spooner** [comment]
@AnnoyingB  On main ? Or on the latest alpha ?

**Comment by AnnoyingB** [comment]
main

**Comment by AnnoyingB** [comment]
godot 4.0 beta 4 and 5 don't work for me

**Comment by Jowan-Spooner** [comment]
I'm working on this btw

**Comment by AnnoyingB** [comment]
found the problem yet?

**Comment by Jowan-Spooner** [comment]
As part of the editor rework I am also working on the character editor and will make sure this works again.

**Comment by AnnoyingB** [comment]
oh ok

**Comment by AnnoyingB** [comment]
I tried godot 4.0 beta 4 again and it is mostly black and some button icons don't show and i still get null value error.

**Comment by AnnoyingB** [comment]
I went on godot beta 6 and it is the same as beta 4
