### ISSUE TITLE
When i pressed the choice button i have this exception

### ISSUE THREAD

**Issue by tonymacx86PRO** [coppolaemilio/dialogic#1333]
## The problem

**Describe the bug**
When i pressed the choice button i have this exception (Check image)
**To Reproduce**
1. Started dialog preview
2. Pressed choice button
3. And i saw exception in DialogNode.gd

**Expected behavior**
Say text as it is in timeline

**Screenshots**
https://i.imgur.com/C2TWUkH.png
https://i.imgur.com/0a8dv4F.png
**System**
 - OS: Windows 11
 - Godot Version: 3.5.1.stable.mono
 - Dialogic Version: 1.4.5

**Comment by Jowan-Spooner** [comment]
This means you are missing an end branch event. Each question should end with an end branch event!

**Comment by tonymacx86PRO** [comment]
Thanks for help!
