### ISSUE TITLE
Visualize Waiting period between dialogue boxes

### ISSUE THREAD

**Issue by oliviathevampire** [coppolaemilio/dialogic#134]
A way to add a waiting period between different dialogue boxes where it would stay on the previous one until the waiting period goes down, maybe even a way to show it, like a cooldown bar, either round or straight

**Comment by Jowan-Spooner** [comment]
Just so you know, you can use [nw=X] in a text event to make it automatically continue X seconds after the text finished showing.

**Comment by coppolaemilio** [comment]
I believe this goes more in line with a visible count down to force you to pick an option. 
Similar to this kind of bar at the bottom of the inputs:
![image](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.gamersdecide.com%2Fsites%2Fdefault%2Ffiles%2Fcontent-images%2Fnews%2F2017%2F04%2F23%2Fhow-telltale-games-changing-gaming-industry%2F04-player-choice.jpg&f=1&nofb=1)
