### ISSUE TITLE
Speed tags are not resolved in HistoryRow

### ISSUE THREAD

**Issue by eaganlai** [coppolaemilio/dialogic#1342]
As shown below.

![image](https://user-images.githubusercontent.com/74284983/205513830-be52849d-fd3c-4386-b759-45a764af6586.png)

https://github.com/coppolaemilio/dialogic/pull/1341

**Comment by eaganlai** [comment]
https://github.com/coppolaemilio/dialogic/pull/1344

**Comment by zaknafean** [comment]
Merged it in! Thanks alot for the contribution!
