### ISSUE TITLE
A way to have character portrait integrated into UI

### ISSUE THREAD

**Issue by vmedea** [coppolaemilio/dialogic#1357]
I'm using Dialogic 2 to create a dialog system like in some point&click adventure games:

![screenshot0003_scaled](https://user-images.githubusercontent.com/43048142/208673186-24dd41da-b8c4-45cf-87e5-02df03ced743.png)

![screenshot0007_scaled](https://user-images.githubusercontent.com/43048142/208679899-f52f5903-b35c-4e05-929d-eb7ebca10d12.png)

The goal is to integrate everything (portrait, name, text, choices) into one UI, instead of have independent floating elements. This already works as-is for most of these, except the portrait.

What I did, for now, is to embed the portrait display into the dialog scene UI with a `TextureRect` (instead of a `Sprite2D`) that's member of a specific node group, similar to how `dialog_name_label` is handled. This is very hacky code (so no PR for now), but I think it'd be useful to support this.

**Is your feature request related to a problem? Please describe.**

By default the character portrait is placed in the scene at an absolute position by a marker. Even in RPG mode, although the idea is the same. This doesn't work if you want the portrait to be part of the interface (e.g. position it with VBox/HBox, apply specific rendering/blending, etc).

**Describe the solution you'd like**

I have no preference for a specific solution. I think most straightforward would be an additional PortraitMode that expects the `DialogicDefaultPortrait` UI element already instantiated in the existing scene tree, instead of just a marker.

**Describe alternatives you've considered**

Not sure.

**Additional context**

N/A

**Comment by Jowan-Spooner** [comment]
Agreed that integrating into a UI with a fixed/flexible size/position needs to be made easier. 
I need to brainstorm a bit more on how this could be implemented in the cleanest, most flexible way though.
This could be something to do before the 2.0 release because then we don't need to worry about compatibility so much, but it might be pushed to 2.x.

Thanks for the request!

**Comment by Jowan-Spooner** [comment]
Hi @vmedea, it's been a while, but I have great news, if you are still interested in this.

I've just merged a pull request that replaces portrait positions with portrait_containers. These come with a couple of different size_modes that allow you to fit the portrait into the controls rectangle. 

This is available on the main branch or in the next release.

**Comment by vmedea** [comment]
That's great news indeed!

> I've just merged a pull request that replaces portrait positions with portrait_containers. These come with a couple of different size_modes that allow you to fit the portrait into the controls rectangle.

I'll try to integrate this instead of my current hacks soon.
