### ISSUE TITLE
Jump event doesn't immediately handle event

### ISSUE THREAD

**Issue by vmedea** [coppolaemilio/dialogic#1358]
## The problem

**Describe the bug**

I've added a label and a jump event to my dialog, and it works, but when it triggers I need to push the 'interact' key an extra time before event after the jump is actually invoked.

I'm not sure this is intended behavior but it seemed unexpected to me!

**To Reproduce**

1. Create a label. In my case it's before a Text with Choices inside.
2. Create a jump event.
3. Start the dialog.
4. Get to the point where the jump is. The interaction will appear to "hang" in a limbo state, until a key is pressed.

**Expected behavior**

Dialog immediately continues after the label.

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 4.0.beta9
 - Dialogic Version: 2.0 5b931ab8

## Solutions

**Possible fixes**

What worked for me in cursory testing is to add `handle_event(current_event_idx)` to the end of `jump_to_label` in `DialogicGameHandler`. But this is probably bad in various ways :sweat_smile:

**Comment by Jowan-Spooner** [comment]
I will test that later. Thanks for reporting!

**Comment by Jowan-Spooner** [comment]
Confirmed as not-intended behaviour. Will add to the 2.0 release milestone.
