### ISSUE TITLE
Dialogic keeps creating deleted characters

### ISSUE THREAD

**Issue by AnidemDex** [coppolaemilio/dialogic#136]
## The problem

If you try to delete characters directly from the filesystem, and Godot is still open in background with dialogic plugin activated, dialogic will try to keep a reference to the last created character.

**To Reproduce**
1. Go to Dialogic Editor
2. Create at least 2 new characters
3. Go to `dialogic/characters` in your file explorer
4. Select all characters and remove them

**Expected behavior**
Characters files are gone

**Screenshots**
![error](https://user-images.githubusercontent.com/7025991/113349183-452eac80-92fd-11eb-9892-8874c7ad0c57.gif)

**System:**
 - OS: Windows 10 64x
 - Godot Version: 3.2.3
 - Dialogic Version: 1.0

## Solutions
There's no solution yet, since i have not investigated further around this issue.

**Comment by Jowan-Spooner** [comment]
This was reported quite a while back. Is it still present?

**Comment by coppolaemilio** [comment]
I think it is still present since you shouldn't be removing character files while the editor is open. Leaving open to maybe apply a fix in the future?

**Comment by bitbrain** [comment]
Looking also at https://github.com/godotengine/godot/issues/44123 maybe the issue is that Godot should lock the files instead when they are in use (while the editor is open)

**Comment by AnidemDex** [comment]
@bitbrain oh yeah, I'm aware of that, forgot to mention on this issue. Is related, but is not the issue at all, the issue comes directly with how Dialogic creates files (wich is, essentially, probably the same as Godot keeps resources on cache). Thank you por pointing that.

Closing this issue since is out of plugin's scope.
