### ISSUE TITLE
Drag and dropping outside of the timeline leaves a "placeholder event"

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#138]
## The problem

This one is probably for you @ellogwen 

**Describe the bug**
When you drag and drop an event outside of the timeline area (specially to the left) the placeholder is still on the last position possible and as soon as you click anywhere it gets created.

![drag-and-drop-bug](https://user-images.githubusercontent.com/2206700/113358913-f148b580-9346-11eb-88ad-f7a79799fa0a.gif)

**Comment by ellogwen** [comment]
Yes, I will look into it right now

**Comment by ellogwen** [comment]
@coppolaemilio i fixed it, but my original Draft got already merged. do you want a new pr?

**Comment by coppolaemilio** [comment]
Yes, a new PR is good 👍🏻

**Comment by ellogwen** [comment]
Ok, i try my best. man i really need some coaching regarding branches and upstream synching, my commits look like mess

**Comment by arnaudvergnet** [comment]
Hey @ellogwen, you can learn more about branching here: https://learngitbranching.js.org/.

The website is really well made and you learn quite fast with it. Also, a good practice with git it to make "atomic commits", meaning you do one commit for one change. This makes it easier to rollback a change later.
