### ISSUE TITLE
Trailing slash eats next character line (fringe parse error?)

### ISSUE THREAD

**Issue by generrosity** [coppolaemilio/dialogic#1392]
## The problem

**Describe the bug**
Found while editing and swapping between editor views and swapping between multiline dialogs.

Trailing "\" backslash will display in visual editor but the following line is hidden. When testing PlayTimeline, the backslash is not shown, and the following line is not shown.

**To Reproduce**
1. per screenshot - add a trailing backslash on a line that isn't intended to be multiline.

**Expected behavior**
Likely - to ignore the multiline meaning, and display the slash and the following dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/12838061/210167818-5e85946c-dbf1-48ea-9b00-cd169b86f83f.png)

**System (please complete the following information):**
 - OS: Win10
 - Godot Version: 4 beta 10
 - Dialogic Version: 2-alpha-5

## Solutions

**Workaround**

Obviously, don't do it 😅 but accidents happen. Remove the character is the obvious fix, but it isn't displayed while previewing so its harder to find.

**Possible fixes**

It has the feels of a fringe regex parse issue? just checking for `{Multiline}{EOL}{ ** }` rather than  `{Multiline}{EOL}{! Command}{ ** }`?

**Comment by generrosity** [comment]
When I realized I was having this bug, I ended up needing to control-Z my project a lot as the actual lines of dialog were being removed, but I've been unable to replicate this.

**Comment by generrosity** [comment]
Yup - confirmed a situation.

* Leave a trailing slash on the first row in text editing.
* Return to visual editor.
* Make any change (such as adding and removing a space), and test the scene.
* Tap to look at text editing and immediate return to visual editor.
* Make any change (such as adding and removing a space), and test the scene.
* etc

Obviously the visual editor throws away any invalid lines and character names along the way even it fails forward. Potentially the visual editor could check to see the delta of changes its making and advise the user (as well as if the regex parse was fixed), otherwise Im not sure what else to suggest

**Comment by Jowan-Spooner** [comment]
Do I understand it correctly that you are trying to create multiline events but the editor breaks them? Or do you just want to add a \ at the end?

**Comment by generrosity** [comment]
Sort of. I had a multiline that I edited into separate prompts, but didn't see the trailing character at the time. The editor and the game parser then handles it badly but both are interpreting differently I think? And then the editor eats the line on save.

Sorry if not making sense. I could voice chat or screenshare via discord if that helps

**Comment by Jowan-Spooner** [comment]
So here is the thing: 
There was a regex issue that meant text events that got processed would loose all except the first line (processing only happens in visual mode or when playing). 
Fixing this makes this thing less of an issue. However a text event ending with \ will ALWAYS make the next line part of itself. That means in your case the next event would still not function correctly, but also not get removed (instead turned into a text event). Just removing the \ at any point in time with the text editor should then make the event behave correctly again.

Will merge this small fix asap.

**Comment by Jowan-Spooner** [comment]
Alright I've merged my fix for the regex (which autoclosed this issue, sorry). Maybe you could try again with the latest main branch? As always, keep a backup or use version control when handling WIP software. 

Would appreciate if you could test.

**Comment by generrosity** [comment]
> Alright I've merged my fix for the regex (which autoclosed this issue, sorry). Maybe you could try again with the latest main branch? As always, keep a backup or use version control when handling WIP software.
> 
> Would appreciate if you could test.

Awesomesause - just downloaded and tested HEAD against Godot b10 and it is acting a lot more sane and consistant to the slash spec. [chef kiss]

Thanks!
