### ISSUE TITLE
Jump return_after not working?

### ISSUE THREAD

**Issue by generrosity** [coppolaemilio/dialogic#1394]
## The problem

**Describe the bug**
I am trying out the 'return after' feature but I can't seem to get it to work? It seems to not return at all.

I've used the Jump command provided by the UI which includes "return_after" but I see in this it called just "return"? Neither works, neither has warnings.
https://github.com/coppolaemilio/dialogic/pull/1267 

**To Reproduce**
![image](https://user-images.githubusercontent.com/12838061/211192600-c4e059a7-3dc4-47f7-9306-44d6b75bbf3e.png)

![image](https://user-images.githubusercontent.com/12838061/211192626-08eca0d6-bef7-4cf6-8a65-f642e70639e3.png)

**Expected behavior**
The Jump executes as expected, but once it gets to the end of file the program closes.

**Screenshots**

**System (please complete the following information):**
 - OS: Win10 21h2
 - Godot Version: 4 beta10
 - Dialogic Version: 2.0beta-10

## Solutions

**Workaround**

Just looking at manual jumps for now

**Possible fixes**

I can't find a place in the code where this makes a difference, the return stack might not be implimented yet?

**Comment by Jowan-Spooner** [comment]
I've noticed this and worked on a fix, but not yet merged it.

**Comment by generrosity** [comment]
Awesome - thanks for the confirmation Jowan 👍 no rush, as such, and this can be closed off if otherwise not useful eh.

**Comment by Jowan-Spooner** [comment]
Could you test again with the latest main branch (should work with beta 11). It think that it works a lot better now.
