### ISSUE TITLE
Can't enable dialogic plugin

### ISSUE THREAD

**Issue by MouldyCheese** [coppolaemilio/dialogic#1395]
## The problem
I get an error message when attempting to enable the plugin in my project.

**Describe the bug**
When I try to tick the enable checkbox in the project settings, I get this error message:
>Unable to load addon script from path: 'res://addons/dialogic/plugin.gd'. This might be due to a code error in that script.
>Disabling the addon at 'res://addons/dialogic/plugin.cfg' to prevent further errors.

and I'm unable to actually enable it.
When looking in the file it's complaining about, it claims to have found a multitude of errors. For example, the very first line:
>@tool
Gives this error:
>error(1,1): Parse error: Unexpected '@'

**To Reproduce**
Attempt to enable the plugin.

**Expected behavior**
I expected to be able to enable the plugin.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.5.1
 - Dialogic Version: Dialogic 2 alpha 5

**What you tried to get the feature working**
Tried redownloading, tried several different versions of Dialogic.

**Comment by generrosity** [comment]
I think Dialogic 2 is for Godot 4 - there is a link on the Code tab to the 3.5 branch https://github.com/coppolaemilio/dialogic/tree/dialogic-1

**Comment by Jowan-Spooner** [comment]
Yes. Dialogic 2 is for godot 4. Because of compatibility breaks in the engine, you can also not use 2.x in 3.x.

**Comment by MouldyCheese** [comment]
> I think Dialogic 2 is for Godot 4 - there is a link on the Code tab to the 3.5 branch https://github.com/coppolaemilio/dialogic/tree/dialogic-1

**Comment by MouldyCheese** [comment]
Thanks, I suspected I was doing something wrong
