### ISSUE TITLE
UI does not scale

### ISSUE THREAD

**Issue by HeroicNate** [coppolaemilio/dialogic#140]
## The problem
The UI does not appear to scale with the rest of the interface. 

**Describe the bug**
I work on a high res screen and scale my editor up by 175%. The dialogic items do not appear to scale up. Also I am unable to resize the right column to reveal more of the buttons and text.

**To Reproduce**
1. Increase display scale under editor settings
2. See how buttons stay small and text gets cut off.
3. No drag bar for the right column.

**Expected behavior**
UI scales with the rest of the editor. Right column expands with click and drag.

**Screenshots**
[Screenshot](https://media.discordapp.net/attachments/826949020832366622/827311961985253426/unknown.png?width=1647&height=896)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.2.3
 - Dialogic Version: 1.0

## Solutions

**Workaround**
It does not inhibit function. It's just noticeably squeezed.

**Comment by coppolaemilio** [comment]
Unfortunately the current scale is not exposed to the editor. A PR will be made to Godot to fix this, but in the mean time I'm trying to figure out a workaround.

**Comment by coppolaemilio** [comment]
@HeroicNate Can you test the latest `main` and tell me how your experience is with the new changes? Not everything is scaled up but I think it looks much better than before.

**Comment by HeroicNate** [comment]
![unknown](https://user-images.githubusercontent.com/229208/113629107-eab28a80-9633-11eb-89ef-ef780692dc91.png)
I agree. Works much better!
