### ISSUE TITLE
Adaptive music feature

### ISSUE THREAD

**Issue by MiguelZamoraR** [coppolaemilio/dialogic#1404]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zaknafean** [comment]
Adaptive music tends to be its own system, and fairly complex at that. Godot 4.0 has better built in support for that, but I don't imagine that a full adaptive music system is really in scope for Dialogic.

**Comment by Jowan-Spooner** [comment]
Sorry but without more explanation on why this would be useful <<in dialogic>>, this has to be closed. Feel free to create a new, better issue in the future.
