### ISSUE TITLE
Godot crashes when drag&drop a second Choice in the Timeline

### ISSUE THREAD

**Issue by Dacordi** [coppolaemilio/dialogic#1411]
## The problem

**Describe the bug**

When I add a second Choice in the timeline and try to move it by drag and drop, Godot crashes (each time)

**To Reproduce**

Just add a Choice under another Choice and try to drag and drop it elsewhere. 

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4 Beta 15
 - Dialogic Version: 2.0

**Comment by Jowan-Spooner** [comment]
Thanks for reporting, I will investigate this now.

**Comment by Jowan-Spooner** [comment]
I think this is fixed now (on main branch which is for RC1, probably Rc2 works as well)

**Comment by Dacordi** [comment]
Thank you very much, I will try it !
