### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by aleperaltabazas** [coppolaemilio/dialogic#1415]
## The problem

**Describe the bug**
Website is broken

**To Reproduce**
1. Go to https://dialogic.coppolaemilio.com/

**Expected behavior**
The web loads correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/31170385/215903763-241b97df-32eb-420f-9ade-7992f084d70a.png)

**System (please complete the following information):**
 - OS: Linux
 - Godot N/A
 - Dialogic Version: N/A

## Solutions

**Workaround**

N/A

**Possible fixes**

Given that there's a big red sign that reads "APP_DEBUG is set to true while APP_ENV is not local", my suggestion would be to turn the `APP_DEBUG` flag off.

Edit: nvm, I see that's just a warning. The bug seems to be that there's no welcome view.

**Comment by RincewindWizzard** [comment]
The documentation on github wiki is rather outdated and incorrect and no other documentation is found on the internet, because of the broken website.

This makes it impossible for me to learn the basics of the dialogic addon. It's an absolute deal breaker.

**Comment by D-Ogi** [comment]
The development is still up while there is no documentation?

**Comment by coppolaemilio** [comment]
I made a provisional website so that we link to the releases and documentation. I'll keep updating it but I'll close this ticket now. It was really hard to make the transition but we are getting closer to getting a Godot 4 version working, so stay tuned :)
