### ISSUE TITLE
Unable to use this addon

### ISSUE THREAD

**Issue by RedNekoderr** [coppolaemilio/dialogic#1417]
## The problem

**Describe the bug**
Even after restarting the engine, the errors in the output panel did not disappear.

**To Reproduce**
1. Downloaded the latest version of the addon
2. Moved the "addons" folder to my project
3. Enabled the addon in the project settings and saw a few errors
4. Restarted the editor, as stated in the installation instructions
5. After the reboot, the errors have not disappeared and they prevent the project from starting

**Expected behavior**
These errors are not difficult to fix myself, but I'm not sure that everything will work fine after that.

**Screenshots**
[Screenshot](https://imgur.com/gallery/oZAIiki)

**System**
 - OS: Arch Linux
 - Godot Version (
    As it is written in the godot settings: v4.0.beta.arch_linux [604493eb6]
    Package name: 4.0.r51690.g604493eb6ee3-1
 )
 - Dialogic Version: 2.0 alpha 5

## Solutions

**Workaround**

I changed the code and everything seems to be working fine so far

**Possible fixes**

...

**Comment by Jowan-Spooner** [comment]
Hi, alpha 5 is for godot 4 beta 10, as it was released in december.
Hopefully we can release another alpha soon. The main branch should be compatible with beta 15, not sure about 17, but I'm working on it.
