### ISSUE TITLE
Cannot completely remove dialogic from project 

### ISSUE THREAD

**Issue by dmitsuki** [coppolaemilio/dialogic#1418]
On Godot Mono RC1, I tried to use Dialogic. It did not work, which was partially expected as it has not been updated for this beta. The issue is, when deleting it however I now receive these errors intermittently. 

```
 Script does not inherit a CustomResourceLoader: res://addons/dialogic/Resources/CharacterResourceLoader.gd.
  Script does not inherit a CustomResourceLoader: res://addons/dialogic/Resources/TimelineResourceLoader.gd.
  Script does not inherit a CustomResourceSaver: res://addons/dialogic/Resources/CharacterResourceSaver.gd.
  Script does not inherit a CustomResourceSaver: res://addons/dialogic/Resources/TimelineResourceSaver.gd.

```
I have disabled dialogic in plugins, then deleted it, and have no traces of it left in my project. What is causing these errors?

**Comment by metanoder** [comment]
@dmitsuki I believe you have to go into your project.godot file (using VScode for me), and delete the plugin's inserted code in there.  It's labeled, but to be sure, I checked it against a clean project see what I needed to take out.

**Comment by dmitsuki** [comment]
Ah, the issue was, after I did that, it still gave me the errors. Sorry for
not being clear enough.

**Comment by coppolaemilio** [comment]
I pushed some changes to `main` that should fix Dialogic running on the latest RC1. I'll close but feel free to re-open if you still find some issues.

**Comment by metanoder** [comment]
As this is fixed and now closed, just putting this out there for posterity.  

@dmitsuki if for whatever reason you still want to delete dialogic from your project cleanly, I forgot to mention the .godot folder.  You'll have to go into the hidden files within the target project folder and may have to delete references to dialogic plugin cached in there...


![delete_plugin](https://user-images.githubusercontent.com/117393840/218383796-e301ce76-890d-4492-bd01-1a06ae3caa11.png)

**Comment by eddieataberk** [comment]
issue still occurs
