### ISSUE TITLE
Portrait Holder scene error

### ISSUE THREAD

**Issue by GalloGGMC** [coppolaemilio/dialogic#1419]
I'm trying to set 3 dialogue events in the same scene, but after the first, there is always:

`[Dialogic] If you want to display portraits, you need a PortraitHolder scene!`

I tried adding the DialogicDefaultScene to the scene, instancing the dialogue scene and the Portrait Holder, different methods of calling the timeline, creating a new node in the PortraitHolder class but nothing seems to work. What do I do?

**Comment by Jowan-Spooner** [comment]
Sorry to hear it doesn't work for you.
Could you provide mode information? For example your timeline or what code you use to instance the default scene?

**Comment by Jowan-Spooner** [comment]
I'm going to close this as the portrait holder is no longer existent on main.
