### ISSUE TITLE
Portrait selector should show up if no character is selected

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1420]
![image](https://user-images.githubusercontent.com/2206700/218343446-6e1a9c14-f0bb-4f59-9446-cdd01c54ecd2.png)

**Comment by Jowan-Spooner** [comment]
I guess you meant to say "not" in the title?

**Comment by Jowan-Spooner** [comment]
There is a chance my layout PR fixed this. Would like you to test again.

**Comment by coppolaemilio** [comment]
Yes! I meant "not" 💩 

Tried latest version and it is fixed. Thanks!
