### ISSUE TITLE
Simplify code and contribution guide.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#143]
After so many additions and features the code is starting to be a bit too complex. 
I would love to refactor some of its parts and make it simpler. I know this is a super broad issue, but I'll also use it to create some contribution guide.

**Comment by ellogwen** [comment]
Yes, this is great idea. Do you have any plans in mind? One thing popped in my mind is a base class to share behaviour and callback signature for event nodes

**Comment by coppolaemilio** [comment]
too broad, will create better issues when needed.
