### ISSUE TITLE
Copy Paste error on Visual Editor mode 

### ISSUE THREAD

**Issue by metanoder** [coppolaemilio/dialogic#1444]
## The problem
Can not copy and paste text, Character, nor Set Variable box on the Visual Editor.

**Describe the bug**
Testing the latest "main" dialogic on Godot 4 RC5, Dialogic after [183b4f4], 
Could not paste copied Text box, Character box, nor Set Variable box on the Visual Editor.

* caveat on variables.  An empty variable can not be copy/pasted, however, when it has variable referenced, it does work as expected.  Text Event and Character Event with referenced assets still do not allow copy and pasting.

**To Reproduce**
1. create fresh timeline
2. switch to visual editor
3. add text box, character box, and set variable. 

**Expected behavior**
All other visual editor "event" command boxes work in copying and pasting "event".  These should as well.  

**Screenshots**
<img width="944" alt="image" src="https://user-images.githubusercontent.com/117393840/221388541-3399b17c-e63a-48f8-9252-c49f228360fb.png">

I'm hitting Command-C and Command-P in this video for the stated events...

https://user-images.githubusercontent.com/117393840/221388939-e0ffbf82-b19a-430e-85d7-35fde6713abf.mov

**System (please complete the following information):**
 - OS: MacOS
 - Godot Version: 4 RC 5
 - Dialogic Version: 4 A...6? "Main" after 183b4f4 commit.

## Solutions
?

**Workaround**
text editor

**Comment by Jowan-Spooner** [comment]
Thanks, I will look into this!

**Comment by Jowan-Spooner** [comment]
Found the problem. Will push a fix today.
