### ISSUE TITLE
Errors printed when timeline ends

### ISSUE THREAD

**Issue by kittygyj** [coppolaemilio/dialogic#1447]
## The problem

**Describe the bug**
I am unable to test my timeline by hitting "Play Timeline," and the output message indicates failure in loading resources.

**To Reproduce**
1. Go to dialogic
2. Create a new timeline
3. Click "Play Timeline"

**Expected behavior**
I expected the timeline I am testing to run and see the dialogue in the game.

**Screenshots**
<img width="1728" alt="スクリーンショット 2023-02-25 午後11 21 13" src="https://user-images.githubusercontent.com/82459117/221392213-fd061053-955e-4ecb-aa2b-5bdd8f8b032e.png">
<img width="1728" alt="スクリーンショット 2023-02-25 午後11 21 01" src="https://user-images.githubusercontent.com/82459117/221392208-6cd31217-c29a-4f75-8777-ce8af1347740.png">

**System (please complete the following information):**
 - OS: Mac
 - Godot Version: Godot 4 beta 10
 - Dialogic Version: Dialogic 2 Alpha 5

## Solutions

**Workaround**

**Possible fixes**

**Comment by Jowan-Spooner** [comment]
Would be great if you could try again with dialogic 2 alpha 6 on godot 4.0 stable release.

**Comment by kittygyj** [comment]
Hi, I tried with dialogic 2 alpha 6 on godot 4.0 stable release. I have no problem running the timeline now, but there are still some errors when the timeline ends.
