### ISSUE TITLE
Unable to edit timelines other than adding text and unable to save timelines

### ISSUE THREAD

**Issue by Toodle-ux** [coppolaemilio/dialogic#1448]
## The problem

**Describe the bug**
1. Unable to edit timelines other than adding text
2. Unable to save timelines
3. Unable to run timelines

**To Reproduce**
1. Open up a pre-existing timeline file.
2. Since the pre-existing timeline file only contains text, that's the only thing I can add and edit
3. When I press "ctrl+s", the newly added texts are not saved
4. When I click on "play timeline" or refer to the timeline in the script, I get error messages.

**Expected behavior**
1. I can use other dialogic functions including adding branches
2. The timelines can be created, edited, and saved.
3. I can play timelines. 

**Screenshots**
![Screenshot_20230226_082447](https://user-images.githubusercontent.com/66554025/221413139-1aa3bfdb-29bc-4a44-8052-6d01c778da68.png)
![Screenshot 2023-02-26 082413](https://user-images.githubusercontent.com/66554025/221413156-a0a49691-ee1c-4eac-bf56-6450770c275c.png)
I created a new timeline called "test". When I pressed "ctrl+s", the star disappeared but I couldn't find it in the designated folder. 

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4 beta 16
 - Dialogic Version: 2 alpha 6

**Comment by coppolaemilio** [comment]
You should try using the latest version of Godot. Right now there are many big changes from the beta 16 that you are using and the latest RC.

**Comment by Toodle-ux** [comment]
Thanks Emi! The edit and save function works fine now, but I got different errors while playing timelines. 
![Screenshot_20230226_092600](https://user-images.githubusercontent.com/66554025/221416563-4499d5e8-3012-4b23-8a24-3a42a0c1b28d.png)

**Comment by coppolaemilio** [comment]
We'll see what we can do, the plugin is still in alpha and we are changing things very often 😅
