### ISSUE TITLE
DialogicDefaultLayout has a reference to Emilio.dch

### ISSUE THREAD

**Issue by joaopedrosgs** [coppolaemilio/dialogic#1450]
## The problem

**Describe the bug**
The default layout is broken, trying to run a timeline using it will throw an error

**To Reproduce**
1. Create a new timeline
2. Call Dialogic.start(your_timeline) using the default layout
3. See error

**Expected behavior**
To work with the default layout

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0 RC5
 - Dialogic Version: master

## Solutions

**Workaround**
Open the default layout and replace the reference 

What you tried to get the feature working

**Possible fixes**
Add the Emilio.dhc file to the correct folder and point the reference to it

Any idea to fix the issue or a link to the line of code that might be the cause for this problem
https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Events/DefaultLayouts/Default/DialogicDefaultLayout.tscn#L8

**Comment by coppolaemilio** [comment]
I was removing some files yesterday to keep the project without any outdated resource and probably broke it. I should be able to fix these issues in upcoming patches 😅

**Comment by Jowan-Spooner** [comment]
Should be fixed on main.
