### ISSUE TITLE
Can't use custom layout scene

### ISSUE THREAD

**Issue by viloz1** [coppolaemilio/dialogic#1465]
## The problem

**Describe the bug**
I cannot select another custom scene as layout.

**To Reproduce**
1. Go to "Layout"
2. Change "Preset Mode" to "Custom Mode"
3. Select a scence in the "Custom layout scene"
4. Go to another tab, for example "Glossary"
5. Go back to "Layout". The custom layout scene is now the default scene.

**Expected behavior**
The custom layout scene should stay selected.

**System**
 - OS: Windows 10
 - Godot Version: 4.0 stable
 - Dialogic Version: 2.0-Alpha-6

**Comment by Jowan-Spooner** [comment]
Should be fixed by #1476
