### ISSUE TITLE
[Enhancement] A way to group timelines for easier management

### ISSUE THREAD

**Issue by ellogwen** [coppolaemilio/dialogic#147]
I am a guy that creates a lot of small little timelines with often just one or two text events in it.
In the dialogic timeline editor, all timelines are listen below each other. So I am using a naming convention like, `room.subroom - target - info` and my timelines look like this `0.0 - tina - door trigger` or `0.2 - door - still closed`.

But, to be honest, it would be nice if I could group timelines into a subfolder, e.g. Room1, Room2 ... that i can collapse for easier finding.

This is nothing trivial, if would affect alot of aspects, even down to the TimelineDropdown inspector editor. So for a first attempt i would suggest that you can add one "tag" to a timeline that gets stored withing the file. The timeline editor would sort the timelines by Tag > Name, Ascending, so that you can fold it. The DropdownEditor could do the same without the folding.

*Note* the currently PR pending function for directly jumping into a timeline for editing just accounts for one level deep of the MasterTree control, when searching the correct entry. This would need adjustment aswell:

Alternative: a search field

**Comment by ellogwen** [comment]
@coppolaemilio Mentioned something about chapters in the discord channel. Can you ellaborate this?

**Comment by arnaudvergnet** [comment]
We talked about this in #111

**Comment by coppolaemilio** [comment]
Yeah, I'm closing as a duplicate, but I can leave it open if you want to propose something in particular.
A sear (or filter) functionality would be nice to add. Something like the filter scripts one on the script editor:
![image](https://user-images.githubusercontent.com/2206700/113490683-e8352100-94cb-11eb-9dff-5e33fd68abf5.png)

For now I think that doing folders would work just fine to group timelines.

**Comment by ellogwen** [comment]
> A sear (or filter) functionality would be nice to add. Something like the filter scripts one on the script editor:
> ![image](https://user-images.githubusercontent.com/2206700/113490683-e8352100-94cb-11eb-9dff-5e33fd68abf5.png)

@coppolaemilio I did, see PR#149

**Comment by coppolaemilio** [comment]
Closing this one 🙃
