### ISSUE TITLE
Android: [wait] broken and some lines skipped

### ISSUE THREAD

**Issue by Kangarroar** [coppolaemilio/dialogic#1470]
## Bug is being shown on Android Exports, PC runs go fine without this bug

**Describe the bug**
- The time/wait function doesn't work as intended, even if I set it to 200, it waits for 1 second.
- The dialogue skips two lines, it skips one at the start of the timeline and one at the end, not showing the coded lines, this doesn't happen on PC

This only happens on Android, I already tried different SDKS export and it still happens, same thing in other phones

**System (please complete the following information):**
 - OS: Android
 - Godot Version: 4.0
 - Dialogic Version: 2.0

## Solutions

**Workaround**

Empty first line of dialogue and empty last line of dialogue.

**Comment by LemurShteel** [comment]
Tested on android tablet with keyboard. 
Seems like something with godot on android itself. Touch input calls events twice from devce 0 and -1 somehow. I belive it skips wait and other lines from immedient second call.
Input from keyboard (keys) works as intended.
Can suggest a feature to make a pause between inputs. 
As temporal fix in default_input_handler.gd can be edited in 11th line:
if event.device == -1: return

**Comment by Jowan-Spooner** [comment]
There is now a feature to block input for some moments after input was made. 
@LemurShteel, not sure if you are still using dialogic but if so, maybe you could try this again with the latest alpha9 release?

Alternatively we can still go for the device check.

**Comment by LemurShteel** [comment]
> There is now a feature to block input for some moments after input was made. @LemurShteel, not sure if you are still using dialogic but if so, maybe you could try this again with the latest alpha9 release?
> 
> Alternatively we can still go for the device check.

Checked on Godot 4.1.1, Dialogic 2.0 Alpha 9
Samsung Tab S7FE, Android 13. Empty project, just created timeline with bunch of lines with text and wait.
Works with both tap input and S-Pen input, lines dont skips. Wait works as intended.

**Comment by Jowan-Spooner** [comment]
That's great, thank you for the testing!
