### ISSUE TITLE
My dialogue crashes when a character spawns with "At the position" greater than 4.

### ISSUE THREAD

**Issue by EmmanuelHuazo** [coppolaemilio/dialogic#1474]
When the value "At the position" in the timeline editor is greater than 5 it crashes my game.

**Describe the bug**
As I already said, I was playing with the positions that the character can have and I discovered that if a character uses a value greater than 4 (5,6,7,8,9, etc) the game crashes.

Also, it seems that putting a negative value doesn't move the character to the left.

**To Reproduce**
Steps to reproduce the behaviour:
1. Just put a value bigger than 4.
2. I was using 3 characters at once.

**Expected behaviour**
it crashes.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4
 - Dialogic Version: alpha 6

![Captura de pantalla 2023-03-19 111506](https://user-images.githubusercontent.com/79464276/226194646-c350766d-ad25-4cfe-8baa-72c01c73c917.png)
![Captura de pantalla 2023-03-19 111542](https://user-images.githubusercontent.com/79464276/226194671-97084357-cd2b-4fcc-bf73-4275ec2c90f8.png)
![image](https://user-images.githubusercontent.com/79464276/226194680-e230742f-d140-4497-8f53-378911e3f56b.png)

**Comment by Jowan-Spooner** [comment]
This is somewhat "expected" as the default scene only comes with 5 portrait positions. 
Ideally there shouldn't be crash, only a warning.
