### ISSUE TITLE
Godot shows error in the gd script file

### ISSUE THREAD

**Issue by NothingAnimated** [coppolaemilio/dialogic#148]
Godot shows the bug "The identifier "DIalogicSingleton"isn't declared in the current scop"
how do I fix this? the gdscript file is called "Dialogic class"
![image](https://user-images.githubusercontent.com/69369888/113491991-c4111a00-94a2-11eb-9bf7-9405e866f403.png)

**Comment by ellogwen** [comment]
Is the plugin enabled? Can you show us complete output?

**Comment by NothingAnimated** [comment]
plugin is enabled
and I don't know what you mean by complete output?

**Comment by ellogwen** [comment]
On the bottom there is a panel called "output"
are there any error messages before that?

**Comment by NothingAnimated** [comment]
no

**Comment by ellogwen** [comment]
Ok, so this is when you start your game.
Did you freshly installed the plugin or did you use it before and it stopped working?

**Comment by NothingAnimated** [comment]
freshly installed

**Comment by ellogwen** [comment]
Ok, please make shure that the plugin is installed in
res://addons
so that the struture looks like:
res://addons/dialogic

And please make sure that the plugin is enabled via Project Settings > Plugins > Dialogic > Status > Enabled (Checkbox checked)
After that restart the Godot editor

**Comment by NothingAnimated** [comment]
ok

**Comment by ellogwen** [comment]
If the plugin is installed correctly, there should be a "DialogicSingleton" in Project > Settings > AutoLoad > DialogicSingleton that is Singleton > Enabled checked

**Comment by ellogwen** [comment]
Since he did not respond back I assume it was an installation/Godot issue, so this ticket can be closed.
However, maybe I we add a check at startup for the Singletons and throw a more readable error

**Comment by coppolaemilio** [comment]
Yes, I'll close because they didn't even use the template for bug reports so we have no information. Please, if you post a bug report show the entire screen when doing a screenshot or tell us what version of Dialogic are you using and what version of Godot you are running.
