### ISSUE TITLE
Expand towards UI strings

### ISSUE THREAD

**Issue by stephanbogner** [coppolaemilio/dialogic#1481]
**Is your feature request related to a problem? Please describe.**
- Dialogic is perfect for text content, so it seems attractive to manage every kind of text through it
- My main idea would to use it to manage all user interface strings ("New game", "Quit", "Mouse sensitivity", etc.).
- → This would would streamline working with translators
- → And it would unify the logic for handling translations inside the game (e.g. default locale)

**Describe the solution you'd like**
- Possibly similar to the Glossary approach: You can create documents (analogue to glossaries), e.g. a "Settings" document
- Then a simple JSON-like key-value relationship might be enough: `"controls_title": "How to control the player:"`
- The most important aspect probably would be to allow translations (like for timelines)

**Describe alternatives you've considered**
- Making a custom solution, e.g. having a json-file for each language (like it's common in web development)
- Abusing the glossary feature (which lacks the translation option if I saw correctly)

**Comment by Jowan-Spooner** [comment]
Hi @stephanbogner.
I can see this being handy, but I doubt the core maintainers will implement this soon. 

For me the most interesting question would be: why as a part of dialogic and not a separate plugin?

I could see multiple reasons:
- it would make dialogic a more complete package for creating full visual novels
- it could take advantage of already existing ui/systems (variables, glossary, etc.)

You've mentioned translations: are there any other things you would want this system to do? If it's just that using godot's built in translation system might honestly be easier, idk.

Luckily dialogic 2 is very modular so making something like this as an extension would also be possible pretty easily (meaning the integration is easy, not the actual building of the thing itself necessarily).

Could be cool to have this imo, but we'll have to see where it goes.

**Comment by stephanbogner** [comment]
@Jowan-Spooner Thanks for your quick reply and no worries regarding implementation: I wanted check out if I oversaw something and also if there would be interest, or if it's just me.

**Context:** I am currently working with a friend on our first commercial game (after experiments, gamejams, etc.) and I want to make sure that we choose solutions that allow the complexity required / make our lives easier.

> For me the most interesting question would be: why as a part of dialogic and not a separate plugin?

> You've mentioned translations: are there any other things you would want this system to do? If it's just that using godot's built in translation system might honestly be easier, idk.

I am looking at it in terms of workflows/systems:
- I think if a game is made in only one language then a seperate plugin would be fine. Because the logic to _display_ dialogue is different from other text like UI and loading the strings from different sources is not a problem.
- But if I have text in my game (no matter if it's dialogue, shown in the game world or as part of a menu) that should be translated it gets interesting:
- Taking advantage of Dialogic's features for all text content (especially the CSV export and import) would reduce it to one system, which would be amazing.
- This would also streamline working with translators because they would only need to deal with one type of file

**But** ... now that I read more about Godot's implementation, there of course is also the case of translated audio files (which I won't have but nevertheless) and then there would be the question:
If now all text content is in Dialogic, then why not expand to audio content as well.
But then Dialogic becomes a library for dialogues AND translations which wouldn't be very focussed :sweat_smile:.

**It would be cool if Godot could take care of the i18n bit and Dialogic would hook into that:**
Then it would be best of both: A streamlined workflow for translating provided by Godot and a robust Dialogue system via Dialogic.
(Some wishful/random thinking there obviously)

It's not easy to decide where to draw the line, because probably also the glossary feature goes much further than what Dialogic's main use case is :thinking:

**Comment by thebardsrc** [comment]
will do, thank you :)
