### ISSUE TITLE
Old, Empty Definitions cannot be Read

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#1482]
## The problem

**Describe the bug**
I cannot begin conversion because `res://dialogic/definitions.json` cannot be read. My project has no definitions, so `definitions.json` is empty.

**To Reproduce**
1. Open a project that has just has its Dialogic upgraded from 1.x to 2.0-x
2. If haven't, go to Project > Project Settings > Plugins and enable Dialogic.
3. Go to Dialogic > Settings > Dialogic 1 Converter
4. Click "Verify Files"

**Expected behavior**
For the empty `definitions.json` to be checked as no definitions and move on.

**Screenshots**
![dialogic_forward](https://user-images.githubusercontent.com/15977859/226864933-2c98c12b-7a0b-48bd-83bf-3174ac609b9f.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: v4.0.stable.official [92bee43ad]
 - Dialogic Version: 2.0-Alpha-6

## Solutions

**Workaround**

I ~could delete `definitions.json`~ or ~fill the content with `{}` as an empty dictionary~.
* Deleting `definitions.json` will only cause the conversion to detect the file missing first.
* I've tried the latter and the output no longer states that as an issue. However, "Begin Conversion" is still disabled:
![dialogic_forward2](https://user-images.githubusercontent.com/15977859/226870540-e7de9a92-01f8-4cf9-9849-9805b3f0d7ec.png)

Maybe ~having 1 theme is what's preventing "Begin Conversion" from being enabled~.

Nope, still not it:
![dialogic_forward3](https://user-images.githubusercontent.com/15977859/226880137-4011229b-bb7f-4d64-b6d1-d05e8c67a189.png)

This is the output message I've got by pressing "Veryfy Files":
```
  res://addons/dialogic/Events/Converter/settings_converter.gd:117 - Invalid get index 'variables' (on base: 'Dictionary').
```

**Possible fixes**

I could look at the script responsible for the conversion to see how it works.

**Comment by Jowan-Spooner** [comment]
Hi, thanks for the report. The converter hasn't been touched in a while so I assume there is a number of problems. If you find a solution let us know, otherwise you might have to wait until @thebardsrc can take a look at the converter again.

**Comment by mechPenSketch** [comment]
This is an update on the solutions after reading through the error output.

The second solution works after all, only that instead of being an empty dictionary, `definitions.json` should contain:
```
{
	"variables":{},
	"glossary":{}
}
```

**Comment by mechPenSketch** [comment]
I still have issue converting, but as it's no longer caused by empty definitions, it'll be reserved for another thread.
