### ISSUE TITLE
Dialogic 2 Variable not callable if nested in variable folder

### ISSUE THREAD

**Issue by metanoder** [coppolaemilio/dialogic#1484]
## The problem

**Describe the bug**
In Dialogic 2, variables in the dialogic editor's variable tab, are not assessable from user generated timeline script, if the variable is  nested in variable folder.  It does work when it is flat dictionary, but not assessable when nested from what I found.  

**To Reproduce**
1. create new timeline
2. create character profile named "foo" with {character variable} in character editor section "Display Name" 
3. create variable in variable editor labeled: {character variable} = "bar"
4. create folder and move {character variable} into newly created "character" folder
5. In new timeline, try accessing variable by typing in character "foo".

**Expected behavior**
I expect to have my variables accessible, even though it is nested inside a folder from the variable tab. 

**Screenshots**
<img width="924" alt="Screenshot 2023-03-22 at 10 19 26 AM" src="https://user-images.githubusercontent.com/117393840/226986603-7467b30e-eacf-4fff-9b0e-1c44a8c84237.png">

<img width="1044" alt="Screenshot 2023-03-22 at 10 13 31 AM" src="https://user-images.githubusercontent.com/117393840/226986631-5cdea0f1-9ac9-405a-a575-5e3e3b48817f.png">

<img width="735" alt="Screenshot 2023-03-22 at 10 20 10 AM" src="https://user-images.githubusercontent.com/117393840/226986671-fc8af247-26a4-4b63-a438-73f59d73250d.png">

<img width="556" alt="Screenshot 2023-03-22 at 10 19 38 AM" src="https://user-images.githubusercontent.com/117393840/226986686-8a2cdf6f-07bc-4b61-898d-723cc2cca489.png">

<img width="572" alt="Screenshot 2023-03-22 at 10 19 49 AM" src="https://user-images.githubusercontent.com/117393840/226986704-b0776d08-cd1d-4159-88d0-5d6daca81099.png">

**System (please complete the following information):**
MacOS
Godot 4.0.1
Dialogic 2 alpha 6, latest commit wed mar 22 [47b8aea]

Folders are still needed to use the dialogic converter.  Maybe create a flat structure once it's converted to help accessibility.  

What you tried to get the feature working:
Just keeping inside the functional scope of the feature.  Keeping a flat variable structure with naming conventions.  Not exactly ideal.

**Comment by metanoder** [comment]
@Jowan-Spooner 

Ah, for sure.  Yea, I misunderstood there when calling the character from the timeline.  That does help with the connection between the timeline, character profiles, and variables.  Thank you for explaining that.

But I think I wasn't communicating clearly either, I mainly was wondering about nested variables in variable groups.  What is the procedure to access the nested variable?

<img width="743" alt="Screenshot 2023-03-22 at 11 52 00 AM" src="https://user-images.githubusercontent.com/117393840/227008892-a03406a4-b413-4229-80fe-81b912333f70.png">

**Comment by Jowan-Spooner** [comment]
Oh, right, I forgot to mention: Dialogic uses dots to separate groups (e.g. `{character_group.character_name}`). 

I thought this was shown in the text in the variables editor, maybe it's not. 

This is to make it more similar to how they can be accessed in code (e.g.: `print(Dialogic.VAR.character_group.character_name)`)

**Comment by metanoder** [comment]
@Jowan-Spooner You're absolutely right.  🤦🏻‍♂️ User error.  Personal flaw.  I get tunnel vision and didn't even see that it's sitting right there.  Like I'm holding the manual, and not noticing it's in my hand.  Thank you for your patience.

**Comment by metanoder** [comment]
Works like a charm.  Really brilliant system.  And it's obviously, explicitly right in your face.  I think I'm the 1% who neglected to see it.  Thank you!

**Comment by Jowan-Spooner** [comment]
No problem. I'm wondering though: the text editor should autocomplete/suggest your variable names when you type {. Does that work for you? Because it should automatically suggest the correct path's with the dots.

**Comment by metanoder** [comment]
oh **WOW** 👀!  Yes, yes it does.  I never realized, since I just been only doing narrow tests with it for the dialogic converter, and I don't type out anything out first before trying to access it, like you would.  

Before you explained it, the link I had in my mind earlier between the timeline and character profiles, coupled with narrow testing, would explain why I probably had not triggering it up to this point. 

So you have to type something in the editor to activate it?  **Phenomenal**.  Well done @Jowan-Spooner 👏🏼🍻
