### ISSUE TITLE
Can't connect the signal 'timeline_ended' in my script. Noob Friendly 👍

### ISSUE THREAD

**Issue by Siberius56** [coppolaemilio/dialogic#1485]
## The problem

**Describe the bug / Expected behavior**
When I want to connect the signal 'timeline_ended' to my script to start a new function, when the dialog is over, it seem that nothing is emitting or connected ? Did I miss something in my code or am I doing it wrong ?

**Screenshots**
Here i have created the dialog and then connected the signal 'timeline_ended' to my function 'dialog_is_over':
![image](https://user-images.githubusercontent.com/22679433/227045132-7ab07bf6-8c68-4055-a430-124fff7a12f9.png)

Here is the function 'dialog_is_over':
![image](https://user-images.githubusercontent.com/22679433/227045928-a7646bca-e629-4712-81ef-439db7ad7d41.png)

When I'm in the game and the dialog end, I can see the print is writing has expected (this is in the script 'DialogicGameHandler.gd') but my function 'dialog_is_over' never play:
![image](https://user-images.githubusercontent.com/22679433/227046429-f928fb3a-0d3d-4413-a7d0-7f7054b1fa37.png)
![image](https://user-images.githubusercontent.com/22679433/227046291-ed91d453-437b-4517-a58b-a85bdc6b2d11.png)
![image](https://user-images.githubusercontent.com/22679433/227045236-a5f3b1d4-8e19-4073-8bec-297303752b46.png)
![image](https://user-images.githubusercontent.com/22679433/227045274-620b70ca-ae71-486e-8689-56c02821b7d0.png)

**System:**
 - OS: Windows 10
 - Godot Version: 4.0
 - Dialogic Version: 2.0 Alpha 6

Thank in advance for any help or fixe you could fine :)

**Comment by Jowan-Spooner** [comment]
Hi, this seems like a misunderstanding. 
In dialogic 2 timeline_ended is a signal of the Dialogic autoload. This means a correct connection should look like this:
```gdscript
Dialogic.start("res://path_to_timeline.tml")
Dialogc.timeline_ended.connect(my_function) # alternatively my_func.bind(@arguments) if arguments are wanted
```
*Note that to correctly connect connect you should not have brackets after the function name and it shouldn't be a string either.*

Also note that in dialogic 2 adding the result of the Dialogic.start() method is not needed.

**Comment by Siberius56** [comment]
Oh, I feel a bit stupid, indeed :D
Thank you very much for your reactivity

**Comment by Jowan-Spooner** [comment]
Oh no need to feel stupid, there is so little documentation right now and things have changed quite a bit from 1.x so confusion is kindof expected in the alpha stage ;-)
