### ISSUE TITLE
Dialogic is wrongly read as a Class when it's supposed to be a Singleton

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#1489]
## The problem

**Describe the bug**
Godot engine reads `Dialogic` as a missing class when it's supposed to be a singleton.

As the result, enabling `Dialogic` as the plugin does not add Singleton `Dialogic` to autoload, as its name is shared with the non-existent class.

I also cannot run my project because of the missing `Dialogic` class.

**To Reproduce**
1. Add `addon/dialogic` to your project.
2. Open the project.

**Expected behavior**
Maybe a bit of error messages for missing `Dialogic`, but I can enable the dialogic plugin and `Dialogic` will then be added to Autoload.

**Screenshots**
Opening the project.
![dialogic](https://user-images.githubusercontent.com/15977859/228533055-7425a932-c4c3-47fb-b349-37a6c82bd6f5.png)

Full Error Output
```
  res://addons/dialogic/Events/Text/event_text.gd:91 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/event_text.gd:141 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:11 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:13 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:13 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:13 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:14 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:17 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:17 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:18 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:19 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:26 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:33 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:34 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/default_input_handler.gd:38 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:88 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:90 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:117 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:119 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:142 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:144 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:164 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:166 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:252 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Character/event_character.gd:299 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:43 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:54 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:56 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:56 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:62 - Parse Error: Could not find script for class "Dialogic".
  res://addons/dialogic/Events/Text/node_dialog_text.gd:65 - Parse Error: Could not find script for class "Dialogic".
```

Enabling Plugin Dialogic:
![dialogic2](https://user-images.githubusercontent.com/15977859/228533550-a6b2101e-2de6-4479-9f96-701a26621ed1.png)

About to type in "Dialogic" in the script. Dialogic is marked with an Object icon when it's supposed to be marked with the class icon.
![dialogic3](https://user-images.githubusercontent.com/15977859/228536183-8186eaa7-39d3-4ff2-aaa5-356fe39282c3.png)

For reference, my separate singleton, "GlobalOverworld", has the class icon.
![dialogic4](https://user-images.githubusercontent.com/15977859/228536536-25399b12-8bf4-42b8-9629-e038bbf9924f.png)

**System (please complete the following information):**
- OS: Windows 10
- Godot Version: v4.0.stable.official [92bee43ad]
- Dialogic Version: 2.0-Alpha-6

## Solutions

**Workaround**

I've tried a few, [as shown in this thread](https://github.com/coppolaemilio/dialogic/discussions/1483), but to no avail.

I have successfully added Singleton `Dialogic` into the autoload by manually editing `project.godot` with a text editor. Despite this, the engine does not recognize `Dialogic` as a singleton but still a missing class.

**Possible fixes**

So far, I have thought of two:
1. Go to the Godot Engine to make it account that the "missing class" could plausibly be a missing singleton. That way, when a new singleton is attempted to be added, the message will check whether it's supposed to fill in the missing singleton.
2. Replace all `Dialogic` word (matching case) in all plugin scripts with `get_node(root/Dialogic)`.

**Comment by Jowan-Spooner** [comment]
Hhmm... I cannot  replicate this.
I've done this:
- created a new godot project (godot 4.0.1 stable)
- created an addons folder and copied the dialogic folder into it
- restarted the godot project
- enabled the plugin
- restarted again
- I do not get any errors anymore, the plugin is enabled and the autoload added correctly. 

Did you have dialogic 1 installed in this project before?
Sometimes godots cash get's in the way as it is not correctly cleared. Maybe try deleting `global_script_class_cashe.cfg` in the `.godot` folder before installing dialogic?

**Comment by mechPenSketch** [comment]
^ My project had Dialogic 1 before. Would try your suggestion next....

**Comment by mechPenSketch** [comment]
Maybe in the future, I should keep the project opened while upgrading Dialogic so that in the process, it will read the new files added whether they have a class name.
