### ISSUE TITLE
Add music signal for use with custom music players

### ISSUE THREAD

**Issue by zextillion** [coppolaemilio/dialogic#1491]
I'm integrating Dialogic into an already existing project, and one issue I see is that Dialogic's music events is managed... well, by Dialogic. This is fine on its own if the project is built with Dialogic in mind from the start, but integration into already existing music players can feel janky.

What I'd like is a toggleable option in the settings where instead of having music events use the Dialogic music player, to instead emit a music_update_requested signal on the base Dialogic singleton. This way, users can hook up the Dialogic music events using Dialogic timelines with music players outside of the Dialogic addon.

A similar system could probably be set up for sound effects too.

**Comment by Jowan-Spooner** [comment]
Hmm... I understand where you are coming from, but wouldn't it be easier to just use the signal event then? Alternativly creating a simple custom event that is tailored specifically to your audio system would be pretty easy too. 
There are plans to add many more signals to all the subsystems though, so maybe this can be implemented later.

**Comment by zextillion** [comment]
The generic signal event right now is a bit limited, as the only argument you can pass it is a string. I think it would be a better if the argument for the signal event could be set to a dictionary, or preferably any type. 

Or figure out a way to dynamically create signals. I think Godot 4 features a way to dynamically create and attach signals to objects, which in this case would be the main Dialogic singleton. But that's a whole other feature that deserves its own proposal.

One workaround I can do right now is to use the Call Node event; it looks like I can use custom arguments for it, but again, it's also limited in that it seems like the only argument type it will take are strings. And it's a little clunky to do this every time I want to play music.

**Comment by Jowan-Spooner** [comment]
Hi. The big signal update included some signals that might help with this, `sound_started` and `music_started` In theory you should be able to use your own audio players by "disabeling dialogics audio players". Although there is no built-in way to do that, something like this might work (pseudo-code, not tested):
```
func _ready():
    Dialogic.Audio.base_music_player.process_mode = PROCESS_MODE_DISABLED
    Dialogic.Audio.base_sound_player.process_mode = PROCESS_MODE_DISABLED
    
    Dialogic.Audio.music_started.connect(play_music)
    Dialogic.Audio.sound_started.connect(play_sound)

func play_music(info:Dictionary):
     # do whatever you want. 
     # info contains the path, volume, bus and loop info
     # same goes for play_sound
     pass 
```
Maybe this helps.

**Comment by Jowan-Spooner** [comment]
I will consider this closed. If there is interest in further developement feel free to reopen or start a new issue.
