### ISSUE TITLE
Set Variable Doesnt Work

### ISSUE THREAD

**Issue by NHodgesVFX** [coppolaemilio/dialogic#1499]
## The problem

**Describe the bug**
When setting  variable var_1 to "a different text" in the timeline the below error occurs. One thing I noticed is that the invalid named index  in the error has so far always been the first word or character (anything before the first space) of the string you are trying to set the variable to.

```
Dialogic: Expression failed to execute: Invalid named index 'a' for base type Object
Dialogic: Failed accessing 'a different text'.
```

**To Reproduce**
1.  Create a variable, set the name and the value to something.
2.  Within a timeline add a set variable node, select the variable you created earlier, set the to be field to something different than specified in the step above.
3.  Below the set variable node add a text node that shows your variable. For example "{my_var}"
4.  Press the play timeline button

**Expected behavior**
The variable is set and displays the newly set value not "null" and no errors are printed.

**Screenshots**
![image](https://user-images.githubusercontent.com/11403345/229363973-43f0adc0-9684-42f6-a020-a24b62ed7f82.png)
![image](https://user-images.githubusercontent.com/11403345/229363993-c1cc510f-2282-4d85-a0ca-f41f3ff84ba7.png)

**System (please complete the following information):**
Godot Engine v4.0.1.stable.official.cacf49999 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2080 SUPER
Windows 11
 - Dialogic Version: main branch

## Solutions

**Workaround**

Tried various ways of grouping the variable and placing the set variable node somewhere else but I have not found a workaround.

**Possible fixes**

**Comment by Jowan-Spooner** [comment]
I will check it out! Thanks for the report.

**Comment by Jowan-Spooner** [comment]
Sorry this was auto-closed by the PR I just pushed. I hope it actually fixes the issue for you. Maybe you can try again with this fix?

**Comment by NHodgesVFX** [comment]
Thanks for the quick fix, I can confirm that set variable is now working!
