### ISSUE TITLE
[1.0.1] Can't get a Dialogic window to show up.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#150]
## The problem

I strongly suspect this is user error rather than an actual bug in Dialogic, but anyway. I have a scene with a `Node2D` root node. I've set up Dialogic with a test theme, test character and test timeline.

The script:
```
onready var xxx = Dialogic.start ("sslaxx_test_talk")

func _ready () -> void:
	print_debug (get_script ().resource_path, " ready. Node ", self, " (", self.name, ").")
	call_deferred ("add_child", xxx)
	print (xxx)
	return
```
`xxx` is a valid variable result - `[Control:xxxx]`. I have tried using both `add_child` and via `call_deferred` with the same non-result. Nothing shows, no prompts, and it appears to be non-responsive. I know the node is being loaded as when I added background music, it plays (just nothing else seems to work).

**Expected behavior**
Expected behaviour is the timeline being played out.

**Screenshots**
![Dialogic_woes](https://user-images.githubusercontent.com/324679/113508100-093a5800-9546-11eb-8a4e-5e4bc5805d39.png)

**System (please complete the following information):**
Linux (Ubuntu 20.10, 64-bit); Godot 3.2.3; Dialogic 1.0.1.

Attached the project as well: https://www.dropbox.com/s/nrf0v6i60w9gqqf/150_demonstrator.7z?dl=0

**Comment by ellogwen** [comment]
do not try onready var the dialog try it like this:
```
var dialog = null

func _ready():
    dialog = Dialogic.start(<my_timeline>)
    add_child(dialog)

on some occasions you need to add a Canvas Layer to your Level und attach the dialog there. it depends on your project structure
```

**Comment by Sslaxx** [comment]
I did try it without `onready` as well, same result.

Adding a `CanvasLayer` makes it work as expected. However, it'd be nice (if possible) for Dialogic to give a warning/error about viewport visibility.

**Comment by coppolaemilio** [comment]
Yes. It would be nice to send a warning if the node has been added to a non-control/canvas layer node.

**Comment by Sslaxx** [comment]
The documentation is not at all clear about what type of nodes work best with Dialogic.

**Comment by coppolaemilio** [comment]
yeah, there is a lot that has to improve on the documentation. Specially making a proper user guide.

**Comment by Jowan-Spooner** [comment]
I think this issue could be closed. @coppolaemilio In case you want to keep track of the mentioned problems I would suggest creating new, seperate issues.

**Comment by coppolaemilio** [comment]
I want to keep it open so I remember to address it 😅

**Comment by Sslaxx** [comment]
Fixed by https://github.com/coppolaemilio/dialogic/commit/cba8dbcd708acb571d7f4fdcf82abfce6c5e9191
