### ISSUE TITLE
Customize player name with dialogic 

### ISSUE THREAD

**Issue by MrAnonymous96** [coppolaemilio/dialogic#1516]
I am trying to set up where the player can create their own player name through dialogic but I don't know how.  I suspect it's done through the character file and creating a json file.  But I'm not sure.  I can get it running but I can't get it do what I want.  Plus help
![20230417_002636](https://user-images.githubusercontent.com/131008352/232527320-3b0dd2d0-8f60-4c45-9535-51a50ce41df3.jpg)

![20230417_002440](https://user-images.githubusercontent.com/131008352/232527365-68c3628d-79c1-4118-be63-46b1b0625283.jpg)

![20230417_003055](https://user-images.githubusercontent.com/131008352/232527292-99bf1871-385a-4436-9b29-91f08a93c36c.jpg)

![20230417_002404](https://user-images.githubusercontent.com/131008352/232527270-d9992ed0-e8b7-4c16-a1b9-035c6d2bd6b6.jpg)
![20230417_002414](https://user-images.githubusercontent.com/131008352/232527279-6a54d71e-794c-48e4-96f6-5faab2cb8cf1.jpg)

**Comment by Jowan-Spooner** [comment]
You likely need to add a variable definition named Buddy too for this to work.

**Comment by Jowan-Spooner** [comment]
Could you please let us know if adding a "Buddy" definition fixed this for you? Otherwise I will have to close this soon.

**Comment by MrAnonymous96** [comment]
I tried that, but it didn't work

**Comment by Jowan-Spooner** [comment]
Alright, thanks then maybe @zaknafean has to take another look. Personally left 1.x behind a long time ago...

**Comment by MrAnonymous96** [comment]
I know how to do this on renpy.  I'm new to godot, and I'm still learning.
so I tried to figure out what I'm doing wrong. Unfortunately, anytime I ask
either reddit or someone on YouTube it seems they don't know for sure
either.  There must be a way to do it but I don't know how to do that.

**Comment by coppolaemilio** [comment]
If you are not too far into development I would recommend you to start with Godot 4 and Dialogic 2. It is pretty simple to do something like this in the new Dialogic, even if it is still not officially released.

**Comment by zaknafean** [comment]
Sorry only just saw this. So this works, but you're slightly overcomplicating things. Dialogic will handle the definition for you, but you have to set it up ahead of time. I'll attach a quick video of it working in action. 

https://user-images.githubusercontent.com/7741797/235303919-fbefbf10-930b-4495-86ef-d53f751391b2.mp4

And the relevant screenshots in Dialogic
The Timeline
![image](https://user-images.githubusercontent.com/7741797/235303961-4ef625d4-8cac-4a4b-845c-a4e4de4e56e6.png)
The Character
![image](https://user-images.githubusercontent.com/7741797/235303976-89b553ef-f8e1-4199-9145-a4d472a5a681.png)
and critically, the definition
![image](https://user-images.githubusercontent.com/7741797/235303999-267d43ce-e0c9-4b24-8fb0-119009174770.png)

Within your script, here is where the defintiion is being set:
![image](https://user-images.githubusercontent.com/7741797/235304021-642f34f5-4445-41f1-af4c-c68b396ee806.png)

You aren't and do not need to edit the JSON directly. Let the definitions do the work

**Comment by MrAnonymous96** [comment]
Thx for getting back to me.  I'll definitely look into it.  If I'm able to
get working I'll show you my progress just in case.  Because I would like
to use it, because it does have a good set up, and helps to reduce errors.
I can't say the same thing with Renpy where the coding was easy but I ran
into huge problems.

**Comment by Jowan-Spooner** [comment]
@MrAnonymous96 let us know if this was fixed or abandoned, so we can close this.

**Comment by MrAnonymous96** [comment]
No, it has not.

**Comment by metanoder** [comment]
Following zaknafean's process, I can confirm it works like a charm for dynamically changing character names.  I think if you follow zaknafean's process, you should be able to get what you're looking for.


https://github.com/coppolaemilio/dialogic/assets/117393840/58ffacbb-b239-4d70-b607-cd828561fc1e
