### ISSUE TITLE
How To: Use Portraits

### ISSUE THREAD

**Issue by ZedCode** [coppolaemilio/dialogic#152]
**Is your feature request related to a problem? Please describe.**
I have no idea how to use the portrait feature

**Describe the solution you'd like**
documentation or a link to documentation from the main `readme.md` file

It seems like portrait settings should be in theme, but I don't see anything. I'm using the 1.0.1 release.

**Comment by Sslaxx** [comment]
As in portraits for characters? When you create a character, there's a "Portraits / Expressions" section.

![Portraits_via_Characters](https://user-images.githubusercontent.com/324679/113523217-5e09bd00-959e-11eb-80d9-50f0d5eacb11.png)

**Comment by ZedCode** [comment]
Yes, do you have to do something to make them show up? A minimum resolution? When I add one I don't see it displayed. Perhaps this is actually a bug?

**Comment by Sslaxx** [comment]
Just edited my response to talk about actually getting the characters to show. This is another documentation issue.

**Comment by ZedCode** [comment]
![image](https://user-images.githubusercontent.com/5529651/113523323-195d3200-955c-11eb-9393-1c9b79891da2.png)
![image](https://user-images.githubusercontent.com/5529651/113523328-1eba7c80-955c-11eb-9db0-6fd2c8bc803d.png)
Yet in the game I don't see anything in the selected position

**Comment by Sslaxx** [comment]
Well, try setting scale to 100% and see if anything shows up then.

**Comment by ZedCode** [comment]
changing to 100% didn't seem to help, but it did get me to go digging around the json:
from the `character-xxxx.json`:
```
{"color":"#ff9496fd","default_speaker":false,"description":"","display_name":"","display_name_bool":false,"id":"character-1617546291.json","name":"Bill","offset_x":0,"offset_y":0,"portraits":[{"name":"Default","path":"res://assets/images/portraits/bill.png"}],"scale":100}
```
from the `timeline-xxxx.json`:
```
{"events":[{"action":"join","character":"character-1617546291.json","portrait":"","position":{"0":true,"1":false,"2":false,"3":false,"4":false}},{"character":"character-1617546291.json","portrait":"Bill","text":"Hmmm...that appears to be... \n[item_description]"},{"action":"leaveall","character":"[All]"},{"close_dialog":""}],"metadata":{"dialogic-version":"1.0","file":"timeline-1617546838.json","name":"BillExamines"}}
```
it looks like I somehow did something that caused it to not read the portrait into the json for the timeline.

**Comment by ZedCode** [comment]
Now the text above the dialogue vanished and I can't help but think they're related.

Preview:
![image](https://user-images.githubusercontent.com/5529651/113525455-ea4dbd00-9569-11eb-9234-40237ea91ca0.png)

In game:
![image](https://user-images.githubusercontent.com/5529651/113525465-f5a0e880-9569-11eb-9fa9-b6c05953e015.png)

**Comment by ZedCode** [comment]
found I needed to set offset for y to -600+ for him to show up properly
![image](https://user-images.githubusercontent.com/5529651/113528286-fee38280-9574-11eb-9aff-4cabeb0fad15.png)
