### ISSUE TITLE
Hidden layout node still filters mouse input

### ISSUE THREAD

**Issue by KoB-Kirito** [coppolaemilio/dialogic#1553]
I tried to use the feature to hide and reuse the layout node instead of deleting it after every dialog, to save performance (as reinstancing often is wasting resources). But there is a problem:

## The problem

**Describe the bug**
The layout node blocks mouse input, also while hidden.

**To Reproduce**
1. Go to Dialogic>Settings>General
2. Click on 'On timeline end'
3. Change to 'Hide'
4. Create a scene where you want to have dialog, but still need to look for mouse input afterwards (_gui_input)
5. Don't receive _gui_input

**Expected behavior**
The layout node to ignore inputs while hidden.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51691757/236899896-c8b4caaf-7a3e-4cbb-98dc-4f4a3af0f091.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0.2.stable
 - Dialogic Version: 2.0-Alpha-7

## Solutions

**Workaround**
Keep the setting on 'Delete Layout Node', reinstancing it everytime.

**Possible fixes**
Set mouse_filter to ignore, when hiding the layout.

**Comment by Jowan-Spooner** [comment]
I cannot reproduce this. @KoB-Kirito could you test if this still happens to you with the latest alpha9 release?

**Comment by KoB-Kirito** [comment]
Will test later.

**Comment by KoB-Kirito** [comment]
Well, it doesn't block input at all now. So what should I test?
[DialogicTest.zip](https://github.com/coppolaemilio/dialogic/files/12501355/DialogicTest.zip)

**Comment by Jowan-Spooner** [comment]
You mean it's a bug that it doesn't block input now? or is that a good thing? Would you consider this issue still relevant is what I'm wondering.

**Comment by KoB-Kirito** [comment]
Well, not a bug, but a hassle imho. If you use a layout like that, you almost always want it to block input. Just removing that cause it's easier feels cheap. Sure, this issue is solved if it doesn't block input at all, but it's replaced by another.
I think the default behavior of dialog should match what most use-cases would expect. If you try to add dialog into any game that has gameplay in the background, you need the dialog to block input, also you mostly want to pause the game, or cut input to the player at least. Requiring the dev to add those makes dialogic harder to use. It should at least be simple.

**Comment by Jowan-Spooner** [comment]
I'll consider this closed.

The intention is:
- Custom layouts have to decide on their own whether they want to block input or not.
- The default layouts won't block input as it's annoying when not needed.
- For use in-game what happens to the game "behind" the dialog has to be decided by the user. Some games might have a global state for dialog (that prevents other gameplay from advancing), some might just pause the game and set Dialogic to keep running. It's possible we add easier method to pause the rest of the game while dialogic is active, but that's a separate issue.
