### ISSUE TITLE
Link Characters & Portraits in wiki

### ISSUE THREAD

**Issue by GodoterFR** [coppolaemilio/dialogic#1555]
Just wrong link at this page :
https://github.com/coppolaemilio/dialogic/wiki/Tutorial:-Getting-Started

> You can learn more about portraits, custom portraits and the character settings in this tutorial: [Characters & Portraits](https://github.com/coppolaemilio/dialogic/wiki/Docs:-Characters-and-Portraits)

github.com/coppolaemilio/dialogic/wiki/Doc _s_ :-Characters-and-Portraits

Need delete the 's' to Doc in the link.

**Comment by Jowan-Spooner** [comment]
Thanks!
