### ISSUE TITLE
Example Asset portraits animation bug

### ISSUE THREAD

**Issue by non-nattawut** [coppolaemilio/dialogic#1557]
## Example Asset portraits animation bug

**Describe the bug**
I try to use portraits animation from CustomPortrait_AnimatedSprite.tscn
so I found that in godot 4 can not use it anymore

**To Reproduce**
1. Create character
2. use Scene as a portrait follow to step 3
3. use CustomPortrait_AnimatedSprite.tscn in addons -> dialogic -> Example Assets -> portraits
4. found an error

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/255338de-ec0f-4422-b53a-6a5ee86e8026)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0.2.stable
 - Dialogic Version: Dialogic 2.0 Alpha 7 (for godot 4.0.2 stable)

## Solutions

**Workaround**

As you can see in **Screenshots** in red rectangle so I solve it by use `sprite_frames` instead of `frames`
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/7e5cd78a-cb35-40e3-916f-0091516c72d6)

**Possible fixes**

so `frames` on line 12-13

but I don't know how `_get_covered_rect()` (line 12-13) work , I try to fixed them but still can't figure it out.
I delete all that call `frames` to this 
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/c721ab28-1948-494c-acc1-a3b572b9c7e3)
it is working OK , at the time I posted this issue I still not face any bug

PS.I don't use `_on_sprite_animation_finished()` function
because I set animation to loop , so it will not error in `_on_sprite_animation_finished()` function

**Comment by Jowan-Spooner** [comment]
Thanks for the issue! The examples are unfortunately rarely up to date and only touched from time to time. For the 2.x release I assume most of them will be removed from the main repo, also to keep the size of the plugin relatively small. They would probably be moved into a separate examples repo where it would be clearer for what version they are intended.
I will however try to fix this as it doesn't seem to complicated and can be useful for further testing of custom portraits.
