### ISSUE TITLE
Choices to answer to Questions don't appear.

### ISSUE THREAD

**Issue by NerdChickenGames** [coppolaemilio/dialogic#158]
## Choices to answer to Questions don't appear

**Describe the bug**
When I add a Question in the Timelines, dialogic stop and no choice appears to the screen. 

**To Reproduce**
1. Create a dialog
2. add a Question
3. Add choices
4. Launch the Debug 
5. No choice appears

**Expected behavior**
Choices to answer to the Question should appear

**Screenshots**
![Capture d’écran du 2021-04-05 16-20-32](https://user-images.githubusercontent.com/81973078/113584201-e897fe00-962a-11eb-9ab8-f81f398540c3.png)

**System (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Godot Version: 3.2.3
 - Dialogic Version: 1.1

## Solutions

No idea...

**Comment by coppolaemilio** [comment]
Yes, there seems to be something wrong on `main`. I'm fixing it right now 👍🏻 thanks for the report!

**Comment by coppolaemilio** [comment]
@NerdChickenGames  Can you try again with the latest version?

**Comment by NerdChickenGames** [comment]
@coppolaemilio Ok it works fine ! Very good job ! I love your dialog system ! It's very fun to use.

**Comment by coppolaemilio** [comment]
Thanks! :)
