### ISSUE TITLE
Glossary paths not working in exported games

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1587]
As @Kozelek discovered glossaries don't work in exported games. 

It turns out godots FileAccess.file_exists() method (as well as listing files with DirAccess) cannot be trusted (across the non-exported to exported border). This is because resource files are removed and/or renamed (ending with a .import or .remap). Confusingly they still work with load() (that one takes imports and remaps into account). 

For now we will have to work around this, but I have asked for the correct way to deal with this on github (https://github.com/godotengine/godot/issues/25672#issuecomment-1571865076).

**Comment by Jowan-Spooner** [comment]
The issue has been fixed, but I would like to keep this open for some time, in case a better solution is brought to my attention, as I'm worried the same thing will be a problem in other areas as well.

**Comment by monitz87** [comment]
`FileAccess.file_exists` is still being used all over the project, and it breaks exported builds in other places (for example, when loading subsystems, it looks for `index.gd` files, which get turned into `.gdc` when exporting). Why not replace all `FileAccess.file_exists` calls with `ResourceLoader.exists`? It's much more robust
