### ISSUE TITLE
I am having trouble using dialogic-1.4.5 plugin

### ISSUE THREAD

**Issue by KFC-Fighter** [coppolaemilio/dialogic#1597]
## The problem

**Describe the bug**
I'm kinda new to Godot programming and I wanted to learn how to use this cool text plugin but I keep getting the Unexpected "Identifer"Class body in Lines 5, 6, and 7. Please help and thank you. I really don't know what's wrong. I just got the latest zip folder and wanted to give this a try.

![Capture](https://github.com/coppolaemilio/dialogic/assets/135555760/1571cc72-e24a-4df0-8ef4-7a82d964d4bd)

![Capture1](https://github.com/coppolaemilio/dialogic/assets/135555760/aa89d55f-fe1d-4394-b2df-d32ec04c3e3a)

**Comment by non-nattawut** [comment]
What godot version do you use?
3.X or 4.X

If you use godot 4.X you must download latest release (dialogic 2.0)
here https://github.com/coppolaemilio/dialogic/releases

**Comment by Jowan-Spooner** [comment]
@KFC-Fighter as pointed out above I think you are using godot 4. Dialogic 1.x is only for godot 3, while dialogic 2.x is for godot 4, so please retry with the latest alpha or the main branch!

**Comment by KFC-Fighter** [comment]
> @KFC-Fighter as pointed out above I think you are using godot 4. Dialogic 1.x is only for godot 3, while dialogic 2.x is for godot 4, so please retry with the latest alpha or the main branch!

I see thank you and sorry for the delayed replay. As of now, I won't use this add-on for the future until an update comes in for Godot 4 update. Thanks for the replay I'm kinda new to this coding website.

**Comment by KFC-Fighter** [comment]
> 

Yes, this is Godot 4 where I'm starting fresh on this software. Also, I may have used the outdated add-on. But when I try using the lastest dialogic 2.x I'm still having the same issue. I'm hoping the creator can make an update video on installing the lastest version because I'm in trouble for some reason.

**Comment by KFC-Fighter** [comment]
> Yes, this is Godot 4 where I'm starting fresh on this software. Also, I may have used the outdated add-on. But when I try using the lastest dialogic 2.x I'm still having the same issue. I'm hoping the creator can make an update video on installing the lastest version because I'm in trouble for some reason.

**Comment by Jowan-Spooner** [comment]
I'm sorry that you had trouble using this version. There will be a walk through tutorial once we reach a beta version. Until then we have to focus on getting the plugin more stable.

**Comment by KFC-Fighter** [comment]
> I'm sorry that you had trouble using this version. There will be a walk through tutorial once we reach a beta version. Until then we have to focus on getting the plugin more stable.

No Worries, I really do appreciate the reply! That really means a lot that we know the project is still in great development and supported! Wish you guys the best!
