### ISSUE TITLE
Uninstallation issue

### ISSUE THREAD

**Issue by Tolly24** [coppolaemilio/dialogic#1604]
## The problem
Getting error messages about not finding the Dialogic files on every run of my project after uninstalling the plugin
I installed this for a project that ended up not needing a dialog system. So I uninstalled it months back and I don't exactly know how but I vaguely remember reading the docs or something telling me to delete the files and going into project settings > plugins and removing it there. 

I did that and now have no files or plugins installed but on every run of my project, I get the same error messages and I've tried to get rid of them several times without ever finding a solution.

**Describe the bug**
I installed this for a project that ended up not needing a dialogue system. So I uninstalled it months back, I vaguely remember reading the docs or something telling me to delete the files and going into project settings > plugins and removing it there. I believe I also had issues installing it as it didn't function properly which might've contributed to this issue. I'm not 100% sure but I might've installed it on a 3.5 version of the project while now I'm on 4.0.2

I did that and now have no files or plugins installed but on every run of my project, I get the same error messages and I've tried to get rid of them several times without ever finding a solution.

**To Reproduce**
Since this happened months ago, I can't really remember how but I believe I just:
1. Deleted the "addons" folder containing the plugin.
2. Removed the plugin within the project settings

**Expected behavior**
Since I believe the installation wasn't done properly. I don't know if this will result in the same behavior. 

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/65282021/032b6ffd-eed9-4284-96d1-d924b5a4e952)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.0.2
 - Dialogic Version: No clue as there are no files left in the directiory.

I don't expect a solution, support or anything but if anyone has any ideas on how to fix this, I'd very much appreciate it!

**Comment by Jowan-Spooner** [comment]
Hey, this could be caused by the godot class cache. I have seen similar stuff multiple times now. 
You can go into the .godot folder of the project and delete the cache file (not super sure what its called rn, but I think you will identify it). This will force the cache to be relisted on the next project start.

**Comment by Tolly24** [comment]
I found the file called "global_script_class_cache.cfg" which only contained entries for Dialogic. I deleted it as you suggested and restarted Godot which does seem to fix it entirely. Thank you!

**Comment by Jowan-Spooner** [comment]
I will consider this fixed

**Comment by squalvj** [comment]
Im encountered this issue as well when I was trying to uninstall it from my project, I'd say this is not fixed and require people to delete the `global_script_class_cache.cfg` too.

Unfortunately deleting the `global_script_class_cache.cfg` fix it but all my scripts that detecting reference to a class are also deleted and required me to re-open all the files that declaring Class.

Would great if we can reopen this and maybe consider deleting the plugin from the cache file when uninstalling it.
