### ISSUE TITLE
The Hide Layout Node Behaviour setting makes the hidden dialog reapear briefly when starting a new timeline.

### ISSUE THREAD

**Issue by phantomdesvin** [coppolaemilio/dialogic#1610]
I tried this setting to have the Layout Node always instanced to solve the lag spikes caused by instancing the Layout Node each time Dialogic.start() was called. The problem is that when I call Dialogic.start(), the latest hidden dialog text will be visible for an instant before displaying the new one.

The expected behaviour for this setting would be to never show the hidden timeline again.

Godot 4.0.3, Dialogic 2.0 Alpha 8, Windows 10.

**Workaround**

I'm using the hide textbox when empty option and an empty textbox timeline to jump to that timeline at the end of every timeline so the Layout Node is always instanced to avoid the instancing lag spikes during gameplay. However, this solution is a little bit hacky and has the problem that when instancing an empty textbot timeline you can see the textbox briefly before disapearing (I will make a separate issue report for that.

Please if I'm doing something wrong or you know any other workarrounds or techniques to solve these lag spikes let me know.

**Comment by Jowan-Spooner** [comment]
First of all thanks for all the reported problems @phantomdesvin. I will try to go through them all and see what can be done.

This sounds like a bug! I will have to investigate the best solution for this.
