### ISSUE TITLE
DefaultDialogicNode layout inconsistent

### ISSUE THREAD

**Issue by rassweiler** [coppolaemilio/dialogic#1616]
## The problem

**Describe the bug**
The DefaultDialogicNode layout seems to have random sizes and locations for elements:
![image](https://github.com/coppolaemilio/dialogic/assets/5359617/058c7413-101a-4d3d-8b6b-2488c0481411)

Also having the DialogTextAnimationParent's position animated hard codes an odd offset:
![image](https://github.com/coppolaemilio/dialogic/assets/5359617/d100f39d-b01d-44eb-a9b8-ebd79f8c16e8)

**To Reproduce**
1. Download latest master branch zip

**Expected behavior**
A more consistent layout, I'm not sure what the intended layout is

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 4.0.3
 - Dialogic Version: Master

## Solutions

What you tried to get the feature working

**Possible fixes**
- Delete the animated position key frames
- re-adjust layout to intended setup and scales.

**Comment by Jowan-Spooner** [comment]
This is kinda outdated and I think most of the described problems are either fixed or won't be fixed.
