### ISSUE TITLE
Main portrait settings get overriden by the way loading behaves right now

### ISSUE THREAD

**Issue by IkutiDev** [coppolaemilio/dialogic#1619]
## The problem

**Describe the bug**
Due to how currently main settings and UI showing it works, when we change some values for 1 character and than go to another character we override this another character main settings with the values we set in the last one. The only main setting that this not happen to is the first one, Main Scale

**To Reproduce**
1. Create a character and set some main settings (ex. Main Mirror)
2. Create another character and change main settings there as well (for example have the opposite Main Mirror bool state to the first one)
3. Go back to the first character and see that all main settings beside Main Scale get overriden by the character we were editing before.

**Expected behavior**
The values don't get overriden when editing more than 1 character.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0.3
 - Dialogic Version: Freshest from the repo.

## Solutions

**Workaround**

Only workaround it not to use the main settings for characters beside Main Scale

**Possible fixes**

In char_edit_section_portraits.gd when we do the loading, we duplicate the loaded resource and use that values. This way we don't have to worry about current resource values being wrong when changing UI values. Like this:
`

	func _load_character(resource:DialogicCharacter) -> void:
		var resource_duplicate = resource.duplicate()
		%DefaultPortraitPicker.set_value(resource.default_portrait)
		%MainScale.value = 100*resource_duplicate.scale
		%MainOffset.set_value(resource_duplicate.offset)
		%MainMirror.button_pressed = resource_duplicate.mirror
	
`

**Comment by Jowan-Spooner** [comment]
Good catch. I will implement a fix for this asap, probably just not saving any changes when loading. This is mainly a problem because some UI nodes will emit a changed signal even when changed from code.
