### ISSUE TITLE
Indentation errors

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#162]
## The problem

**Describe the bug**
In many cases when moving/deleting/adding new events to the timeline, the indentation function doesn't trigger.

**Screenshots**
(from Rab_Loe on discord)
![image](https://user-images.githubusercontent.com/2206700/113712212-2443ce00-96e6-11eb-8b75-9efde78987d8.png)

## Solutions
**Workaround**
Use one of the actions from the context menu of an event that moves up/down so the indent function triggers.

**Possible fixes**
We should trigger the indent function whenever a change happens on the timeline, but I'm worried about it being too intensive for slow computers.

**Comment by ellogwen** [comment]
mhh strange, i thought i added the indentation to every move. Does this happen often? The screenshot does not look like a valid timeline, maybe this is part of the issue?

**Comment by coppolaemilio** [comment]
I was able to reproduce it. it seems to be the context menu delete action causing this
![image](https://user-images.githubusercontent.com/2206700/113726659-b521a600-96f4-11eb-819e-6b3a57cd142e.png)

**Comment by ellogwen** [comment]
Is the shortcut deletion affected as well?

**Comment by coppolaemilio** [comment]
nope, that one is working fine 👍🏻

**Comment by coppolaemilio** [comment]
Partially fixed. I only need to fix a bug when moving events with the mouse
