### ISSUE TITLE
Multiple text input nodes in 1 timeline causes the text input variables to be overriden

### ISSUE THREAD

**Issue by IkutiDev** [coppolaemilio/dialogic#1620]
## The problem

**Describe the bug**
When we have more than 1 text input node in the timeline, we make it so that each next text input nodes overrides the last text input variable.

**To Reproduce**
1. Make a text input node and assign variable to it
2. Make another text input with different variable assigned to it
3. Play the timeline and use variables in text nodes to see what's inside of them
4. See that both variables have the same value as the last text input that player inserted into, instead of having possibly different value in each variable.

**Expected behavior**
Text inputs don't override each others values.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.0.3
 - Dialogic Version: Latest from repo

## Solutions

**Workaround**

Have only 1 text input? Not sure if bug still exists if we have 1 text input per timeline, but having to have multiple timelines with only 1 text input each seems problematic in architecture of any project using it.

**Possible fixes**
This is caused because we connect the func "_on_DialogicTextInput_input_confirmed" from "event_text_input.gd" to the input_confirmed signal, but we never disconnect it. Thus, each confirm button press for future text inputs run all the funcs connected to it, from the text input before it and assign the same value to each of it.
Possible fix for that is to disconnect it from the signal the moment we are finished with "_on_DialogicTextInput_input_confirmed"
`

	func _on_DialogicTextInput_input_confirmed(input:String) -> void:
		if !Dialogic.has_subsystem('VAR'):
			printerr('[Dialogic] The TextInput event needs the variable subsystem to be present.')
			finish()
			return
		dialogic.VAR.set_variable(variable, input)
		dialogic.TextInput.hide_text_input()
		dialogic.current_state = Dialogic.states.IDLE
		finish()
		dialogic.TextInput.input_confirmed.disconnect(_on_DialogicTextInput_input_confirmed)
`

**Comment by Jowan-Spooner** [comment]
Thanks for the report! I think a cleaner fix is to use the "ONE_SHOT" flag on the connection. I will make a PR with this fix asap.
