### ISSUE TITLE
Right clicking doesn't select the item under the mouse cursor, so the contextual menu doesn't affect the right-clicked event.

### ISSUE THREAD

**Issue by phantomdesvin** [coppolaemilio/dialogic#1627]
When the user wants to delete an event from the timeline, for example, he will use the right click over that specific event to open the contextual menu and then click on delete. The problem is that the right click doesn't select the event, so if no event is selected the delete option won't work, and if the user has another event selected he will delete that event and not the one he made right click over. Trying to undo that action also didn't work, but I guess that's a different issue with the undo feature. 

Windows 10, Dialogic 2.0 alpha 8, Godot 4.0.3

**Comment by Jowan-Spooner** [comment]
This should be fixed on main by #1630
