### ISSUE TITLE
Portrait change text command doesn't work if there are any '/' characters in the portrait name

### ISSUE THREAD

**Issue by klein-eng** [coppolaemilio/dialogic#1635]
## The problem

**Describe the bug**
I would expect the following portrait change command to work:
`John (CloseUp/Happy): "My expression changes [portrait=CloseUp/Sad] while speaking."`
However, what actually ends up being output is:
`"My expression changes CloseUp while speaking."` or `"My expression changes Sad while speaking."`

It seems like the [option1/option2] random choice command is interfering with the portrait command when there are any '/' characters in the portrait name. Because the '/' character is used for portrait groupings, this would come up fairly often.

**Expected behavior**
Even if there is a '/' character in the portrait name, the example above would change John to the CloseUp/Sad portrait.

**System (please complete the following information):**
 - Godot Version: 4.1
 - Dialogic Version: 2.0

**Comment by Jowan-Spooner** [comment]
Thank you very much for the report! Sorry for not answering for so long, I was on holiday ;). I will try to fix it now.
