### ISSUE TITLE
Choice event: Adding condition-logic to Choices

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#165]
**Is your feature request related to a problem? Please describe.**
In many cases I would want to create questions where I can only choose some ansers under certain conditions. If the condition is false, the answer should be hidden or greyed out (depends on the game creators needs, so this could be a setting or similar).

**Describe the solution you'd like**
The cleares to see in the timeline editor would be to have a condition behinde the choice much like the IF-event.
IDEA:
![dialogic](https://user-images.githubusercontent.com/42868150/113718699-2fe6c300-96ed-11eb-83d0-a44d04375d32.png)

**Describe alternatives you've considered**
Create if statements and multiple versions of each question inside them.
Very annoying and space and time consuming.

**Thoughts**
I could think of cases where I would want multiple conditions for one choice, especially for inbetweens (show choice if VARIABLE is less then X and greater then Y). But then you would have to deal with possibly infinitly long events and ANDs/ORs between them.
I think it would make much more things possible, but be a great deal of work.

**Comment by arnaudvergnet** [comment]
Yes I need this feature as well, would make creating games that rely on choices much easier
