### ISSUE TITLE
wait for input bug when use hide text box with jump to other timeline

### ISSUE THREAD

**Issue by non-nattawut** [coppolaemilio/dialogic#1656]
## The problem

**Describe the bug**
text box not show (always hide) when wait for input while use jump to other timeline

**To Reproduce**
1. use Dialogic.start("timeline A path") in start scene
2. in timeline A use jump to timeline B at the begining
3. use wait for input with "hide text box" checked
4. use text node with some sentence
5. run scene (not run timeline on it own if run only timeline it work fine)

**Expected behavior**
text must show, but not

**Screenshots**
start scene code
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/bdc3cfdc-06a4-4615-8068-d9b4445be466)

timeline A
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/2f0a2ce2-ab05-45be-b7a0-b475f4483c97)

timeline B
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/209d8249-e7d3-4bff-83e2-8743bedfd4e0)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version:  4.1.1 stable
 - Dialogic Version: 2.0 alpha 8

## Solutions

**Workaround**

1. tried hide before jump to timeline B , not work
2. if not hide text box, it working fine

FIXED when use "wait" instead of "wait for input"
all other are same as **Screenshots** section
![image](https://github.com/coppolaemilio/dialogic/assets/67323548/52446535-73e1-467a-b639-30772271dcd1)

**Comment by non-nattawut** [comment]
sorry this is my mistake
the dialogic version is latest version (download by "<> code" -> "Download Zip")

**Comment by Jowan-Spooner** [comment]
Thanks for the report! I will try to test this later today or tomorrow.

**Comment by Jowan-Spooner** [comment]
Hey @non-nattawut I've been able to reproduce the problem and I think I found a fix. Maybe you can try again with the PR #1659.
Alternatively (it's a very small change so installing that version could be annoying) you can manually add this line:

```gdscript
dialogic.current_state_info['text'] = ''
```

At the top of the subsystem_text.gd scripts hide_text_boxes() method (at line 171), so it looks like that:
```gdscript
# instant skips the signal and thus possible animations
func hide_text_boxes(instant:=false) -> void:
	dialogic.current_state_info['text'] = ''
	var emitted := instant
	for name_label in get_tree().get_nodes_in_group('dialogic_name_label'):
		name_label.text = ""
	if !emitted and !get_tree().get_nodes_in_group('dialogic_dialog_text').is_empty() and get_tree().get_nodes_in_group('dialogic_dialog_text')[0].textbox_root.visible:
		animation_textbox_hide.emit()
		if Dialogic.Animation.is_animating():
			await Dialogic.Animation.finished
	for text_node in get_tree().get_nodes_in_group('dialogic_dialog_text'):
		if text_node.textbox_root.visible and !emitted:
			textbox_visibility_changed.emit(false)
			emitted = true
		text_node.textbox_root.visible = false
```

Please let me know if this actually fixes the problem for you!

**Comment by non-nattawut** [comment]
Hi @Jowan-Spooner it works!

**Comment by Jowan-Spooner** [comment]
Very cool! Then I will merge the PR. Thanks for the report once again.
