### ISSUE TITLE
Theme editor: Add modulate color option for background images

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#166]
## Why
I think this would be an very easy way to create very unique theme. I like to create a lot of my UI as white/grey art and then tint it with with modulate.

## Why not?
Right now the Theme editor is pretty cluttered but there was a hint at improvements (#116), so maybe then there would be space for such a thing. 

## Describe the solution you'd like
Have modulation for each the textbox background and the charactername background as an option in the the theme editor.

Maybe even for the next-indicator.

## Describe alternatives you've considered
Just don't do it. You can easily create the backrounds with the colour you want right now. And if you change your mind, you can just create a new one.

**Comment by coppolaemilio** [comment]
- [x] Box background
- [ ] Name background
- [ ] Button background

**Comment by Jowan-Spooner** [comment]
I would also suggest to change the color of the default background images to white, when this is done. This way you can use the default images to create a lot more diffrent themes.
