### ISSUE TITLE
In game: Select/Focus the first choice button

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#167]
**Is your feature request related to a problem? Please describe.**
While it is totally possible to advance text events only using the keyboard right now, at each question you get stuck and have to use the mouse to select a choice. 

**Describe the solution you'd like**
I think it should be possible to navigate the choice buttons via UP and DOWN arrow and then accept the focused one with the action key (could be a prolem if you have mouse button as action key) or ENTER. 

The easiest way would be to just focus the first choice button, right?

**Describe alternatives you've considered**
I don't know any.

**Additional context**
For me it's just a convenience issue, but I think it would be good for accessibility in general.

**Comment by timkrief** [comment]
I got it working but it was also pressing the button from the last input. Will try to open a PR tomorrow!
