### ISSUE TITLE
Need exempla use call Node pleas

### ISSUE THREAD

**Issue by Hemenguelbindi** [coppolaemilio/dialogic#1706]
Good afternoon, I wanted to clarify, I need an example of calling a node in the timeline, I want to call a scene with animation in the dialog, but for some reason I can't, and unfortunately there are no such examples in the documentation. Thank you in advance.

**Comment by Jowan-Spooner** [comment]
Hey [this discussion](https://github.com/coppolaemilio/dialogic/discussions/1752#discussioncomment-7216726) might help. Alternatively [using signals](https://github.com/coppolaemilio/dialogic/wiki/Tutorial:-Dialogic-Signals) is always a good way to achieve things.

More documentation will hopefully come once we approach 2.0.
