### ISSUE TITLE
position_move_time is not parsed to float

### ISSUE THREAD

**Issue by m-edlund** [coppolaemilio/dialogic#1707]
**Describe the bug**
Using an update node with movement duration causes a type error 

**To Reproduce**
1. Create an upodate node with animation and movement duration
2. Run your game
3. See error

**Expected behavior**
No error

**System (please complete the following information):**
 - OS: Manjaro
 - Godot Version: v4.1.1.stable.official [bd6af8e0e]
 - Dialogic Version: 2.0-alpha-9

## Solution
Add float cast [here](https://github.com/coppolaemilio/dialogic/blob/849cf5fb87c4077996a114042fe9edc4723a2bd1/addons/dialogic/Modules/Character/event_character.gd#L282C5-L282C23)
`
position_move_time = float(shortcode_params.get('move_time', position_move_time))
`

**Comment by Jowan-Spooner** [comment]
@m-edlund thank you for the report!
I've tried adressing this issue in my latest PR #1713.
If you want, you can download the latest main branch zip from github and try if the issue is fixed for you.
