### ISSUE TITLE
Verifying Files does not enable Begin Conversion

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#1715]
## The problem

**Describe the bug**
I can't begin the conversion even after verifying the files

**To Reproduce**
1. Go to the Dialogic Workspace
2. Got to Settings > Features > Converter
3. Click 'Verify Files'. Folder `converted-dialogic` should then appear in `res://`.

**Expected behavior**
For the 'Begin Conversion' to then be enabled.

**Screenshots**
![dialogic](https://github.com/coppolaemilio/dialogic/assets/15977859/65c23eba-5a9b-4e28-bef5-081869ca93dd)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: v4.1.stable.official [970459615]
 - Dialogic Version: 2.0-Alpha-9

## Solutions

**Workaround**
I'll fix the code directly.

**Possible fixes**
I'll look at `res://addons/dialogic/Modules/Converter/settings_converter.gd` first.

It looks like on `res://addons/dialogic/Modules/Converter/settings_converter.tscn`, the node `RightPanel` has `HBox` as its parent and not `Converter`.
I've posted my fixes on #1716.

**Comment by Jowan-Spooner** [comment]
I've merged #1716. Should I close this issue?

**Comment by mechPenSketch** [comment]
I'll close this now that it's merged.
