### ISSUE TITLE
Dialogic works on test but not build

### ISSUE THREAD

**Issue by cammySashimi** [coppolaemilio/dialogic#1717]
## The problem

**Describe the bug**
Dialogic 2 is working perfectly in my project when testing builds from the editor, but it fails to pull up text when running a build of the project (debug or not). It's worth noting that the rest of the game works fine, and it doesn't crash or hang.

**To Reproduce**
1. Create a new project
2. Add a Node2D
3. Create a basic character and timeline
4. Run Dialogic.start() in the _ready() function of the Node2D
5. Note that the text works
6. Build project on default settings
7. Run project
8. Note that no text box appears

**Expected behavior**
Text works identically in test run and full build.

**Screenshots**
Node2D script:
![Screenshot_20230911_135051](https://github.com/coppolaemilio/dialogic/assets/10779248/c9809665-59fd-4ee4-afdb-9dc46ed24f2d)

Dialogic character:
![Screenshot_20230911_135111](https://github.com/coppolaemilio/dialogic/assets/10779248/b83993ec-3996-464a-a1c7-d2b71226949b)

Dialogic timeline:
![Screenshot_20230911_135119](https://github.com/coppolaemilio/dialogic/assets/10779248/ed97a755-8338-43f1-a0f7-bddf307bed56)

Node and file heirarchy:
![Screenshot_20230911_135145](https://github.com/coppolaemilio/dialogic/assets/10779248/c0d26276-4d46-48d0-8020-4535f4744cca)

Console output:
![Screenshot_20230911_140146](https://github.com/coppolaemilio/dialogic/assets/10779248/2609ab2d-4859-4713-9b57-0eeacaa08d6a)

**System (please complete the following information):**
 - OS: Linux, Kubuntu 22.04
 - Godot Version: v4.1.1.stable.official.bd6af8e0e
 - Dialogic Version: 2.0 alpha-9

## Solutions

**Workaround**

I tried enabling and disabling debug build, adding custom export filters for .dtl and .dch files, manually selecting all resources for export, disabling Editor > Export > Convert Text Resources to Binary in project settings, starting the timeline with load("res://test_timeline.dtl") instead of just the name string.

**Possible fixes**

Not sure, but it seems that Dialogic is having trouble loading its game handler script during runtime? I'm fairly new to Godot and this is my first time using Dialogic. For what it's worth, my main project is also using the [Terrain3D](https://github.com/TokisanGames/Terrain3D) plugin, which is working on both test runs and full builds.

**Comment by cammySashimi** [comment]
Uploading the Godot project file [here](https://drive.google.com/file/d/1abV8gVyuD87w9E_-Y_vRiLq5JobV_SPf/view?usp=sharing) for reference

**Comment by Jowan-Spooner** [comment]
@cammySashimi I can test it later myself but something similar was reported a couple of days ago and is supposedly fixed on main (it was caused by a reference to a editor-only class). So maybe you can try the main branch and see if it works any better?

**Comment by cammySashimi** [comment]
Oh, great call! I updated to main and it fixed my problem. Thank you so much!
