### ISSUE TITLE
Dialogic.load_full_state not working

### ISSUE THREAD

**Issue by GoldExperience** [coppolaemilio/dialogic#1719]
## The problem

Dialogic.load_full_state not working.
get error:
> Invalid type in function 'add_layout_style' in base 'Node (subsystem_styles.gd)'. Cannot convert argument 1 from Nil to String.

**To Reproduce**
```
func _ready():
	var dialog = Dialogic.start("timeline")
	var save_state = Dialogic.get_full_state()
	print(save_state)
	Dialogic.load_full_state(save_state)
```

**Expected behavior**
no error.

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/22605164/3317962a-e3de-4a4f-aebc-a5174f7f6fad)

**System (please complete the following information):**
 - OS: Windows11
 - Godot Version:4.1.1
 - Dialogic Version: 1.9

**Comment by Jowan-Spooner** [comment]
Can confirm. Can be fixed very easily, it's just a missing default. 

If you want to apply the fix localy so you don't have to wait for a new version:

change line 16 in subsystem_styles.gd to 
```
	add_layout_style(dialogic.current_state_info.get('style', ''))
```
I'll make sure that this is included in the next release.
