### ISSUE TITLE
Next indicator custom texture not functioning

### ISSUE THREAD

**Issue by cammySashimi** [coppolaemilio/dialogic#1720]
## The problem

**Describe the bug**
When loading a custom texture for the next indicator in the style editor, the indicator continues to use the default texture.

**To Reproduce**
1. Go to the style editor
2. Load a new next indicator graphic under Settings > Other
3. Test project
4. Next indicator continues to use default texture

**Expected behavior**
Next indicator switches to using custom texture.

**Screenshots**
![Screenshot_20230914_115939](https://github.com/coppolaemilio/dialogic/assets/10779248/5bf80e96-c50c-4d8d-b67e-5ede9a96b116)
![Screenshot_20230914_115957](https://github.com/coppolaemilio/dialogic/assets/10779248/fdbe6df2-6b9c-49b5-a255-bb2a19c79848)

**System (please complete the following information):**
OS: Linux, Kubuntu 22.04
Godot Version: v4.1.1.stable.official.bd6af8e0e
Dialogic Version: 2.0 alpha-9

## Solutions

**Workaround**

Can be worked around by replacing the next indicator example graphic at res://addons/dialogic/Example Assets/next-indicator/next-indicator.png and re-importing. However, this changes the graphic for all styles in the project.

**Possible fixes**

There's no error messages, so my immediate thought is that Dialogic isn't replacing the texture at all for some reason.

**Comment by Jowan-Spooner** [comment]
Can confirm. While the property is set, it's actually only read on _ready() which happens BEFORE the value is set properly. 
Will try to fix for the next release.

**Comment by Jowan-Spooner** [comment]
Sorry this was autoclosed by me merging #1724. It fixed the problem for me. If it doesn't for you, let me know and I can reopen this!
