### ISSUE TITLE
Cannot enable Dialogic 1.5 within new project

### ISSUE THREAD

**Issue by aumusic** [coppolaemilio/dialogic#1726]
Hi,

So, after following the install instructions (which are to simply copy/paste the 'addons' folder into the main project folder) and trying to enable the Dialogic plug-in VIA Project/Project Settings/Plug-ins, I receive the following error:
Unable to load addon script from path: 'res://addons/dialogic/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dialogic/plugin.cfg' to prevent further errors.
This was done in a completely new project.

Any thoughts?
Thanks in advance

**Comment by Jowan-Spooner** [comment]
Just in case, 1.5 is for godot **3.x**. 
For **4.x** you have to use the 2.0 alphas.

If this isn't it, you should checkout the plugin.gd script and tell us if there are any errors in that script.

**Comment by aumusic** [comment]
That was my issue. I apologize for the inconvenience, but thank you for your time.
