### ISSUE TITLE
Layouts: Allow mouse_input to be collected by a Control node

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1727]
This has been a problem for a long time. However for usability it should be optional to add such a node. 

If added any mouse input in the Input action would only be catched by _gui_input of that node, making it easy to block the mouse with other UI elements or limiting the clicking area to parts of the screen like the box.

Edit: This might also allow us to move to _unhandled_input again which was unable to recieve mouse input as that seemed to always be collected by the window or something idk. Had trouble with it the last time I tried.

**Comment by SeaLiteral** [comment]
Even the built-in "History" button would probably benefit from this (clicking it and then clicking the "Return" button advances the dialogue, which probably isn't intended; also, clicks on buttons added by the game itself also seem to trigger the forwards action, making it difficult to add custom UI).
 
(I was considering to report that issue about the history button, but I guess it's more like a sub-issue of this one. I might still report another issue with the history button, but that's unrelated to this one.)
