### ISSUE TITLE
Allowing "Change Timeline" to jump to a specific point in a timeline.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#174]
**Is your feature request related to a problem? Please describe.**
Not particularly, but I'm of the mind it might become a problem for larger projects. Timelines do not have (and therefore do not support) jumping to specific "points" in another timeline (or itself).

**Describe the solution you'd like**
I hope these (crudely edited) screenshots illustrate what I'm getting at:
![Change_timeline_prop](https://user-images.githubusercontent.com/324679/113871187-8cf47e80-97aa-11eb-857e-07d47214401a.png)
![Change_timeline_point](https://user-images.githubusercontent.com/324679/113871793-29b71c00-97ab-11eb-90fa-560445d81721.png)

Essentially: you can specify points in a timeline to be "jumped" to when changing to that timeline. Selecting a timeline but not a point in that timeline works as it currently does - from the beginning. Selecting a point but not a timeline jumps to that point in the current timeline.

**Describe alternatives you've considered**
Nothing comes to mind, really, except possibly duplicating timelines, which would be inefficient.

**Comment by Sslaxx** [comment]
Still leaves the possibility of having to duplicate a lot of logic in those smaller timelines.

**Comment by coppolaemilio** [comment]
Checkpoints could be a nice event to add eventually. I think TyranoBuilder has something like that 👍🏻

**Comment by IoriBranford** [comment]
I made these events as "Jump" and "Jump Point". They do the job, but jumps can't handle if the target jump point's id changes; it's not straightforward to do so without event instances having some unique identifier.

If jump points have duplicate ids, jumps to that id will go to the first one.

[jump-custom-events.zip](https://github.com/coppolaemilio/dialogic/files/7690541/jump-custom-events.zip)

**Comment by zaknafean** [comment]
#592 has alot of this functionality at this point, though not the ability to jump timelines AND anchors at this time.

**Comment by coppolaemilio** [comment]
An option to jump to a particular anchor should be inside the change timeline event

**Comment by Jowan-Spooner** [comment]
Implemented in 2.0
