### ISSUE TITLE
Exported game crashes when run

### ISSUE THREAD

**Issue by Theooolone** [coppolaemilio/dialogic#1745]
## The problem

**Describe the bug**
When I export a project with Dialogic to Windows, the game crashes when run if debug mode is disabled.
When the exported game is initially run, this windows error occurs:
```
The instruction at [Memory Address] referenced memory at [Memory Address]. The memory could not be read.
```
This error only displays once, and if the game is ran again, it will crash as before but without displaying that error.

If I run the game from the console wrapper, this error occurs before the console window closes due to the crash:
```
SCRIPT ERROR: Parse Error: Could not find type "EditorPlugin" in the current scope.
          at: GDScript::reload (res://addons/dialogic/Other/DialogicUtil.gd:17)
```

**To Reproduce**
1. Create a new Godot project
2. Create any root node and set it as the main scene
3. Install Dialogic 2.0 - alpha 9
4. Go to Project > Export, and add a 'Windows Desktop' preset
5. Change 'Export Console Wrapper' to 'Debug and Release'
6. Click 'Export Project', untick 'Export With Debug', then save.

**Expected behavior**
Game should not crash and should run as expected.

**Screenshots**
![Windows Application Error](https://github.com/coppolaemilio/dialogic/assets/110533961/2db1d10b-c24e-4d35-9f72-b6eb59fd2479)
![Dialogic Script Error](https://github.com/coppolaemilio/dialogic/assets/110533961/c1b8a72a-d84b-4c6e-a5e9-ac9558e91412)

**System:**
 - OS: Windows 10
 - Godot Version: 4.1.1
 - Dialogic Version: 2.0 - alpha 9

**Comment by Jowan-Spooner** [comment]
I believe this error has already been fixed on main. Could you try updating to the main branch?

**Comment by Theooolone** [comment]
I have switched to the main branch and the problem no longer occurs, thank you!
