### ISSUE TITLE
Pass autoloads into Condition Expression

### ISSUE THREAD

**Issue by jonbonazza** [coppolaemilio/dialogic#1753]
**Is your feature request related to a problem? Please describe.**
I have a "Blackboard" auto load that allows me to just set and get arbitrary flags as data. I want to check for a certain flag here in a timeline Condition. However because it doesn't use Dialogic Variables, I can't use a Variable condition, and because the Condition's Expression object doesn't load in autoloads, it can be used in expressions to evaluate for the Condition.

**Describe the solution you'd like**
I think a simple solution here would be to pass in all autoloads when executing the Expression, so that the they can be used in the Expression syntax. (See the [Expression docs](https://docs.godotengine.org/en/stable/classes/class_expression.html) for more details here.

**Describe alternatives you've considered**
In my case, the alternative is to track individual quest flags as explicit variables in a global singleton/autoload. It's doable, but cumbersome given the quest system I am using.

I've also thought about creating these quest flags up front as Dialogic Variables, and if this issue is not implemented, this is likely the route I will need to go, but it's a lot of upkeep and quite annoying as I not only need to preset all of the flags in the Dialogic UI, (and there's no way to do this programmatically it seems), I also need to have some node who's job is to replicate state from my quest system to Dialogic variables and vice versa. It's quite cumbersome.

**Comment by Jowan-Spooner** [comment]
Uhm.. You can use autoloads in expressions already. You can even use them in the set variable event.
![grafik](https://github.com/coppolaemilio/dialogic/assets/42868150/c37c0d62-6d60-4928-a665-3796af807185)

To anser your question in [another thread](https://github.com/coppolaemilio/dialogic/issues/263#issuecomment-1732210287), this also allows you to call methods. Now if you use the visual editor then you should switch your mode into "expression" mode and just type in `Autoload.my_function()`. Dialogic will evaluate whatever your method returned. You can also give arguments: `Autoload.my_function(0.5, "extreme")`.
![grafik](https://github.com/coppolaemilio/dialogic/assets/42868150/70523df5-3ab3-4997-85f2-37f30761f893)

By the way this even works inside of text: `I think today I will call myself {Autoload.get_random_name()}!`

**Comment by jonbonazza** [comment]
Hmm... I was trying to do `Blackboard.get_val("foo")` == "bar" however it wasn't working for me. I didn't try expression mode. In expression mode can I just do `Blackboard.get_val("foo") == "bar"` directly?

**Comment by Jowan-Spooner** [comment]
> Hmm... I was trying to do Blackboard.get_val("foo") == "bar" however it wasn't working for me.

Can you share how you tried (possibly with a screenshot) so I can see what didn't work.

> In expression mode can I just do Blackboard.get_val("foo") == "bar" directly?

Yes that should be possible.
