### ISSUE TITLE
Layouts: Relative UI Styling

### ISSUE THREAD

**Issue by XAMPPRocky** [coppolaemilio/dialogic#1765]
**Is your feature request related to a problem? Please describe.**
Hello 👋 I've been trying out the framework for the first time, and am enjoying using it. However after setting up my first project, I noticed that A) the default window size is very small. B) When I scale the window to make up for it, the dialog and text don't scale with it. I looked in the styles, and I can't really figure it out at the moment.

**Describe the solution you'd like**
I wish there was an easy way to make the offsets and dimensions of styles relative rather than absolute. Especially since Godot is an engine designed to be run a tonne of platforms, each of them are going to have different resolutions and dpi (digital pixels per inch). To be honest I think relative should be the default rather than the current absolute system, as that would be more intuitive.

**Comment by Jowan-Spooner** [comment]
Hey @XAMPPRocky how is your window setup? How godot's UI nodes scale and expand very much depends on the window stretch and stretch aspect modes that are set in the project settings.

**Comment by XAMPPRocky** [comment]
Going to close this as I figured it, I didn't have the Godot window settings match the styles. It might be good to have a warning when it's bigger than the Godot settings.
