### ISSUE TITLE
Script Error crash upon export

### ISSUE THREAD

**Issue by neonvita** [coppolaemilio/dialogic#1770]
I have tried exporting my Godot 4.1.1 project that uses Dialogic 2.0 to .exe but it immediately crashes once launched. 

I checked the debugger and it's giving me the following error.

SCRIPT ERROR: Parse Error: Could not find type "EditorPlugin" in the current scope.

This is followed by a few other similar script errors.

I have enabled .cfg and .json files in the non-resource files box in the export menu but that hasn't solved the issue.

**Comment by Jowan-Spooner** [comment]
No need to enable cfg and json in v2. This bug is likely fixed on the main branch.

**Comment by neonvita** [comment]
I'm still getting the same errors. Do you have any idea how I can resolve them?

**Comment by neonvita** [comment]
I managed to fix it! I reinstalled the plugin after replacing the addon file with the latest version. Thank you for your help.
