### ISSUE TITLE
Release Builds of 2.0-alpha9 crash on launch due to missing type :cry: 

### ISSUE THREAD

**Issue by QueenOfSquiggles** [coppolaemilio/dialogic#1774]
## The problem

**Describe the bug**
Release builds with [Dialogic 2.0-alpha9](https://github.com/coppolaemilio/dialogic/tree/2.0-alpha-9) crash on release with this error:
```
SCRIPT ERROR: Parse Error: Could not find type "EditorPlugin" in the current scope.
          at: GDScript::reload (res://addons/dialogic/Other/DialogicUtil.gd:17)
```
I'm honestly unsure if this is a dialogic-side problem or godot-side problem.

**To Reproduce**
1. Add Dialogic (2a9) to a project
2. Export a build (personally only tested desktop builds)
3. Try to run it

**Expected behavior**
Doesn't crash on launch

**Screenshots**
none that would be helpful

**System (please complete the following information):**
 - OS: tested Linux & Windows
 - Godot Version: 4.1.1-Mono
 - Dialogic Version: 2.0-alpha9

## Solutions

**Workaround**

Removed type hinting from the affected line and everything works. See [commit here](https://github.com/QueenOfSquiggles/ContactRange/commit/f4ca50cadcce92a0356d183c0e1b26e0e3b6ebec)

**Possible fixes**

IDK if my workaround is really a long term solution

**Comment by Jowan-Spooner** [comment]
Solved on main, please try that branch directly.
