### ISSUE TITLE
Using RegEx in condition expressions

### ISSUE THREAD

**Issue by opaintner** [coppolaemilio/dialogic#1775]
**Is your feature request related to a problem? Please describe.**
I think that we should be able to use regex functions in expressions for conditions, like this, where {item} is a user-provided string :

![image](https://github.com/coppolaemilio/dialogic/assets/25113596/8c75a2a3-cedd-4152-b807-46603e581c84)

It's particularly useful for changing grammar for user-provided string variables when used in text. 

**Describe the solution you'd like**
I've already got a solution to add to the main methods section of subsystem_expression.gd, but I'm new to GitHub so I don't know what I should do to add it to the code, or if this functionality already existed. Should I just make a new branch, add it, commit, and then do a pull request?  

```gdscript
func d_regex(input: String, pattern: String, offset: int, end: int) -> bool:
	var regex : RegEx = RegEx.create_from_string(pattern)
	regex.compile(pattern)
	var match = regex.search(input, offset, end)
	if match:
		return true
	else:
		return false
``` 

Thanks a bunch.

**Comment by Jowan-Spooner** [comment]
@opaintner thanks for this cool request and also thansk for already including a solution.

Three things:
A) yes, creating a branch, putting those changes in and then making a Pull Request is the typical solution in open-source. However if you don't want or can't, this way is okay too for us.

B) This is a pretty advanced feature. It might make sense to limit the amount of build-in methods in the expression subsystem. Advanced users can work around this by putting whatever methods they like on an autoload and calling those inside of their expressions: e.g. if you'd put this metehod on any of your autoloads you could type `Autoload.d_regex({item}, "\\b([AEIOUaeiou]", 0, 1)`

C) However I'd be willing to even put this in the core as it seems like a handy feature that doesn't need too much up-keep. I would however do the following changes:
   - make the match statically typed (akak `var match := `
   - make offset and end optional parameters which default to the whole string.

**Comment by opaintner** [comment]
I definitely agree with you when talking about keeping the core methods small, and I think we should limit it to things that remove unnecessary friction for the end user. Dialogic is extremely easy to pick up for a new Godot user (My friend, who has no experience with Godot or game development really enjoys it) and I think we should reduce friction for both advanced users and newbies! 

But, I feel like this being an advanced feature is okay! It's only really going to be used after the user has clicked a button that shows a textbox for "advanced expressions", and makes sure that the power that advanced users need is there but hidden away from the easily overwhelmed new user. Because of this, I think that in the interest of reducing friction for edge cases that users might encounter, it might be best to implement tools with a broad use in processing text (like regex) that can't be accessed under the normal scope of Godot expressions. 

I'm not sure what other tools could (or should) be added, but if I come across it in the course of my current project I'll be sure to add them in another issue and pull request.

**Comment by opaintner** [comment]
I added a pull request #1778 with your suggested changes.  Hopefully everything is good!
