### ISSUE TITLE
Errors are thrown when typing in the Text Editor

### ISSUE THREAD

**Issue by opaintner** [coppolaemilio/dialogic#1779]
## The problem

**Describe the bug**
When typing in the text editor, the console spits out two errors every time a character is typed.

`res://addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd:63 - Trying to assign value of type 'Nil' to a variable of type 'Array'.`
`Couldn't find the given section "DES" and key "hidden_event_buttons", and no default was given.`

**To Reproduce**
1. Go to the Text Editor
2. Just start typing!

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.1.1.stable (Steam)
 - Dialogic Version: 2.0 Alpha 9

**Comment by Jowan-Spooner** [comment]
Thanks for the report! I think this is already fixed on the main branch. Hopefully we can wrap up some of the currently happening work and release a new alpha version in the coming weeks.
