### ISSUE TITLE
DefaultLayout: Expose Typing sounds

### ISSUE THREAD

**Issue by EmmanuelHuazo** [coppolaemilio/dialogic#1782]
Hi guys,

In DIalogic 1 there was a feature made I think by Tim, that allowed us to add sound to the text while being displayed in the text box.

It would be awesome if you could re implement it and also expand it letting us to set different sounds for each character.

Hope you have a nice day.

**Comment by zaknafean** [comment]
While not tightly integrated into the Text Event this time around, the functionality still exists by adding a vocal event before a text event.

There is also a PR for 'advanced' 'auto-advance' functionality that should be merged 'soon' that makes sure the vocal event finishes before moving on.

While not the exact functionality, I think it does still cover most cases.

**Comment by Jowan-Spooner** [comment]
This is more about typing sounds I believe and contrary to how it sounds in the original comment, typing sounds ARE already implemented in 2.x. However they are not exposed to the default layout. If I believe correctly that was what this is about: Exposing the typing sound settings on the default layout (and possibly the other layouts as well).
