### ISSUE TITLE
Make Portraits more 'alive'

### ISSUE THREAD

**Issue by RutraSan** [coppolaemilio/dialogic#179]
**Is your feature request related to a problem? Please describe.**
Many, the main problem is to change character's portrait while he is in the scene.
Next is just add more variety for join/leave actions, like dissolve, shake, move(changing position), nothing(rn always fades) which could be used as a transition, and also you would be able to call the event on the same character again and the transition will be played again, which will make it look like just an effect, can go well with the shake

**Describe the solution you'd like**
Adding an option to chose the transition and be able to set the speed for it. 
Also, making sure that if the character already presented, it will play the transition/move him anyway, right now I think only of using shake transition, and changing portraits position.

the transition/animations/effects(idk how it should be called) I thought of so far

- [ ] changing character's portrait 
- [ ] dissolve
- [ ] shake verticaly/horizontaly
- [ ] moving portrait to different position, the character have to be on screen already
- [ ] flip verticaly/horizontaly 

**Additional context**
I actually want to work on it, so I will see what I can  do

**Comment by Jowan-Spooner** [comment]
This is related to this #169.

I agree that these changes would be nice. 

I wonder if it would be possible to make custom animations a thing. Because I am sure people will always complain and want more specific ones.

**Comment by Jowan-Spooner** [comment]
The flip horizontal part reminds me of #168.

**Comment by ArtyKarty** [comment]
yeah you are right they are

> I wonder if it would be possible to make custom animations a thing. Because I am sure people will always complain and want more specific ones.

You can always modify the source, so yes, you will have to write the  function in Portrait.gd

**Comment by ArtyKarty** [comment]
I see, thanks!

**Comment by coppolaemilio** [comment]
I found this reference that I wanted to save somwhere, so leaving it here for when I start implementing effects: https://twitter.com/arkiniac/status/1358614722312998913

**Comment by coppolaemilio** [comment]
Another example of character animations:

https://user-images.githubusercontent.com/2206700/137584531-93e08ff6-81db-4db6-bdce-3afd2215f03c.mp4

This is done like this in renpy: 
![image](https://user-images.githubusercontent.com/2206700/137584536-217ed886-9864-449e-b18b-42f1cb6d74e3.png)

So we can probably create an event to do that or include some animation links to the character event

**Comment by bitbrain** [comment]
Did anyone yet consider how we can create animated avatars yet? Currently, we can load a still image in Dialogic but using an animated character, either `AnimatedSprite` or even attaching an `AnimationPlayer` to the avatar that we can control might be a good idea.

**Comment by Jowan-Spooner** [comment]
@bitbrain You can do that, technically. You can select scenes as portraits and these can be AnimatedSprites as well. But it's far from perfect, for sure.

**Comment by Jowan-Spooner** [comment]
At least the inital work on this has been done, with the rework of the Character event for 1.4. You can now make the already joined characters play animations. Also it is relatively easy to add new animations using the [ANIMA](https://github.com/ceceppa/anima) animation format. If you want to request more animations I would rather create a new issue for that.
