### ISSUE TITLE
Can't add timelines in Godot 4.1.2

### ISSUE THREAD

**Issue by DancingEngie** [coppolaemilio/dialogic#1799]
## The problem

**Describe the bug**
Upgraded my project to 4.1.2. When attempting to load or create a new timeline, the timeline window doesn't function due to an error.

**To Reproduce**
1. Open a (new) project in Godot 4.1.2 and install the plugin
2. Attempt to create a new timeline
3. See an error and a bugged window

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/9748479/87918838-55d2-442d-8108-8f5c15542747)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot 4.1.2
 - Dialogic ver.: latest pull from GitHub

## Solutions

**Possible fixes**

Downpatching to 4.1.1 it seems

**Comment by CakeVR** [comment]
Hello, could you please the error you encounter?

**Comment by DancingEngie** [comment]
Alright, I'm a big dumb dumb. I got back to investigating this issue a few minutes ago and realized the console was screaming about unknown references. After reloading the project, everything's working fine. So uh, if there's a way to force-reload Godot after importing this plugin, that'll certainly help newbs like me :)
