### ISSUE TITLE
Resource View doesn't update on filesystem changes.

### ISSUE THREAD

**Issue by XAMPPRocky** [coppolaemilio/dialogic#1807]
## The problem

**Describe the bug**
The dialoguer resource view seems decoupled from what's in the project. If I create a timeline, and then delete it in the Godot filesystem view, the timeline is still there in the in the dialoger view.

**To Reproduce**
1. Create timeline
2. Delete timeline

**Expected behavior**
The timeline is removed.

**Comment by CakeVR** [comment]
Hello, thank you for reporting this issue, I was able to reproduce this misbehaviour on Dialogic 2 Alpha 10 with Godot 4.2.beta.1.

**Comment by RetroJimbo** [comment]
Yeah it's pretty inconvenient, the only way to fix it at the moment is closing and opening Godot.
