### ISSUE TITLE
Allow timelines to return a value to a calling timeline.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#181]
**Is your feature request related to a problem? Please describe.**
Related to #174.

**Describe the solution you'd like**
Essentially, either as an alternative to that proposal or a complement to it.

A timeline that has been called by another timeline can return a value to it ala a function. This could be a simple true/false value, or any other valid variable. This would require expanding the if event to be able to process what to do with that value.

This could also be used with function calls (regarding future plans for timelines)?

This may require making how definitions/variables are defined, stored and used more flexible.

**Describe alternatives you've considered**
See #174 for where this came from.

**Comment by ellogwen** [comment]
Can you provide an example usecase? You can use the definitions to store and retrieve data in/between timelines (utilizing Set Value Event) and with the upcoming release you can use the Call Node event to execute functions during timeline execution as well.

**Comment by Sslaxx** [comment]
Is it intended for Call Node to be able to return a value to whatever's calling it?

**Comment by ellogwen** [comment]
No, but you can dynamically set a definition value inside the that function, if you need to.

**Comment by coppolaemilio** [comment]
I don't see any user case either and you can use definition values like ellogwen said. Feel free to reopen if you have a more precise definition and examples 👍🏻
