### ISSUE TITLE
Crashes new project on start with "Invalid get index 'Settings'..."

### ISSUE THREAD

**Issue by Maaack** [coppolaemilio/dialogic#1819]
## The problem
Trying [Dialogic 2.0 - alpha 10](https://github.com/coppolaemilio/dialogic/releases/tag/2.0-alpha-10) on a brand new project and it crashes as soon as I run any scene.

**Describe the bug**
Crash on run with error message:
`Invalid get index 'Settings' (on base: 'Node (DialogicGameHandler.gd)').`
at:
`addons/dialogic/Modules/Text/subsystem_text.gd:464`

**To Reproduce**
1. I created a new project and closed it.
2. I installed the dialogic addon from the zip of the alpha release.
3. I enabled the project > project settings > plugins
4. Reloaded the project
5. Check that it is loading in project > project settings > autoload as well.
6. Run the scene
7. See error

**Screenshots**
![Screenshot from 2023-10-20 11-16-30](https://github.com/coppolaemilio/dialogic/assets/788630/7d92fdd5-8422-4b3e-871c-23d3891af310)

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 4.1.2
 - Dialogic Version: 2 alpha-10

## Solutions

**Workaround**

Using different dialogue system.

**Comment by Lakelezz** [comment]
Please update your Godot version to 4.1.2!

**Comment by CakeVR** [comment]
There is a now deleted comment, but it's likely the solution for this problem.
Please update to Godot 4.1.2 :)

**Comment by Maaack** [comment]
My mistake, this was in Godot Version: 4.1.2. In the middle of a game jam and I rushed this post. Updated the original.

**Comment by imberny** [comment]
I added the line
`static var Settings = preload("res://addons/dialogic/Modules/Settings/subsystem_settings.gd").new()`
to the start of res://addons/dialogic/Other/DialogicGameHandler.gd

No idea if it's the good solution as I've just installed Dialogic for the first time, but at least my game is starting now.

**Comment by imberny** [comment]
Ok, I've debugged a little and I know what's happening. Commit #1718 added the problematic lines in your screenshot. These lines are part of the "Text" subsystem. The "Settings" subsystem is another one. The issue is that "Text" gets loaded before "Settings", so "Settings" isn't available yet.

**Comment by imberny** [comment]
I opened a pull request that fixes this by adding a separate "install" step to subsystems once every subsystem has been added to the tree.
