### ISSUE TITLE
Use the Godot internal Translation - System

### ISSUE THREAD

**Issue by wpshadow** [coppolaemilio/dialogic#182]
If you would like to add a translation with the Godot internal translation - system to the dialog system, it handles it like a string.

tr("test")

![translation](https://user-images.githubusercontent.com/5918603/114020185-9c89cb00-986f-11eb-969b-6312eae0bf23.png)

It would be a great improvement to add the posibility.

**Comment by AnidemDex** [comment]
related to #21 #20 and #127

**Comment by coppolaemilio** [comment]
This is working now! you should be able to enable experimental translations in the project settings. You can learn more here: https://github.com/coppolaemilio/dialogic/pull/284
