### ISSUE TITLE
Typing sounds work in the editor but do not work on export

### ISSUE THREAD

**Issue by DancingEngie** [coppolaemilio/dialogic#1834]
## The problem

**Describe the bug**
When providing a style with a typing sounds folder, the typing sounds can be heard in the editor but not on export.

**To Reproduce**
1. Create a new timeline and character, and write some sample dialogue.
2. Choose any style and provide it with a typing SFX folder in the "sounds" tab.
3. Call the new timeline by any means you see fit. 
4. Play the timeline in the editor, and see that everything is working properly.
5. Export the game and launch it.
6. Observe that dialogues have no typing SFX.

**Expected behavior**
Typing sounds should be heard in all platforms.

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.1.2
 - Dialogic Version: Alpha 10

## Solutions

**Workaround**

After many, MANY attempts with console printouts, I found that the `load_sounds_from_path` function does not recognize exported .wav files. It does, however, recognize .import files. Therefore, this (extremely dirty) rewrite works:

```
static func load_sounds_from_path(path:String):
	var dir = DirAccess.open(path)
	var sounds : Array[AudioStream]
	if dir:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while file_name != "":
			print(file_name)
			if file_name.get_extension() == "import":
				file_name = file_name.split(".import")[0]
				var stream:AudioStream = load(path + "/" + file_name)
				sounds.append(stream)
			file_name = dir.get_next()
	return sounds
```

**Possible fixes**

Rewriting the function to work with Godot's internal build logic, I guess. Maybe it's something that needs to be brought up with the engine, but I dunno, I'm a noob.

**Comment by Jowan-Spooner** [comment]
@DancingEngie Thanks for the report!
We've had similar struggles before so I will try to fix it as best as possible for the next release.

**Comment by Jowan-Spooner** [comment]
I think this is fixed now on main.

**Comment by DancingEngie** [comment]
> I think this is fixed now on main.

Yup. Thanks :)

**Comment by DancingEngie** [comment]
> I think this is fixed now on main.

For some reason defining the var type in the for loop breaks that segment. Removing that makes everything actually work. Dunno why. But other than that, the issue is indeed fixed.

![image](https://github.com/coppolaemilio/dialogic/assets/9748479/f3dc2101-1e49-4410-83c9-e76cc38b81fd)
![image](https://github.com/coppolaemilio/dialogic/assets/9748479/72c54ad9-599f-4d83-9ef2-4ed91f75ac61)

**Comment by Jowan-Spooner** [comment]
Oh damn. I'm so dumb. I'm already using 4.2 alpha 3 and it has static typing in for-loops. 
Will remove this. We still need to decide whether we want to increase the minimal needed godot version again.
