### ISSUE TITLE
Dialog works when running from editor, but exported game fails

### ISSUE THREAD

**Issue by DanielOaks** [coppolaemilio/dialogic#1838]
## The problem

**Describe the bug**
My Dialogic 2.0 dialog works properly in the editor and when running my game from the Run Project (F5) button. My dialog fails to work after exporting my game.

Here is the specific error I see in the exported game's debug console (but not when running it using the Run Project button):
![image](https://github.com/coppolaemilio/dialogic/assets/251281/0787bdb9-d692-4926-9e21-358e66d413b0)

I'm not sure how or why this is an issue and I've been tearing my hair out a little trying to work out if this is a Godot bug, some weird state I've gotten myself into, or something different.

**To Reproduce**
1. Add Dialogic to my game.
2. Start a scene with this text:
```gdscript
var timeline = preload("res://dialogic/eyemonstervn.dtl")

func start_dialog():
	Dialogic.timeline_ended.connect(_on_timeline_ended)
	Dialogic.VAR.set_variable("vibe", game_data.current_vibe_i)
	Dialogic.start(timeline)
```
3. Dialog works totally fine when running the game using the Run Project (F5) button in the Godot editor.
4. Export the project using the Windows Desktop preset.
5. Try to run the exported `.exe`.
6. See error.

**Expected behavior**
I expect the dialog to appear. When the error happens, the textboxes and dialog do not appear.

**Screenshots**
Here are my export settings:
![image](https://github.com/coppolaemilio/dialogic/assets/251281/1a6ed69f-43c4-4087-9c97-2b75cd9ee206)
![image](https://github.com/coppolaemilio/dialogic/assets/251281/b0c089f0-3e50-4c64-bb03-f5460c58e044)
![image](https://github.com/coppolaemilio/dialogic/assets/251281/8cd635b6-b006-4dde-9b31-992226c21ab0)

---

Here's the debug console of an exported game:
![image](https://github.com/coppolaemilio/dialogic/assets/251281/0787bdb9-d692-4926-9e21-358e66d413b0)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: Tested with both Godot 4.1.2 and 4.2.beta2.official
 - Dialogic Version: Dialogic 2.0 Latest commit https://github.com/coppolaemilio/dialogic/commit/2e92ec497c8d44e63356ab33d845bddbccaf565f

## Solutions

**Workaround**

I went on a bug-hunting spree and came up with the below, which let me export and successfully run my game in the end but feels sloppy.

**Possible fixes**

Making this change seemed to fix the issue for me and get it working:
https://github.com/DanielOaks/game2/commit/dec1e177d7cd215bcb0281583dca5802b3dc3971

The `print_debug("textbox root is: ", textbox_root)` there produces two different results:
- When run from the Godot editor: 
    ![image](https://github.com/coppolaemilio/dialogic/assets/251281/b405cc84-f4c7-4fe3-8790-2134128c716c)
- When run from the exported .exe:
   ![image](https://github.com/coppolaemilio/dialogic/assets/251281/73f1318f-45d6-46a0-b62c-5abc618d14b0)

So it seems like the textbox root ends up being null somehow... but looking at the code of `Modules/Text/node_dialog_text.gd` and the default layout I have no clue how that could end up happening. I'm using the DialogicDefaultLayout and letting Dialogic load that into my scene with `Dialogic.start()`, for reference.

**Comment by Jowan-Spooner** [comment]
Hey @DanielOaks thanks for reporting this. I haven't really dug into this yet, but it's a very strange error on the surface. As you said the code should never lead to this being null. 

You are using the default layout right?

**Comment by DanielOaks** [comment]
Hey @Jowan-Spooner, thank you! I am new to Godot, so maybe I've stuffed up an import setting or something else? But yeah, I haven't been able to get a more concrete idea of why this weird error happens only in this case.

Yep, I'm using the default layout. All I've got in my game re Dialogic is a dialog file and some character files here: https://github.com/DanielOaks/game2/tree/main/dialogic

**Comment by Jowan-Spooner** [comment]
The workaround for this is now on main. It's a strange thing but likely just a quirk of godot exports.
