### ISSUE TITLE
get_variable will incorrectly parse the entire expression as the variable path if two variables are being compared

### ISSUE THREAD

**Issue by McStebb** [coppolaemilio/dialogic#1841]
## The problem

**Describe the bug**
Comparing two Dialogic variables like this:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/c5b46a97-912f-4894-81ed-a893af8c315c)

... will result in an execution error:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/2534842d-6ba6-4b2f-8a61-ec57b24aadab)

However, comparing a variable to a value like this:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/3a813a13-aa0f-495e-8d1a-08d84e5c3372)

... will function normally.

**To Reproduce**
1. Write a timeline `if` statement to compare any two variables.
2. You must compare two variables. Like this: {var1} == {var2}

**Expected behavior**
Two Dialogic variables will be compared and the result will be True or False.

**Screenshots**
I placed a breakpoint at Line 39 of `subsystem_expressions.gd` where the error occurs to try and find a pattern.

Here's what the debugger looks like when you compare a variable to a value:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/3a813a13-aa0f-495e-8d1a-08d84e5c3372)
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/b334c8f3-1d5c-4b5b-934b-b378ab407b18)
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/12b2e2c4-502d-41d2-b455-735b00f6d5a2)

This is correct, because `CharVars.Mitchi.timesTalked` is 0. It parsed the variable correctly.

Here's what the debugger looks like when you try to compare two variables:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/c5b46a97-912f-4894-81ed-a893af8c315c)
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/c036a809-67fa-4050-9931-1657d293524b)
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/3132aa6f-97eb-4417-921c-5b53f6a1ac24)

**This is the smoking gun:**
`CharVars.Mitchi.timesTalked} == {GameParams.StartKeyEvent`

It appears that `func get_variable` starts by trimming the left and right curly braces off of the expression
```gd
func get_variable(variable_path:String, default :Variant= null) -> Variant:
	variable_path = variable_path.trim_prefix('{').trim_suffix('}')
```

But if you are comparing multiple variables, this can trip it up because it will go after the first and last curly braces only and try to parse out the entire expression as a variable path.

I believe this is the source of this error:
![image](https://github.com/coppolaemilio/dialogic/assets/46116575/2534842d-6ba6-4b2f-8a61-ec57b24aadab)

**System (please complete the following information):**
 - OS: Windows 10 64bit
 - Godot Version: 4.1.1.stable.mono
 - Dialogic Version: 2.0-Alpha-9

**Workarounds**
Can probably do variable comparisons inside of a gdscript instead of the timeline editor.

**Possible fixes**

Parse out the left and right hand sides of the comparison operator separately to send the value to `execute_condition`

**Comment by Jowan-Spooner** [comment]
This is likely fixed in alpha 10. Could you try with the latest version?

**Comment by McStebb** [comment]
Confirmed: This is fixed in Alpha-10.
Thanks for the hard work, folks.
