### ISSUE TITLE
Sound Mood does not reset to default when there is no character on text event.

### ISSUE THREAD

**Issue by chipolux** [coppolaemilio/dialogic#1842]
## The problem

**Describe the bug**
When a text event without a character plays it uses the sound mood from the previously speaking character.

**To Reproduce**
1. Set a default sounds folder under Styles -> Sounds -> Typing Sounds
2. Add a character and add a Typing Sounds -> Mood with different audio than the style default and set it as the characters default sound mood.
3. To a timeline using the style with typing sounds add 3 text events.
    * The first should have no character (to hear the default typing sound)
    * The second should have the character you set a default sound mood on (to hear the characters sound mood)
    * The third should have no character (to hear the previous characters sound mood continue to be used)
4. Play the timeline, in engine or using the preview function.

**Expected behavior**
When no character is speaking the sound mood should revert back to the default that is set for the style.

**System (please complete the following information):**
 - OS: Windows, macOS
 - Godot Version: 4.1.2.stable
 - Dialogic Version: 2.0-Alpha-10

## Solutions

**Possible fixes**

Adding `dialogic.Text.update_typing_sound_mood({})` alongside [this line](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Modules/Text/event_text.gd#L84C40-L84C40) fixes the issue! But I'm not sure if that's the desired way it should work, or if reverting back the default should be explicit in some way (option on the text event/settings).

**Comment by Jowan-Spooner** [comment]
Looks like this is a good fix. It should always switch back to the default, no need to make that a setting. Thanks for the report (and providing a fix!)
