### ISSUE TITLE
where is the class DialogicPortrait ??

### ISSUE THREAD

**Issue by snarkmultimedia** [coppolaemilio/dialogic#1859]
I'm trying to implement Custom Portraits,  a rigged and animated character, a character with a single body but many face variations, for that I found this tutorial [https://github.com/coppolaemilio/dialogic/wiki/Tutorial:-Custom-Portraits](https://github.com/coppolaemilio/dialogic/wiki/Tutorial:-Custom-Portraits) the problem is that **I cant find DialogicPortrait class** inside the plugin, I'm using dialogic 1.5.
when I try to expand my character scene to DialogicPortrait as told in the tutorial  I get this error
Parser Error: Unknown class: "DialogicPortrait".
Is there a solution for what I'm trying to do?

**Comment by Jowan-Spooner** [comment]
The entire wiki is for dialogic 2. There is no DialogicPortrait class in 1.5.

I can't personally help you with 1.x questions. You can try asking on the dialogic-1 channel in emilios discord server.

**Comment by snarkmultimedia** [comment]
thanks I will try that
