### ISSUE TITLE
Subsystem method signature

### ISSUE THREAD

**Issue by Faulkwing** [coppolaemilio/dialogic#1862]
## The problem

**Describe the bug**
Generated subsystem-method load_game_state from subsystem creation in settings delivers outdated method signature.

**To Reproduce**
1. Go to Settings
2. Create a new extension with subsystem
3. See error when editing file

**Expected behavior**
No error :P 

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.1.1
 - Dialogic Version: 2 beta 10

## Solutions
PR 1861

**Workaround**
Fix manually

What you tried to get the feature working

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by Jowan-Spooner** [comment]
Sorry. I already merged the PR... Thanks for the fix though!

**Comment by Faulkwing** [comment]
Merged, thank you :)
