### ISSUE TITLE
Remove the blue outline on custom styled buttons for the options

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#189]
We need to remove the default styling of the blue outline around the text and implement a different set of options to style the buttons while being selected.

**Comment by Jowan-Spooner** [comment]
I think the easiest way to implement all the button behaviour but using textures is by using the TextureButton. Not sure how this should be done though, because the ChoiceButton Scene has a normal Button as root...

**Comment by coppolaemilio** [comment]
I removed the blue outline on the buttons. Need to add a focus style to the theme editor. But maybe using texturebutton will be the best way to go.
