### ISSUE TITLE
Invalid get index 'nodes'

### ISSUE THREAD

**Issue by chucklepie** [coppolaemilio/dialogic#19]
1. Add Dialog.tscn to project
2. Start game

```
print('-------------------------\n', dialog_resource.nodes)
```
This line errors. After removing it works fine.

Maybe I haven't caught up? I'm on v0.6, but still watching video 1...

**Comment by coppolaemilio** [comment]
Dialogic is not usable yet, it will start being available for using in version 1.0

**Comment by chucklepie** [comment]
I know, but I'm eager to get something up and running. It seems to work ok with this line removed. Maybe you need to create a dev branch and only push stable (as in, can be run) to main when you can run without errors?

**Comment by coppolaemilio** [comment]
Yes, after v1.0 is released that is how I will push updates to the repo, but until then nothing is going to work unless you really know how the plugin is set up. Hopefully v1.0 will come soon
