### ISSUE TITLE
Portrait text command doesn't work

### ISSUE THREAD

**Issue by NinoM4ster** [coppolaemilio/dialogic#1902]
## The problem

**Describe the bug**
The `[portrait=xxx]` text command does not appear to do anything. The portrait does exist and the name is correct and does not contain any special characters: `[portrait=Wave]`. There are no errors or warnings.

**To Reproduce**
1. Create a character with two portraits ("one" and "two" for example)
2. Create a timeline
3. Add a Text node set to the character with portrait "one" and paste this: `This should show portrait one. [pause=1][portrait=two]This should show portrait two.`
4. Play timeline

**Expected behavior**
The portrait would change right after the pause.

**System:**
 - OS: Windows 10
 - Godot Version: 4.1.3.stable.official [f06b6836a]
 - Dialogic Version: 2.0-alpha-11

## Solutions

**Workaround**

I tried renaming the portrait to lowercase letters `[portrait=wave]` and wrapping the portrait name in quotes `[portrait='Wave']` but neither solved it.

**Comment by Jowan-Spooner** [comment]
Thanks for the report. I can confirm that this is a bug and that it's easy to fix, so it will be fixed for the next version!
