### ISSUE TITLE
Have Localization account for Recurring texts.

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#1906]
**Is your feature request related to a problem? Please describe.**
I'm going to have to repeat the Yes/No choices in the translations.

**Describe the solution you'd like** (Final solution in bold)
Either of the following:
* An option to type keys directly into the text field instead of default language.
* Make special kinds of Text and Choice that dropdowns a list of recurring texts.
* An option for same texts (including choices) to share a single key.

**Describe alternatives you've considered**
* Probably modifying the plugin itself to do that, but then I'll have to maintain it for future updates.
* On hindsight, I could make Text and Choices that hold recurring texts myself.
* I could've also learn to elaborate on choices instead of simplifying it to a single-word Yes/No.
* **Use Variables to store recurring texts.**

**Additional context**
For example, on my project, I have a list of dialogs in .csv format:
```
keys,en,ja,es
SIGNPOST,Welcome to JRPG Fragment - Overworld!,はじめまして。これわＪＲＰＧフラグメント・オバワルド。,Bienvenido a JRPG Fragment – Overworld!
SIGNPOST2,"In this version, you can walk around and talk to nearby people.",このバージョンでは、歩き回って近くの人々と話すことができます。 ,"En esta versión, puedes caminar y hablar con personas cercanas."
BOB_QUESTION,"Hi, do you like apples or oranges?",今日は。りんごが　好きですが？オレンジ　ですが？,"Hola, ¿te gustan las manzanas o naranjas?"
BOB_CHOICE_APPLES,Apples,りんご,Manzana
BOB_CHOICE_ORANGES,Oranges,オレンジ,Naranja
BOB_ANSWER_APPLES,I like apples too - they're sweet and crunchy!,僕も　りんご　好きです。彼らは　甘くてカリカリ　です！,"También me gustan las manzanas, ¡son dulces y crujientes!"
BOB_ANSWER_ORANGES,I love oranges too - they're soooo juicy!,僕も　オレンジ　好きです。彼らは　すっごくジューシー　です！,"También me encantan las naranjas, ¡son tan jugosas!"
DIANA_QUESTION,"Hi, I'm practicing my teleportation spell. Would you like to volunteer?",こんにちは。私は私のテレポーテーションの呪文を練習しています。ボランティアをしますか？ ,"Hola, estoy practicando mi hechizo de teletransportación. ¿Te gustaría ser voluntario?"
CHOICE_YES,Yes,はい,Si
CHOICE_NO,No,いいえ,No
DIANA_ANSWER,"Okay, here goes......",はい。行けます…,"Está bien, aquí va ......"
DIANA_ANSWER2,"Oh! Sorry, looks like I failed to get it right again.",お－！ごめんなさい。失敗です。,"¡Vaya! Lo siento, parece que no pude hacerlo bien de nuevo."
```
Of the lines, in future development, `CHOICE_YES` and `CHOICE NO` would be used in more than one dialog.
However, even when I set Translation File Mode to Per Project, the list is updated to be:
```
keys,en
Text/11/text,Hi,I'm practicing my teleportation spell. Would you like to volunteer
Choice/12/text,Yes
Choice/12/disabled_text,
Text/13/text,Okay, here goes......
Text/14/text,Oh! Sorry, looks like I failed to get it right again.
Choice/15/text,No
Choice/15/disabled_text,
Text/16/text,Hi, do you like apples or oranges?
Choice/17/text,Apples
Choice/17/disabled_text,
Text/18/text,,I like apples too - they're sweet and crunchy!
Choice/19/text,Oranges
Choice/19/disabled_text,
Text/1a/text,I love oranges too - they're soooo juicy!
Text/1b/text,Welcome to JRPG Fragment - Overworld!
Text/1c/text,In this version, you can walk around and talk to nearby people.
```
Would a new line be made if I were to make another yes/no choices? I'm not sure on this, even though I have looked over the code.

[UPDATED] I've replaced the Apple/Oranges texts with Yes/No to see whether the latter set will be repeated. Here is the results:
```
keys,en
Text/11/text,Hi,I'm practicing my teleportation spell. Would you like to volunteer
Choice/12/text,Yes
Choice/12/disabled_text,
Text/13/text,Okay, here goes......
Text/14/text,Oh! Sorry, looks like I failed to get it right again.
Choice/15/text,No
Choice/15/disabled_text,
Text/16/text,Hi, do you like apples or oranges?
Choice/17/text,Yes
Choice/17/disabled_text,
Text/18/text,,I like apples too - they're sweet and crunchy!
Choice/19/text,No
Choice/19/disabled_text,
Text/1a/text,I love oranges too - they're soooo juicy!
Text/1b/text,Welcome to JRPG Fragment - Overworld!
Text/1c/text,In this version, you can walk around and talk to nearby people.
```

**Comment by CakeVR** [comment]
Hello, I'm working on a lot of CSV changes inside Dialogic 2 lately.

I will eventually take a look at this. I think `gettext` may be a lot better for this scenario, however, it's not so simple and not supported by Dialogic yet.

Either way, this is not a trivial problem. When we generate CSVs Per-Timeline, we write many files.
This would require a second pass before writing the CSVs, which creates a lot of complexion.
A duplicate word does not always mean it has the same context even. Some languages like to add nuances based on the speaker or location.

However, it would be fairly simple during Per-Project mode. Forcing the Dialogic user to use this is not the best idea. 

Adding a feature to mark an event as common is one solution.
Sadly, marking an event as recurring/common text is not UX friendly and poses another question on how Dialogic wants to adjust the visual editor for this. Most text is not common, but the UI change will always appear.

If you or anyone has an idea for a workflow, I would be happy to hear about it.

**Comment by mechPenSketch** [comment]
Would using variables in godot work as a workaround? First, I can set up a group of variables. Then a global singleton, upon being loaded, calls all variables in the group to be translated.

Then, on the text and choice dialogic nodes, I can just type the variable names between brackets `{}` in the syntax.

**Comment by mechPenSketch** [comment]
I'm closing this thread since I've found a workaround and possible solutions seem to be rather convoluted.
