### ISSUE TITLE
Glitchy behavior with a Choice inside another Choice

### ISSUE THREAD

**Issue by NinoM4ster** [coppolaemilio/dialogic#1907]
## The problem

**Describe the bug**
If you add a Choice node inside another Choice node, it cannot be drag-moved, unless... you delete it and bring it back with Ctrl + Z.
You can also move it with the right-click options, but that breaks the UI pretty badly (unless you delete and restore it first).
A friend of mine confirmed the issue on his machine with the same versions.
Potentially related to #1785/#1787?

**To Reproduce**
1. Create a Timeline
2. Add a Text node
3. Add a Choice node
4. Add another Choice node inside the first Choice node
5. Try to move the inner Choice node:
    - By dragging it
    - By using the right-click menu options

**Expected behavior**
I would be able to move the inner node, without breaking the UI.

**Video**

https://github.com/coppolaemilio/dialogic/assets/8485761/971c5602-7c08-40b6-a9e3-ba8b7bb15109

**System:**
 - OS: Windows 10
 - Godot Version: 4.1.3.stable.official [f06b6836a]
 - Dialogic Version: 2.0-alpha-11

## Solutions

**Workaround**

Just delete the node and add another one where it should actually go.

**Comment by Jowan-Spooner** [comment]
Hello @NinoM4ster I've finally gotten around to fixing some bugs again. 

This one, while bad UX isn't really a bug. It's just that the beginning of a choice is never allowed to be lower than the end. If you select both the choice and it's end node, you can drag them wherever you want. it's hard to see whether the end block is selected tbh.

To fix the UX issue I will auto-select the end block if someone tries to drag an empty choice, I think that feels a lot better and should solve your issue too.
