### ISSUE TITLE
Docs: Install-Clarification in 1. Installation (para 1)

### ISSUE THREAD

**Issue by GigglingGalaxy** [coppolaemilio/dialogic#1909]
## The problem

**not a major problem, just a minor reword for clarity on install folders**
Current 1. says:
1. Installation & Activation

First of all, you should install dialogic. This can be done by downloading the latest [release](https://github.com/coppolaemilio/dialogic/releases) zip-file from github, extracting it and moving the addons/dialogic folder to your projects res://addons/dialogic (you might have to create the addons folder).

My reword suggestion:

First of all, you should install dialogic. This can be done by downloading the latest [release](https://github.com/coppolaemilio/dialogic/releases) zip-file from github, and extracting it. You will see 3 nested folders: dialogic-main/addons/dialogic. Move only the /dialogic folder by itself into your Godot Project's addons folder. Your project file path should be: res://addons/dialogic.

???***keep (what's in parentheses) as is or change to " (if you don't have an addons folder in your project, you can just move the whole addons folder with /dialogic inside it).

---------
Again, I'm not adding anything you don't already say, but by putting addons/dialogic it might be taken as put both folders in project addons by noobs and over thinkers alike lol.

**Comment by Jowan-Spooner** [comment]
Thanks. We can include this for sure. For future issues, they can be made on [the documentation repository](https://github.com/dialogic-godot/documentation) directly. 

Also the need for manual installations is hopefully only a pre-stable issue (we want to move to the asset lib again afterwards.

**Comment by Jowan-Spooner** [comment]
It should be better now, thanks to @CakeVR.
