### ISSUE TITLE
Missing words on the text box

### ISSUE THREAD

**Issue by miguelgomezmunoz** [coppolaemilio/dialogic#1912]
Just an example, it seems it happens with some words that start with capital letter

Sarah does not appear on the text, it does if I write "sarah" instead of "Sarah"

![fy1qe9ohkw0c1](https://github.com/coppolaemilio/dialogic/assets/3616599/8fb0dd49-616a-462e-b825-abf2001967c1)

Adding "Sarah" at the end makes the first Sarah appears but not the last one

![ezouzhyokw0c1](https://github.com/coppolaemilio/dialogic/assets/3616599/0ab31e78-b812-46bb-a6ab-422cc62df1ec)

**System**
 - OS: Windows
 - Godot Version: 3.5.3
 - Dialogic Version: 1.5

**Comment by Jowan-Spooner** [comment]
Do you by chance have color-character-names on and a character name sarah with a white color setup?

**Comment by miguelgomezmunoz** [comment]
> Do you by chance have color-character-names on and a character name sarah with a white color setup?

Yeah I just found it, It was that. I was going to delete this post. Should I do that or keep it?

**Comment by CakeVR** [comment]
> > Do you by chance have color-character-names on and a character name sarah with a white color setup?
> 
> Yeah I just found it, It was that. I was going to delete this post. Should I do that or keep it?

I would keep the issue and simply close it. This way more people may find about it in the future that encounter the same situation.
