### ISSUE TITLE
Text Remains After Ending Timeline

### ISSUE THREAD

**Issue by sokay** [coppolaemilio/dialogic#1915]
**Describe the bug**
The last displayed text remains visible after ending a timeline. When starting a new timeline, I'm having characters joining while the last displayed text remains visible, until the first character begins speaking. This is a problem for the 2nd conversation and onward. This may not be noticeable with the default theme.

**To Reproduce**
1. Layout some portrait containers and a Dialogic text box
2. Start a timeline with "Dialogic.start_timeline(timelineName)"
3. Continue until a "timeline_ended" event has been fired.
4. If Dialogic textbox is still visible, you should still see the last line of the timeline in the text field.
5. Checking "Dialogic.current_state_info.text", the last line of the previous timeline appears to still be set.

I've attached a sample project.

**Expected behavior**
I'm expecting the text box to be empty after a timeline has ended. And to be empty as a new timeline is started.

**System (please complete the following information):**
 - OS: OSX
 - Godot Version: 4.1.2
 - Dialogic Version: 2.0-Alpha-11

## Solutions

**Workaround**

It seems that calling the Dialogic.Text.clear_game_state() will clear the text. For some reason I'm not seeing it being fired from DialogicGameHandler.clear() unless I remove the if statement completely.

This seems to work but I understand there's consequences to clearing everything at the end of every timeline.

**Possible fixes**

 Looking into the code a bit, it seems that Dialogic.Text.clear_game_state() doesn't appear to be fired at the end of a timeline, except when initializing Dialogic.

In DialogicGameHandler.clear(),

```gdscript
	if !clear_flags & ClearFlags.TIMLEINE_INFO_ONLY:
		for subsystem in get_children():
			subsystem.clear_game_state(clear_flags)
``` 
It appears that clear() for the Text module doesn't seem to be called after ending a timeline. When removing the 'if,' the text appears to clear after a timeline ends (but of course that causes other issues).

I've attached a project demonstrating this.

[DialogicTest_TextClear.zip](https://github.com/coppolaemilio/dialogic/files/13399628/DialogicTest_TextClear.zip)

If this is intended behavior, a work around would be appreciated. Thanks!

**Comment by sokay** [comment]
FYI, my current workaround is to just force text to clear at the every "timeline_end" event.

In DialogicGameHandler.clear(), I'm executing this after the existing "clear_game_state()" call.

```gdscript
# force text to always clear
for subsystem in get_children():
	if subsystem.get_name() == "Text":
		subsystem.clear_game_state(clear_flags)
```

**Comment by Jowan-Spooner** [comment]
If you want to clear stuff, then the "Clear" event is your friend. 
In case it doesn't do what you want `Dialogic.Text.update_text("")` would be an easier way of removing the text.
