### ISSUE TITLE
Can't find Dialogic (DialogicClass.gd) node/file

### ISSUE THREAD

**Issue by freddiearms** [coppolaemilio/dialogic#1916]
## The problem

**Describe the bug**
I can't find the node to create which allows me to pick which timeline I want to appear first (Dialogic (DialogicClass.gd) it should be called - or something similar. I've finished my project and I would like to export it etc. But to do that I need to create that node apparently - and I can't find the node. I believe it should be called something like 'Dialogic (DialogicClass.gd'

**To Reproduce**
1. Go to 'Create New Node'
2. There should be something called 'Dialogic (DialogicClass.gd)' which is what I think I need, but there isn't.

**Expected behavior**
I expected to find the node/file, and then select which timeline I want to appear first in the game but I can't find it.

**Screenshots**
<img width="173" alt="dialogic 1" src="https://github.com/coppolaemilio/dialogic/assets/151394303/88ec69d7-b45b-4254-b9dc-8ba4494c90a7">
<img width="494" alt="dialogic 2" src="https://github.com/coppolaemilio/dialogic/assets/151394303/514f34b6-79d8-4b39-a4b1-862367dfc6ae">

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.1.3.stable
 - Dialogic Version: 2.0

**Comment by CakeVR** [comment]
Have you taken a look at the introduction? https://dialogic-docs.coppolaemilio.com/documentation/getting-started/

**Comment by freddiearms** [comment]
> Have you taken a look at the introduction? https://dialogic-docs.coppolaemilio.com/documentation/getting-started/

Thanks, I've had a look - however it doesn't say the names of the nodes which I should add or provide an in-depth tutorial. Is there anything which can provide more specific information?

**Comment by CakeVR** [comment]
> Thanks, I've had a look - however it doesn't say the names of the nodes which I should add or provide an in-depth tutorial. Is there anything which can provide more specific information?

All you need is your own script and call the referenced method.

**Comment by Jowan-Spooner** [comment]
@freddiearms I'm not sure if you've used 1.x previously or just got confused by some 1.x documentation. However as CakeVR said in dialogic 2 there is no node you add to start dialog, instead it's done via code. A good code example for that is in the gettings started documentation. 

To make sure this happens as soon as you start the game you just put the call in the ready function of your main scenes script. You can set the main scene in the project settings or by right clicking the scene file in the file system dock.

**Comment by freddiearms** [comment]
I understand a bit more now, however my bad coding/computer skills is still holding me back. I'll pay someone £30 ($37) if they can fix my project to make it export and work properly. I've done all the work, all I need is someone to tell me what exactly to do now (eg. what code to add to which script and if I need to do anything else what that is etc.)

**Comment by CakeVR** [comment]
I recommend to create a new scene from scratch.
Attach a script to the root node, inside the `_ready` function, load your timeline with the aforementioned `Dialogic.start`.

You can change your main scene in the project settings: 
![image](https://github.com/coppolaemilio/dialogic/assets/65981767/e2c301a5-9276-40c9-ba9d-c92e6bbebc1f)

**Comment by freddiearms** [comment]
I did that, but again, I don't know what type of node to add to the main scene - so because I don't know what to add I added a random node (CustomEventConverter) and attached the dialogic script (with this code included in the script as well as the other stuff: 
func _ready():
    # Load the Dialogic timeline
    Dialogic.start('timeline 1')
    
    When I ran the project, unsurprisingly, it gave me an error saying instance_create: Script inherits from native type 'Resource', so it can't be assigned to an object of type 'Node'.
    
    
<img width="521" alt="help 1" src="https://github.com/coppolaemilio/dialogic/assets/151394303/41665d7a-1b75-4445-94f4-ca052f74e55f">

So I need help with what type of node to add to the main scene etc.

**Comment by CakeVR** [comment]
What do you mean by adding to the main scene? 
I do not recommend to attach any random nodes to your scene, it's just asking for trouble.

When you create a new scene, you already have a root node and you attach your own new script to it.
You need no Dialogic nodes at all, they are used internally in the Dialogic layouts.

**Comment by freddiearms** [comment]
When I create a new scene though, I don't get a root node. Instead, I have to create either a 2d, 3d, user interface or other node. 

<img width="356" alt="help 2" src="https://github.com/coppolaemilio/dialogic/assets/151394303/510e8070-7e0c-458d-87bf-9377dbb203fc">

This is where I don't know what to do.

**Comment by CakeVR** [comment]
If you make a 2D game, simply click 2D Scene, it will create the root accordingly and then you can attach your own script.
I recommend to learn a bit more about Godot's basics.

**Comment by freddiearms** [comment]
I clicked 2D Scene, and added my script - which was the script created by Dialogic after I simply created my timelines. However, when I tried to run the project it gave this error.

<img width="326" alt="help 3" src="https://github.com/coppolaemilio/dialogic/assets/151394303/0a936893-c557-471b-b041-f8802ae5f893">

Do you see the problem now?

**Comment by CakeVR** [comment]
Do not attach any scripts by Dialogic, you must create your own GDScript file for this.

Right-click the node and select "Attach Script".
Now, select some path where you want your scripts to be stored and decide on the name.

**Comment by freddiearms** [comment]
Ohh, thank you so much for your help. Sorry for the confusion. I did what you said and everything works perfectly now. 

Thank you.
