### ISSUE TITLE
Pop-up Warning Whenever I want to Enable the Plug In

### ISSUE THREAD

**Issue by CovetHiss** [coppolaemilio/dialogic#1927]
## Can't add autoload: Invalid Name. Must not collide with existing global script class name

**Describe the bug**
A warning pop-up and says "Can't add autoload: Invalid Name. Must not collide with existing global script class name" whenever I want to enable the plug in. In my debugger, this is what it shows: "core/config/project_settings.cpp:358 - Property not found: autoload/Dialogic"

**To Reproduce**
1. Go to 'Project Setting -> Plug in -> enable Dialogic plug in'
2. Warning pops up

**Expected behavior**
Shouldn't be having any warning pop-up

**Screenshots**
none

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.1.1
 - Dialogic Version: 2.0 alpha 11

**Workaround**
I checked what are those global scripts, class name and etc but I couldn't find anything useful. I am new to programming so I dunno what to do next.

**Possible fixes**
-

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by CakeVR** [comment]
Hello, you can try to delete the `.godot/global_script_class_cache.cfg`, then restart Godot, it will regenerate this file.
Eventually, enable Dialogic again. If everything goes smoothly, Dialogic will be part of the Autoloads tab.

**Comment by CovetHiss** [comment]
> Hello, you can try to delete the `.godot/global_script_class_cache.cfg`, then restart Godot, it will regenerate this file. Eventually, enable Dialogic again. If everything goes smoothly, Dialogic will be part of the Autoloads tab.

should I delete it within the godot editor, or using the file explorer?

**Comment by CakeVR** [comment]
> should I delete it within the godot editor, or using the file explorer?

I would close Godot, delete the file, and open Godot.

**Comment by CovetHiss** [comment]
> > should I delete it within the godot editor, or using the file explorer?
> 
> I would close Godot, delete the file, and open Godot.

Nice! No more warning pop-ups. Thank you so much ^^

**Comment by CovetHiss** [comment]
![node_2d tscn - BoW - Godot Engine 11_29_2023 2_37_54 PM](https://github.com/coppolaemilio/dialogic/assets/110328712/1bd7faca-4523-4d51-97b7-35f646f2311b)

But now the editor is showing nothing after I restarted...

**Comment by CakeVR** [comment]
You have a lot of errors in your console window that you have hidden. Please show them.
Also, ensure your `.godot/global_script_class_cache.cfg` has regenerated.

**Comment by CovetHiss** [comment]
> You have a lot of errors in your console window that you have hidden. Please show them. Also, ensure your `.godot/global_script_class_cache.cfg` has regenerated.

I know this is ridiculous, but after I completely reinstalled the entire plugin, everything is fixed. Anyway, big thanks to you. The file you mentioned has been generated and everything went smooth now.

**Comment by CovetHiss** [comment]
> > > You have a lot of errors in your console window that you have hidden. Please show them. Also, ensure your `.godot/global_script_class_cache.cfg` has regenerated.
> > 
> > 
> > I know this is ridiculous, but after I completely reinstalled the entire plugin, everything is fixed. Anyway, big thanks to you. The file you mentioned has been generated and everything went smooth now.
> 
> I'm glad you got it sorted out, you were not the first to encounter it. I wanted to add the solution for problem to our FAQ. If you have the time, I will appreciate to listen to what reinstalling entails. As in: Have you removed the files and restarted and any point?

1st, I disable both the plugin and the autoload in project settings/plugins.
2th, exit Godot without saving the scenes
3rd, open project's source files in file explorer, go to add-ons folder and delete the entire dialogic folder.
4th, open the Godot again, and make sure the plug in is not available anymore in project settings / Plugin (You might encounter some error of game trying to load and access to the plugin's files but it is fine)
5th, close the godot again, without saving.
6th, reinstall the plug in by dragging the Dialogic folder to the project's add-on folder.
7th, open your godot again, and enable the plug in in Project Settings / plug in.
8th, close the godot again without saving, then open godot again

This works for me, but I can't guarantee it will work for others.

**Comment by Jowan-Spooner** [comment]
Thanks for the detailed explanation! It might be good to add this to the FAQ indeed. 
I'll close this issue though, as I'm not aware of any way to fix this, I believe this is godot handeling global classes a bit badly.
