### ISSUE TITLE
Link in Github page text does not work

### ISSUE THREAD

**Issue by WalruswareGames** [coppolaemilio/dialogic#1948]
The "Getting Started" link in the front page description leads to a 404 error. 

![image](https://github.com/coppolaemilio/dialogic/assets/94482762/ecfe44f8-6b87-4321-87da-34194ecc8ce8)

(I know this is not a code error so apologies if I have put this in the wrong place)

**Comment by CakeVR** [comment]
Yes, indeed, the link seems to be outdated.

Here is the correct URL: https://dialogic-docs.coppolaemilio.com/getting-started.html#1-installation--activation
