### ISSUE TITLE
Resource still in use at exit

### ISSUE THREAD

**Issue by EFrion** [coppolaemilio/dialogic#1978]
## The problem

**Describe the bug**

Hi all!

I get the following error when I close Godot, whether a scene was played or not. I don't know how much it impacts the editor though.

ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:493)
Resource still in use: res://addons/dialogic/Resources/character.gd (GDScript)
Resource still in use: res://addons/dialogic/Resources/event.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Core/event_end_branch.gd (GDScript)
Resource still in use: res://addons/dialogic/Other/DialogicGameHandler.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Text/event_text.gd (GDScript)
Resource still in use: res://ghost.dch (Resource)
Resource still in use: res://combuchat.dch (Resource)
Resource still in use: res://addons/dialogic/Modules/Settings/event_setting.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Audio/event_music.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Audio/event_sound.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/History/event_history.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Clear/event_clear.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Background/event_background.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Condition/event_condition.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Signal/event_signal.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Wait/event_wait.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Style/event_style.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/End/event_end.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Comment/event_comment.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Voice/event_voice.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Save/event_save.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/WaitInput/event_wait_input.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/TextInput/event_text_input.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Variable/event_variable.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Character/event_character.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Character/event_position.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Call/event_call.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Jump/event_jump.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Jump/event_label.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Jump/event_return.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Choice/event_choice.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Character/node_portrait_container.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Text/node_dialog_text.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Text/node_name_label.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Choice/node_choice_button.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.tscn::StyleBoxFlat_smrwn (StyleBoxFlat)
Resource still in use: res://addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.tscn::StyleBoxFlat_775n1 (StyleBoxFlat)
Resource still in use: res://addons/dialogic/Modules/Character/preview_character.tres (Resource)
Resource still in use: res://addons/dialogic/Modules/Character/default_portrait.gd (GDScript)
Resource still in use: res://addons/dialogic/Modules/Character/dialogic_portrait.gd (GDScript)
Resource still in use: res://addons/dialogic/Editor/Images/preview_character_speaker.png (CompressedTexture2D)

**To Reproduce**
1. Open your Godot project (I open with on Ubuntu via command-line with the --verbose option)
2. When your project is loaded, exit Godot
3. Scroll in the cmd up to the line "ERROR: Resources still in use at: clear (core/io/resource.cpp:493)"

**Expected behavior**
Resources should be freed to avoid leakage

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Godot Version: 4.2
 - Dialogic Version: 2.0-Alpha-11

**Comment by Jowan-Spooner** [comment]
Can you retry with alpha 12?

**Comment by EFrion** [comment]
No more problems with alpha 12! Nice work :)
