### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by breadnone** [coppolaemilio/dialogic#2]
As in any narrative based games, there are few functions or effects that are missing in this wonderful plugin.

1. Screen shake effects
2. Character sprite animation (useful for character expressions such as; angry, sad, etc...)
3. Choices tagging (for conditional multiple endings) e.g: if I choose "YES" in ch1 and "NO" in ch3 I will get bad ending and so on and so forth.
4. Better multimedia handling (audio, video, sound effects, start to end of the audio being played).
5. Tweening kinda effect (Character leaving the scene from left to right or the other way around)
6. Visual editor/chart (useful to know the branching paths)

Point 1-3, I coded these manually and it's not that hard but for the sake of completeness of this awesome plugin, it would be nice if they come out of the box.

Thanks for this awesome plugin. Cheers!

**Comment by coppolaemilio** [comment]
Some of this points are already implemented, but I'll close this issue and you can re-open them one by one instead of all of them in one big list. I won't implement all you are proposing here but it would be nice to keep it documented in case it gets implemented eventually. Thanks!
