### ISSUE TITLE
Wait Seconds Event: Two wait seconds events near to each other break the game

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#206]
## The problem

**Describe the bug**
Having two Wait Seconds events near to each other makes the game break.

**To Reproduce**
1. Create a timeline similar to this:

![grafik](https://user-images.githubusercontent.com/42868150/114427822-c159a780-9bbb-11eb-9ec1-b90373a5ee0b.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3
 - Dialogic Version: 1.1 something

I think it is @coppolaemilio fault ;).

**Comment by coppolaemilio** [comment]
> I think it is @coppolaemilio fault ;).

Always 🥲

Closing with https://github.com/coppolaemilio/dialogic/commit/5438e5c37889e853a77607ce7ec0565d8f2a623c
