### ISSUE TITLE
Translate Dialogic UI to multiple languages

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#21]
Initial work for this one has been done. This will be a tracker now of the things left to translate:

- [ ] Timeline Editor (Event buttons)
- [ ] Character Editor
- [ ] Definition Editor
- [ ] Theme Editor
- [ ] Settings

**Comment by Jowan-Spooner** [comment]
I would like to help. I could translate to german. Is this already possible or just a dream?

**Comment by coppolaemilio** [comment]
@AnidemDex is working on this one, but I'm not sure of the state of it

**Comment by AnidemDex** [comment]
Take a look to https://github.com/coppolaemilio/dialogic/pull/127
The plugin can be translated to any other language, you can [see the CSV files here](https://github.com/AnidemDex/dialogic/tree/translation/addons/dialogic/Translations) and the editor will be translated after reload. Anyway, there's no translations to events, yet
