### ISSUE TITLE
End Branch Event: make deleting easier / or more obvious

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#219]
**Is your feature request related to a problem? Please describe.**
Sometimes I delete a question event or a condition event and the end branch just stays there. Most of the time I notice it and delete it, but sometimes I don't and then I get an error. 

**Describe the solution you'd like**
It would be cool if the event could show an error if it is placed incorrect like the choice event or if it would just be deleted together with the corrsponding starting event.

**Comment by Jowan-Spooner** [comment]
Adding to this: I think it would make even more sense (be easier to use) if you couldn't delete the End Branch event and couldn't add it by hand. I cannot think of moments where I would want to only delete the End Branch event or add a single one (as both will result in Errors).

**Comment by muchitto** [comment]
Doesn't make sense to me either that you can delete or add these nodes. Was pretty confused what they were used for when tried the plugin out for the first time.

**Comment by coppolaemilio** [comment]
I think we can close this one for the 2.0, right @Jowan-Spooner ?

**Comment by Jowan-Spooner** [comment]
Yes!
