### ISSUE TITLE
Dialogic dialogue box doesn´t scale at all when stretch mode is set to 2D and aspect is kept to keep

### ISSUE THREAD

**Issue by Dragon20C** [coppolaemilio/dialogic#222]
## The problem

**Describe the bug**
Dialogic dialogue box doesn´t scale at all when stretch mode is set to 2D and aspect is kept to keep

**To Reproduce**
1:set the project resolution to say a pixel resolution I have 320,180
2:set stretch mode to 2D and aspect to keep
3:The dialogue box doesnt show up on the screen but it exists

**Expected behavior**
The dialogue box to scale to the correct resolution
**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.2.3
 - Dialogic Version: 1.0
## Solutions
 turn off 2d stretch but now everything is small, not a good solution
**Workaround**
none
What you tried to get the feature working

**Possible fixes**
scale when 2d stretch is selected
Any idea to fix the issue or a link to the line of code that might be the cause for this problem
none

**Comment by coppolaemilio** [comment]
This was fixed before and it seems like some of the new updates broke it. I'll revisit the issue and make sure that it works as expected for 1.1

**Comment by coppolaemilio** [comment]
@Dragon20C The fix is already on `main`. I will close, but feel free to re-open if it is not fixed

**Comment by Dragon20C** [comment]
That was quick! I'll be sure to take a look soon!

**Comment by AlexeevAlex** [comment]
Hey, I was having the same problem, I've tried it and it doesn't work yet
The resolution is 480x270, it is set to 2D and keep. 
![image](https://user-images.githubusercontent.com/74484311/114918162-ffd1ab00-9de3-11eb-9dcf-732ca368ae2e.png)

**Comment by coppolaemilio** [comment]
@AlexeevAlex can you send me the project?

**Comment by AlexeevAlex** [comment]
Yep, here it is 

[Test.zip](https://github.com/coppolaemilio/dialogic/files/6320332/Test.zip)

**Comment by coppolaemilio** [comment]
The stretch mode is working correctly, you just have to create a theme and set the size to be smaller than your screen @AlexeevAlex

**Comment by AlexeevAlex** [comment]
Oh, okay, yeah, I've just noticed... Make the dialogue box smaller and customize the default font to a smaller size and everything is fine!
