### ISSUE TITLE
Add a way to manage saves manually.

### ISSUE THREAD

**Issue by mscharley** [coppolaemilio/dialogic#224]
**Is your feature request related to a problem? Please describe.**

My game has multiple save slots which the player can save or load from. This doesn't seem to be supported by the current autosave mechanisms in Dialogic.

**Describe the solution you'd like**

The ideal situation I can think of consists of three parts:

1. An opt-out scheme for the autosaves, perhaps `Dialogic.set_autosave(false)`. Nothing should be written into `user://` until a conversation dialog is shown at the earliest to give some time to the developer to call this function.
2. A `Dialogic.export() -> data` function that returns a single data structure representing the current Dialogic state.
3. A `Dialogic.import(data) -> void` function that takes a data structure from a previous export and updates Dialogic's state to those settings.

**Describe alternatives you've considered**

Using an opt-in scheme for autosaves could make the Dialogic code simpler at the cost of being a breaking change to developers using this addon.

**Additional context**

The current setup doesn't seem to be tenable for any style of game having more than one save state.

**Comment by arnaudvergnet** [comment]
All saves are written in the `user://dialogic` folder, so a simple workaround would be to manually copy this folder. For example, each of your saves have folders names `user://dialog-saveX`, and when you want to load it, move the wanted folder to `user://dialogic`. SO there is a way to do that if you really need to right now.

But I agree, the saving system could be improved!
