### ISSUE TITLE
Select choices using keyboard

### ISSUE THREAD

**Issue by LoipesMas** [coppolaemilio/dialogic#226]
**Is your feature request related to a problem? Please describe.**
Currently player has to select choice using mouse.

**Describe the solution you'd like**
Ability to highlight and then select choice options using keyboard (/other input device e.g. gamepad)

**Describe alternatives you've considered**
Don't know of any alternatives

**Comment by coppolaemilio** [comment]
I believe this is already implemented by @timkrief. Is that correct?

**Comment by timkrief** [comment]
Yes! but the highlight will only happen if using standard godot buttons (toggle available in themes) as we discussed. We could add different texture choices for highlight or a little arrow to show which one is selected for instance.

**Comment by LoipesMas** [comment]
Oh right. I was using the release. It works on main branch.
But on main branch the choice options seem to be placed in top-left corner, pretty much out of the screen, while on release version they were centered. Is this a (known) bug, or I need to do something differently?

**Comment by coppolaemilio** [comment]
@LoipesMas can you post screenshots and more details about your setup?

**Comment by LoipesMas** [comment]
Release:
![image](https://user-images.githubusercontent.com/46327403/115038125-83b49180-9ecf-11eb-8b2e-046fd420fc82.png)
![image](https://user-images.githubusercontent.com/46327403/115038201-962ecb00-9ecf-11eb-9d8b-14bb43b12455.png)
Main branch:
![image](https://user-images.githubusercontent.com/46327403/115038386-c7a79680-9ecf-11eb-90c1-d4c66eb4783b.png)
![image](https://user-images.githubusercontent.com/46327403/115038442-d42bef00-9ecf-11eb-9e80-a0f88d853f31.png)

Both using unchanged theme and default scene.

**Comment by coppolaemilio** [comment]
I'll look into it! thanks for the screenshots

**Comment by LoipesMas** [comment]
Also the scene setup is just a Node2D that in `_ready()` spawns dialog and adds it as its child.

**Comment by coppolaemilio** [comment]
okay, I recently did some changes with the stretch mode and that seemed to be the reason. 
Try with the latest version of `main` and it should be centering properly 👍🏻

**Comment by LoipesMas** [comment]
Yep, it works now.
Thanks.

**Comment by coppolaemilio** [comment]
Glad it works now! Closing :)

**Comment by rjboczar** [comment]
Did this get removed/broken? No longer works for me on most recent commit (1d6624), on Godot 3.4b6.

I can see that the `_on_option_hovered` callback is getting called when using the keyboard to switch options, but the options only change style to hover on mouseover (which does `not` call that callback).
