### ISSUE TITLE
Keyboard option selection doesn't work sometimes

### ISSUE THREAD

**Issue by LoipesMas** [coppolaemilio/dialogic#227]
## Keyboard option selection doesn't work sometimes

**Describe the bug**
Keyboard option selection doesn't work if the question event isn't preceded by text event.
You need to press action key once for it to start working. 

**To Reproduce**
1. Create new timeline
2. Add question event
3. Launch dialog
4. Try selecting option using arrow keys

**Expected behavior**
Option selection should work from the start, without the need to press the action key.

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.2.3
 - Dialogic Version: main branch (commit 5676045)

## Solutions

**Workaround**

If there is Text Event directly before Question Event it works correctly.
So "Text Event -> Question Event" time line works.
But with "Text Event -> Question Event -> Question Event" the second question doesn't work.
As stated above, when at the question event, pressing action key once fixes it for current question event.

**Comment by coppolaemilio** [comment]
This should be fixed in the latest branch :) more improvements coming tomorrow!
