### ISSUE TITLE
Scaling on 2D

### ISSUE THREAD

**Issue by ViperousRogue67** [coppolaemilio/dialogic#234]
So right now in 2D, there is a problem
If you have a lower resolution (320x180, 2D Stretch)
This Happens:
![Screenshot 2021-04-19 214445](https://user-images.githubusercontent.com/79262633/115247430-5c70f500-a159-11eb-8cf3-346e0cbbda44.png)
What I recommend is to make a feature to rescale the text or provide a workaround to fix this problem. As I have been trying to fix it for an hour.

**Comment by Jowan-Spooner** [comment]
What version are you using?

**Comment by ViperousRogue67** [comment]
3.2.3 (Latest)

**Comment by ViperousRogue67** [comment]
1.0

**Comment by Jowan-Spooner** [comment]
Could you please try your project with 1.1 WIP. Make sure to make a copy of your project!
It could be that this problem is already solved. Support for all stretch modes is still in the work ;).

**Comment by coppolaemilio** [comment]
It seems like you are using the default theme. You need to create a custom one with your desire size and make it fit to your resolution. Hope that helps! 👍🏻
