### ISSUE TITLE
Portraits Broken

### ISSUE THREAD

**Issue by zakary93** [coppolaemilio/dialogic#235]
Hey, just downloaded newest build w/ portrait fix. It is not fixed. Portraits still don't show up (actually first time for me, previous build I have was from 4/14/21 and it worked then). On Windows 10.

**Comment by coppolaemilio** [comment]
@zakary93 hello! I pushed another fix for portraits. Can you check now?

**Comment by zakary93** [comment]
It is good now. Sorry for late reply. I am working on a fork to include Nicknames (which get autocolored with the names if enabled) and fixed a recurring issue with names but the builds from the last 2 days broke other parts so I got absorbed in that. Still trying to track that down.

**Comment by coppolaemilio** [comment]
if you think it is a feature that would benefit more people you could always add it as a feature request issue and/or send a PR. Glad it is finally fixed! Closing this now

**Comment by zakary93** [comment]
I will send a PR when I get it to work properly in the current build. I might make a small one to fix the recurring name coloring issue soon in the meantime though.
