### ISSUE TITLE
Question text going out of screen in editor

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#237]
## The problem

**Describe the bug**
As the question text is one line only, it can be too long and go out of screen, making an horizontal scroll appear.

**To Reproduce**
1. Open a timeline
2. Create a question
3. Write a long line
4. See the scroll appear

**Expected behavior**
The line should wrap if too long, like in a text edit.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Godot Version: 3.2.3
 - Dialogic Version: latest main 7970e027f9226de14aa29cc9eaa95e2c9dc03a77

## Solutions

**Possible fixes**

We could use the new template to reuse the text input content, so the behavior would be the same, but limiting to one line only.

**Comment by Jowan-Spooner** [comment]
This is basically fixed on the main branch. The Question event now is more similar to the text event.
