### ISSUE TITLE
Session State

### ISSUE THREAD

**Issue by codecomedytv** [coppolaemilio/dialogic#245]
I don’t github so good so please be kind. Can I recommend a session state? I think you can view dialog as 3 states for variable definition. Starting state, session state, and cached result state. Starting state is whats required to power the next branch. Cached state is already what you have for reset_saves and save(false). However, this gives incorrect results for session + 1. There also seems to be a wait 1 second requirement for calculations that depend on definitions. I can currently solve this with dialogic_signal and external store but this doesn’t allow me to use all of your cool features. Perhaps expose session saved definitions in the root rather than user which currently has saves

**Comment by coppolaemilio** [comment]
I don't really understand this issue 🙈
