### ISSUE TITLE
Allow using custom choice buttons

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#247]
**Is your feature request related to a problem? Please describe.**
The current options for choice buttons are too limited, and the amount of possibilities someone could request is too great. For this reason, we should let the user use its own component for buttons. 

**Describe the solution you'd like**
In the theme editor, `Choice Buttons` tab, create a new field letting the user select a custom button scene, telling him the only constraint is that is has a `pressed` signal available.

**Describe alternatives you've considered**
I tried using native buttons but we can't customize them, same if using only a texture.

**Additional context**
I first planned on adding more customization options, but then saw all the possibilities and ditched the idea.

**Comment by Jowan-Spooner** [comment]
I like the idea but would suggest, that in that case there should be an default button scene, that can be expanded upon/ changed. Also wouldn't such a scene need a set_text function?

**Comment by arnaudvergnet** [comment]
As you can see in #248, the user is warned about those requirements. Adding a default scene is an idea, but I am not sure it is necessary as it would just be a scene with a button in it

**Comment by Jowan-Spooner** [comment]
I think personally I see no reason for using this feature with a button scene, instead of using a theme. My first thought was to use a texturebutton. But they don't have text. So you would have to add a label to that scene and add a setget function that updates the label... but yeah it's not neceasary.

**Comment by arnaudvergnet** [comment]
Well, I wanted different textures depending on the cursor (hover, pressed, normal), and the theme did  not allow me do to that

**Comment by Jowan-Spooner** [comment]
Well that is only possible with a Texturebutton and that has no native text property/display. Doesn't mean it's not possible, but that's why I thought a default scene that already has such a button with working text could be easiest to understand and work with.
