### ISSUE TITLE
Dialog position issue with low resolution screen size

### ISSUE THREAD

**Issue by FilloSov** [coppolaemilio/dialogic#251]
## The problem

**Describe the bug**
The dialogue box center always shows up on (0,0) on the main scene, even if we instanciate it as a child of the player. If we set up the Box Size from the Dialogic theme editor to 230*70 and the Bottom gap to 1, the dialogue box center is in the correct position. For every other combination of values it goes back to (0,0). Font dimension is 6.

**To Reproduce**

We used the following code:
```
extends Area2D

class_name TriggerDialog

onready var currentPosition = $CurrentPosition

func _ready():
	pass


func _on_TriggerDialog_body_entered(body):
	if body is Player:
		var player := body as Player
		player.block()		
		var current_dialog = Dialogic.start(DialogManager.next_as_string())
		current_dialog.connect("event_end", player, "unblock")
		player.add_child(current_dialog)
		current_dialog.rect_position = Vector2.ZERO + Vector2(0, 50) #centered on the player + offset
		
		queue_free()

```

**Expected behavior**
We expect to have the dialogue box to be always centered wrt the player.

**Screenshots**
Theme Settings
![image](https://user-images.githubusercontent.com/61621554/115698699-33bd4b00-a365-11eb-8f45-649c5c281716.png)
Correct Dialogue Position (the camera is zoomed out for debug reasons):
![image](https://user-images.githubusercontent.com/61621554/115698946-75e68c80-a365-11eb-9de1-ba24ca63d864.png)
Theme Settings changed (71 instead of 70):
![image](https://user-images.githubusercontent.com/61621554/115699090-9f071d00-a365-11eb-9758-e9cc6e076e22.png)
Consequent beahvior:
![image](https://user-images.githubusercontent.com/61621554/115699200-bba35500-a365-11eb-8059-909ad90c20d8.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.3
 - Dialogic Version: 1.0

## Solutions

**Workaround**

We can keep it in 230*70.

This is our first project so probably it is all our bad. Thank you for the amazing work, Dialogic is amazing.

**Comment by Jowan-Spooner** [comment]
Could you try it with the latest main branch? Some sizing issues where already fixed but I'm not sure if thia is one of them. Make a copy of your project first. 

Also note that in most cases you would want to add your dialog as child of a canvas layer node, so it is not affected by the camera.

**Comment by FilloSov** [comment]
Adding the dialogue as a node of a canvasLayer solved the issue, thank you very much.
