### ISSUE TITLE
Have the Character name display within the dialog box

### ISSUE THREAD

**Issue by Shargon-Pendragon** [coppolaemilio/dialogic#252]
**Is your feature request related to a problem?  I'm unable to move the character's name to the inside the dialog box where I designed a name box.

**Describe the solution you'd like**
Would like to be able to move the character's name to where I need using x and y. 

**Describe alternatives you've considered**
Just give me some way to move the character's name

**Additional context**
This is a mock done in photo shop of what I would like the dialog box the look like. See how the character's name is inside the dialog box. 

![dbox game shot example](https://user-images.githubusercontent.com/29558236/115779543-bbaf4f00-a37d-11eb-84f1-ba0184ea0766.png)

**Comment by Shargon-Pendragon** [comment]
Thanks for scheduling this feature. Can't what to see it.

**Comment by Jowan-Spooner** [comment]
Wouldn't this be possible with #261?

**Comment by Splyth** [comment]
I believe that issue only deals with horizontal movement 

This one is about adding vertical movement.

**Comment by coppolaemilio** [comment]
You should be able to modify the vertical position of the node using this settings on the theme editor: 
![image](https://user-images.githubusercontent.com/2206700/117021647-d11a6680-acf7-11eb-9a94-310755a503a7.png)

I will add other offset x and offset y soon

**Comment by Shargon-Pendragon** [comment]
I updated dialogic to 1.2 for our project. Using the options you highlighted was able to get the name to move to the correct position but now dialogic isn't working. Using the code below I try to add a dialog box to my game. Yet I keep getting the error "Invalid get Index 'event_id' ". How can I correct this issue. 

Code:
	var new_dialog = Dialogic.start('Starting Dialog')
	add_child(new_dialog)

Error:
![Dialogic_Error](https://user-images.githubusercontent.com/29558236/117051404-1f217100-acdc-11eb-82c3-7ff8beaa474e.png)

**Comment by Jowan-Spooner** [comment]
Could you have a look into the event variable down there in the Debugger and post an image of it? Thanks. Sorry you encounter this but.

**Comment by Shargon-Pendragon** [comment]
Here you go
![Dialogic_Error](https://user-images.githubusercontent.com/29558236/117186652-ab956780-ada0-11eb-8c06-a41fbbb99caf.png)

**Comment by coppolaemilio** [comment]
@Shargon-Pendragon can you try again on the latest version of `main`?

**Comment by Shargon-Pendragon** [comment]
That worked, Thank you!!
