### ISSUE TITLE
Errors whenever dialog starts

### ISSUE THREAD

**Issue by spookto** [coppolaemilio/dialogic#253]
## The problem

**Describe the bug**
Whenever a new dialog starts Godot returns an error saying " 'Texture' is not instantiable ".

**To Reproduce**
1. Create a new GDScript.
``` 
func _ready():
	var d = Dialogic.start("interaction")
	add_child(d)
```
2. Run scene.

**Expected behavior**
The dialog should appear on screen without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/52279309/115961472-2d72ce80-a51f-11eb-9fa6-1ca3bda33ed4.png)
![image](https://user-images.githubusercontent.com/52279309/115961700-3e700f80-a520-11eb-849d-8104efdbc4f9.png)

**System:**
 - OS: Windows
 - Godot Version: 3.3
 - Dialogic Version: main (1.1)

## Solutions

**Possible fixes**

Changing `` Texture.new() `` to `` ImageTexture.new() `` or any class that inherits `` Texture `` fixes the error.

Godot's Documentation says:
[``Texture`` is a base for other resources. It cannot be used directly.](https://docs.godotengine.org/en/stable/classes/class_texture.html)

**Comment by coppolaemilio** [comment]
Thank you!
