### ISSUE TITLE
How to show character sprites during dialog?

### ISSUE THREAD

**Issue by Handsomeprisim** [coppolaemilio/dialogic#254]
I couldn't find information on how the character sprites are to be shown during dialog.

**Comment by coppolaemilio** [comment]
Hello there! This is a pretty common mistake, I added an answer on the FAQ:

https://github.com/coppolaemilio/dialogic#-i-cant-see-the-character-sprites-during-the-dialog

> For the characters to be visible during the dialog, you need to add them to the current scene buy using the "Character Join" Event. Select the character you want to add, the position and the rest of the settings. Whenever you want them to leave, use the "Character Leave" event. 

Hope that helps!
