### ISSUE TITLE
Impossible to add timeline, characters etc. 

### ISSUE THREAD

**Issue by NerdChickenGames** [coppolaemilio/dialogic#255]
## The problem

**Describe the bug**
With the last version (25.04.2021 16:53) the plugin doesn't work. The buttons to add Timelines, Characters, Definition and Themes are empty. And when I click on the icon, nothing happen. 

**To Reproduce**
1. Go to Dialogic plugin 
2. Click on timelines or character or wherever you want, nothing happen. 
3. 
**Expected behavior**
Create a new Timelines, Characters etc. 

**Screenshots**
![Capture d’écran du 2021-04-25 19-02-16](https://user-images.githubusercontent.com/81973078/116002320-8151e600-a5f9-11eb-83a1-3c468a9c6bdb.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Godot Version: 3.3.3
 - Dialogic Version: 1.1 (25 april update)

## Solutions

No idea... 

**Possible fixes**
Burning the computer... maybe...

**Comment by Jowan-Spooner** [comment]
Have you tried the icons in the toolbar?

**Comment by NerdChickenGames** [comment]
> Have you tried the icons in the toolbar?

I closed Godot and restarted it and now it's work. Strange because with the last versions, I never restarted Godot after installing Dialogic

**Comment by Jowan-Spooner** [comment]
I would vote to close this. It's quite normal that restarting is necessary.
