### ISSUE TITLE
Adding a Random dialog Node to the Dialogic graphical mode

### ISSUE THREAD

**Issue by NerdChickenGames** [coppolaemilio/dialogic#259]
### Description of the concept
I would like to propose you to integrate in the graphical mode of Dialogic a "random dialog node". 
The idea is to allow a character to display a random dialogue among several possibilities. This is to avoid repetition and linearity of dialogs when an NPC has to do a dialogue loop (exemple: the welcom dialog of a vendor in a market place). These small variations of text that have no impact on the main story make the dialogues more alive.

**How it would work ?**

![dialogic random text](https://user-images.githubusercontent.com/81973078/116204690-4bb61580-a73d-11eb-9695-c7c285f64c1c.png)
Printscreen of the Random dialog interface

- Random dialogs would be available as a node in the Timeline section.
- The user can add the node in the Timeline with drag and drop (like others nodes like Text Event, question etc.)
- The user can set the number of possibilities and wich character speak. 
- By adding the number of possibilities, the text events are automatically created as well as the end node. 
- The user can change the order of the Text events with drag and drop 
- The user can set the probability to display each Text events with a priority order (In the example above, the second answer is twice as likely to be displayed as the others.)

I hope you like the idea, I think it would be really useful especially in visual novels when there are dialogue loops to make the characters more alive.
Unfortunately my knowledge of GDScript is not yet advanced enough to implement this new node within Dialogic.

**Comment by arnaudvergnet** [comment]
Seems like a good idea!

Maybe the easiest way to implement this would be to add a random value to the `Set value` event, and then make several `if` after.

As a workaround until such a feature is implemented, what you can do is emit a signal, then catch this signal in your game to set the value of a Dialogic variable to a random value. This will emulate a `Set random value` graphical node.
You can then create several `if` events in the graphical editor to display different dialogs depending on the value.

**Comment by coppolaemilio** [comment]
I like the idea. I would call the event `Chance` and make it work with "options" for the branches, not sure it would get implemented soon, but thanks for the mockup and explanation since it seems like an awesome feature to add to Dialogic! 👍🏻

**Comment by NerdChickenGames** [comment]
@arnaudvergnet Yes it's a possibility but if you work with a team (especially with writers and artists) it's a difficult way to use dialogic. With this feature, people who don't have habits to code can easily write the dialogs. 

@coppolaemilio Your welcome, I really like you addon and I use it a lot !  I hope to participate further in the development of dialogic

**Comment by coppolaemilio** [comment]
@NerdChickenGames in the latest update I added @Jowan-Spooner new feature of setting a random value. It is not exactly as you made it here since you will need to be checking with "if events" but you can achieve better results now than you could before. Please let me know if this works for you, and if it does we can close this issue 🙃

**Comment by Jowan-Spooner** [comment]
As @NerdChickenGames said he doesn't have much time right now, I would close this for now. If there is a need for more, this can be reopened.
