### ISSUE TITLE
Samples not valid JSON

### ISSUE THREAD

**Issue by chucklepie** [coppolaemilio/dialogic#26]
Hello,
If you move your embedded JSON sample script (in dialog_node.gd) to a file then it fails to load because it is not valid JSON. In addition, your file() method performs no checks on the parsed JSON to see if it's valid, it simply returns null back to your code.

I know this is all WIP and not ready, just trying to help in case you didn't have these in your list of things to do.

Hope this helps ;-)

1. In the following the comma after 'face' should not be there, it's invalid JSON
	{
		'character': 'Kubuk',
		'text': 'Maybe... Now that you mention it, I can actually see your face!'**,**
	},

2. None of your single quotes are valid, they should be double:
	{
		"character": "Kubuk",
		"text": "Maybe... Now that you mention it, I can actually see your face!"
	},

In your file() method, you may want to check the dict is valid, i.e. as below is simply check for null.

if typeof(p.result) == TYPE_ARRAY:

btw, I think it looks a lot neater moving all that json sample in the dialog script to a separate json file...

**Comment by coppolaemilio** [comment]
Those samples are not being included any more. Not sure why I had them there still :)
