### ISSUE TITLE
fade_out connects when already connected

### ISSUE THREAD

**Issue by chucklepie** [coppolaemilio/dialogic#264]
## The problem

**Describe the bug**
If you call fade_out multiple times. You get an error:
E 0:00:10.845   connect: Signal 'tween_all_completed' is already connected to given method 'queue_free' in that object.

Apologies if this is fixed in 1.0 somewhere else in the code, as I'm on an earlier version, but the fade function below is still the same.

```
func fade_out(node = self, time = 0.5):
	tween_modulate(modulate, Color(1,1,1,0), time)
	$Tween.connect("tween_all_completed", self, "queue_free")
```

While it still functions fine, the fix would be to only connect if not already connected, or disconnect first.

**Comment by coppolaemilio** [comment]
I can't reproduce, can you try it again in the latest version?

**Comment by chucklepie** [comment]
I'll try and recreate it
