### ISSUE TITLE
Some fonts do not render text effects correctly.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#265]
## The problem

**Describe the bug**
Text formatting using some fonts does not accurately work. For example, a project that uses Open Sans does not render bold or italic text correctly. Other fonts may well have similar behaviour - the default font does.

**To Reproduce**
1. Create a theme that uses Open Sans.
2. Create a timeline that uses that theme with text that uses `[b]` or `[i]` tags.

**Expected behavior**
Bold and italic text to display correctly.

**Screenshots**
![Using_italics_timeline](https://user-images.githubusercontent.com/324679/116391129-b25b3200-a816-11eb-8b53-24b485b94a29.png)
![Using_italics_game](https://user-images.githubusercontent.com/324679/116391131-b2f3c880-a816-11eb-88c1-9c05a95acfc5.png)
![Default_font_faulty_preview](https://user-images.githubusercontent.com/324679/116391715-69f04400-a817-11eb-958a-a8b04e801f62.png)

**System (please complete the following information):**
 - OS: Ubuntu Linux 20.10
 - Godot Version: 3.3
 - Dialogic Version: 1.1

## Solutions

**Possible fixes**

Using a different font?

**Comment by Jowan-Spooner** [comment]
This is know. There are no italic and bold fonts. Related to #122.

**Comment by coppolaemilio** [comment]
@Sslaxx A fix for this has been merged in the current main! Check it and if you think it is not fixed you can comment again here. Please remember that you might need to change the fonts that you picked on your theme.
