### ISSUE TITLE
Definitions don't seem to be loading from JSON correctly

### ISSUE THREAD

**Issue by dorkyface** [coppolaemilio/dialogic#267]
Basically, I added a new definition to my game called "Familiarity". However, Dialogic keeps returning an empty string as if it can't find it. I printed the glossary of definitions to console, and sure enough:
![image](https://user-images.githubusercontent.com/69087850/116419970-38db3800-a846-11eb-9fa5-657365a412d5.png)

What's weird, is that when I go to the file stored on my system, the new definition IS listed:
![image](https://user-images.githubusercontent.com/69087850/116420171-69bb6d00-a846-11eb-8ad7-c40e53a747d7.png)

Here it is listed along with the rest of the definitions in the Dialogic tab:
![image](https://user-images.githubusercontent.com/69087850/116420362-94a5c100-a846-11eb-81a1-42e4cbd25100.png)

I'm on Windows 10, Godot 3.3, and Dialogic 1.1

**Comment by Jowan-Spooner** [comment]
I think I have incountered this before. What sometimes makes this happen is if you set reset_saves to false. In that case it thinks it knows everything and just loads the definitions from your save. But maybe the definition didn't exist when your save was created. 
If you are able to without destroying something, try setting reset_saves to true.
Nevertheless this is a bug and should be fixed.

**Comment by dorkyface** [comment]
> 
> 
> I think I have incountered this before. What sometimes makes this happen is if you set reset_saves to false. In that case it thinks it knows everything and just loads the definitions from your save. But maybe the definition didn't exist when your save was created.
> If you are able to without destroying something, try setting reset_saves to true.
> Nevertheless this is a bug and should be fixed.

Yup, I can confirm that opening a dialogue box with reset_saves set to true fixed it. Thanks for the tip! Still a bug tho :)

**Comment by arnaudvergnet** [comment]
Yes it doesn't compare default definitions and saved ones, so if you added new definitions compared to your last save, it won't know about it unless you reset the saves. Might be a problem when making updates to a game.

**Comment by craigostrin** [comment]
Oh god, this bug's a killer. I was really struggling with it (and was about to abandon the plugin entirely) when I found this thread.

I'm working on a prototype without a save system, and right now the most sensible workaround seems to be to just call "Dialogic.reset_saves()" every time the game launches. If I had a save system, I suppose I'd call reset_saves() when the player starts a new game.

So far this seems like a fine workaround, and it makes sense that Dialogic wants to start from its save by default, but it's somewhat counter-intuitive behavior during development. Honestly, you might not have to make any grand changes to the code if this were just clearly documented somewhere.

**Comment by coppolaemilio** [comment]
I'm going to close this one since the save system is rewritten for 1.3
