### ISSUE TITLE
Make resources more "git friendly"

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#269]
**Is your feature request related to a problem? Please describe.**
Resources such as definitions and timelines are saved minimized, thus on the same line.
This makes working with git harder as each change will trigger a merge conflict.

**Describe the solution you'd like**
Pretty print JSON in the files. This will increase file size but maybe we can add a minify script that users can run before packing the game.

**Describe alternatives you've considered**
Right now I make sure only one person edits a timeline at the same time, but this is not practical.

**Comment by coppolaemilio** [comment]
I really like this one 👍🏻
