### ISSUE TITLE
Offset and scale settings for portraits should be per-picture.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#274]
## The problem

From a character description file:
```
	[...]
	"offset_x":0,
	"offset_y":-200,
	"portraits":[
		{"name":"Default", "path":"res://Assets/Graphics/1262274531.thesheatechnique_sslaxxheadcomm500.png"}
	],
	"scale":85
}
```

This means that portrait files must all be the same resolution in order for offset and scale settings to work. And true, all portrait files *should* be the same resolution. But sometimes they may not be, and if so then there's no way in editor to set an individual portrait's scale and/or offset.

**To Reproduce**
Just add more than one portrait to a character.

**Expected behavior**
Being able to set scale and/or offset settings for individual portraits.

## Solutions

**Workaround**

Editing the portraits in software like GIMP, Krita etc.

**Possible fixes**

Editing the portraits in software like GIMP, Krita etc.

**Comment by coppolaemilio** [comment]
An improvement to portraits would be nice. This could be one of the options for each portrait for sure :)

**Comment by coppolaemilio** [comment]
Related to https://github.com/coppolaemilio/dialogic/issues/820

**Comment by Jowan-Spooner** [comment]
In 2.0 offset, scale and mirror are per-portrait. 
Ther is also a global scale setting. I think a global offset and mirror would be good as well.
