### ISSUE TITLE
Wait seconds event unfolded

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#275]
## The problem

**Describe the bug**
When click on the unfold button on the top left, the wait seconds event is also unfolded while it has no body.

**To Reproduce**
1. Open a timeline
2. Add a wait seconds event
3. Click on unfold all events on the top left
4. See the unfolded event

**Expected behavior**
It should not be possible to unfold events without a body

**Screenshots**
![Screenshot_20210429_194439](https://user-images.githubusercontent.com/80701113/116595513-b1fc8d00-a923-11eb-9e37-8e2e12c71855.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Godot Version: 3.2.3
 - Dialogic Version: latest main

## Solutions

**Possible fixes**

Block unfolding when event has no body

**Comment by Jowan-Spooner** [comment]
This was fixed by the Timeline eventblocks rework.
