### ISSUE TITLE
Character positioning gets cut off with lower resolutions and scaling

### ISSUE THREAD

**Issue by jatgm** [coppolaemilio/dialogic#279]
## The problem

**Describe the bug**
When using a lower resolution for the game, the positioning of the sprites can sometimes be cut off when not using the center position. For example, when using a HD resolution, 
![image](https://user-images.githubusercontent.com/37679610/116826006-c4a2dc00-ab46-11eb-8aca-b6801a5665e0.png)
It works just fine
![image](https://user-images.githubusercontent.com/37679610/116826160-80640b80-ab47-11eb-9749-09a0ce483e48.png)
However, when you're lowering the resolution and also stretch it up, the sprite no longer appears on screen (Using 2D Scaling)
![image](https://user-images.githubusercontent.com/37679610/116826259-f9fbf980-ab47-11eb-9eac-0a3164a74398.png)

**To Reproduce**
1. Lower the resolution of your project, and stretch it up to a higher resolution using 2D stretching
![image](https://user-images.githubusercontent.com/37679610/116826288-21eb5d00-ab48-11eb-8ed5-a002cc66d4a9.png)
2. Put your character in any place other than the middle position

**Expected behavior**
Have the character be on screen

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3
 - Dialogic Version: 1.1

**Comment by coppolaemilio** [comment]
Hey! Thanks for the report. What is the resolution of the sprite you are using?

**Comment by jatgm** [comment]
Hello! Thank you for the response.
![image](https://user-images.githubusercontent.com/37679610/116833812-1d3a9f00-ab70-11eb-850b-f1859b839190.png)
I'm using 1000x1000 px for the sprite.

**Comment by coppolaemilio** [comment]
Yeah, your portrait is too wide, so dialogic tries to show the image in the wrong position. You can use the offset feature (under the portrait preview in the character editor) and add 500px of offset, or just make the image less wide and more like a vertical rectangle with less empty space to the sides

**Comment by jatgm** [comment]
I tried making the sprite smaller and making it thinner, however it still had the same problems it did with the 1000x1000 sprites, where if they were in either the 1st or the 5th position slot they would be completely cut off

**Comment by jatgm** [comment]
If I raise my resolution, they start slowing coming back into frame but I need to keep my resolution low because I also intend to make a pixel art RPG game

**Comment by coppolaemilio** [comment]
This is not a Dialogic issue. The portraits are showing as expected and the resolution issues can all be fixed by changing how you render the game in Godot
