### ISSUE TITLE
Constant errors on placing a dialog node

### ISSUE THREAD

**Issue by mmmegaidiot** [coppolaemilio/dialogic#28]
I got two errors of the following:
1. 0:00:00.506   get_node: Node not found: TextBubble/NameLabel.
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1381 @ get_node()
  <Stack Trace> dialog_node.gd:27 @ _ready()
2.E 1:14:19.183   get_node: Node not found: TextBubble/NextIndicator.
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1381 @ get_node()
  <Stack Trace> dialog_node.gd:103 @ _process()

**Comment by coppolaemilio** [comment]
Can't reproduce
