### ISSUE TITLE
character portrait animations?

### ISSUE THREAD

**Issue by amphirevu** [coppolaemilio/dialogic#280]
adding the option to give the character portraits simple animations like jump or bounce or shaking would be rly cool!

**Comment by Jowan-Spooner** [comment]
Would you want this animation to play constantly or only when the character is talking?

**Comment by amphirevu** [comment]
> Would you want this animation to play constantly or only when the character is talking?

once when the character talks? i'm imagining it as sort of a visual effect to indicated that they're surprised or something so their portrait jumps up or theyre happy so they do a little bounce

**Comment by Jowan-Spooner** [comment]
So this would be a feature of the talk/join event I guess. Or even of the character/portrait picker, so you can choose this whenever you have a character focused.

**Comment by amphirevu** [comment]
yup sounds about right !

**Comment by zakary93** [comment]
What about having full fledged portrait animation with animation frames as an Event called Play Portrait Animation (you choose which character that has already joined the scene and which animation from drop down boxes), which loops once and has a checkbox/button to make it loop (for things like generic mouth animations)? I think that would be really powerful.

**Comment by wsankey** [comment]
Thanks for adding this to the milestones. In the short run I was thinking about adding a portrait to the themes that I could swap in and trigger with a signal.

**Comment by coppolaemilio** [comment]
I added the option to use scenes as portraits, so you can now use an AnipatedSprite or whatever node you want. I will keep improving this, but I'll close this issue for now since there is another one already https://github.com/coppolaemilio/dialogic/issues/179 :)
