### ISSUE TITLE
timelines are not exported

### ISSUE THREAD

**Issue by PapaCheese** [coppolaemilio/dialogic#283]
the tool works perfectly on the editor but when i export to windows or html i get an error that it cant find the '/dialogic' folder

the error on windows (same on html):
`[Dialogic] Error while accessing path res://dialogic/timelines - Error: 31
[Dialogic] Saved definitions not present, creating file: 0
[Dialogic] Error opening default definitions file: 7
[Dialogic] Error while opening config file res://dialogic/settings.cfg. Error: 7
SCRIPT ERROR: load_theme: Invalid call. Nonexistent function 'get_value' in base 'Nil'.
          At: res://addons/dialogic/Nodes/dialog_node.gdc:852
[Dialogic] Error while accessing path res://dialogic/characters - Error: 31
SCRIPT ERROR: event_handler: Invalid get index 'event_id' (on base: 'Dictionary').
          At: res://addons/dialogic/Nodes/dialog_node.gdc:451`

**To Reproduce**
export any working dialogic project (did not try my self on other projects)

**Expected behavior**

**Screenshots**
run in the editor
![Screenshot (36)](https://user-images.githubusercontent.com/55656526/117019959-9cf67400-acfe-11eb-9fac-7e661ebf460e.png)

at export to pc or html
![Screenshot (35)](https://user-images.githubusercontent.com/55656526/117019967-9ec03780-acfe-11eb-8f3f-3191362e532c.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version:  3.3
 - Dialogic Version: just pulled latest, but also with 1.0 release

id appreciate any quick fix for this

**Comment by coppolaemilio** [comment]
Have you tried this stated on the Readme.md?
https://github.com/coppolaemilio/dialogic#-preparing-the-export

>### 📦 Preparing the export
>When you export a project using Dialogic, you need to add `*.json, *.cfg` on the Resources tab `Filters to export...` input field ([see image](https://coppolaemilio.com/images/dialogic/exporting-2.png?v2)). This allows Godot to pack the files from the `/dialogic` folder.

**Comment by PapaCheese** [comment]
thanks for the quick response!
my bad for missing that, it totally worked haha 
thanks a lot!

**Comment by coppolaemilio** [comment]
haha no worries! I hope we can make it so that you don't have to do that manually in the future :) closing this now!
