### ISSUE TITLE
Allow for drag-and-drop new events to timeline

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#29]

**Comment by ellogwen** [comment]
@coppolaemilio 
Hi, I was bored and tried to implement this for you. Interested? I can do a PR after I cleaned up the little janky edge cases

https://streamable.com/8ikupt

**Comment by ellogwen** [comment]
> This looks amazing! yeah, feel free to send the PR because I would love to see it in action 🤩
> Just to make sure, a single click should still create an event (for accessibility reasons) and drag should let you drop it wherever you want.

Sure, buttons still work as bevore. I am nearly done, just fixing some issue with placing in indented block, just be done soon.
expect PR this evening (for me)
