### ISSUE TITLE
Add dragging support for multiple events

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#293]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to move more then one event.

**Describe the solution you'd like**
When dragging it should drag all selected events.

**Describe alternatives you've considered**
You can leave it like it is because CRTL+X and CRTL+V already allow for very easy.

**Comment by thebardsrc** [comment]
I'd have to double check before closing this one, but I believe this is working in 2.0 visual editor?

**Comment by Jowan-Spooner** [comment]
Don't think so.
