### ISSUE TITLE
Add face atlas for keeping filesizes small

### ISSUE THREAD

**Issue by jay11800** [coppolaemilio/dialogic#294]
I know I've seen a few games use a full character portrait as the base, and if nothing changes with the base they simply add the face as a small addition instead of replacing the full sprite.

Would this be a possibility to help cut down on file sizes, and possibly efficiency in whatever small way it may?

**Comment by coppolaemilio** [comment]
I would love to include some features like this, but I find it extremely hard to conceptualize in an intuitive manner.

**Comment by thebardsrc** [comment]
implemented by #1162! thanks @Jowan-Spooner!
