### ISSUE TITLE
Export to .EXE does not funtion

### ISSUE THREAD

**Issue by alexlealch** [coppolaemilio/dialogic#299]
## The problem:
Export to .EXE from Godot export, the dialogues doesn't run.

**Comment by coppolaemilio** [comment]
Have you tried this stated on the Readme.md?
https://github.com/coppolaemilio/dialogic#-preparing-the-export

>### 📦 Preparing the export
>When you export a project using Dialogic, you need to add `*.json, *.cfg` on the Resources tab `Filters to export...` input field ([see image](https://coppolaemilio.com/images/dialogic/exporting-2.png?v2)). This allows Godot to pack the files from the `/dialogic` folder.
