### ISSUE TITLE
Set Glossary improvements

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#300]
- [x] If no glossary is selected, don't show the folding icon
- [x] When a glossary is selected automatically unfold and show the icon
- [x] Remove the word "New" from each label.

**Comment by Jowan-Spooner** [comment]
I will try to work on this.

**Comment by Jowan-Spooner** [comment]
Hey emilio I'm not quite sure but I think the second one was also fixed with the #317.
Maybe you can try it and update this?

**Comment by coppolaemilio** [comment]
True! sorry I forgot to close 🙈
