### ISSUE TITLE
Able to create multiple/overlapping dialogues 

### ISSUE THREAD

**Issue by chunkymilkyo** [coppolaemilio/dialogic#302]
## Able to create multiple/overlapping dialogues 

**Describe the bug**
When using Area2d using this code [https://pastebin.com/gpG80pzq](url). You'll be able to create an infinite amount of dialogue options. 

**To Reproduce**
1. Create Area2d
2. Use this code: https://pastebin.com/gpG80pzq
3. Use key on Area2d 
4. Spam it and infinite dialogue boxes

**Expected behavior**
Only one dialogue should appear 

**Screenshots**

https://user-images.githubusercontent.com/84057424/117913188-eb7fb180-b2ae-11eb-9542-d2134152c46e.mp4

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3
 - Dialogic Version: 1.1

## Solutions

**Workaround**

Not known.

**Possible fixes**

**IT MAY BE HOW AREA2D WORKS, I AM NOT SURE. IF THERE IS A BETTER WAY TO CODE THIS PLEASE TELL LET ME KNOW. THIS ALSO SEEMS TO BE A SAME ISSUE WITH MOUSE CLICKS TOO [*https://pastebin.com/jhfp4CP8*](url)

**Comment by coppolaemilio** [comment]
You need to check if a dialog exists already. I'm closing the issue because this is not Dialogic related, this is how Godot works. You should try to follow other tutorials and learn how the node system works and you should be able to fix this one really easily.
