### ISSUE TITLE
[Dialogic] Saved definitions not present, creating file: 0

### ISSUE THREAD

**Issue by pranshuthegamer** [coppolaemilio/dialogic#306]
[Dialogic] Saved definitions not present, creating file: 0

i just installed this plugin and i get this error when i play a dialogue
it prints `[Dialogic] Saved definitions not present, creating file: 0
` in debug

**Expected behavior**
it should play the dialogue

**System (please complete the following information):**
 - OS: Windows
 - Godot Version:  3.3
 - Dialogic Version: e.g. 1.1

**Comment by coppolaemilio** [comment]
@pranshuthegamer can you try with the current 1.2 version from `main`?

**Comment by pranshuthegamer** [comment]
> 
> 
> @pranshuthegamer can you try with the current 1.2 version from `main`?

so you want me to download main?

**Comment by pranshuthegamer** [comment]
ok it works now
