### ISSUE TITLE
Ability to duplicate all types of resources

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#309]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to have a second version of your resource. While for some resources it is easy to recreate the same result (e.g. Definitions) for characters it can be really annoying.

**Describe the solution you'd like**
Have a duplicate option.

**Describe alternatives you've considered**
For timelines you can copy the events and paste them into an empty timeline, for definitions it's not really hard to enter the same values and for themes the option already exist.

**Additional context**
I just think it makes sense to have the option and wanted to add this as a reminder.

**Comment by coppolaemilio** [comment]
Using native resources, so this is as easy as copy + paste now
