### ISSUE TITLE
Add features to help with RTL languages

### ISSUE THREAD

**Issue by hohfchns** [coppolaemilio/dialogic#313]
**Is your feature request related to a problem? Please describe.**
I want to use Dialogic with an RTL language (Hebrew) and it is usable, but you have to type all the dialog in reverse in order to get coherent text, which is relatively fine, but some features like text speed just don't work well with it (text appears from last to first characters) 

**Describe the solution you'd like**
Attempt to make certain features like text speed RTL language friendly. Example is making the text appear in reverse order when using text speed.
An option to automatically reverse the text so that it will appear and be typed coherently

**Describe alternatives you've considered**
Typing the text in an external way, reversing it and pasting into Dialogic.
Using a text speed of 1 which makes text appear instantly

**Comment by coppolaemilio** [comment]
I'll see what things I can add to improve this 👍🏻

**Comment by hohfchns** [comment]
After using it for my actual project I also noticed that while you can align the text to the right side you cannot align the speaker's name to the right side

**Comment by coppolaemilio** [comment]
Unfortunately Godot 3.x doesn't support RTL languages, so I can't do much more at the moment. You can set the dialog speed to 0 (so you won't see the animation letter by letter) and then align the name/text to right. I will revisit this when Dialogic comes to Godot 4 and I can implement better support for RTL. Sorry but if you think there is anything else I could implement I can give it a try :)

**Comment by hohfchns** [comment]
Okay, that's perfectly understandable. Thanks for all the help so far and hopefully in the future!
