### ISSUE TITLE
Add grayed-out choices

### ISSUE THREAD

**Issue by craigostrin** [coppolaemilio/dialogic#316]
**Is your feature request related to a problem? Please describe.**
I'd love to use Dialogic for a CRPG-style game with many dialog choices, some based on the player-character's skills, but it's not really designed for that. (If that's intentional, it's fine; I'll look elsewhere for a solution.)

**Describe the solution you'd like**
I'd like a setting that lets me display dialog choices with unmet conditions, but grayed out and unselectable. Currently, if the condition is unmet, Dialogic will simply not show that choice to the player.
[edit: Moved second request (choices inside dialog box) to a separate request]

**Describe alternatives you've considered**
I suppose I could have an If Condition that shows a Text Event saying you don't have the necessary skills to do something, but that's kinda terrible and doesn't scale well at all.

**Additional context**
Here's an example from Pillars of Eternity: [https://forums.obsidian.net/topic/66562-flavor-vs-actual-responses/](url)

![](http://abload.de/img/poedialoguewindowklym9.png)

**Comment by Jowan-Spooner** [comment]
Maybe it would be good to split this into to requests, as I can easyily see the first one being added, but the second one looks a lot more complex. What do you think?

**Comment by craigostrin** [comment]
Yeah, that makes sense. I'm new-ish to actually posting/commenting on GitHub. Should I just delete this thread and post two new ones?

**Comment by Jowan-Spooner** [comment]
@craigostrin Yeah either two new ones or edit this one and add one new one.

**Comment by Alexey-Ost** [comment]
Yes! Choices inside dialog (and highlighting by condition) it's more native for many old-style game.

**Comment by Jowan-Spooner** [comment]
Would it be best to have this greying out as a global option or a setting per choice?

**Comment by coppolaemilio** [comment]
Per choice, since you might want to hide some options and let the user know that others could be available if they met the requirements

**Comment by craigostrin** [comment]
A global setting would be good enough for my personal use cases, but I think the ideal solution is a setting per choice.

I could see a situation where you'd want to hide a choice so as not to spoil something in the story, but visibly gray-out other choices simply because the player doesn't have the requisite skill.

Also, I'm not sure if it was clear in the original request, but it'd be great to have the option of displaying alt-text for a grayed-out choice. Like in the Pillars of Eternity example, where you can see what skill you need, but you can't see what the dialogue would've said. (Some games just show the unselectable line anyway though, like Mass Effect or The Outer Worlds, pictured below.)

![image](https://user-images.githubusercontent.com/40326682/120845042-1b744a80-c525-11eb-88a9-421e82880586.png)

**Comment by coppolaemilio** [comment]
I didn't consider the alt-text, but it should be included 100% 👍🏻

**Comment by Jowan-Spooner** [comment]
In 2.0 you can set choices to be disabled if their condition is false. 
There is currently no way of specifying an alternative text to say tho.
I will close this and create a new issue for that.
