### ISSUE TITLE
Plugin doesn't seem to be listed?

### ISSUE THREAD

**Issue by electricwig** [coppolaemilio/dialogic#32]
Please excuse me if I am making a really basic beginner error, but I am unable to get Dialogic to show up as a plugin in Godot! I have followed the documentation -- i.e. opening a new project, then downloading the zip, unzipping it and copying the 'addons' folder over to my empty Godot project, then checking in Project Settings>Plugins -- but Dialogic isn't listed there as a plugin to enable? 

I have tried both the very latest build (0.8) and also v0.7 and it's not showing up in either.

I'm using Godot 3.2.3 on a Mac (Catalina 10.15.6).

**Comment by electricwig** [comment]
Ah .. I seem to have it working now! I don't know if I was doing something incorrectly, but by creating my own 'addons' folder in my project rather than dragging in the existing one, it seems to be showing up as a plugin that I can enable now. Sorry for cluttering up your GitHub issues with such a basic thing - I was just excited to dive in with Dialogic because it sounds perfect for my project! :)

**Comment by coppolaemilio** [comment]
no worries! glad you were able to resolve it. I'll try to reproduce it and see if I can update the readme. Once Dialogic gets to the Godot AssetLib it will probably be easier to install
