### ISSUE TITLE
Simple one-line dialog without creating a timeline

### ISSUE THREAD

**Issue by HarleyDavidson86** [coppolaemilio/dialogic#322]
I'm developing a point&click adventure. Each item has standard-options like "look at", "talk to" and "use".
Now I'd have to create three timelines for each option. "look at" is only a one-liner in most cases.
It would be really cool if there's an option to start a simple one-liner dialog.

Here's a small example:
Player clicks on item "chair" and select option "look at".
For now, I've created a timeline with one text-event which says "Hey this is a nice chair".

```
var dialog = Dialogic.start_from_save("chair_talk")
add_child(dialog)
(...)
```

A possible solution would be

```
# Dialogic.start_from_save("<Name of character>", "<String>")
var dialog = Dialogic.start_from_save("Player", "Hey this is a nice chair")
add_child(dialog)
(...)
```
Or is there another way to create a small dialog without creating a whole timeline?

**Comment by Jowan-Spooner** [comment]
You can create events in code. It's a bit hacky but it works: 
https://github.com/coppolaemilio/dialogic#-can-i-create-a-dialog-using-gdscript

**Comment by HarleyDavidson86** [comment]
Ok, I can wrap this in a method.
Maybe this would be a feature for the future.

**Comment by HarleyDavidson86** [comment]
I tried to create a dialog with this method, but nothing shows up:
My code:

```
	var gdscript_dialog = Dialogic.start('', true, "res://addons/dialogic/Dialog.tscn", true)
	gdscript_dialog.dialog_script = {
		"events":[
			{ 'event_id':'dialogic_001', "character": "character-1622178230.json", "portrait":"", "text": "This dialog was created using GDScript!"}
		]
	}
	add_child(gdscript_dialog)
```


```
[Dialogic] Saved definitions not present, creating file: 0
[D] Current Event: {character:character-1622178230.json, event_id:dialogic_001, portrait:, text:This dialog was created using GDScript!}
[D] Other event. {character:character-1622178230.json, event_id:dialogic_001, portrait:, text:This dialog was created using GDScript!}
```

Have I forgotten seomthing?
