### ISSUE TITLE
Play control for Audio Event 

### ISSUE THREAD

**Issue by Alexey-Ost** [coppolaemilio/dialogic#324]
Need to play once (parallel to text) the sound of the character's voice but the audio event is currently looped and can only be 'stopped' by an empty sound. And after the text event.

The problem will be solved by adding playback control for Audio Event; choosing to loop or play N times (or N seconds). And stopping by condition (like event activity or selection).

**Comment by coppolaemilio** [comment]
This is based on how you import the audio files in Godot, not on the plugin. I'm not sure if there is a way to prevent sounds from looping from code if they were imported with the loop tag. So I'll check it here because many new comers don't know this about Godot.

**Comment by Jowan-Spooner** [comment]
I think this should go into the documentation and then this should be closed.

**Comment by Jowan-Spooner** [comment]
I have added a note about how looping works to the documentation. Should we close this @coppolaemilio ?

**Comment by coppolaemilio** [comment]
yes 👍🏻 hopefully we can bypass the default editor stuff in the future, but I'll close for now since that is how Godot works unfortunately. Thanks!
