### ISSUE TITLE
Node Graph system instead of Top-Down List

### ISSUE THREAD

**Issue by ka23ppa3** [coppolaemilio/dialogic#326]
**Is your feature request related to a problem? Please describe.**
Problem in list-like systems is that they are going to be more complex to understand with scaling.

**Describe the solution you'd like**
Node-Graph systems is known to be always better than lists. You have more virtual space, you clearly see connections between nodes and can easily understand and extend logic.

**Describe alternatives you've considered**
https://assetstorev1-prd-cdn.unity3d.com/package-screenshot/70dc982b-4e72-4baf-94d6-dfa896eb0576.webp

**Additional context**
It will be good if you can make it as extension for Godot visual scripting.

**Comment by coppolaemilio** [comment]
Thanks for reaching out, unfortunately I already stated several times that I won't be using graph node.
On the readme:
https://github.com/coppolaemilio/dialogic#-why-are-you-not-using-graph-nodes

> 
> 🔷 Why are you not using graph nodes?
> Because of how the graph nodes are, the screen gets full of UI elements and it gets harder to follow. If you want to use graph based editors you can try Levraut's LE Dialogue Editor or EXP Godot Dialog System.
