### ISSUE TITLE
Can't add a new character

### ISSUE THREAD

**Issue by lemilonkh** [coppolaemilio/dialogic#33]
Whenever I try to add a character to my Dialogic project, I get the following error message and nothing happens:

`ERROR: File must be opened before use.
   At: core/bind/core_bind.cpp:2216`

Do I need to add some specific file to my project in order to make it work? (Other than the plugins subdirectory)

I'm on Windows, Godot 3.2.3 stable, Dialogic 0.8.
Haven't tried it yet on Linux but if you think that might help I can give it a shot.

Let me know if you need an example project to reproduce this.

**Comment by coppolaemilio** [comment]
Can you try with the latest version from here? I fixed a couple of bugs related to character creation in new projects

**Comment by DeerTears** [comment]
I also got this bug, except it just threw `File must be opened before use.` as an error in the output. I'll also try the current code in the repo and see if that will work.

Windows 64, Godot 3.2.2 stable, Dialogic 0.8.

**Comment by lemilonkh** [comment]
I just tried it with the newest version on the master branch.
Unfortunately there seems to be a syntax error in `dialogic.gd` (this appears as a popup when I open the project with the new version):

```
Unable to load addon script from path: 'res://addons/dialogic/dialogic.gd'
There seems to be an error in the code, please check the syntax.
```

I also get the following error messages in the Godot output, not sure if that's strictly related.
The file in the error message does exist though so maybe it contains some invalid XML?
 ```
No loader found for resource: res://addons/dialogic/Images/plugin-editor-icon.svg.
 res://addons/dialogic/dialogic.gd:35 - Parse Error: Can't preload resource at path: res://addons/dialogic/Images/plugin-editor-icon.svg
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
```

**Comment by lemilonkh** [comment]
Ok I created an empty project and added the new version of the addon there and it works as intended :)
It seems the 0.8 version might have left some files/ configuration in the project that broke the script?

Anyways, it would still be nice to be able to drop the addon into any existing project I suppose.

**Comment by coppolaemilio** [comment]
Glad it works!
Yeah, I'll try to resolve all the errors that can happen when you have an existing project or you are updating from a previous version. Closing this!

**Comment by mindtonix** [comment]
I also get this error when i try to create a new character. Just downloaded latest release v0.8 and added it to a tiny project i created earlier today.

![image](https://user-images.githubusercontent.com/78102347/106031855-0cd9da80-60d0-11eb-87f9-dc6b53f0d3bf.png)

**Comment by mindtonix** [comment]
I found a file inside the dialogic directory named `characters`. I figured there should be a folder there instead, so i deleted the file and next time i tried adding a character, a `characters`-folder was created and it now worked. 

I did not create the `characters`-file, and i don't know how it got there. I guess maybe that's a bug, but until it's fixed, deleting the file solves the problem :+1:

**Comment by coppolaemilio** [comment]
I'll be making some changes on v0.9 all over the place, so this might break some compatibility but hopefully things like this will not happen again. Happy you were able to resolve it!
