### ISSUE TITLE
Possibility to add images into Question and answer

### ISSUE THREAD

**Issue by GribeauValmy** [coppolaemilio/dialogic#330]
**Is your feature request related to a problem? Please describe.**
I would like to try a "non verbal" game.

**Describe the solution you'd like**
I would like to be able to drag and drop game asset directly into the Text Event and other Logics like Question, Choices ect.

**Comment by coppolaemilio** [comment]
As far as I know you should be able to use images in Bbcode, but it might be a bit tedious. Take a look at the docs: https://docs.godotengine.org/en/stable/tutorials/gui/bbcode_in_richtextlabel.html

**Comment by GribeauValmy** [comment]
Ho nice, thanks for the information !
