### ISSUE TITLE
Set glossary event. Error when selecting some definitions

### ISSUE THREAD

**Issue by idontkillcoyotes** [coppolaemilio/dialogic#333]
## Unable to select definitions that do not reside in a subfolder.

**Trying to select a definition in the event "Set glossary" that does not reside in a subfolder causes an error and it does not get selected to modify.**

The error:
`core/object.cpp:1257 - Error calling method from signal 'index_pressed':`
`'VBoxContainer(EventPart_GlossaryPicker.gd)::_on_PickerMenu_selected': Method expected 2 arguments, but called with 1..`

By contrast, selecting another definition in that resides in a subfolder is working as intended.

**To Reproduce**
1. Create a new timeline
2. Create an "extra information" definition (glossary). Do not move this new definition from its default folder
3. Add the event "Set glossary" on the timeline and try to select definition
4. See error on console
5. (Optional) Create a subfolder on the "Definitions" folder.
6. (Optional) Create a new "extra information" definition and move it the new subfolder
7. (Optional) In the timeline, select the new definition from it's subfolder. (Working as intended) 

**Expected behavior**
Selecting a glossary definition should work regardless of its location on the folder tree

**Dialogic Version**
 - Version: 1.2

## Solutions

**Workaround**

A workaround could be putting all definitions into subfolders

**Possible fixes**

I think this is the line of code that might be the cause:
script file: `EventPart_GlossaryPicker.gd`
line: 10 -> 13
`# used to connect the signals`
`func _ready():`
`	picker_menu.get_popup().connect("index_pressed", self, '_on_PickerMenu_selected')`

**Comment by Jowan-Spooner** [comment]
Thanks, I will look into this. It should be added to the Version 1.2 Milestone.

**Comment by coppolaemilio** [comment]
This should be fixed now, can you confirm @idontkillcoyotes ?

**Comment by idontkillcoyotes** [comment]
Sorry, read this a bit late.

But yes it works now
