### ISSUE TITLE
New event, wait for signal

### ISSUE THREAD

**Issue by idontkillcoyotes** [coppolaemilio/dialogic#336]
## Why am I asking for this feature?
**Imagine you have a "cutscene" or a interactuable part in your game and you need to wait for it or for the player to finish it and then continue the dialog.**

I would like to be able to make a timeline wait for a variable amount of time, or better yet for a signal (probably from an autoload EventBus like node).

**Describe the solution you'd like**
A new event, that is functionaly like the wait X seconds event, but instead waits for a signal from another node (autoload for the simplest solution) to continue the timeline (hiding the dialog box could be optional)

**Describe alternatives you've considered**
One of the alternatives would be to split the timeline in two separate ones.
The problem with this is that if there are characters on the scene before the split, the next scene needs to re-enter them causing to enter animation to play again making it look very weird

**Additional stuff**
I've managed to create this event, at least in a very simple way

What I did was to add an EventPart with two variables as data:
- the name of the node emitting the signal
- the name of the signal

and then to process this event:
- to look up for the node as child of root, 
- connect to the signal in ONESHOT mode
- in the callback method, resume the timeline

**Comment by Jowan-Spooner** [comment]
Hey I really like the idea and I think something similar was requested before. 

But I would instead of a new event propose a rework of the call node function. If I understand the original implementation #130 correctly it's supposed to wait for the function it calls to finish (which could be used for something similar to what you want). As that event is already a bit messy and hard to use (relative path's are hard to get right) a rework wouldn't hurt I think.

What do you guys think?

**Comment by Jowan-Spooner** [comment]
Alternatively this would be a good use-case for a custom event.

**Comment by idontkillcoyotes** [comment]
I already made this as a custom event, it was pretty simple to implement with the way custom events are handled 👍

**Comment by IllyasOnii** [comment]
> I already made this as a custom event, it was pretty simple to implement with the way custom events are handled 👍

any chance you could share that? I'd appreciate it much thank you!

**Comment by qskousen** [comment]
One way to do this would be to have a custom signal at the "pause" part, that you can make the end of a timeline (or listen to the "end_timeline" event and check the timeline name). Then you can play your cutscene, then at the conclusion of the cutscene you can start the next part of the dialog, as a different timeline.

In short, you can split your timeline into two and trigger the cutscene at the end of the first, and trigger the second timeline at the end of your cutscene.

**Comment by Jowan-Spooner** [comment]
Hi, for anyone looking for this. In 2.0 (currently alpha) you can use the Call Node event to wait until the function you've called has finished. This might be helpful for usecases like the one you described. 

If you have a method like
```
func wait_for_signal(signal):
    yield(self, signal)
```
You have basically a wait for signal event.
