### ISSUE TITLE
First dialog can be skipped entirely

### ISSUE THREAD

**Issue by zoliostudios** [coppolaemilio/dialogic#337]
The first dialog can be skipped entirely by pressing Space without Dialogic actually finishing the dialog completely.

[https://discord.com/channels/628713677239091231/752503389241475072/849943475075940353](url)
on Emilios discord server.

![dfd](https://user-images.githubusercontent.com/74095141/120628982-a8c58980-c4a8-11eb-8e15-7c52d7fdf1b2.PNG)

**Comment by coppolaemilio** [comment]
Hopefully fixed :)
