### ISSUE TITLE
Automatic Dialog Skipping and Movement of each letter polish

### ISSUE THREAD

**Issue by rystaldev** [coppolaemilio/dialogic#338]
This feature is supposed to give a smooth gameplay feel and an easy one. 

Automatic Dialog Skipping
When the dialog is done and the player has no input, after a few more (adjustable) seconds the dialog automatically goes on to the next one. Kind of like Katana Zero's dialog system.

Movement of each letter polish
There should be a little intro to each letter to give more polish instead of just popping up. Kind of like Katana Zero

**Comment by Jowan-Spooner** [comment]
Hey, thanks for your ideas. Just for the future: it's best to create seperate issues for seperate ideas. This one contains two ideas that are not connected. It makes it harder to close these issues. Thanks!

**Comment by Jowan-Spooner** [comment]
Now for the first thing I could imagine it to be combined with the auto-advancement planned in #303. What do you think? Maybe if we have a little auto-advance box with a time we could have a checkbox for it to wait for the text to finish. Or to multiply the waiting time with the number of characters.

**Comment by zoliostudios** [comment]
Oh, alright thanks for the advice! Yes I agree with the auto-advance thing, it could be combined and would be really cool if it was.

**Comment by Jowan-Spooner** [comment]
So 2.0 has the auto-continue (with delay) option. Currently only globally but an version of the nw is planned.

Also I'm not sure letter polish you want for. You can add sound effects per letter. If you want something more specific, feel free to make a new issue.
