### ISSUE TITLE
Dialog node doesn't load text in an exported project

### ISSUE THREAD

**Issue by InitialCon** [coppolaemilio/dialogic#34]
When exporting a project that contains a dialog_node the node only displays the default text even when supplied with a timeline and only uses the default settings. The node works when loading in the editor however where it displays the correct text and uses the correct settings

Error as reported by godot debug output(image attached):
![Dialogic_issue](https://user-images.githubusercontent.com/66960524/105007169-51b2a100-5a40-11eb-9ad7-e3eacadccab3.PNG)

SCRIPT ERROR: parse_branches: Invalid get index 'events' (on base: 'Dictionary').
          At: res://addons/dialogic/Nodes/dialog_node.gdc:64
(1024, 600)
[!] settings loaded: {}
-------------
dialog_node.gd loading settings
{}
-------------
SCRIPT ERROR: load_theme: Invalid get index 'theme_font' (on base: 'Dictionary').
          At: res://addons/dialogic/Nodes/dialog_node.gdc:441
SCRIPT ERROR: load_dialog: Invalid call. Nonexistent function 'has' in base 'Nil'.
          At: res://addons/dialogic/Nodes/dialog_node.gdc:191

Screenshot from the exported project: 
![Dialogic_text](https://user-images.githubusercontent.com/66960524/105010386-524d3680-5a44-11eb-82ce-61d199249e58.PNG)

**Comment by coppolaemilio** [comment]
I think that you need to add some extra information when exporting so that it will include the *.json files. I'll try to export something myself and make a small tutorial on how to export it.

**Comment by InitialCon** [comment]
Thanks, I tried manually including the json files but that still lead to the same error being given so I think it might not be the json files that are causing the issue.

**Comment by InitialCon** [comment]
Thanks for the tip in the readme on how to fix the issue. Closing the issue.

**Comment by coppolaemilio** [comment]
Yes! Sorry I didn't tag you, I was going to check tickets again today and reply :)
