### ISSUE TITLE
When you use a variable, an error occurs

### ISSUE THREAD

**Issue by chunchuna** [coppolaemilio/dialogic#348]
## The problem

**Describe the bug**
When you use a variable, an error occurs

**To Reproduce**
1.Use the set variable

**Expected behavior**
invalid get index value on base dictionary 

screenshot:
[](url)
![bug1](https://user-images.githubusercontent.com/32768062/121288122-6e7b4280-c915-11eb-9a07-ba814d482b81.png)
![bug2](https://user-images.githubusercontent.com/32768062/121288130-70dd9c80-c915-11eb-9503-436e2d5d9427.png)

**System (please complete the following information):**
 - OS: win10
 - Godot Version: 3.2.3
 - Dialogic Version: The latest edition

## Solutions

**Workaround**

What you tried to get the feature working

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by coppolaemilio** [comment]
@chunchuna can you try again downloading the latest version from github? It should say 1.3 BETA on the title
![image](https://user-images.githubusercontent.com/2206700/135611834-bd32704e-3fe1-4d58-a72e-6e1906b9bee0.png)

**Comment by Jowan-Spooner** [comment]
Cannot reproduce. Could be a case of #388 (definition added after a save was created, then loading the game from save and the definition isn't present, so it cannot be found)
