### ISSUE TITLE
Need help with variables

### ISSUE THREAD

**Issue by jay11800** [coppolaemilio/dialogic#349]
Hi there! I've been using Dialogic for a while now and really like it, but I can't seem to figure out how the variables and definitions feature works. Currently now I'm using a variable "Chips" to sync how much currency the player has to be used in a basic dialogic shop. 
Here is the code:

```
func _ready():
	Dialogic.set_variable("Chips", 1000)
	Dialogic.save_definitions()
	currentChips = Dialogic.get_variable("Chips")
	var new_dialogue = Dialogic.start("Shop", false)
	get_tree().get_nodes_in_group("UIViewport")[0].add_child(new_dialogue)
	new_dialogue.connect("timeline_end", self, "afterDialogue")
	new_dialogue.connect("dialogic_signal", self, "DialogueSignal")
	print("Current chips are: ", currentChips)
```

When the dialogue opens, and it prints to the console, Chips is null and none of the if conditionals that use chips goes off. Am I doing something wrong? It would help to get code examples in the usage page to get a basic idea of context if I am doing this the wrong way please.

**Comment by jay11800** [comment]
Additionally, when I choose a choice option where Chips is greater than x, all the other choices go off at the same time, instead of just the one choice I picked.
Like if I choose "Buy x for 100 chips", it will also set off "buy for 50" and "buy for 25" because chips is higher than those numbers, but yet I did not choose that option

**Comment by jay11800** [comment]
also, is it possible and if so how to reference a variable in the dialogic timeline? For example, if I paid 20 coins to spin a random wheel, and the result of that spin is stored as "var", how would I be able to say in the dialogic timeline: 
"Congratulations! You've won: " %var

**Comment by coppolaemilio** [comment]
Are you creating the variables (definitions) using the dialogic editor?

You might be also resetting the variable values (check on the dialog node)

> also, is it possible and if so how to reference a variable in the dialogic timeline? For example, if I paid 20 coins to spin a random wheel, and the result of that spin is stored as "var", how would I be able to say in the dialogic timeline:
"Congratulations! You've won: " %var

you can print variables in the text using brackets: `Congratulations! You've won: [var] coins`

**Comment by jay11800** [comment]
> Are you creating the variables (definitions) using the dialogic editor?
> 
> You might be also resetting the variable values (check on the dialog node)
> 
> > also, is it possible and if so how to reference a variable in the dialogic timeline? For example, if I paid 20 coins to spin a random wheel, and the result of that spin is stored as "var", how would I be able to say in the dialogic timeline:
> > "Congratulations! You've won: " %var
> 
> you can print variables in the text using brackets: `Congratulations! You've won: [var] coins`

Thanks for the answer, I set up the definition in dialogic's UI, and assigned it to 1000 to debug it, I think I noticed it took a restart to fix, but I'll have to double check again after work. 

Essentially my goal is to take my current amount of coins, and when the shop dialogue opens, update the dialogic's coin variable, initiate dialogue and changing values with your system, plus using signals to actually buy things, then when the dialogue is over, take dialogic's variable value and overwrite the save data with this new value (of course using float() to convert). I believe this is all possible, I just wanted to confirm I had the logic right and wasn't misusing functions.

Also I appreciate the comment on the printing, that's super helpful!

**Comment by Jowan-Spooner** [comment]
I think this can be closed. If you need any help, consider joining emilios discord server!
