### ISSUE TITLE
Create a basic dialog with GDscript doesn't work

### ISSUE THREAD

**Issue by havana24** [coppolaemilio/dialogic#350]
## The problem

**Describe the bug**
I copy paste the code showed here https://github.com/coppolaemilio/dialogic#-can-i-create-a-dialog-using-gdscript in order to create a basic dialog directly from the script, but it doesn't work. How can I get a basic dialog show via script?

**To Reproduce**
1. copy paste the code showed here https://github.com/coppolaemilio/dialogic#-can-i-create-a-dialog-using-gdscript
2. the code is:
 `func _ready():
	var gdscript_dialog = Dialogic.start('')
	gdscript_dialog.dialog_script = {
		"events":[
			{ 'event_id':'dialogic_001', "character": "", "portrait":"", "text": "This dialog was created using GDScript!"}
		]
	}
	add_child(gdscript_dialog)`
3. Tun the game
4. Godot show this error "Invalid set index 'dialog_script' (on base: 'CanvasLayer (canvas_dialog_node.gd)') with value of type 'Dictionary'."

**Expected behavior**
A basic dialog should appear

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.1
 - Dialogic Version: 1.2 (beta)

**Comment by Jowan-Spooner** [comment]
Yup you are right. We need to ask @coppolaemilio why the Dialogic.start() function should ever return the canvas layer node? What would that be usefull for? And woulnd't that also make it impossible to connect to the signals of the dialog node?
It used to work before the whole canvas layer fix.

**Comment by coppolaemilio** [comment]
I will need to update the documentation on this one

**Comment by havana24** [comment]
So, at the moment, there is no way to create a dialog via GDscript?
I just need to being able to set a text message using a variable inside a script... in this way I can have a multilanguage setup.
Or maybe there is a better way to achieve that?
Thanks in advance,
Alessandro

**Comment by coppolaemilio** [comment]
on the latest version of the repo you can do this:
```gdscript
func _ready():
	var gdscript_dialog = Dialogic.start('')
	gdscript_dialog.set_dialog_script( {
		"events":[
			{ 'event_id':'dialogic_001', "character": "", "portrait":"", "text": "This dialog was created using GDScript!"}
		]
	})
	add_child(gdscript_dialog)
```

Hope to improve it later on :)

**Comment by coppolaemilio** [comment]
tell me if it works for you!~

**Comment by havana24** [comment]
It works, thanks! :)
Would be amazing to have a bit of documentation of this in the future, thanks for the great plugin!

**Comment by coppolaemilio** [comment]
Thanks!
yeah, I hope to update and improve the documentation soon
