### ISSUE TITLE
get_value' in base 'Nil

### ISSUE THREAD

**Issue by jayjamesdr** [coppolaemilio/dialogic#351]
ERROR: get_language_code: Invalid locale 'C'.
   At: core/translation.cpp:958.
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:982.
WARNING: _update_root_rect: Font oversampling does not work in "Viewport" stretch mode, only "2D". To remove this warning, disable Rendering > Quality > Dynamic Fonts > Use Oversampling in the Project Settings.
   At: scene/main/scene_tree.cpp:1244.
[Dialogic] Error while accessing path res://dialogic/timelines - Error: 31
[Dialogic] Saved definitions not present, creating file: 0
[Dialogic] Error opening default definitions file: 7
[Dialogic] Error while opening config file res://dialogic/settings.cfg. Error: 7
SCRIPT ERROR: load_theme: Invalid call. Nonexistent function 'get_value' in base 'Nil'.
   At: res://addons/dialogic/Nodes/dialog_node.gdc:808.
[Dialogic] Error while accessing path res://dialogic/characters - Error: 31
SCRIPT ERROR: parse_alignment: Invalid call. Nonexistent function 'get_value' in base 'Nil'.
   At: res://addons/dialogic/Nodes/dialog_node.gdc:193.
SCRIPT ERROR: update_text: Invalid type in function 'parse_definitions' in base 'Control (dialog_node.gd)'. Cannot convert argument 1 from Nil to String.
   At: res://addons/dialogic/Nodes/dialog_node.gdc:341.

**Comment by coppolaemilio** [comment]
please follow the issue template or provide the required information:
What version of Dialogic are you using? What version of Godot? What OS?

**Comment by jayjamesdr** [comment]
godot 3.3 
Dialogic 1.1
arch linux

ı test game engine inside and it's works but ı try export game but not work

**Comment by coppolaemilio** [comment]
Have you tried what it is described in the readme?
https://github.com/coppolaemilio/dialogic#-preparing-the-export

> 📦 Preparing the export
> 
> When you export a project using Dialogic, you need to add *.json, *.cfg on the Resources tab Filters to export... input field (see image). This allows Godot to pack the files from the /dialogic folder.

**Comment by jayjamesdr** [comment]
okay my bad 
thanks

**Comment by coppolaemilio** [comment]
did it work? 👀

**Comment by jayjamesdr** [comment]
yes
