### ISSUE TITLE
Definitions RMB bug in 1.3

### ISSUE THREAD

**Issue by 77HriP77** [coppolaemilio/dialogic#356]
## The problem

**Describe the bug**

I downloaded the post-release version, marked already 1.3. And when I tried to click on Difinitions with the right mouse button, I got an error. Also in this version drag and drop timelines and other does not work.

**Screenshots**
https://img-host.ru/58F8.png

## Solutions

I downloaded release 1.2, everything works here. I figured I'd better let you know about this bug. If he is.

p.s. Thanks a lot for the work done with the folders!

**Comment by coppolaemilio** [comment]
Thanks for the report!

**Comment by coppolaemilio** [comment]
I reverted the change that caused this, hopefully it will be fixed the next time 😅
