### ISSUE TITLE
Can't select/edit characters or definitions in current build

### ISSUE THREAD

**Issue by Th-eo** [coppolaemilio/dialogic#357]
## The problem

**Describe the bug**
![imagen](https://user-images.githubusercontent.com/42318572/122234629-4fecec80-cebd-11eb-9c29-5244ba2bcb4d.png)

**To Reproduce**
1. Go to the Dialogic tab
2. Click on New Character/Definition
3. Notice the tool is unable to tweak any values in the Character or Definition (you can edit the JSON directly though)
4. (No error/crash, just not working properly before last update -- Themes and Timelines still work)

**Expected behavior**
Being allowed to do the proper edits.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/42318572/122235108-b83bce00-cebd-11eb-93b2-df9bbc14f18b.png)

**System (please complete the following information):**
Works in 1.2, stopped working in last commit https://github.com/coppolaemilio/dialogic/commit/9e01f073d84d4b8d42930a1dad24d32d91d0d261

Any idea to fix the issue or a link to the line of code that might be the cause for this problem:
This commit seems to have broken it  https://github.com/coppolaemilio/dialogic/commit/9e01f073d84d4b8d42930a1dad24d32d91d0d261

**Comment by coppolaemilio** [comment]
@Th-eo I pushed a possible fix right now, can you tell me if it works now?

**Comment by Th-eo** [comment]
> 
> 
> @Th-eo I pushed a possible fix right now, can you tell me if it works now?

It does!
