### ISSUE TITLE
The problem with the color of Names in the text

### ISSUE THREAD

**Issue by 77HriP77** [coppolaemilio/dialogic#359]
## The problem

**Describe the bug**
Depending on the order in which the names are written, they behave incorrectly. Since I am extending this via google translator, it is better to show it so that you understand.
Monika1 - Character Name
Monika2 - Display Name
Monika3 - Nickname
The player too.

<img src="https://img-host.ru/63Rb.jpg">

The test lines look like this.

<img src="https://img-host.ru/CMJF.jpg">

Here's what we get in the game:

<img src="https://img-host.ru/uXmg.png">
<img src="https://img-host.ru/mqv8.png">

The following order also behaves strangely:
<img src="https://img-host.ru/6d1T.png">

As I understand it, DisplayName was not intended to change the color in the text at all.

I also wanted to note that bbcode does not work in the glossary. Perhaps this was intended, but it would be convenient if it was possible.
<img src="https://img-host.ru/Vyty.jpg">
<img src="https://img-host.ru/EjrB.jpg">

Version 1.2 release

**Comment by coppolaemilio** [comment]
Thanks for the testing and such a good ticket!
The glossary part should be a separated issue, but I believe it is an easy fix. Regarding the names... I'm thinking about improving the character editor since it is too basic now, but I'll see how I can improve the name replacements to make it consistent. I don't know how many people will encounter this issue since it seems a bit of an edge case, but it should help with many unexpected issues along the way. Thanks again!

**Comment by coppolaemilio** [comment]
I enabled the bbcode to the glossary entries, the other part of the ticket about the names still needs to be fixed

**Comment by Jowan-Spooner** [comment]
I want to work on this now. 
As far as I can see display names are just ignored for coloring. 
I would think though that if a display name is set, then the original name should probably not even be colored, right?

**Comment by coppolaemilio** [comment]
I think they should be colored as well? but the purposes for which I made the display name feature maybe it's not the best implementation of it at the moment. Maybe enabling that on the character options or just general options can be a solution, or just think what the best way to handle names, nicknames, and display names is and try to design it form the ground up

Sorry to not answer anything and propose more stuff 🤣
