### ISSUE TITLE
Timeline paused after emitting a signal

### ISSUE THREAD

**Issue by 16bit-belane** [coppolaemilio/dialogic#36]
Hi,

when using a "emit signal" the timeline paused processing the next event.
Maybe an go_to_next_event() in line 311 from dialog_node.gd is missing.

Line 311 in dialog_node.gd
`		{'emit_signal'}:
			print('[!] Emitting signal: ', event['emit_signal'])
			emit_signal("dialogic_signal", event['emit_signal'])
			go_to_next_event()
`

btw, dialogic is really great. :)

**Comment by coppolaemilio** [comment]
Hello there! thanks for the report :)
This should be fixed now with this commit:
https://github.com/coppolaemilio/dialogic/commit/f6a02d71ebb342e5ceadeb5222a4827a69388bc8

thanks again 👍🏻
