### ISSUE TITLE
Dialogic indicator [nw] not working with experimental translations

### ISSUE THREAD

**Issue by TheDuckCow** [coppolaemilio/dialogic#361]
## The problem

When using the experimental translation optional, some dialogic indicators don't work. Most specifically I notice that the [nw] key no longer works. Translations are otherwise picked up as expected, and of course BBcode passed through renders as expected, it's just the dialogic indicators that don't. Also worth calling out that the `speed` indicator DOES work as expected.

**To Reproduce**
1. Create a timeline
2. Assign the value DEMO_TEXT
3. Setup a translation csv like below, import into godot as a translation file, and add the local to the project translation tab

| key       | en              |
|-----------|-----------------|
| DEMO_TEXT | [speed=20]Don't wait![nw] |

Raw csv:
```
key,en
DEMO_TEXT,[speed=20]Don't wait![nw]
```

4. Run a scene with a dialogic set to this timeline.

**Expected behavior**
I expect that by including [nw], the conversation would auto progress (and close the dialogue) after 2 seconds. Instead the line waits for my manual input. Oddly though, it does seem to be parsed - because the [nw] isn't showing up as raw text or anything in the displayed (translated) chat. Furthermore, the `[speed]` indicator DOES work.

**System (please complete the following information):**
 - OS: Mac
 - Godot Version: 3.3.2-stable
 - Dialogic Version: v1.2

## Solutions

**Workaround**

Not sure yet. I imagine at worse I could add a signal emission after the line I want to not wait, and then have other code that calls the private `_load_next_event()` method on the node(not tested, but I assume it would work).

**Possible fixes**

My initial guess would have been to run the text parsing for keywords like [nw] strictly after translation has converted the text, but it seems some of that has already occurred since `[nw]` itself doesn't appear in the resulting text.

I also note that [this condition](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Nodes/dialog_node.gd#L344) is NOT met, because the "next" indicator indeed still shows in the editor. My guess is that when translations are on, it should attempt to pull the string value once and then do further references on that downstream. [This line](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Nodes/dialog_node.gd#L405) is also probably where a call could be made to the translate server, although again probably better done once upstream rather than doing another translation call at that point.

**Comment by TheDuckCow** [comment]
Fast follow, did just confirm locally that making these two tweaks works, but I still feel that saving the translated text to the key would be better:

Line 339

```
	if current_event.has('text'):
		if '[nw]' in current_event['text'] or '[nw]' in tr(current_event['text']):
			$TextBubble/NextIndicatorContainer/NextIndicator.visible = false

```

Line 397

```
		if '[nw]' in current_event['text'] or '[nw]' in tr(current_event['text']):
			yield(get_tree().create_timer(2), "timeout")
```

**Comment by coppolaemilio** [comment]
Thanks for the detailed report, I'll see if I can fix it tonight!

**Comment by coppolaemilio** [comment]
Can you try with the latest version? I made some changes that *might* make it work now

**Comment by TheDuckCow** [comment]
Hey thanks for the update. Looked at [this commit](https://github.com/coppolaemilio/dialogic/commit/b61c92ebf3b6f26c1e8df8ac8c15fbeacc81a1ac), super looking forward to using the variable wait-time feature.

That being said, I did just copy down the folder from the head branch and ran into this error on starting godot. Not sure if it was an issue on my side, but it DID work after restarting and manually re-enabling godot:
```
Unable to load addon script from path: 'res://addons/dialogic/dialogic.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dialogic/plugin.cfg' to prevent further errors.
```

With more specific details from the console:
```
 No loader found for resource: res://addons/dialogic/Images/Plugin/plugin-editor-icon-light-theme.svg.
 res://addons/dialogic/dialogic.gd:58 - Parse Error: Can't preload resource at path: res://addons/dialogic/Images/Plugin/plugin-editor-icon-light-theme.svg
 modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR
 No loader found for resource: res://addons/dialogic/Images/Plugin/plugin-editor-icon-light-theme.svg.
 res://addons/dialogic/dialogic.gd:58 - Parse Error: Can't preload resource at path: res://addons/dialogic/Images/Plugin/plugin-editor-icon-light-theme.svg
 modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR
```

Again, went away after a restart, but figured I'd share this anyways. This was after removing and copying over the new dialogic addons folder en full from master.

Now, in terms of the change taking place, it didn't seem to right away. While my translations are working, and the [nw] flag appears to be parsed out, it's still stuck waiting for user input. Again, I think the key is to call the translation earlier and reference that at the lines of code where you create the timer. Because right now, it's doing the actual logic against the translation *key*, rather than the resultant translated text. Hope that helps!

**Comment by coppolaemilio** [comment]
Since the translation was experimental and a new system will be implemented I'm closing this one
