### ISSUE TITLE
Scrolling dialog text with keys

### ISSUE THREAD

**Issue by moonwolf-github** [coppolaemilio/dialogic#363]
If the text does not fit into the box, a scroll bar appears so you can scroll the text with the mouse. Can the keys be used for this purpose?

**Comment by Jowan-Spooner** [comment]
Maybe if we focus the text element. Would need to try it out. Good idea though

**Comment by coppolaemilio** [comment]
I think we should make a setting to select if you want the game input to be mouse, keyboard or both. That way we can handle all this kind of interactions depending on each project. This would fix many other issues of people having issues with not wanting one or the other as input methods.
