### ISSUE TITLE
Allow to pick typing audio files per character on the character editor

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#364]

**Comment by GamerJuice377** [comment]
this would be a very good addition

**Comment by coppolaemilio** [comment]
@timkrief yes, not sure how viable it is to implement now or what, but many people requested this

**Comment by timkrief** [comment]
It's more accessible now than it was before since I centralized the audio stuff in the dialog_node.gd where we have access to characters. Plus we could reuse the audio_picker from the theme editor.

**Comment by Jowan-Spooner** [comment]
This is kinda possible now in 2.0 with the TypingSound moods, although smaller improvements should be made to the system.
