### ISSUE TITLE
Cannot perform set_variable()

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [coppolaemilio/dialogic#367]
## The problem

**Describe the bug**
Cannot perform Dialogic.set_variable()

**To Reproduce**
1. Go to the Dialogic tab
2. Click on "New Value"
3. Create a new value (in this case "variable1" with the value of 1)
4. Create a new GDscipt script
5. Insert the text "Dialogic.set_variable('variable1', 2)" inside any function
6. For debugging purposes print the value out to the console 
        "var MyVar = Dialogic.get_variable('variable1')"
        "print(MyVar)"
7. Output value is 1 despite performing step 5. get_variable() works but set_variable() doesn't
7.5 The same bug occurs when adding the variable to a timeline with [variable1]
**Expected behavior**
The value "variable1" should change from 1 to 2

**Screenshots**
Not necessary

**System (please complete the following information):**
 - OS: Ubuntu 18.05.4 LTS kernel version 4.15.0-144-generic 
 - Godot Version: 3.3.2 Stable official
 - Dialogic Version: 1.2

Have I made a mistake in the code or is this a bug?

**Comment by AwesomeUnicorn3** [comment]
It does not seem to save the variable value after the timeline is complete.  I figured out a workaround where I emit a signal during the timeline that is connected to a method with a match statement, and I used the argument as the match that would run code to update the variable value.


![Screenshot from 2021-06-22 00-37-40](https://user-images.githubusercontent.com/63011553/122864227-3bac5380-d2f2-11eb-92aa-c592fb24f573.png)
![Screenshot from 2021-06-22 00-37-19](https://user-images.githubusercontent.com/63011553/122864251-449d2500-d2f2-11eb-8e6a-8ddd6c2a84f6.png)

**Comment by Jowan-Spooner** [comment]
Make sure you set the reset_saves parameter to false if you want to keep your changes. It's an option of the Dialogic.start() function and true by default, which means all values will be reset to their defaults.

Otherwise I can look into this later.

**Comment by coppolaemilio** [comment]
What @Jowan-Spooner said. It is probably that you are resetting the variables when the dialog shows up. This was added so it is easier to debug things (otherwise variables would be saved after the game closes and continue with the same values in future runs) but hopefully we can do a different save/load system for 1.3 because many people find this confusing.

I also see that your dialogic UI is super big compared to the rest of your editor. Can you share what resolution are you using and what rendering scale for Godot?

**Comment by Chevifier** [comment]
> 
> 
> Make sure you set the reset_saves parameter to false if you want to keep your changes. It's an option of the Dialogic.start() function and true by default, which means all values will be reset to their defaults.
> 
> Otherwise I can look into this later.

This fixed my issue that I had the get_variable was working fine but running the dialog, the values were always set to its default value.
