### ISSUE TITLE
Allow user to use "Call Node" to run Autoload scripts

### ISSUE THREAD

**Issue by AwesomeUnicorn3** [coppolaemilio/dialogic#369]
I have not been able to stress test it, but I was able to run an autoload script with arguments after adding the below code

The code would need to be added to the dialog_node.gd script, in the event handler function

'dialogic_042':
			var result
			dprint('[!] Call Node signal: dialogic_signal(call_node) ', var2str(event['call_node']))
			emit_signal("event_start", "call_node", event)
			$TextBubble.visible = false
			waiting = true
			var target = get_node_or_null(event['call_node']['target_node_path'])
			var method_name = event['call_node']['method_name']
			var args = event['call_node']['arguments']
			if (not args is Array):
				args = []
			if (target != null):
				if (target.has_method(method_name)):
					if (args.empty()):
						var func_result = target.call(method_name)
						if (func_result is GDScriptFunctionState):
							yield(func_result, "completed")
					else:
						var func_result = target.call(method_name, args)
						if (func_result is GDScriptFunctionState):
							yield(func_result, "completed")

			if target == null:
				target = event['call_node']['target_node_path']
				var script = GDScript.new()
				var args_text = ""
				var count = 0
				###if Arguments are text they must be in quotes " " otherwise returns error
				for i in args:
					if count == 0:
						args_text = args_text + i
					else:
						args_text = str(args_text) + "," + i
					count += 1
				args_text = "(" + args_text + ")"
				method_name = method_name + args_text
				var input = target + "." + method_name
				script.set_source_code("func eval():\n\treturn " + input)
				script.reload()
				var obj = Reference.new()
				obj.set_script(script)
				result = obj.eval()

			waiting = false
			$TextBubble.visible = true
			_load_next_event()
		_:
			visible = false
			dprint('[D] Other event. ', event)

**Comment by Jowan-Spooner** [comment]
Hey @AwesomeUnicorn3 could you try with the current main branch? Be careful and maybe create a backup (or just use version control). You can now just type in the name of your autoload/singleton into the Target Node field

**Comment by Jowan-Spooner** [comment]
If this works I think this could be closed.

**Comment by AwesomeUnicorn3** [comment]
@Jowan-Spooner I just tested and it is working.

**Comment by Jowan-Spooner** [comment]
That's great to hear. Then I'll close this. If you need anything else, feel free to ask.
