### ISSUE TITLE
Keyboard noises missing in exported project

### ISSUE THREAD

**Issue by lacunoc** [coppolaemilio/dialogic#370]
Hey, I've added some dialogues with dialogic and also ensured, that *.json and *.cfg are exported. But somehow the keyboard noises, which are enabled by default, aren't played in the exported version. And idea, what am I missing or is this is a bug?

**Comment by coppolaemilio** [comment]
Hey! this bug is confirmed and will be fixed asap. Some users on the discord server were able to make a fix but it wasn't pushed to Dialogic yet. Hopefully it will be fixed soon.
