### ISSUE TITLE
Text lines can be skipped during Dialog fade in animation.

### ISSUE THREAD

**Issue by idontkillcoyotes** [coppolaemilio/dialogic#374]
## The problem
While waiting for the dialog to fade in the user can skip the current line and it the fade will stop. 

**Describe the bug**
Lines can be skipped during the fade animation of the dialog, making the lines unreadable sometimes

**To Reproduce**
1. Create a timeline and add some text events
2. Create a theme and set up a long fade in transtion
3. Play the timeline and try to skip the first line during the transition
4. See how lines are skipped during the transition

**Expected behavior**
Line skipping should wait for the dialog to complete the fade in animation

**System (please complete the following information):**
 - Godot Version: 3.2.3
 - Dialogic Version: 1.2

## Solutions

**Possible fix**
This piece of code solved it for me. I just added a new bool check for the line skipping
```gdscript
func _input(event: InputEvent) -> void:
    if not Engine.is_editor_hint() and event.is_action_pressed(input_next) and not waiting:
        if not $TextBubble.is_finished():
            # Skip to end if key is pressed during the text animation
            $TextBubble.skip()
        else:
            if waiting_for_answer == false and waiting_for_input == false and while_show_up_animation == false:
                _load_next_event()
        if settings.has_section_key('dialog', 'propagate_input'):
            var propagate_input: bool = settings.get_value('dialog', 'propagate_input')
            if not propagate_input:
                get_tree().set_input_as_handled()
```

**Comment by coppolaemilio** [comment]
Thank you for the fix! I'll credit you on the change log :)
