### ISSUE TITLE
Touch input compatibility

### ISSUE THREAD

**Issue by AwesomeUnicorn3** [coppolaemilio/dialogic#375]
This is how I got touch input to work:

For the choice Buttons add script and connect gui_input signal:

extends Button

func _on_Button_gui_input(event):
	if event is InputEventScreenTouch: 
		if event.is_pressed() == true and pressed == false:
				set_pressed(true)
				emit_signal("pressed")

To advance the dialog:
in DialogNode:
add a texture rect as child of TextBubble
connect a gui_input signal to from the new texture rect to DialogNode script

func _on_TextBubble_Touch_Area_gui_input(event):
	if $Options.get_children().size() == 0:
		if event is InputEventScreenTouch: 
			if event.is_pressed() == true:
				var a = InputEventAction.new()
				a.action = input_next
				a.pressed = true
				_input(a)
				a.pressed = false

**Comment by coppolaemilio** [comment]
Thanks! I'll see if I can add some options for different input preferences for 1.3 👍🏻

**Comment by Bellusterra** [comment]
It looks like the most recent version 1.4 allows for selecting choices on mobile and from clicking with mouse. In regards to to advancing the dialog from mobile (touch) you can open the TextBubble.tscn file found under addons>>dialogic>>Nodes, create a TouchScreenButton and in the newly created TouchScreenButton Inspector create the shape you want to be selectable. Resize to fit over area of the text box. Change the Action to the same thing that you have set in Dialogic Settings under Input settings Default action key. You can create a new one from the Project>>Project Settings>>Input Map  or use a predefined one such as ui_accept.  Would have not have know where to start if it was not for your comment above @AwesomeUnicorn3 Thank you.
