### ISSUE TITLE
Dialogic editor doesn't work properly when not all editor tabs are visible

### ISSUE THREAD

**Issue by moonwolf-github** [coppolaemilio/dialogic#376]
## The problem

I have a rather peculiar problem. There are two characters and one timeline. After turning off the "2D" and "AssetsLib" tabs in the editor, problems with Dialogic begin. Trying to add a character sometimes adds two, sometimes more. Attempting to change the character of the event closing Dialogic editor. Turning those tabs back on fixes this issue.

**To Reproduce**
1. Create a new project, add and activate the Dialogic plugin
2. Create Node2D root node
3. Turn off "3D" and "AssetsLib" tabs 
4. Create 1 character
5. Create 1 timeline and add "Character join" event
6. Try to assign a character to it

**Expected behavior**
Everything should work properly

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.3.2
 - Dialogic Version: 1.2

## Solutions

**Workaround**

Do not turn off any editor tabs

**Possible fixes**

No idea, sorry :(

**Comment by coppolaemilio** [comment]
Interesting bug, I'll try to see what I can do 🤔

**Comment by coppolaemilio** [comment]
@moonwolf-github this issue should be fixed in the latest version in `main`. Can you confirm before I close the bug?

**Comment by moonwolf-github** [comment]
Sorry, I was gone for a while. I'll check it in few hours.
