### ISSUE TITLE
More in-depth documentation, in general

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#382]
**Problem:**
So, I used to write my own dialogue system for my games, but after finding dialogic I've started using it instead. My issue comes with the documentation. When it comes to the documentation of dialogic, as great of an addon as it is, I cannot for the life of me find any clear documentation on it. Some things I'd love clarified would be text tags, things like **[wave]** and **[color]** aren't even documented on the text events page which makes me wonder what else they haven't documented. Not only this, but other features like custom choice buttons, is there a way to detect if it's being hovered? currently selected? maybe a way to check the widest option so you can set the width to be the same for all of the options? no idea. or maybe nicknames? how do you set multiple nicknames? is there a way to change the display name to one of the nicknames? I have no idea because it's not at all documented, not only that but hovering over 90% of the options tells me nothing as to what it actually does which leads me to have to test it out myself rather than work on what I wanted to get done. The only downside so far to this addon from what I've experienced so far is the fact there is no real documentation.

**Solution:**
Flesh out the documentation. Obviously with this being on Github, I'll try and contribute what I can and I'm sure others will too, but I find the lack of documentation to be rather annoying as it means I have to dig through the addon and posts on forums for hours to find how to do something with 0 idea if there's already a function or easier solution.

**P.S.**
Love the addon so far, when it works. The dialogue timeline editor is exactly what I've been looking for, keep up the good work!

**Comment by coppolaemilio** [comment]
Docuemntation will be improved 100% 👍🏻

**Comment by Jowan-Spooner** [comment]
How exactly will we decide when this is finished ;). I mean the docs aren't finished but with the builtin documentation and new stuff being written all around I'm not sure when this should be closed?

**Comment by coppolaemilio** [comment]
I would close this one whenall the help pages are somewhat reasonable for a release, but I have to review it a few times 😅  hopefully it can be done this week!

**Comment by Jowan-Spooner** [comment]
Could we collect a list of what should definitely be documented (at all or better) before 1.3? Of course there should be proof-reading of (at best) everything. But I'm thinking about what new articles are missing. These are the things that I can think of:

## General
- [ ] A page explainging the use of the glossary
- [ ] A page explaining the use of values
- [ ] A page explainging saving and loading (already in the works on my saving system branch)
- [ ] A better explenation of the functions of the DialogicClass (also probably better be made after the saving system)
- [ ] A page about the Voice Line Support
- [ ] Maybe a page about the TimelineEditor? Where some not so well known functionality is explained?
## Missing Event pages:
- [ ] Set Glossary
- [ ] Change Timeline
- [ ] Set Background
- [ ] Close Dialog
- [ ] Wait Seconds
- [ ] Set Theme

Please feel free to give feedback if something is unnecessary or missing!

**Comment by coppolaemilio** [comment]
I don't think that we really need a documentation page for everything, you already wrote the most important stuff and we can keep updating it when necessary. I'll remove the milestone tag on this issue to keep tracking for the future but I'm pretty happy with the state of the docs at the moment :)

**Comment by Jowan-Spooner** [comment]
I agree with you, we can add more documentation later on. 

The only docs that are on the main branch and not complete/up to date and thus can be super misleading is the "Beginners Guide Tutorial". I think it would be very cool if you could have a look at that again @coppolaemilio!

**Comment by Jowan-Spooner** [comment]
One more note: the FAQ articles have way to long names! Make them shorter

**Comment by coppolaemilio** [comment]
Closing because it is too broad
