### ISSUE TITLE
I can't add a theme

### ISSUE THREAD

**Issue by BenHerbst** [coppolaemilio/dialogic#385]
_When I want to create a theme, I get the following error:_
```
SCRIPT ERROR: new_theme: Invalid call. Nonexistent function 'create_theme' in base 'ScrollContainer (ThemeEditor.gd)'.
          At: res://addons/dialogic/Editor/MasterTree/MasterTree.gd:574
```

**Comment by coppolaemilio** [comment]
Hey, what version of Dialogic are you using? Have you tried rebooting Godot after enabling Dialogic?

**Comment by BenHerbst** [comment]
After reboot of Godot it worked. Thank you for your help!
