### ISSUE TITLE
Inconsistent nested question behavior, pulls "choice" elements from other questions

### ISSUE THREAD

**Issue by Crystalwarrior** [coppolaemilio/dialogic#39]
As can be seen on the gif, the Timeline's questions are set up one way, but the parser takes more than it's supposed to and bugs out.
![qnYt5qNCG5](https://user-images.githubusercontent.com/3470436/106385477-9562be80-63e1-11eb-812d-734d56b5dbf9.gif)

The timelines used for testing this:
[timelines.zip](https://github.com/coppolaemilio/dialogic/files/5899804/timelines.zip)

Version: master, commit 83a7a0efcfc99d453495ba91aaa83fe992ba7481

**Comment by Crystalwarrior** [comment]
More info:
![image](https://user-images.githubusercontent.com/3470436/106385965-d9ef5980-63e3-11eb-8729-866b90118248.png)

**Comment by Crystalwarrior** [comment]
I'm questioning if the "End Branch" element is even necessary...

**Comment by Crystalwarrior** [comment]
This seems to be a major problem with json saving, as when I reload the timelines they seem to be completely broken up:
![MGgxDAsO4n](https://user-images.githubusercontent.com/3470436/106386484-423f3a80-63e6-11eb-889f-ea42968aacb3.gif)

**Comment by coppolaemilio** [comment]
Can you check if this one is fixed with the new saving fixes?
