### ISSUE TITLE
Deleting characters and creating them crashed Godot

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#390]
After creating/deleting/creating/deleting characters several times, either the editor crashes, or you see "ghost" characters in the list. 
 - Dialogic Version: 1.2.5

**Comment by theludovyc** [comment]
Maybe a link with https://github.com/coppolaemilio/dialogic/issues/397

**Comment by coppolaemilio** [comment]
The error seems to be located at the `DialogicUtil.get_character_list` function returning outdated data. Still under investigation.

**Comment by coppolaemilio** [comment]
found the issue! closing
