### ISSUE TITLE
Error in DialogicSingleton And resize visibility

### ISSUE THREAD

**Issue by dpnnl** [coppolaemilio/dialogic#391]
I tried to install Dialogic by downloading through Github and putting it in the Addons folder and this error always happens. I tried versions 1.2.4 and 1.2.5.

If I install via AssetLib this error doesn't happen. (I would like to test 1.2.5 :) ).

![20210707_144749](https://user-images.githubusercontent.com/84047200/124806414-0aa76200-df33-11eb-8117-25e60939c294.png)

Some help?

**Comment by coppolaemilio** [comment]
Pushing a fix soon to this issue

**Comment by coppolaemilio** [comment]
@dpnnl I made the changes, can you test it out again with the latest version? https://github.com/coppolaemilio/dialogic/commit/c1e04721bec80f1636f6eb9ee1d4d6162b590dcf

**Comment by dpnnl** [comment]
Now it's working. 
Now I have just one more problem, the dialog becomes visible if I resize the window. Do I need to open another topic?

**Comment by coppolaemilio** [comment]
Not sure I understand the issue. Can you post a video? This same thread is fine :)

**Comment by dpnnl** [comment]
I ended up finding out why, I hope you can see it on the video. (sorry for slow recording, my notebook is of middle age).

https://user-images.githubusercontent.com/84047200/124820335-bc4e8f00-df43-11eb-93ab-9d0f62b33f95.mp4

**Comment by coppolaemilio** [comment]
why was it then? you shouldn't touch the anchor nodes since that is handled by dialogic depending on your rendering mode

**Comment by dpnnl** [comment]
I apologize, I think you can close this topic now, everything is working correctly now. :) Thank you.
