### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by dpnnl** [coppolaemilio/dialogic#392]
Hello again :)

I would like to know if it is possible to use the Godot translation system in Dialogic. I tried it but it didn't work, so I assume I did something wrong...

![Screenshot_20210708_151022](https://user-images.githubusercontent.com/84047200/124971504-a7373600-dfff-11eb-84ec-bdc1034f76e0.jpg)
![Screenshot_20210708_150818](https://user-images.githubusercontent.com/84047200/124971509-a8686300-dfff-11eb-996f-16421469a002.jpg)

Some help?

**Comment by Jowan-Spooner** [comment]
Hey you can use it. There is a setting (in the settings) to treat all text events as keys for translation. So you won't have to do the tr() when the setting is enabled.

**Comment by dpnnl** [comment]
What should I do?

**Comment by Jowan-Spooner** [comment]
Go to the settings
![grafik](https://user-images.githubusercontent.com/42868150/124976751-f39a6a00-e02f-11eb-86bc-3daf077813ae.png)

Enable this option
![grafik](https://user-images.githubusercontent.com/42868150/124976711-eaa99880-e02f-11eb-8d9d-6b70d2f248e7.png)

Then just write your translation key into the text event. (In your example test)

Disclaimer: I have actually never used this and no idea if it works. That's just how it SHOULD work.

**Comment by dpnnl** [comment]
Thanks! I was trying to use it with this plugin (https://github.com/Zylann/godot_translation_editor) (using $$test for example) but unfortunately it doesn't work. Without it it's working normally...
