### ISSUE TITLE
Possible fix to the export settings requirement?

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#393]
https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html

In this class there is a method called `add_file`

Maybe it could be used and add all the .json and .cfg files, so that we don't have to make the user do that manually on the export dialog.

Still haven't tested any of it, but if you are reading this issue and feel adventurous give it a try :)

**Comment by Lucas-Romao** [comment]
I managed to get it working, I'll open a pull request

**Comment by Jowan-Spooner** [comment]
I will test this now and close the issue if it works.

**Comment by Jowan-Spooner** [comment]
It works, but only if you have a theme (as reported in #466). It could very well be a different thing that produces the error though.

Great work @LuRomao !!

**Comment by Jowan-Spooner** [comment]
I would say this is solved. Thanks again @LuRomao
