### ISSUE TITLE
Actor fade in/out styles

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#394]
Would love for different styles for actors to fade in/out, maybe having an additional option when having an actor join/leave a dialogue eg.

- fade from left
- fade from right
- no transition (actor just appears)
- squish in (scales from 0,2 to 1,1)
- eg.

same for options when leaving the scene but with contextual changes eg. "fade **_to_** left/right".

**Comment by coppolaemilio** [comment]
Yeah, that would be great to add. It is something that has been on our to-do list for a long time, but there are always other fires to put out. Hope we can add it soon! If you can complete the list of animations that would be a great reference for implementation :)

**Comment by Schwender-exe** [comment]
for sure! I'm sure others can think of more, but what comes to mind would be transitions/animations like:

- no transition/animation
- fade in from up/down/left/right
- fade out to up/down/left/right
- fade in/out (no direction)
- scale in/out X only/Y only/both (scales from 0 -> 1, or in out case 1 -> 0) 

with fade and scale having adjustable speeds and with the fade, possible adjustable distance?
keep up the great work btw, love checking in from time to time to see how much you've fixed/added!

**Comment by Jowan-Spooner** [comment]
Not all of the mentioned animations are added, but 1.4 will provide some nice animations for entering and exiting. Also it is relatively easy to add new animations using the [ANIMA](https://github.com/ceceppa/anima) animation format.
