### ISSUE TITLE
if condition does not work

### ISSUE THREAD

**Issue by skyace65** [coppolaemilio/dialogic#395]
## The problem

**Describe the bug**
I have set up two if conditions in my timeline. If a value is 0 it's supposed to change the timeline. The default value is 0 and the if condition is always skipped over.

**To Reproduce**
1. Create an definition with a value of 0
2. Create a timeline with an if condition for that value equaling 0
3. Run the dialogue

**Expected behavior**
Since the value is 0 the timeline should change

**Screenshots**
![Timeline1](https://user-images.githubusercontent.com/6080368/125176977-34b48a80-e1a6-11eb-8ecf-ab2f087ef125.PNG)
![Definition](https://user-images.githubusercontent.com/6080368/125176987-45650080-e1a6-11eb-93a2-1458d4e6e90f.PNG)

**System:**
 - OS: Windows 10
 - Godot Version: 3.3.2 mono (not using C# for this project though)
 - Dialogic Version: 1.2.4

**Comment by theludovyc** [comment]
Hello !

I find where it come from. When you create new condition "equal to" is default. But its not save in the json.
Example :
`
{
	"condition": "",
	"definition": "1625991849-648",
	"event_id": "dialogic_012",
	"value": "0"
}
`

But when you set equal, its works !
`
{
	"condition": "==",
	"definition": "1625991849-648",
	"event_id": "dialogic_012",
	"value": "0"
}
`

**Comment by theludovyc** [comment]
I think it's here

TimelineEditor.gd:467
`
# the Condition button adds multiple blocks 
func _on_ButtonCondition_pressed() -> void:
	if len(selected_items) != 0:
		# Events are added bellow the selected node
		# So we must reverse the adding order
		create_event("EndBranch", {'no-data': true}, true)
		create_event("Condition", {'no-data': true}, true)
	else:
		create_event("Condition", {'no-data': true}, true)
		create_event("EndBranch", {'no-data': true}, true)
`

**Comment by coppolaemilio** [comment]
I'll take a look at the issue tonight when I'm free and see if the defaults are the issue 👍🏻

**Comment by theludovyc** [comment]
I found this

[dialog_node.gd](https://github.com/coppolaemilio/dialogic/blob/93176a4bbc194435e39a8d873b0c20f83e3fb965/addons/dialogic/Nodes/dialog_node.gd#L1053)

```gdscript
if condition == '':
  condition = '==' # The default condition is Equal to
match condition:
  "==":
    condition_met = converted_def_value == converted_event_value
```

**Comment by theludovyc** [comment]
On Godot 3.2.3 no problem

![image](https://user-images.githubusercontent.com/7337158/125190757-03d46400-e23f-11eb-8b2f-88f1dadab8fe.png)

**Comment by theludovyc** [comment]
On Godot(Mono) 3.3.2 no issue

![image](https://user-images.githubusercontent.com/7337158/125190874-b7d5ef00-e23f-11eb-99d9-a6c48d1bde4b.png)

Project :
[TestDialogic124(Mono).zip](https://github.com/coppolaemilio/dialogic/files/6796684/TestDialogic124.Mono.zip)

**Comment by theludovyc** [comment]
On Godot 3.2.3 no issues on change timeline

![image](https://user-images.githubusercontent.com/7337158/125191018-9590a100-e240-11eb-92b1-54d695e51975.png)

Project :
[TestDialogic124_1.zip](https://github.com/coppolaemilio/dialogic/files/6796697/TestDialogic124_1.zip)

**Comment by theludovyc** [comment]
@skyace65 can you send your project with issues please ? =)

**Comment by skyace65** [comment]
I checked the json file for that timeline and you're right, it's not setting equal as the condition by default. Here's a test project I just made that has the issue.
[DialogicTest.zip](https://github.com/coppolaemilio/dialogic/files/6797004/DialogicTest.zip)

**Comment by skyace65** [comment]
There's more to this issue than I thought. Changing the condition to something else, then back to equal does change the json file. However it still doesn't work. And when I try to print the variable to the console there's nothing. Are there any Godot editor files I should try deleting to reset settings?

**Comment by coppolaemilio** [comment]
the parser knows that if there is no option selected the default is `equal to` so it doesn't really have to pollute the json with more info than it's needed. But I don't think this is the origin of the issue. It might be something related to testing `0` as `false` or something like that. I will try to investigate further

**Comment by skyace65** [comment]
In that case don't bother with the test project I shared. That was just to show that the default condition was blank. I tried making another test project but this one is working. I'll do some more testing and let you know if I figure something out. The project I'm having the issue in is too big to upload.

**Comment by skyace65** [comment]
I just took the plugin and scripts and put them in a separate project and they started to work properly. Since this doesn't seem to be an issue with the plugin I'll close this issue.

**Comment by coppolaemilio** [comment]
Thanks! If you figure out what it is let me know to see if there is anything I can do to prevent it from happening! Cheers :)
