### ISSUE TITLE
Deleted Default Value is Recreated

### ISSUE THREAD

**Issue by theludovyc** [coppolaemilio/dialogic#397]
When you deleted a default value and recreate one, older is recreated too

**To Reproduce**
1. Created new value
2. Delet it
3. Recreate one

**Expected behavior**
Not recreated older one

**Screenshots**
![image](https://user-images.githubusercontent.com/7337158/125190040-780d0880-e23b-11eb-9bfd-eff37a0ef0f4.png)

**System:**
 - OS: Windows, Linux
 - Godot Version: 3.2.3
 - Dialogic Version: 1.2.4

**Comment by coppolaemilio** [comment]
Fixed this issue with the latest commit. Feel free to reopen if it is still happening to you 👍🏻

**Comment by theludovyc** [comment]
Yeah \o/ ! I take a look when I have time ;)
