### ISSUE TITLE
Voice support.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#401]
**Is your feature request related to a problem? Please describe.**
Dialogic has no support for voice acting built in. This means there is no (easy) way to add voiced lines.

**Describe the solution you'd like**
Not sure. Maybe like Parrot does? https://github.com/deep-entertainment/parrot/blob/main/docs/resources.md Or AGS - https://adventuregamestudio.github.io/ags-manual/MusicAndSound.html#voice-speech

**Describe alternatives you've considered**
Not really sure there can be any, without hacking into Dialogic's source code.

**Comment by RedXGames** [comment]
I'm working on implementing voice support for my game, I will pull a request when it's ready.

**Comment by RedXGames** [comment]
@coppolaemilio  Hey, Emilio, I'm almost done with the voice support, It is working perfectly except for one tiny bug.
I couldn't find the part of the code that creates extra messages when entering new lines in text events.
I need to find it because somehow the voices don't play if the text event has multiple lines with the option to create new messages is on.
Do you know where can I find it in the code?

**Comment by coppolaemilio** [comment]
@RedXGames it should start here: https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Nodes/dialog_node.gd#L211

**Comment by RedXGames** [comment]
I must be blind, I spent 30 minutes in that script and didn't see it xD.
Thanks for the help

**Comment by Jowan-Spooner** [comment]
Hey @Sslaxx. I've finished @RedXGames pr and merged it. Feel free to test it. Of course make sure to have a backup of your project!! Main is always WIP and surely contains bugs.

I'll write a little tutorial on the feature later today but it's easy to use: Just enable Voices in the Settings and (if you want) pick a default voice audio bus!

Hope it works as you wanted it.

**Comment by Jowan-Spooner** [comment]
Let us know if this fixes this issue for you, so we can close it.

**Comment by Jowan-Spooner** [comment]
I'll close this for now. If the feature doesn't work correctly or more is needed, we can reopen this or add new issues.
