### ISSUE TITLE
Events still executing after calling "Close Dialog" event

### ISSUE THREAD

**Issue by RedXGames** [coppolaemilio/dialogic#405]
## The problem

**Description :** 
If you spam the action key when the dialogic window is fading away after a close dialog event, any text events after that, will still appear while the dialog is fading away.

**To Reproduce**
1. Adding text events after a Close dialog Event in the timeline.
2. Spamming The Action key when the dialogue is playing
3. The bug appears

**Expected behavior**
Dialogue fades away without showing the next text event.

**Screenshots**
A screenshot of the timeline example : 
I'm using a variable to choose what text event should execute.
![Layer 25](https://user-images.githubusercontent.com/87644362/126238679-0c27dc4d-0c68-4c5a-a2b1-01e98c18cd2d.png)

Here's a screenshot of what happens after the dialogue end but I keep spamming the action key.
![Layer 26](https://user-images.githubusercontent.com/87644362/126239813-739ee67d-f588-4b2f-8b8e-4137ddf44eb2.png)
The IF statement was true so the text event inside appeared. The dialogue already ended but it is still executing events and it should not show the text event that is displayed in the screenshot.

**System**
 - OS: Win10
 - Godot Version: 3.2.3
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**
You can put the code after the close dialog event in another If statement with the opposite condition but that's not ideal especially if you have multiple choices.

**Possible fixes**
Prevent Dialogic from fetching new events after detecting a "close dialog" event

**Comment by coppolaemilio** [comment]
@RedXGames I pushed a fix for this one: https://github.com/coppolaemilio/dialogic/commit/102e68f9ede7c6440d1b3b39930dba47d49bc864
If it doesn't I'll reopen the issue 👍🏻
