### ISSUE TITLE
EndBranch element used for conditionals, yet internally called 'endchoice'

### ISSUE THREAD

**Issue by Crystalwarrior** [coppolaemilio/dialogic#41]
It's saved in json as 'endchoice' and is called that internally (in code) despite being "EndBranch" in editor and working with conditionals.
Suggested refactor should still be able to read the 'endchoice' in json but transform it to correct 'endbranch' naming automatically for backwards compatibility/migration to new method.

**Comment by coppolaemilio** [comment]
I didn't add the backwards compatibility because we are not on v1.0 yet, but this event is renamed 👍🏻
