### ISSUE TITLE
The Documentviewer [code] font is not properly loaded.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#415]
When using the ``` characters, the font is just of a different color and doesn't change to monospaced.
Maybe getting the theme editor font could help: `get_font("source", "EditorFonts")`

**Comment by Jowan-Spooner** [comment]
Well this is because I haven't actually set a MonoSpace font. As far as I could see, Godot uses Noto Sans UI by default, so that's what I decided to use. But I couldn't find a mono space version so for now I just used the regular one. 

Setting it like you suggested could be an option.
