### ISSUE TITLE
Action Key is not getting set on Choice Button

### ISSUE THREAD

**Issue by ksjfhor** [coppolaemilio/dialogic#416]
## The problem
I have the following input map:
Keyboard "E" = ui_inspect
Keyboard "ENTER" = ui_accept

When I switch from "ui_accept" to "ui-inspect" it is on the Choise Buttons still "ui_accept".
Normal Conversations work fine, but the ones with questions (and a choice) seem broken.

**Describe the bug**
Default Action Key from Settings or Themes are not getting set on Choice Buttons.
I want to use "ui_inspect", but it keeps "ui_accept", but shows "ui_inspect" in the Settings.

**To Reproduce**
1. Go to 'Dialogic'
2. Click on 'Settings'
3. Switch the Default action key from "ui_accept" to "ui_inspect"
4. I can talk with NPC via "ui_inspect", but on the Choice Buttons it just moves one up, but don't continue the text.
For more I still need to press "ui_accept".

**Expected behavior**
When I switch the Default action key I want it to be used on Choice Button.

**Screenshots**

**System (please complete the following information):**
 - OS: Win 10
 - Godot Version: 3.3.2.stable
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**

I tryed to also set the action key in the theme settings on "Dialog Box/Behaviour", but it won't change a thing.

**Possible fixes**

I'm not sure how to fix this.

**Comment by coppolaemilio** [comment]
Thanks for the report! I'll investigate and see what I can do 👍🏻

**Comment by coppolaemilio** [comment]
@ksjfhor I pushed a fix to the latest version, can you check if it works for you?

**Comment by ksjfhor** [comment]
works perfectly, thank you btw
