### ISSUE TITLE
Ability to call resources with their folders

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#417]
**Is your feature request related to a problem? Please describe.**
Although we have folders in the resource tree, calling timelines (in Dialogic.start()) or definitions still only recognizes their names. This means it's possible to have two timelines named identically but it's impossible to call one of them.

The same goes for definitions (in texts).

**Describe the solution you'd like**
I would like to be able to call 
`Dialogic.start("myfolder/mytimeline")`

and write (in a text event)
`Hey how are you doing [Companion/Name]?`
`Thanks I'm fine [Player/Name]. How are you?`

**Describe alternatives you've considered**
... don't know?

**Comment by coppolaemilio** [comment]
The first part is added already (paths to timelines), but I'm not sure it would be handy for having other resources like characters in the mix. Is this some issue you ran into or a "nice to have"?

**Comment by Jowan-Spooner** [comment]
@schmertenk I have good news at last! This was added and will be the suggested way of calling variables in 1.4. Thanks to @thebardsrc !
