### ISSUE TITLE
Timeline-Folders in the timeline picker of the dialog node

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#418]
**Is your feature request related to a problem? Please describe.**
The timeline picker of the timeline property of the dialog node doesn't show the folders like the pickers inside the dialogic tab.

**Describe the solution you'd like**
Have a similar picker to the change timeline event

**Describe alternatives you've considered**
I personally don't even instance the node directly often. Mostly I do it by code so if this isn't implemented soon i'm not sad. But I think if this option is provided, this feature should come one day.

**Comment by coppolaemilio** [comment]
Added a partial fix to the timeline pick: 
> `Dialogic.start()` will now use paths for specific timelines. A fallback is in place, but specificity is preferred. For instance: `Dialogic.start('my-timeline')` will search any timeline with that name; `Dialogic.start('/chapter-1/my-timeline')` will open the timeline namde `my-timeline` inside the folder `chapter-1`.

But the inspector picker should be updated next.

**Comment by coppolaemilio** [comment]
Not using this system any more
