### ISSUE TITLE
Engine.get_singleton('DialogicSingleton') throws error?

### ISSUE THREAD

**Issue by Schwender-exe** [coppolaemilio/dialogic#425]
EDIT: accidentally pressed enter, oops.

with Godot V3.2.3 and Dialogic 1.2.5

not sure exactly how this happened, I had an older version working but on updating versions it threw an error on calling
`Dialogic.reset_saves();`
I fixed this on my end by replacing calls of `Engine.get_singleton('DialogicSingleton')` with just `DialogicSingleton`

**Comment by Schwender-exe** [comment]
should also specify, the error claimed there was no singleton named 'DialogicSingleton' despite it being autoloaded. I restarted godot a few times to see if that would help, but it didn't seem to. I'm not entirely sure if this is just a Godot V3.2.3 bug, but I figured I should mention it here just in case.

**Comment by Jowan-Spooner** [comment]
On the main branch this is already solved. I've removed pretty much all instances of this curded line. Thanks for telling us anyways.

**Comment by Schwender-exe** [comment]
ahh gotcha
