### ISSUE TITLE
Canvas layer setting is not being shown as saved.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#427]
## The problem

**Describe the bug**
Changing the canvas layer setting does not appear to be saved. I changed it in settings to 128, saved then restarted my project, and the settings have reverted back to the default 1.

However, running the project, from the Remote local debug scene tree, the created `CanvasLayer` is on layer 128. For some reason the correct canvas layer setting value does not show up in the debug settings when you reload a project or restart Godot.

**To Reproduce**
1. On the settings panel, change the canvas layer to something else.
2. Save.
3. Restart the project.
4. See error - canvas layer in settings is back to default.

**Expected behavior**
For the canvas layer setting to be saved between sessions.

**System (please complete the following information):**
 - OS: Ubuntu 21.04
 - Godot Version: 3.3.2
 - Dialogic Version: 1.2.5

**Comment by Jowan-Spooner** [comment]
Thanks for pointing that out. From what I can see there is not actually anything in the code that load's this setting back into the UI when opening the Settings Editor. Should be easy to fix, so I will add it to the 1.3 Milestone.

**Comment by Jowan-Spooner** [comment]
Oh and I didn't mention: This doesn't mean it doesn't work. It's saved properly when you change it. It's just not properly displayed.
