### ISSUE TITLE
Selected event is very dark in the white theme

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#431]
Needs to be updated because the text is hard to read.

**Comment by Jowan-Spooner** [comment]
Actually I was thinking about changing the behaviour to only have a blue outline around for selected events instead of changing the whole color. What do you think?

**Comment by coppolaemilio** [comment]
I think that was my original intent, but there is a issue when you modify one theme property (like the border color) that will change all the instances of that theme as well. If you can figure it out it would be brilliant

**Comment by Jowan-Spooner** [comment]
I will see if there is an easy way.
