### ISSUE TITLE
some form of Goto event for timeline?

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#434]
would love for some form of Goto event with a secondary event which would act as a bookmark for the Goto event to select from possibly?

**Comment by Jowan-Spooner** [comment]
Hey I agree this would be cool.
It's related to if not a duplicate of #325. I thought of your bookmarks as anchors. It's quite a bit of work tho. We'll see if it actually makes it into 1.3.

**Comment by Jowan-Spooner** [comment]
This became reality! In 1.4 we have the Go To and the Label event that allow exactly this!
