### ISSUE TITLE
Will you be using wiki to store documentation?

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#436]
As I tend to check the main github page, I would find it more convenient to find out more about dialogic by clicking on the Wiki page.

Other please to go settings and uncheck Wiki. Currently, clicking on Wiki re-directs back to Code.

**Comment by coppolaemilio** [comment]
I'm writing the documentation at the moment. This documentation will be added inside the resource tree, but we will also mirror the information in Dialogic's website. I'm not sure if there is an easy way to also mirror that documentation in the Wiki here, but I will uncheck it as you suggest. 
Thanks!
