### ISSUE TITLE
Add an ability to save Backgrounds outside of Dialogic similar to Definitions.

### ISSUE THREAD

**Issue by Chessa1** [coppolaemilio/dialogic#437]
I made a plug-in that uses RNG to initialize timelines to simulate an AI for RPG battles -- Everything works, I added the stats to be saved in the plugin vs dialogic and to link up to it through signals/etc, but there's one thing that seems to lack any ability to be linked this way -- Backgrounds.

This means to have any background consistently, I have to add the background at the start of every timeline that will be chosen, the problem with this is...

Everytime it swaps timeline, it flickers and then pops onto the screen. So, basically, it's not really useable at all in that way...

So, my request is simply just, adding a way to set a background via code, similar to saving stats via code, outside of the dialogic node itself but still using the editor.

**Comment by coppolaemilio** [comment]
In version 2.0 you should be able to interact much better with every aspect of dialogic from code. Leaving open to make sure this works and it is easy to do.

**Comment by thebardsrc** [comment]
The flickering mentioned here I believe was actually a 1.x bug that was fixed a while back. Rest of this feature-wise should be implemented by the overall Dialogic 2 design, together with the custom background scene system in #1225
