### ISSUE TITLE
Allow for solid color as a background option.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#441]
Internally it can be just a 1px white image stretched and with some modulation so that we don't have to do the logic of making a color rect node and all that. But whatever is fine.

**Comment by thebardsrc** [comment]
This could be included in the default portrait scene, for if an HTML color code is passed instead of an image path

**Comment by coppolaemilio** [comment]
Yeah, this issue is really more about the 1.x theme... I think we can close this one because with new themes this is just adding a regular control node.
