### ISSUE TITLE
Timeline_end doesn't trigger without end timeline event

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#447]
Reported by a discord user. Needs to be tested.

**Comment by skyace65** [comment]
Can't confirm. Just tested on windows with Godot 3.3.2 and Dialogic 1.2.5

**Comment by Jowan-Spooner** [comment]
Okay thanks for the answer. Wonder why it didn't work for the user then...Who knows.

**Comment by zaknafean** [comment]
I got a similar-ish error when I forgot to give the 'current_timeline' argument to my callback function. It did throw an error about the lack of argument and the method was of course not called, making it seem like the signal failed. Could have been that, but otherwise can't recreate a failure.

**Comment by Jowan-Spooner** [comment]
Cannot reproduce either. Will close this. If it happens again, please reopen or create a new issue.
