### ISSUE TITLE
reset_saves() is broken in 1.2.5

### ISSUE THREAD

**Issue by skyace65** [coppolaemilio/dialogic#448]
## reset_saves() is broken in 1.2.5

**Describe the bug**
When trying to use `reset_saves()` the game gives the error `Attempt to call function 'init' in base 'null instance' on a null instance.`

**To Reproduce**
1. have any code that uses the reset saves method
2. Run the code

**Expected behavior**
The reset saves method should work

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.2 Mono
 - Dialogic Version: 1.2.5

**Attachments**
- Here is a test project where I got the bug to occur. 
[DialogicTest.zip](https://github.com/coppolaemilio/dialogic/files/6949267/DialogicTest.zip)

- I'm not sure if this is relevant or not but this project was using an older version of dialogic which I then upgraded. (deleted old dialogic folder from the addons folder, and then put the new one there)

**Comment by Jowan-Spooner** [comment]
If you have the time feel free to test this on main. Could be that it is already solved.

When testing make sure to use version control or have a backup!

**Comment by skyace65** [comment]
It works with the master branch. Should I close this issue now or wait until the next release?
