### ISSUE TITLE
Can't use dialogic

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [coppolaemilio/dialogic#450]
## The problem

**Describe the bug**
When I run the project it says that the timeline is loaded but I can not see the dialogic window as I see on the editor

**To Reproduce**
1. Run the project
2. Console says it is loaded and when I press enter it goes to the next part
3. Can't see the window nor the text

**Expected behavior**
See the widget with the text

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.2 Mono
 - Dialogic Version: 1.2.5 ( The same with 1.2.4 )

Have Tried:
Reinstall dialogic
Install older version of dialogic
Both of the above on new projects

**Comment by AhNesh** [comment]
In Project settings under Plugins, is Dialogic enabled? 
![image](https://user-images.githubusercontent.com/33862238/128633015-6a7d621d-2749-4a06-bf21-03c2e6584191.png)

**Comment by GalaxyGamingBoy** [comment]
> In Project settings under Plugins, is Dialogic enabled? 
> ![image](https://user-images.githubusercontent.com/33862238/128633015-6a7d621d-2749-4a06-bf21-03c2e6584191.png)
> 

Yes, yes it is.

**Comment by coppolaemilio** [comment]
Are you using any canvas layer? I'm 100% sure the issue is with the scene you are adding Dialogic to. Have you tried creating an empty scene and see if Dialogic is showing up or not?

**Comment by GalaxyGamingBoy** [comment]
> 
> 
> Are you using any canvas layer? I'm 100% sure the issue is with the scene you are adding Dialogic to. Have you tried creating an empty scene and see if Dialogic is showing up or not?

Ah, that was the issue. Thank you.
I am quite new to the control node on godot.
I don't use it much. Thank  you.

**Comment by coppolaemilio** [comment]
Glad you found the issue! 👍🏻
