### ISSUE TITLE
Full text event view of text?

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#456]
Would it be possible to have a setting which would disable scrolling on the body content (text) and instead have it so it displays all of the text? It's a minor thing but it'd make for a nice QOL feature I'd think.

**Comment by coppolaemilio** [comment]
yeah, dynamic sizes should make it eventually to Dialogic, but not sure when yet 🤔

**Comment by Jowan-Spooner** [comment]
Not sure if I understand this correctly, but if I do, then this is probably fixed in 1.4 WIP.
