### ISSUE TITLE
Dialogue is missing in exported release version

### ISSUE THREAD

**Issue by lacunoc** [coppolaemilio/dialogic#459]
## The problem

**Describe the bug**
I've exported my game as a release version and somehow one of the dialogues (didn't test all of them) is missing.

**To Reproduce**
1. Approach the NPC in debug version in editor
2. Dialogue works
3. Export game as release with steamgodot template
4. Approach the same NPC again
5. Dialogue is missing

It always affects the same dialogue, though. And the dialogue definitely exists, as it works out of the editor since months.

**Expected behavior**

**Screenshots**
This is the error
![Screenshot 2021-08-14 080228](https://user-images.githubusercontent.com/9279502/129435907-5b9ccb17-c271-4522-ab20-74031bf16b75.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 3.3.2.custom_build (SteamGodot)
 - Dialogic Version: 1.2.4

## Solutions

**Workaround**

No workarounds found so far.

Any idea how to debug this? It's one of the blockers releasing my game.

**Comment by lacunoc** [comment]
Even renaming the dialogue to e.g. "vendor2" is throwing an error again, but with the renamed dialogue name.

**Comment by Jowan-Spooner** [comment]
Have, you exported your project correctly?don't forgetto add *.cfg and *.json as described on the front page!

**Comment by Jowan-Spooner** [comment]
https://github.com/coppolaemilio/dialogic#-preparing-the-export

**Comment by lacunoc** [comment]
Yes, I've exported it correctly and also added the needed file types. As I said, all of the dialogues I've tested so far are working in this export, but this exact one can't be found. Even after renaming and re-exporting.

**Comment by lacunoc** [comment]
I've also tried to export it with Godot 3.3.2stable by ripping out the Steam part. Same issue, unfortunately.
The debug console just says:
`[Dialogic] Initializing save file: 0`, but the above mentioned error occurs.

**Comment by lacunoc** [comment]
I fixed it by recreating the above mentioned dialogue with a new name but the exact same content. Now the dialogue works in an export. Weird. Is this worth to investigate? The dialogue name "vendor" seems to be burned.

**Comment by coppolaemilio** [comment]
Could it be possible that your timeline called `vendor` is duplicated in another directory? 

Also, can you try the latest version of `main`? It includes an auto exporter for those files (so no settings needed) and it also has an improved timeline picker for when you set the `Dialogic.start()` which includes full path support and stuff like that.

**Comment by lacunoc** [comment]
There's a Vendor directory, but with a capital V. But why did it work before and still worked in the editor? Anyway, I'm hesitating a bit changing the current version, as I'm only weeks before the game release. But will do, definitely.

I will close this for now, as I found a proper fix.
