### ISSUE TITLE
Better keyboard support.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#46]
Writing text requires to use the cursor way too many times, so I'll be adding a few hotkeys for better keyboard navigation.

## Some ideas for the Text Event are: 

- [x] `Shift` + `Enter`: Create a new text event with the same settings as this one? (or maybe alternating between this and the previous, so you can create a conversation between two characters easily)
- [x] `Tab`: Jump to the next Text Event text edit field
- [x] `Shift` + `Tab`: Jump to the previous Text Event text field
- [x] `Alt` + `up` / `Alt` + `down`: Move selected event up or down

**Comment by ellogwen** [comment]
Just working on this issue, Alt up and Alt down is working already. Tab to jump to the next field is "blocked" because tab is a default character, i would propose to use Control + Up, Control + Down in unisence with the move shortcuts

**Comment by ellogwen** [comment]
Implemented Movement and Selection in PR#137 as a draft
