### ISSUE TITLE
UX-Improvement for Custom Events

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#462]
**Is your feature request related to a problem? Please describe.**
When you don't use custom events the section shouldn't be visible. Also why do I need to enable them after I created one?

**Describe the solution you'd like**
Auto-detect whether to use them.

**Comment by zaknafean** [comment]
Solution chosen was to ignore the setting check, and just allow the size of the custom_events dictionary to determine if the UI elements are hide() or show() in the TimelineEditor. A similar check was also removed from the dialog_node.gd.  This should be a pretty low 'cost' change for the UX improvement.

The custom events related UI elements appear on project start or after a click to any other dialogic timeline element.

**Comment by Jowan-Spooner** [comment]
Fixed by #515 some time ago.
