### ISSUE TITLE
DialogNode Inspector Timeline Open button doesn't work

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#464]
## The problem

**Describe the bug**
There is this button next to the timeline selector that should open the timeline, but some reference is broken so it just prints an error.

![grafik](https://user-images.githubusercontent.com/42868150/129734625-794e0ccb-b22e-4762-8fda-9defb5e6e15d.png)

**Comment by coppolaemilio** [comment]
Fixed :)
