### ISSUE TITLE
Exporting without a theme doesn't work

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#466]
**Describe the bug**
This is what I get:
![grafik](https://user-images.githubusercontent.com/42868150/129737359-5b56efd4-c6a1-4aa5-a6f2-d36177015d29.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.2
 - Dialogic Version: 1.3 WIP

**Comment by coppolaemilio** [comment]
Can you create an empty project and test it again with the latest version?

**Comment by coppolaemilio** [comment]
Since a base theme is created now I will move this issue to 1.4 to see if there is a possible solution or to add some functionality that prevents you to remove the latest theme in your project (so you always have 1 at least)
