### ISSUE TITLE
Documentation RegEx gets interrupted by the # character.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#468]
Markdown file:
![image](https://user-images.githubusercontent.com/2206700/129911150-e0cac230-7584-4cbd-8dda-9e8aa8428671.png)
Documentation viewer
![image](https://user-images.githubusercontent.com/2206700/129911082-7f70a983-69f2-4b64-98ff-8d0cee8fc058.png)

The character should be escaped from the regular expression

**Comment by Jowan-Spooner** [comment]
it should indeed
