### ISSUE TITLE
Dialogic not stopping input from filtering down to parent game

### ISSUE THREAD

**Issue by chucklepie** [coppolaemilio/dialogic#47]
Input in Dialogic (input_next) is handled by the _process() method and not _Input.

This means the scene tree method set_input_as_handled() cannot be called. The result is if the underlying game is not paused then the input event is propagated down to the rest of the game that may handle _input, so if the same key handling input in Dialogic is handled in the game it is still called.

I'm not too hot on gui input in Godot but I had to fix the above problem by moving the _process() code handling input into the following similar code:

```
func _input(event: InputEvent) -> void:
	if Input.is_action_just_pressed(input_next):
		get_tree().set_input_as_handled()
```

i.e. after dialogic has processed the next screen key, it cancels input, otherwise Godot will just send the key to the rest of the game regardless.

Apologies if this version has already addressed this, I was using a slightly older version, but a quick scan of the code shows the same input being used.

**Comment by coppolaemilio** [comment]
Thanks for the report! I'm not sure how I should deal with this, since I don't want Dialogic to block any input, but I'm not sure if I should be doing it. I'll keep it open until I start to test it more in real world scenarios and see what changes I can make.

**Comment by chucklepie** [comment]
Maybe treat it as two stages. 

First, you aren't blocking it you're simply moving it from a polling system in _process to the _input event where it should be because dialog is GUI and GUI input work best as event driven.

This means it gives it gives the end user (or the dialogic api) the choice of controlling input better..

**Comment by AnidemDex** [comment]
What about adding it to `_input` and also making a boolean variable inside the theme editor to figure out if the user wants to propagate the input to the resto of the tree or not?
