### ISSUE TITLE
Timeline events in the editor have poor readability when using a light Godot theme

### ISSUE THREAD

**Issue by Lunadyn** [coppolaemilio/dialogic#471]
## The problem

**Describe the bug**
Many timeline events have poor readability in the editor when using a light Godot editor theme.

Punctuation is white, making it completely unreadable:
![image](https://user-images.githubusercontent.com/59242420/130266329-b1f6315b-f9f2-48ef-93ce-84fa0c272578.png)
![image](https://user-images.githubusercontent.com/59242420/130266382-f9c27ebc-9934-40dc-bc28-b0ed8e1021b5.png)

Here are all of events when viewed in light mode:
![image](https://user-images.githubusercontent.com/59242420/130262748-781dc164-7882-438e-8872-c2e1092cbe7b.png)

The most problematic cases involve the use of dark text with the dark backgrounds of the purple and dark green events:
![image](https://user-images.githubusercontent.com/59242420/130262971-6f45e131-1295-42c5-8a50-f630f0d4fcf9.png)

Highlighted events have similarly low readability:
![image](https://user-images.githubusercontent.com/59242420/130263100-619038d6-3e1d-45d0-bd8b-178ced4c64a6.png)

Buttons are darker than ideal in light mode, making them somewhat unreadable:
![image](https://user-images.githubusercontent.com/59242420/130264778-1591bd97-0ae5-40b6-95db-ea4de6431ffa.png)

White icons are used in the light theme, leaving us with rather low contrast:
![image](https://user-images.githubusercontent.com/59242420/130264651-fde6e8af-5d2b-4edd-9a99-83729e3df3a2.png)

**To Reproduce**
1. Use a light Godot editor theme
2. View and select events in Dialogic's timeline editor

**Expected behavior**
n/a

**Screenshots**
As above

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.3
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**
n/a

**Possible fixes**
For the punctuation within the text event, a dark text colour should be consistently used.

For all of the other issues, there should ideally be a set of light background colours for use with light mode, and the current light icons should have dark variants. This would allow for dark text and icons to be consistently readable against the light backgrounds.

Alternatively, since the backgrounds appear to be partially transparent, they could all be changed to be completely opaque, and light text could be used against them. This would provide a consistent appearance with the existing readable dark mode.

**Comment by Jowan-Spooner** [comment]
Thanks for the great report. Only thing I can say is that the styling of selected events was already changed in 1.3Wip. They now only have a blue outline and their normal background.

**Comment by Jowan-Spooner** [comment]
Hey @Lunadyn I tried to tackle some of the described projects in the PR #502. I think the only thing missing are the darker icons. If you are satisfied with the rest of the changes, then I'd like to close this in favor of a new issue that's just about the icons. Let me know when you were able to take a look!

**Comment by coppolaemilio** [comment]
dark icons will be hard because we would most likely have to make them again... but if needed I can make them

**Comment by Jowan-Spooner** [comment]
yeah I know. That's why I left them out of the PR. Sadly we cannot just modulate the icons of the buttons

**Comment by coppolaemilio** [comment]
I know, we might need to submit that on a PR to the Godot Engine itself, so that we can modulate icons, but doubt it will be easy to get on there
