### ISSUE TITLE
A default theme should be created and visible on new projects

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#477]
I see many people using the default settings and not knowing that they can modify things, so I believe a default theme should be visible from the start. That way it will be easier for people to discover the theming functionalities.

**Comment by Jowan-Spooner** [comment]
This would also pretty much solve #466.

**Comment by zaknafean** [comment]
There is room for debate on when this should occur. My solution copies the default-theme.cg found in **addons/dialogic/Editor/ThemeEditor/** and put it in the themes folder when the themes folder is created. Code looks like this:

![image](https://user-images.githubusercontent.com/7741797/133266771-10c77eb0-457c-42ad-af1a-cf7e0dd674be.png)

and results in 

![image](https://user-images.githubusercontent.com/7741797/133266841-53ece0d0-5603-47e2-9823-a44e60a2d18a.png)

Pull request will be coming up shortly
