### ISSUE TITLE
The root of documentation folders should not be selectable.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#484]
I like the idea, but it doesn't make a lot of sense to have those pages:

![image](https://user-images.githubusercontent.com/2206700/132135891-dda08ff3-0f59-4415-adc2-1cb8fa2592d3.png)

I like the fact that there is an index, but it feels very unintuitive and most of the time you are only repeating content that could live somewhere else.

**Comment by Jowan-Spooner** [comment]
This was just solved by #485
