### ISSUE TITLE
Add a way to change the position of the choice buttons.

### ISSUE THREAD

**Issue by BenjaTK** [coppolaemilio/dialogic#493]
**Is your feature request related to a problem? Please describe.**
It's annoying how the choice buttons have to be in the center of the screen and can't be changed. 

**Describe the solution you'd like**
An offset variable or a choice position variable would help a lot.

**Comment by Jowan-Spooner** [comment]
While I like the idea of adding some settings to the theme editor, this would definitely be somewhat solved by #449.

**Comment by coppolaemilio** [comment]
Added more options for the choice buttons :) you can now set offsets and anchor positons. Closing this
