### ISSUE TITLE
Having an issue with accessing definition variables.

### ISSUE THREAD

**Issue by specialagentsoftware** [coppolaemilio/dialogic#494]
I have created a defined variable. However, when I try to set or get the variable within the dialog editor there is an error at line 84 of DialogicSingleton.gd. It is in the set_variable_from_id function. TargetDef is set from a loop of current_definitions. For some reason that seems to be empty. If I access default_definitions then the values are there. I have also used the dialogic singleton method set_variable successfully via code to set the variable but the editor does not seem to be able to set or get the values for defined variables. I am on the latest release of 1.2.5 and Godot 3.3.

**Comment by specialagentsoftware** [comment]
does the same thing with Glossary entries.

**Comment by Jowan-Spooner** [comment]
This is the same problem originally described in #388. 

Maybe you have a Dialogic.start() with reset_saves set to false? This might be part of the problem. 

I doubt the same is in the WIP branch as the DialogicSingleton was removed.

**Comment by specialagentsoftware** [comment]
I was passing false everywhere I had tried it when I was getting the error.  I changed it to pass true and I no longer get an error and I can retrieve the value. I just can't set it.

**Comment by specialagentsoftware** [comment]
I got it to work. Essentially I needed to only send reset true when I initialize the value the first time.. any other time I need to pass false so it's not over-written and cleared out. I do not know what your procedure is so I will leave this open, but feel free to close it if you want.

**Comment by specialagentsoftware** [comment]
Is there any documentation for setting and saving definitions?

**Comment by Jowan-Spooner** [comment]
Hey @specialagentsoftware I saw that noone answered you yet. There is little documentation about that. Also the saving system is being reworked big time for 1.3. There will be better documentation in the next version!
If you need help at anything specific, you can try to get help on the discord server though.
