### ISSUE TITLE
Has condition in choices does not work.

### ISSUE THREAD

**Issue by BenjaTK** [coppolaemilio/dialogic#495]
## The problem

**Describe the bug**
When adding "has condition" in a choice node, it will never show the choice, even if the condition is true.

**To Reproduce**
1. In a choice node, enable "Has condition?"
2. Choose a value and is [ whatever option you want ] and the value set it to something that would be true
3. Play the timeline
4. The choice won't appear

**Expected behavior**
Well, as expected, if the condition is true I assume the choice should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/73806216/132616329-26e264e7-82bb-4913-9f07-d5b509be5b2d.png)
![image](https://user-images.githubusercontent.com/73806216/132616337-cb5da254-a1fb-4209-9aed-712ec9063283.png)
![image](https://user-images.githubusercontent.com/73806216/132616357-f03e4150-6208-4794-a56d-cc209cedbb77.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**

Can't figure it out

**Possible fixes**

idk what could be happening.

**Comment by coppolaemilio** [comment]
It is definitively a bug. Hopefully it won't happen in 1.3, but won't be releasing any other 1.2.X versions, so you will have to upgrade eventually.

**Comment by Jowan-Spooner** [comment]
if when you instance your dialog reset_saves is set to false the value might be loaded as something different then 1 every time from the save.
So if you are instancing with reset_saves = false then I would suggest trying it with reset_saves = true

**Comment by Jowan-Spooner** [comment]
not sure if it's a problem with 1.2.5 but it works for me in 1.3. Maybe someone else can try it out.

@BenjaTK did you try out what I wrote above?

**Comment by coppolaemilio** [comment]
Same, it is working for me. Can't reproduce.
