### ISSUE TITLE
Documentation entries can be "renamed" by double clicking on them

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#500]
The rename dialog shows up and all but ofc nothing happens after you press enter 😅

**Comment by Jowan-Spooner** [comment]
Found out why :-/ 
Turns out someone (probably I) wrote the falses as strings... 
![grafik](https://user-images.githubusercontent.com/42868150/132704230-13c03df0-794d-4ccf-96e9-5387fa4e0c68.png)

**Comment by Jowan-Spooner** [comment]
Will fix this within the next docs update
