### ISSUE TITLE
Parser Error: Unique global class "DialogicBackgroundMusic" in BackgroundMusic.gd already exists.

### ISSUE THREAD

**Issue by besnarda** [coppolaemilio/dialogic#508]
## The problem

**Describe the bug**
When launching Dialogic for the first time in a void project, I had this bug
`Parser Error: Unique global class "DialogicBackgroundMusic" already exists at path: res://Addons/dialogic/Nodes/BackgroundMusic.gd`
Making the game crash

**To Reproduce**
Copy Dialogic in a folder called Addons (the capital letter seems important), create a minimal timeline and add a theme. Launch DialogNode

**Expected behavior**
The addons is not crashing

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.2
 - Dialogic Version: 1.3

## Solutions

Rename Addons folder to addons.

**Comment by AnidemDex** [comment]
Can you please add more information? Maybe the console log?

Your issue seems related to a duplicated file resource inside Godot, and can be easily solved restarting the editor or restarting the plugin after cleaning custom classes

**Comment by besnarda** [comment]
> Running: C:/Users/alban/Documents/ALBAN/GODOT/Godot_v3.3.2-stable_win64.exe --path C:/Users/alban/Documents/ALBAN/GODOT/TESTING2 --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 3452 --position 448,240 res://Node2D.tscn
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL ES Batching: ON

>SCRIPT ERROR: GDScript::reload: Parse Error: Unique global class "DialogicBackgroundMusic" already exists at path: res://Addons/dialogic/Nodes/BackgroundMusic.gd
          At: res://addons/dialogic/Nodes/BackgroundMusic.gd:2
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
Running: C:/Users/alban/Documents/ALBAN/GODOT/Godot_v3.3.2-stable_win64.exe --path C:/Users/alban/Documents/ALBAN/GODOT/TESTING2 --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 3452 --position 448,240 res://Addons/dialogic/Dialog.tscn

I really think this is due to my addons folder being named Addons, renaming the folder has completely solved the problem.
