### ISSUE TITLE
Button related Error when using the Dialog Node directly

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#518]
## The problem

**Describe the bug**
Something broke in the choice/button selection when you use a Dialogic Node directly in a scene.

**To Reproduce**
1. Create a new scene
2. Add a Dialogic Node to the scene
3. Observe error, nothing further is needed to see it. It spams indefinitely

**Expected behavior**
N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/7741797/133146565-cbf5264d-9db1-42c4-b76f-961c15a1d2bd.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.4 beta
 - Dialogic Version: 1.3 'nightly'

## Solutions

**Workaround**
N/A

**Possible fixes**
It's pretty clear where it runs into an error, I assume this is related to the new button  adjust ment code as my build in my main project from a day or two ago doesn't have this issue, just the sync'd stuff from today.

Notably this issue does not occur if you use the Dialogic.start method to run Dialogic, only when you use the node manually.

**Comment by coppolaemilio** [comment]
Thanks for the heads up! I'll try to fix it

**Comment by coppolaemilio** [comment]
I think that the node you drag and drop as the dialogic node should be a different one now. One that spawns the regular Dialogic.start function instead of the node itself. I can't reproduce this issue on any of my projects but I will see what I can do with the screenshots and adding extra checks to those sections

**Comment by zaknafean** [comment]
I can no longer seem to recreate this. Gonna close this cuz I think it may have been something I mangled locally during dev work.
