### ISSUE TITLE
Dialogic dialog fills whole screen with small resolution

### ISSUE THREAD

**Issue by AJ08Coder** [coppolaemilio/dialogic#519]
## The problem

**Describe the bug**
When playing the dialog, it covers the entire screen because of the low project resolution

**To Reproduce**
1. Create a dialogic
2. Change project resolution to a low setting for pixel art
3. play the scene

**Expected behavior**
The dialog pops up without filling the entire screen

**Screenshots**
Without Dialogic:
![image](https://user-images.githubusercontent.com/29516950/133184913-89aaee54-2ba6-4779-848c-8ec749fe174e.png)
With Dialogic:
![image](https://user-images.githubusercontent.com/29516950/133184991-c7dfe3ab-a946-478d-b867-1b54153ba32c.png)
Project resolution:
![image](https://user-images.githubusercontent.com/29516950/133185041-510588ac-0acc-44be-bfa2-3f2d8a20c553.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.3.2
 - Dialogic Version: 1.3

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by coppolaemilio** [comment]
You have to create a theme and set a smaller font size and dialog size
