### ISSUE TITLE
Creating a character with the same name as a definition breaks the definition for other uses

### ISSUE THREAD

**Issue by WaitingForAnon** [coppolaemilio/dialogic#525]
## The problem

**Describe the bug**
Creating a character with the same name as a definition breaks the definition for other use

**To Reproduce**
1. Go to the Dialogic tab in Godot
2. Create a new definition, give it any name and any value. (ex: foo -> testDefinition)
3. Create a new character, give it the same name as the definition from the previous step but within square brackets. (ex: [foo])
4. Create a Timeline with a Text Event. 
5. Set the character for the event to the character from the previous step (ex: [foo])
6. Include the definition somewhere in the text for the event (ex: [foo])

**Expected behavior**

**Screenshots**
[screenshot 1](https://cdn.discordapp.com/attachments/790247120615243796/889276531153723433/definitionIssue0.PNG)
[screenshot 2](https://cdn.discordapp.com/attachments/790247120615243796/889276838931726386/definitionIssue2.PNG)
[screenshot 3](https://cdn.discordapp.com/attachments/790247120615243796/889280296728547428/definitionissue3.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.2.3
 - Dialogic Version: 1.3

## Solutions

**Workaround**
Ticking the "Different display name" for the character and leaving the field for the display name blank seems to fix the issue. I don't understand why though. That, however, also seems to introduce another issue.

**Possible fixes**
It seems like color-coding is added to the text containing character names. When the text reaches _insert_variable_definitions(), the text that used to contain [name] no longer contains [name], but rather [[color=#ffffffff]name[/color]] for example.

I don't really know how to RegEx, but I managed to make something using some online tool:

`func _insert_variable_definitions(text: String):`
`    var final_text := text;`
`	var regex = RegEx.new()`
`	for d in definitions['variables']:`
`		regex.compile("\\[(\\[color=\\#[a-z]{8}\\])?" + d['name'] +  "(\\[/color\\])?\\]")`
`		for result in regex.search_all(final_text):`
`			var start = result.get_start()`
`			var end = result.get_end()`
`			final_text = final_text.substr(0, start) + d['value'] + final_text.substr(end, final_text.length() - end)`

**Comment by Jowan-Spooner** [comment]
Hm... What behaviour would you expect when naming a character EXACTLY like a definition and putting brackets around it? Yes, dialogic will find the name and color it (if the setting is enabled) and that makes the definition replacement (which happens much later) impossible. 

I'm not against implement your check, but I think that this is a problem that can be easily avoided. Or is there anything I'm missing?

**Comment by Jowan-Spooner** [comment]
I've tried to fix #651 with my new pr #681. It could be that it fixed this as well.

**Comment by Jowan-Spooner** [comment]
I think this is fixed, at least from my test everythin worked like expected. If that's not the case, please just reopen this and let us know.
