### ISSUE TITLE
A way to make text automatically skip

### ISSUE THREAD

**Issue by WaterExpensive** [coppolaemilio/dialogic#528]
Hello there,
I would like a feature where they would be an option when I input text into dialogic, it will skip automatically without pressing a key
like, instead of pressing the enter key to progress to the next dialogue box, it will progress automatically from there
I hope I got the explanation right

**Comment by Jowan-Spooner** [comment]
You can add the [nw] (no wait) tag to your texts and it will autmatically continue after all text is displayed. You can also set the wait time (in seconds) like this: [nw=5]

**Comment by WaterExpensive** [comment]
> You can add the [nw] (no wait) tag to your texts and it will automatically continue after all text is displayed. You can also set the wait time (in seconds) like this: [nw=5]

oh, I see, so there's away.
but I'm not sure how to add these tags to my text, do you mind helping good sir?

**Comment by Jowan-Spooner** [comment]
Of course I don't mind. You will have to just type it into the line you want to automatically continue. 
![grafik](https://user-images.githubusercontent.com/42868150/134128400-84e51eb3-6dc2-4ef9-a5bc-725a1c74fce6.png)
It won't be visible in the game!

**Comment by Jowan-Spooner** [comment]
Let me know once (or if) you get it to work, like you want it, so I can potentially close this issue.

**Comment by WaterExpensive** [comment]
Thank you very much Jowan, you can close this issue
And thanks once again, may God be with you

**Comment by Jowan-Spooner** [comment]
Great! [Here you can find some more info about the options of the Text Event](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Documentation/Content/Events/000.md)

Good luck with your project!
