### ISSUE TITLE
Way to resize text in Dialogic.

### ISSUE THREAD

**Issue by WaterExpensive** [coppolaemilio/dialogic#532]
Hey there,
I really like your plugin good sir, but for some reason, there isn't an option to resize text size in Dialogic.
but when I use custom fonts it becomes so much smaller and I can't make it larger because there isn't an option
I think it would be neat to have that option

**Comment by zaknafean** [comment]
Dialogic uses resource files to handle fonts, which not everyone is completely familiar with. Once a font resource is set up, you can adjust the font size within dialogic. I won't go into too much detail but here's a quick crash course. Possibly we can put this in docs or FAQ later.

1. Find online or create a font you want to use!
2. Create a new font resource with this font (Inspector -> New -> Dynamic Font)
![font-resize-example](https://user-images.githubusercontent.com/7741797/134533505-4768b9dc-38b8-44f6-b706-85aa3c3fd1c4.gif)
3. Load the font like you would in other areas in Godot
![image](https://user-images.githubusercontent.com/7741797/134533689-8c23f9b5-45d2-4854-bf80-51dd0539d281.png)
4. Adjust the size, color, etc
![image](https://user-images.githubusercontent.com/7741797/134533815-cd88904d-6167-46a3-a31d-ec493e5abac7.png)
5. Hit the save icon and **Save As...** the new resource somewhere
![image](https://user-images.githubusercontent.com/7741797/134533929-7e820d76-852f-450a-acd8-7bedd3d7dbee.png)
6. Select the font in dialogic! If you find it needs to be a different size, you can hit the pencil icon to bring up the resource editor in the inspector at any time
![image](https://user-images.githubusercontent.com/7741797/134534094-c58b86ec-232f-4b6e-b27c-9e68c3acce45.png)

**Comment by zaknafean** [comment]
Re-reading your question, I think all you really need is to 'hit the pencil' next to the fonts, go to settings and adjust the size of the font. My images above should show that, but let me know if you need any further help.

**Comment by WaterExpensive** [comment]
Oh my god, you don't know how many hours I've been stuck with this problem. thank you very much, good sir!
but one question though, a bit unrelated:
how do I make text cut off right instead of clipping through the window?
for example, this is what happens when I type a sentence:
![image](https://user-images.githubusercontent.com/34092413/134539142-79421fc9-a2cd-478c-b0b7-eb29578b61e0.png)
The original text says "Stanley works for a company in a big building where he was employee number 427" (Test text to test out your solution)
for some reason it goes through the screen, there was a way to get around it by switching to the stretch mode in project settings->window but I would rather like it to be in 'Keep' mode
is there a way to get around this?
and thank you in advance!!

**Comment by zaknafean** [comment]
Off hand I think you need to adjust the themes dialog box. 
![image](https://user-images.githubusercontent.com/7741797/134540053-2cfa7558-861f-4b0b-9e0f-1a4da952a773.png)
Adjusting the box size to be smaller than the screen size will probably fix this

**Comment by WaterExpensive** [comment]
Ah, I saw that option but I thought it was for the box in the background!
thank you very much, good sir. I'm quite glad about the result
![image](https://user-images.githubusercontent.com/34092413/134542023-e856d5ca-d6ce-4ac0-aa3d-41f32f445768.png)
Finally got it right!
I require no longer help, you can close this case if you may
and thanks once again for your help, God bless!

**Comment by Jowan-Spooner** [comment]
Great you got it to work. For future questions consider asking for help on [emilios discord server](https://discord.com/invite/VwMSSsbhkh). I know in this case you didn't know the feature existed, but if you need any further help, that's the best place to get it!
