### ISSUE TITLE
Create new custom event button

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#533]
There should be a dialog from the settings or somewhere that when you click on it and you fill a minimal list of items (kinda like when you create a plugin with godot) Dialogic will create the boilerplate folder with your custom event. So it would take something like:
- [text input] Event name
- [text input] Directory name (suggest based on Event Name)
- [text input] Event id (suggest based on event_name)
**[Create] [Cancel]**

After pressing on [Create] it will copy/paste the template, modify the script name and set up stuff like that. This will make it easier to start creating a custom event.

**Comment by Jowan-Spooner** [comment]
The tool was added with #553.
