### ISSUE TITLE
Allow waiting and changing text speed mid-sentence

### ISSUE THREAD

**Issue by maksutheam** [coppolaemilio/dialogic#537]
I saw this mentioned in the Dialogic 1.2 highlights devlog, but I didn't see an issue about it here, so I thought I'll write one up just in case.

**Is your feature request related to a problem? Please describe.**
The biggest reason as to why I'm not using Dialogic right now is that I can't pause or change the speed of the text mid-sentence. How long a character takes to say their line, or the delivery of the line in other words, is _really_ important in communicating the meaning of the message when all you have is a textbox. If a character has a hard time saying something, I could use slow text and a lot of pauses to communicate that. If text appears too slow or fast, it can ruin a good joke or make an emotional moment fall flat. 

Here's an example. See how the characters pause their dialogue for half of a second after a comma or a punctuation? And how "Butz" goes from feeling sad to desperate by slowing down and speeding up his text, despite never changing his portrait? And how the pauses between the words at the end makes the reveal more impactful? With the current Dialogic version, I couldn't replicate this.

https://user-images.githubusercontent.com/60304828/134929281-9a6d0220-071d-4831-9a8e-7fdfb31cd004.mp4

**Describe a solution**
For example, if I had a text event that contained 
`[speed=1]What!?[speed=20] What's wrong, Larry?`
the `What!?` would appear at a speed of 1, and the text after that would appear at a speed of 20. You know, left to right.

An alternative to this is right to left. In that case, I would have to write
`What!?[speed=1] What's wrong, Larry?[speed=20]`
But I personally think left-to-right is more intuitive.

**Describe alternatives you've considered**
I could just separate each pause and text speed change into a different line. But then the player would have to manually skip a lot, and it would limit how much text I could show on screen.

**Comment by Jowan-Spooner** [comment]
I agree. This has been asked for many times. Same goes for little pauses mid-sentence.

Just so you know (not as a solution, just a usefull fact), you can use the [nw=1] tag to automatically make the dialog continue after 1 second.

**Comment by Jowan-Spooner** [comment]
Okay this is implemented in the current WIP version (main branch on github). There is now a [pause=X] command to pause at that point for X seconds. Also the [speed=X] command doesn't affect the full event anymore, only what comes after it (so speed can change as often as you want during your text event.

I'll hopefully implement automatic pauses for special symbols soon.
