### ISSUE TITLE
Add some vanity stats on this screen (or find a purpose for it)

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#543]
![image](https://user-images.githubusercontent.com/2206700/135248377-ab134dc9-7383-4c44-b77f-a6ba57bffb50.png)

It would be nice to have something here, I thought about adding stats like: Character counts, timeline counts, or stuff like that. But any idea is welcome for discussion :)

**Comment by Aurora-Eluvia** [comment]
Maybe instead of vanity stats, it could be a visual representation of whatever you have? A kind of GUI version of the file structure.

**Comment by coppolaemilio** [comment]
This page doesn't exists any more
