### ISSUE TITLE
Crash when you change a theme after a question branch

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#555]
## The problem

**Describe the bug**
When changing themes after a choice, godot chokes and crashes

**To Reproduce**
Steps to reproduce the behavior: See screen shot

But the key seems to be set a theme, make a choice, change the theme

**Expected behavior**
Theme changes and timeline continues

**Screenshots**
![image](https://user-images.githubusercontent.com/7741797/135736722-044897b4-e5d2-4017-bf65-237b9307e9c5.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.4-beta4
 - Dialogic Version: nightly

## Solutions

**Workaround**
Don't change theme after a choice, but that may not always be a possibility

**Possible fixes**

In my test build (which isn't using todays merge), I crash in the answer_question function due to 'i' being null. While this isn't a fix, it may give a clue as to whats going on.

![image](https://user-images.githubusercontent.com/7741797/135736787-334aa0c7-9398-42ce-b39e-b6fa901b6515.png)

Note, this bug seems totally reproducible out of the regular 'nightly' so it isn't related to my timeline code directly,

**Comment by coppolaemilio** [comment]
@zaknafean Pushed a potential fix to this one (commit: https://github.com/coppolaemilio/dialogic/commit/02867068bd528bf1cd73ed382e8abebd15084a0c). Can you test again and let me know if it is fixed?

**Comment by zaknafean** [comment]
Blah sorry. Looks like the fix is causing some weird error spam...

![image](https://user-images.githubusercontent.com/7741797/135896525-4196c0c7-f926-4840-9adb-160bc758f7d4.png)

This is after proejct restarts etc. You seeing it too?

**Comment by coppolaemilio** [comment]
Can't reproduce this one 🤔 @zaknafean

**Comment by zaknafean** [comment]
Will try a fresh pull and see if it persists

**Comment by coppolaemilio** [comment]
at least that error will make it easier to find the true fix and not this ugly hack

**Comment by coppolaemilio** [comment]
it seems to be here: https://github.com/coppolaemilio/dialogic/blame/02867068bd528bf1cd73ed382e8abebd15084a0c/addons/dialogic/Nodes/DialogNode.gd#L651

**Comment by coppolaemilio** [comment]
So, the fix to the error is because of the yield. I did a timer node that doesn't get freed so it is not reporting the error again. Let me know if it persists!

**Comment by zaknafean** [comment]
That looks like it did it! Closing again for real this time.
