### ISSUE TITLE
Replace the yield timers with $DialogicTimer when possible

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#556]
I found that a lot of people online are complaining that yield timers broke their code but it never did now until recently.
[example 1](https://godotengine.org/qa/76800/resumed-function-after-yield-but-class-instance-is-gone) [example 2](https://godotengine.org/qa/90988/how-can-i-wait-until-the-end-of-a-frame-to-continue-a-function)

So, whenever possible the $DialogicNode should use its new $DialogicTimer node to perform the waits/yields and avoid this particular error.

**Comment by Jowan-Spooner** [comment]
I've made a pull request that fixes another place where get_tree().create_timer() was used. I think that is all of them tho, except the ones in the editor where we obviously cannot use the $DialogicTimer.
