### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by KaminskiDaniell** [coppolaemilio/dialogic#565]
**Describe the solution you'd like**
I would like to make translation to Polish language, but I'm not sure if I do this in a .csv file. Could you please help me? I will be very gratefull :)

**Comment by Jowan-Spooner** [comment]
I'd be happy about an explanation about this too, as all my previous attempts at doing german translation failed terribly too.

**Comment by coppolaemilio** [comment]
Thanks for the offer! We are now working on the 2.0 so there isn't much to translate yet, when it is ready I'll write docs about how to contribute.
