### ISSUE TITLE
Better support for custom events. 

### ISSUE THREAD

**Issue by idontkillcoyotes** [coppolaemilio/dialogic#581]
**Is your feature request related to a problem? Please describe.**

When making custom events, you need to know exactly what variables/methods the main DialogNode script has in order to use them properly.
It would be nice to have methods on the DialogNode script to be called from a custom event script, as well as a custom class for autocompletion 

**Describe the solution you'd like**

Add new methods on the DialogNode.gd and create a new class for autocomplete.
Example:
```gdscript
class_name DialogicMainNode
```
and for events: 
```gdscript
set_waiting(value)
set_textbubble_visible(value)
next_event()
emit_signal()
```

Then from a custom event script we could just do, for example:
```gdscript
func handle_event(event_data, dialog_node : DialogicMainNode):
   dialog_node.set_waiting(true)
   dialog_node.set_textbubble_visible(false)
   #handle the event
   dialog_node.set_waiting(false)
   dialog_node.set_textbubble_visible(true)
   dialog_node.next_event()
```

**Comment by Jowan-Spooner** [comment]
I'm currently working on this and am open for suggestions what would be nice, but I think some of these don't need extra functions. In the example script `dialog_node._load_next_event()` is already explained, also dialog_node.emit_signal("dialogic_signal", "text") wors already too. 
I like the `set_textbubble_visibility()` one, and also wanted to add the ability to react to user input, so I've created the action_input signal that will be emitted everytime the input action is performed.

**Comment by Jowan-Spooner** [comment]
I will close this, as it is very far from the current state of dialogic. Also due to the introduction of subsystems as classes there are much more exposed and easily accessable methods now. The only thing that is missing is the proper documentation (which would also be built-in) of those classes/methods.
