### ISSUE TITLE
Supporting line breaks within choice boxes

### ISSUE THREAD

**Issue by f2si** [coppolaemilio/dialogic#593]
**Is your feature request related to a problem? Please describe.**
For the majority of my game, I have rather long pieces of text in my choice boxes, and find myself in dire need of line breaks.

**Describe the solution you'd like**
Supporting line breaks within the choice boxes :)

**Describe alternatives you've considered**
Using a custom button scene instead? But I don't think that that would be worth the hassle just for a simple line break, and the choice boxes otherwise fit my needs perfectly, so it would be super helpful if it could just be implemented directly into the choice boxes.

**Comment by Jowan-Spooner** [comment]
I think the only way to achieve this is by making the text of the button a label instead of using the built in text of the button class. This means a bit of work manually doing the hover changes, etc. Not sure if this will be in 1.4 to be honest. But if anyone want's feel free to do so of course.

**Comment by Jowan-Spooner** [comment]
Alright little update on this: Because godot 4 buttons support this it's just a matter of how you enter them. 
We could either allow for multiple lines in the text box or use something like [br] or \n (and replace that with a line break).
