### ISSUE TITLE
Focus style for buttons

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#597]
I'm thinking of adding an arrow on the buttons that have focus, something like this:
![image](https://user-images.githubusercontent.com/2206700/138089579-93879bb5-694c-49ba-9883-b726d1ba1739.png)

So, customization options would be:
- one arrow on one side
- one arrow on each side
- border style

As @zaknafean said on discord:

> Exposing a signal for that would also allow people to make their own thing
> On_choice_focus(button)
> Then you could make a whatever to customize it
> Or add sfx etc

**Comment by Aurora-Eluvia** [comment]
Absolutely would love a choice indicator.

Should also have the option to animate it, I think.

It would be nice if you could have the option for the choice arrow to "jump" to the next choice or tween to it, with a chance to set different tween parameters.

**Comment by thebardsrc** [comment]
This is something that can be implemented in the actual scene for the Style itself in 2.0 so I'll mark this one as completed
