### ISSUE TITLE
Hybrid Skills

### ISSUE THREAD

**Issue by Ailurus-F** [coppolaemilio/dialogic#599]
**Problem**
Actually within Dialogic framework we can only do simple skills through Set Values events.
Though it is a very common and useful thing in Table Top RPGs to deduce skills through a calculation (most often an addition) of basic characteristics (strengh, dexterity, intelligence, charisma etc) with capacities (athletism, brawl, melee, etc). We can achieve such a thing by coding it outside of Dialogic's framework, but as known most visual novels creators are writers, graphic artists, not coders, and it would enrich a lot their ability to generate subtle skills system adding depth to their game.

**Solution**
Allowing to deduce a skill based on calculation calling several simple values priorly determined.
For exemple writing in value field : [value1]+[value2]+...

**Additional context**
It would make a lot of sense to find this tool (plus creation of simple values in order to create basic characteristics and capacities) within the character editor.

**Comment by coppolaemilio** [comment]
This concepts are outside of the Dialogic scope and is something that should be coded per-game basis. It would be nice to provide tools to create this kind of systems but it might be better to just allow for Dialogic Plugins to be a thing and allow for this kind of upgrades. Closing the issue for now.
