### ISSUE TITLE
Hard to find plugin when searching for "dialogue"

### ISSUE THREAD

**Issue by viniciusgerevini** [coppolaemilio/dialogic#60]
When I was first looking for dialogue solutions this never appeared in my searches, mainly because all docs use the word "dialog" and I was looking for "dialogue". (i.e search for "dialogue" in Godot's asset library)

Both spellings are correct, but maybe if you find a way to include the second word somewhere you may improve your discoverability.

Nice work, though.

**Comment by coppolaemilio** [comment]
Thanks! I'll try to improve the SEO when the v1.0 is released, thanks for the tip!
