### ISSUE TITLE
Move the timeline editor new node buttons to an external panel

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#603]
Maybe instead of having the new events buttons inside the same center view as the timeline is a bit too crowded for a small screen. Moving it to a panel (like the inspector) could free some space on the screen.

**Comment by Jowan-Spooner** [comment]
But isn't it easier to use godots built in "Distraction Free" mode, that expands the center view? For me that always made enough space and a nice way to edit my timelines.

**Comment by coppolaemilio** [comment]
It might be, but at the same time I feel like: 
1. No one uses it
2. We can take advantage of already existing parts of the editor (for instance the file system, or the signals)

I also remember being super tired when I created this issue, so 🤷🏻‍♂️

**Comment by coppolaemilio** [comment]
So, this is already the case with the filesystem, but for the buttons I think they should stay in the editor. Closing!
