### ISSUE TITLE
Use new types for event instead of a dictionnary in the code

### ISSUE THREAD

**Issue by astrale-sharp** [coppolaemilio/dialogic#608]
**Is your feature request related to a problem? Please describe.**
Not really a problem, this is more an idea in sake of making the code more robust and less error prone.
Currently, a dictionary used for events could have typos in the keys or wrong types in the values which would lead to non trivial error at runtime.

**Describe the solution you'd like**
Instead of having a dictionary, we could have 
An Event type  (extends reference) 
Subtypes (extending Event) for every type of event
example : 
```gdscript
class DialogicTextEvent:
    extends DialogicEvent
    var character := ""
    var text := ""
    func _init(...):
        ... # possibly some sanity checks, error on creation is is invalid
    func has_character(...):
        return self.character != ""
```

Pushing things further we could use one of the class abstraction of godot-next but i have not investigated that yet ;)

Its quite a bit of work but i would be interested in helping ~~

Was that clear? what do you think?

EDIT:
plus instead of checking the type by matching against "dialogic_001", the neater syntax `event is DialogicTextEvent` could be used.
Also, if performance is an issue, this might improve it a little?

**Comment by coppolaemilio** [comment]
The main idea behind checking against string names is to make a better integration with custom events. The issue with classes is that they have to be previously declared to be interpreted by the checks we need to have. So if you have a custom event it is better to check against strings that having to create so many classes and sub classes. 

Unless I'm missing something I don't think that we would be creating those kind of event classes at the moment unless there is a strong argument for it. 

Thanks for the issue! I'll leave it open just in case someone wants to pitch in or if you have any extra considerations

**Comment by astrale-sharp** [comment]
I see your point, although there could be a `DialogicCustomEvent` class with a dictionary field, which would offer the same integration for custom event in my opinion!
The idea is, since everything is represented as a string (even the type of errors) a typo in the code of dialogic or the user could lead to nonsensical behavior and I'm a little shaky about that (being paranoïd i guess).
It's a quality of life improvement, makes the code more sound and stuff. But i get that its also extra work for no added feature (although i'm here to help ;) ).
Was that convincing? 😇

**Comment by AnidemDex** [comment]
This can be related to https://github.com/coppolaemilio/dialogic/issues/10 (not resources, just the part to serialize the data to a class).
