### ISSUE TITLE
[Bug] Using a scene for a background

### ISSUE THREAD

**Issue by Abirthbyanothername** [coppolaemilio/dialogic#610]
I think it's a bug? But maybe I'm just doing it all wrong. My issue is: I was trying to use an animated scene I have in my godot project for a background in the timeline (well, I was thinking about using several ones across the whole timeline). But I don't know why, when I run the dialogic scene, and it loads that part, the debugging tool scapes me to the editor with this error message: "Invalid call. Nonexistent function 'interpolate_property' in base 'Nil'." And it so opens background.gd.

The dialogic scene keeps running, apparently. It keeps the player with said scene open, even when I can't see it. 

![image](https://user-images.githubusercontent.com/47704539/139774422-43c42615-9054-476b-a69b-512ce3c74c47.png)
![image](https://user-images.githubusercontent.com/47704539/139775193-2ede63fd-cb47-43c7-8df9-372d27a877d0.png)
![image](https://user-images.githubusercontent.com/47704539/139775259-925c91a6-ec22-4db4-b7f0-de1d2ac4a125.png)

Windows 10 OS.
It works fine if I change the background asset for a .jpg file.

I'm so new to this stuff I don't know if I'm just failing at some basic step. But just in case it's an actual bug, here I'm. Also, in case I'm doing something the wrong way, any help is welcome.

**Comment by Bellusterra** [comment]
It does appear to be a bug, I'm getting the same result.
