### ISSUE TITLE
Portraits use the portrait specified in the character join node, or default if not specified

### ISSUE THREAD

**Issue by Animus-Surge** [coppolaemilio/dialogic#611]
## The problem

**Describe the bug**
When specifying a portrait in either the question or text nodes, the portrait will not show, and instead be the portrait specified in the character join node, or the default.

**To Reproduce**
1. Create a character with multiple portraits
2. Create a timeline where the portraits change a bunch

**Expected behavior**
I have three portraits in my character (so far), and when the character joins its set to the default. Then the character asks a question and has a confused face that should be showing, but it instead keeps using the portrait specified in the join node.

**Screenshots**
Node graph of the timeline. The default portrait is used in the beginning, and when the player selects the "Hey there!" option in the question, the portrait should change to the confused portrait.
![Capture](https://user-images.githubusercontent.com/22083792/140081702-049ebaa5-e2fc-437c-bc94-36fec45e1f8f.PNG)
Confused portrait that should be showing
![Capture2](https://user-images.githubusercontent.com/22083792/140081707-e2b19fa3-26ad-4ab2-8abc-26174aaa8a2c.PNG)
Default portrait
![Capture3](https://user-images.githubusercontent.com/22083792/140081709-aaf8c20f-0920-40cb-b392-f769d61ce6e2.PNG)
This is correct, showing the default portrait in the beginning
![Capture4](https://user-images.githubusercontent.com/22083792/140081711-5760dd0d-731b-48d6-9a74-114b4b5a1312.PNG)
This is incorrect. It should be showing the confused portrait, not the default portrait. (I selected the "Hey there!" option in the previous screenshot)
![Capture5](https://user-images.githubusercontent.com/22083792/140081713-84a25769-d05c-4366-b25f-48911f48c284.PNG)

**System (please complete the following information):**
 - OS: Windows 10 Enterprise x64
 - Godot Version: 3.3.4
 - Dialogic Version: 1.4-dev

## Solutions

**Workaround**
I don't even know where to begin, as I've been using dialogic for only a day now.

**Possible fixes**
I've made a similar system with portraits (albeit without an editor like what you have here), and it could be that the nodes don't call a function or modify the texture of the portrait.

**Comment by Jowan-Spooner** [comment]
Hey @Animus-Surge, thanks for letting us know of the issue. I've tried to fix it with the PR #612. Maybe you can try the main branch out? Make sure to use version controll or make a backup! Hope it helps!

**Comment by Animus-Surge** [comment]
Hi, sorry for the late reply. That did seem to fix it. Thank you!
