### ISSUE TITLE
Screeneffect as an event in the timeline editor.

### ISSUE THREAD

**Issue by Nazzaroth2** [coppolaemilio/dialogic#616]
**Is your feature request related to a problem? Please describe.**
For my story i am planning on using multiple custom screen effects eg. screenshake, eyes-opening effect etc.
These effects make most sense if they affect every part of the game (BG, Characters, Textbox), so an extra general event
seems the most usefull solution, instead of parameter-effects on existing events (eg. fade-effect of background event).

**Describe the solution you'd like**
The most general solution i came up with is using shaders. Event would add a Screeneffect-Scene child to DialogNode which handles running the shader. (Similar to how background-event adds the background-scene)

Code that i have so far:
```
extends ColorRect

# lifetime seconds for effect
var effectLength = 1
var shaderEffect = load("res://shaders/screenshake.shader")

func _ready():
	# make sure Effect is fullscreen
	rect_size = get_viewport_rect().size
	
	get_material().set_shader(shaderEffect)
	
# count down lifetime of effect
func _process(delta):
	print(effectLength)
	effectLength -= delta
	
	if effectLength <= 0:
		_endEffect()

# kill effectNode to end the effect
func _endEffect():
	self.queue_free()
```
A very quick and dirty implementation for now to see if shaders are usable. Wanted to check if interest for this idea exists before i go and work on making this into an event.

**Describe alternatives you've considered**
For things like screenshake you could probably use a canvas_transform or camera2d  but i think shaders are more self-contained as there has to be no check/running animation inside the _process()-function and they are more versatile, especially for scene-transitions.

**Comment by thebardsrc** [comment]
This is implemented on #1225 by custom background scenes beyond the basic background fade
