### ISSUE TITLE
Scrollbar does not adjust for the resolution of the game.

### ISSUE THREAD

**Issue by JustDenP** [coppolaemilio/dialogic#619]
Good afternoon!
I decided to try the plugin, but immediately ran into a problem that I can not solve myself unfortunately.
Scrollbar does not adjust for the resolution of the game.

My project runs at 320x180 resolution and viewport size (1280x720).
I changed the theme settings of the plugin and so far everything looks good, except for the huge scrollbar (also would like to have the ability to replace it with my texture in addition to size control).

As far as I can see, this is the behavior of RichTextLabel itself, but it would be great if anyone knows how to fix it.

![image](https://user-images.githubusercontent.com/19192519/140577830-9e08e9e1-560c-4935-9538-26c8c03f01e9.png)

**Comment by coppolaemilio** [comment]
More customization options would be ideal, but for 2.0 this won't be an issue any more, so I'm closing this one at the moment
