### ISSUE TITLE
Bug: Attempt to call funtion 'get_width' in base 'null instance' on a null instance.

### ISSUE THREAD

**Issue by RilDev** [coppolaemilio/dialogic#62]
Good day,

I'm just starting to test Dialogic and when I tried to run it with just one test character without images, it bugged.

```
Attempt to call funtion 'get_width' in base 'null instance' on a null instance.
```
![dialogic-no-character-image-bug](https://user-images.githubusercontent.com/13135150/109508280-fabcd480-7a9f-11eb-9c75-e71af9f78a6e.png)

Adding a picture to the test character fixes the bug.

Cordially,
RilDev

**Comment by coppolaemilio** [comment]
This is not happening any more in the branch 1.0 👍🏻 
Thanks for the report!
