### ISSUE TITLE
Bug: Invalid get index 'center left' (on base 'Dictionary').

### ISSUE THREAD

**Issue by RilDev** [coppolaemilio/dialogic#63]
Good day,

So I was trying to put a character in spot "left center" and got this bug:

```
Invalid get index 'center left' (on base 'Dictionary'). 
```

The bug happens when the character is supposed to join the scene.

![dialogic-bug-character-second-position](https://user-images.githubusercontent.com/13135150/109512493-71f46780-7aa4-11eb-8b1e-aca61375f465.png)
![dialogic-bug-character-second-position-2](https://user-images.githubusercontent.com/13135150/109512504-7587ee80-7aa4-11eb-86da-f582c1579a2b.png)

Cordially,
RilDev

**Comment by coppolaemilio** [comment]
What version are you using?

**Comment by coppolaemilio** [comment]
This was supposed to be fixed in this pull request: https://github.com/coppolaemilio/dialogic/pull/52 that's why I'm asking

**Comment by RilDev** [comment]
I'm using Godot 3.2.3 stable and for the Dialogic, I installed the plugin from the assets library today.

**Comment by coppolaemilio** [comment]
Cool! I'll see if I can update the asset library version to the latest. Thanks for the reports!
