### ISSUE TITLE
Move "Single Portrait Mode" setting to the settings

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#630]
Just makes more sense there I think. Having it in the Theme under "Dialog Text", seems really not like the right place.

**Comment by coppolaemilio** [comment]
I agree that it is weird, but not sure that settings is the proper place either. I think this is something we can figure out better for Dialogic 2.0 and how we want to handle the display and settings of portraits.

**Comment by Jowan-Spooner** [comment]
I've also thought about adding another "Portraits" tab in the theme editor, because there is now also the "Dim Portraits Color" that has no place in the theme editor so far.
