### ISSUE TITLE
CPS tag for Dialogic

### ISSUE THREAD

**Issue by IntangibleMatter** [coppolaemilio/dialogic#641]
Many dialogue systems include ways to change the text speed in the middle of a dialogue, which allows the text to have more versatile expression. Dialogic, despite its complexity, seems to lack this feature.

**Describe the solution you'd like**
A special BBCODE tag which could be something to the effect of {cps=10}, or setting the text speed to 10 characters per second.

**Additional context**
Ren'py does this quite elegantly, and is documented [here](https://www.renpy.org/doc/html/text.html#text-tag-cps), if example is needed

**Comment by Jowan-Spooner** [comment]
There already is a [speed=2] tag, that will change the text speed for the current text event. With 1.4, it will also be possible to change the speed mid sentence with this tag. If you download the WIP version (main branch on github) you can already try it out.
