### ISSUE TITLE
Portrait offset should be mirrored as well

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#643]
*By Calamitous on Discord*
## The problem

**Describe the bug**
Due to the portraits sometimes working in mysterious ways, you sometimes have to add a huge offset. When you then mirror your portrait, it quickly goes off screen.

**Possible fixes**

Having the offset be mirrored as well, if mirroring is true.
![grafik](https://user-images.githubusercontent.com/42868150/143571911-f358126c-1072-48e3-a129-62f8327d0fe3.png)

**Comment by coppolaemilio** [comment]
I'll ask for a sprite to test this because I can't understand how they set up the sprites to need the offset mirroring as well

**Comment by Jowan-Spooner** [comment]
The example is somewhere on the discord server. I can send it later if I find it

**Comment by coppolaemilio** [comment]
I was able to track it down and they sent me the file they are using 👍🏻

**Comment by thebardsrc** [comment]
Need to double check that the DefaultPortrait scene handles this properly, then this can be closed

**Comment by Jowan-Spooner** [comment]
Reminder to @thebardsrc to test this ;)
