### ISSUE TITLE
Text Event with Character name in the text shows name coloured 

### ISSUE THREAD

**Issue by sshearer** [coppolaemilio/dialogic#647]
## The problem

**Describe the bug**
**Given:

1. a Character named Alys coloured in blue,
2. a Timeline with Character Join control configured with Alys, and 
3. a Text Event for Alys which contains 'Alys' in the text ...**

**...her name in the text is coloured blue.  Please see the attached screen capture.**

**Expected behavior**
**In my mind, ANY text, subject to override formatting, should just use the colour palette already set.**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows, Linux]  **Windows 10 Enterprise**
 - Godot Version:    **3.4**
 - Dialogic Version: **1.4**

## Solutions

**Workaround**

What you tried to get the feature working

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by Jowan-Spooner** [comment]
Go to the settings and disable the Color Names in Text events option.
