### ISSUE TITLE
Select multiple events in the timeline editor

### ISSUE THREAD

**Issue by Bargeral** [coppolaemilio/dialogic#65]
Allow an event in the timeline editor to become selected (focus).
 - subsequent event line clicks in the timeline editor should move focus to the new selected event.
 - Allow a contiguous group of events to become selected with a shift+click, when a first line is already selected.
 - allow non contiguous events to be added the selected events with a CTL+click
 - allow selected events to be removed from the selected events with a CTL+click

Allow all selected events to be removed from the selected group with the ESC key. IE clear the selections. 
Allow all selected events to be removed from the selected group with by clicking a blank area of the timeline editor.  IE clear the selections. 

Delete Key - If any events are selected - Prompt the user "Do you want to delete these <#>event(s)" y/n
     - on Y delete the events selected.

If one event or a contiguous group of events are selected, allow them to be moved up or down the timeline via the UP and Down arrow keys. 
If one event or a contiguous group of events are selected, allow them to be moved up or down the timeline via mouse drag. 

Any new event created with the right hand events button menu will be created immediately below the last selected event, or at the bottom of the event list (as it does now) if no event is selected.

**Comment by coppolaemilio** [comment]
> Any new event created with the right hand events button menu will be created immediately below the last selected event, or at the bottom of the event list (as it does now) if no event is selected.

This was implemented! Selecting multiple events will probably not come for v1.0 but I'm sure it will in the future.

**Comment by coppolaemilio** [comment]
I'm closing this because it is partially closed and some of the behaviours are going to be implemented as part of the shortcuts PR
