### ISSUE TITLE
Speed Tag not working - 1.4 DEV

### ISSUE THREAD

**Issue by Farabry** [coppolaemilio/dialogic#660]
Speed Tag not working - 1.4 DEV

I used speed tags on the text events, but in game it looks like this. I know is work in progress, and there may be errors but I tought this may be important to say.

Windows
Godot 3.3.2.stable

![image](https://user-images.githubusercontent.com/95051206/144175533-a7e81e91-a436-4026-bb2f-898f74555339.png)
![image](https://user-images.githubusercontent.com/95051206/144175555-a3d0ddee-9d30-4992-baa2-291afaf01b15.png)

**Comment by Jowan-Spooner** [comment]
I think it's because it has troubl finding tags at the very beginning. Have to test that tho
