### ISSUE TITLE
Dialogs don't accept mouse input

### ISSUE THREAD

**Issue by MercutioGraveman** [coppolaemilio/dialogic#661]
Signal ui_accept is only generated by keyboard.   Why isn't it generated by a mouse click, as well?

**To Reproduce**
Click on a dialog.  Observe that nothing happens.

**Expected behavior**
The dialog should proceed, as if the enter key had been pressed.

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.4
 - Dialogic Version: 1.3 and 1.4

## Solutions
This seems like a basic feature... if it requires gdscript code to wire it into Dialogic, please add that to the Step by Step Beginner's Guide.

**Comment by Jowan-Spooner** [comment]
The "action key" (badly named, agree) is a godot input action, by default the "ui_accept". You can edit what keys (or mouse buttons, or controler inputs) will trigger this action in the Godot ProjectSettings under [InputMap](https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html?highlight=inputmap#inputmap).

**Comment by MercutioGraveman** [comment]
The solution is simple and elegant.  And yet I completely missed it.  Please consider adding mouse click to those defaults, or at least mentioning it in the Beginner's Guide.
