### ISSUE TITLE
Glossary entry not visible in Question event

### ISSUE THREAD

**Issue by DasCapschen** [coppolaemilio/dialogic#663]
## The problem

When there is a Question event, and the player has to pick a choice, hovering over a glossary entry in the text does not open the glossary popup.
The popup does show up in normal text events.

**To Reproduce**
1. Create a glossary entry.
1. Create a question event. In the text include the glossary word.
2. Add a choice for the player to select.
3. Start the dialog in game.
4. Hover over the glossary word.
5. nothing happens

**Expected behavior**
The glossary popup should open, even if the player has a choice.

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: Godot 3.4
 - Dialogic Version: 1.3 (Godot AssetLib)

**Comment by Jowan-Spooner** [comment]
I think this is fixed in 1.4 DEV already. Could you test as well @coppolaemilio?
