### ISSUE TITLE
If / Else Event

### ISSUE THREAD

**Issue by DasCapschen** [coppolaemilio/dialogic#664]
There is already the `if` event, it would be nice if there was also an *optional* `else` event. So if your condition fails, instead of going to the end of the branch, you would go do the else branch.

This is already possible to do right now, by using 2 `if` events, with the second if having opposite condition of the first if. But this is cumbersome, especially if you change the condition if the if, because you then need to change it in 2 places.

**Comment by RickWillcox** [comment]
Just expanding on the "its already possible now" part. One issue with this is lets say you are checking a definition

```
if definition == false:
    # now we want to give the player an option
    Option1: set definition to true
    Option2: keep definition as false
if definition == true:
    #whatever we put here will run if they select option 1. but what I really wanted was If / Else(or elif)
```

I ran into this issue where a character offers a player a potion. If the player refuses it, drunk_potion will be false, later the same npc offers it again but only if it hasnt been drunk already. If not then the player can once again choose. If the player drinks the potion this time, the second if will trigger. Swap out definition in the above example with drunk_potion
````
if drunk_potion == false:
    # now we want to give the player an option
    Option1: Drink the potion and set drunk_potion to true
    Option2: Dont Drink the potion
if drunk_potion == true:
    #whatever we put here will run if they select option 1. but what I really wanted was If / Else(or elif)
```

**Comment by DasCapschen** [comment]
You could work around that particular issue by checking == true first and == false later.
But this is exactly why an if else would be useful, you don't have to be so careful with everything. :)
