### ISSUE TITLE
Add new signal for when the TextBubble visibility changes

### ISSUE THREAD

**Issue by idontkillcoyotes** [coppolaemilio/dialogic#665]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it would be nice to have.

**Describe the solution you'd like**
Have the DialogNode emit a signal when the TextBubble node hides or shows. 
This signal could be used to implement a pause system in a game, so whenever the TextBubble is visible pause the rest of the game.

**Comment by Jowan-Spooner** [comment]
Hi @idontkillcoyotes thanks for the suggestion.
For the use-case you mentioned, you wouldn't want to know wether the TextBubble is visible tho, you would want to know when a dialog is in progress. Or am I misunderstanding this? There are some cases (for example during a wait event) where the text bubble is hidden although the dialog is still in progress.

Currently (in 1.3+) you can use ` Dialogic.has_current_dialog_node()` (returns either true or false) to find out if there is currently a dialog in progress. 

Feel free to clarify, if I misunderstood what you want.

**Comment by idontkillcoyotes** [comment]
Hmm... for my use-case I think it doesn't matter if a dialog is in progress, only the text bubble visibility.

I think one way of describing what I meant is to treat the text bubble as one of those popup windows that prevents you from interacting with the rest of the program until you close it, something like that

**Comment by Jowan-Spooner** [comment]
how would a signal help with this? isn't it much easier to just add use
``` 
# e.g.: you don't want the character to move if there is a dialog in progress
func move_character():
    if Dialogic.has_current_dialog_node():
        return
```

How would your code look if you'd use a signal, like you want?

**Comment by Jowan-Spooner** [comment]
@idontkillcoyotes, could you elaborate if you still think this would be a good idea or what other reasons there could be for this signal?

**Comment by idontkillcoyotes** [comment]
Sorry, I've been busy and forgot about this thread..

About the change, I already implemented it for my game.
I am using it for a UI based minigame, in which the game "pauses" when there is text from the dialog to show. Because the way I'm using the plugin, there is always a dialog in progress for every scene of my game (in this case the dialog, or timeline, is waiting for the player to finish the minigame to continue).
So I need to differentiate whether the text bubble is visible or not

Saying that, I think my case is still not a "normal" use case, so I don't really know if would be a good idea to implement it

**Comment by Jowan-Spooner** [comment]
I see. Makes sense to me, so I will see how it can best be done and probably gonna add it. It won't hurt and we can always decide to remove it again for 2.0.

**Comment by Jowan-Spooner** [comment]
There is now such a signal in 2.x
