### ISSUE TITLE
Search portraits and organize them

### ISSUE THREAD

**Issue by Bricklou** [coppolaemilio/dialogic#666]
**Is your feature request related to a problem? Please describe.**
I'm currently working with a lot of portraits for my characters. This mean I have a **lot** of entries in my portraits list. I'm losing a lot of time just to search one.

**Describe the solution you'd like**
It would be nice to have a search bar to filter entries.

Another features that could be interesting would be able to organize them inside subfolder to have some sort of "state"
(ex: normal/happy, normal/sad in one folder and equiped/happy, equiped/sad, etc...)

**Comment by coppolaemilio** [comment]
Leaving open and also this could be related to: https://github.com/coppolaemilio/dialogic/issues/820

Should portrait be resources? dunno, leaving open to discuss eventually

**Comment by Bricklou** [comment]
Maybe portraits could have some tags or state per character, or sub-categories for each character.

**Comment by Jowan-Spooner** [comment]
I know it's been a long time, but I can pretty safely promise that both a search bar as well as groups will be in dialogic 2.0. Hope we can get it to a beta soon.
