### ISSUE TITLE
Minor Grammar/Spelling Mistakes in Event Docs

### ISSUE THREAD

**Issue by Aurora-Eluvia** [coppolaemilio/dialogic#667]
**Issue**
Not really big issues, just some improvements to the documentation's language.
Relevant areas:
- Question Event
- End Event
- Text Event

I only had time to review a few, these just stood out.

## Solutions
- Question Event

Change:
> When you adding a Question Event

to:
> When you add a Question Event

- End Event

Change:
> This event does by itself.

to:

> This event adds itself.

or

> This event works by itself.

(though, this is a really unclear statement in general. You may want to clarify what it actually refers to.

- Text Event

Change:
> The text event is one of the most important ones since this will be containing most of your text.

to:

> The text event is one of the most important, since it contains most of the dialogue and descriptions.

Change:
> You have up to tree different types of options here:

to:

> You have up to three different options:

Change:
> Definition - You can select any of your Definitions and it will try to match that string with available portraits. This can be used to dynamically show different portraits depending of previous player input.

to:

> Definition - You can select any of your Definitions and it will try to match that string with available portraits. This can be used to dynamically show different portraits depending on the player's previous input.

**Comment by Jowan-Spooner** [comment]
Thanks for the corrections. If you are somewhat familiar with git, feel very free to create a PR yourself. Otherwise I can also do these changes.

**Comment by Aurora-Eluvia** [comment]
I am not overly familiar with it, unfortunately, though I'm in the process of getting there. I suggest doing it yourself for this set.

If I learn, I'll do a PR with other suggestions for fixing later. I've spotted some other areas that could be cleaned up.

**Comment by Aurora-Eluvia** [comment]
Update -

Took some time to learn how to make a PR and did. You can review and approve at your convenience.

I haven't reviewed the entire documentation yet, this is just what I could get to before work today.

**Comment by AnidemDex** [comment]
@Aurora-Eluvia please, mention that your pr (#669 ) fixes this issue in the PR message

**Comment by Aurora-Eluvia** [comment]
Noted - done so!

Should be good now.

**Comment by AnidemDex** [comment]
I was referring to mention it on the original description of the PR, not in a comment. This way, when the PR gets merged, this issue will be closed inmediatly, but its fine

**Comment by Aurora-Eluvia** [comment]
Yes, I noticed after you said that - I've added it to the original description.
