### ISSUE TITLE
More than one signal/function?

### ISSUE THREAD

**Issue by choinheap** [coppolaemilio/dialogic#67]
Hey, started using dialogic for a quick game jam, seems really good for cutscenes, only that I'm not making a visual novel but rather a 3D RPG with a lot of animations. 

Love that I can combine my own functions via signals inside the timeline but unless I'm missing something it seems like I can only set the value and not which function or different signal to use unless it's a different node. Been using if statements for whichever value I set to do different things within the function. But I'm wondering if I'm approaching this wrong and not understanding the intent here.

**Comment by coppolaemilio** [comment]
At the moment there is only that one signal event, so what you are doing with conditionals is how it is supposed to be done. Of course this is not ideal so I'll see what I can do to trigger more signals from the dialog events and more custom "emit signal" calls
