### ISSUE TITLE
Option to Turn Off Name Label

### ISSUE THREAD

**Issue by Aurora-Eluvia** [coppolaemilio/dialogic#677]
**Is your feature request related to a problem? Please describe.**
Not all games need to have a name label, and it's weird that there's no option to completely disable them.

**Describe the solution you'd like**
A check box that would let me remove the name label entirely from a theme.

**Describe alternatives you've considered**
I set the offset to be off screen, but it's still loaded.

**Comment by nickfla1** [comment]
I'd like to give this a go, seems like an easy first contribution,  apart of being useful!

**Comment by zaknafean** [comment]
Was just thinking about this yesterday! I personally think it can't be a global setting, and may be best tied to themes, or toggleable on specific text events.

**Comment by nickfla1** [comment]
I think both a theme and a text event settings are necessary! 
The first lets the user to control a large set of timelines while the latter allows for a more precise control.

What do you think?

**Comment by coppolaemilio** [comment]
I would only add it to a theme, I don't think that every text event should "ask" you about showing or hiding the name label

**Comment by nickfla1** [comment]
That's fair! Any advice on where to put the setting? I think that the "Name label" is the proper section but the current available columns' names don't seem really fitting to me.

What about something like this?
![image](https://user-images.githubusercontent.com/1572060/149641271-8cf0269a-17bd-4c91-af1e-10882308919e.png)
Of course, disabling this option would also disable all other inputs in the "Name label" section.

**Comment by coppolaemilio** [comment]
I like it, but since the default is the label being shown, I would go with the opposite description:
`Hide name labels`

And if enable you can disable the rest of the fields yeah :)

**Comment by Jowan-Spooner** [comment]
I personally think it would be best to do it in a Behaviour section like for the glossary and have the section at the end, not the front.

**Comment by nickfla1** [comment]
The "Behaviour" title makes more sense but I'm not really sure about putting it at the end.
I mean, if we want to disable the other fields it makes sense to put it at the beginning, so it depends on the user experience we want to accomplish

**Comment by Jowan-Spooner** [comment]
yeah I was mainly thinking about space management. maybe try doing it like this so we don't add another column:
![Untitled](https://user-images.githubusercontent.com/42868150/149779268-bd679de9-6dce-4577-a07f-cb8a8b3328f9.png)

**Comment by nickfla1** [comment]
I also like @Jowan-Spooner approach - waiting for a final decision before starting working on this

**Comment by coppolaemilio** [comment]
Feel free to implement it! I like Jowan's mockup as well, seems like a good place where to put this setting :)

**Comment by nickfla1** [comment]
I'm crafting the PR but I have some strange diffs in the `ThemeEditor.tscn` file, changes I didn't made, such as:

![image](https://user-images.githubusercontent.com/1572060/150572464-da4493b9-1450-4ffc-8546-864fc9de1364.png)
<img src="https://user-images.githubusercontent.com/1572060/150572557-65a0b175-1cde-41ab-a0be-97620a98b7a7.png" width="500" />

**Comment by Jowan-Spooner** [comment]
yeah that is pretty usual if you open scenes in godot that have the tool keywoard it will automatically change all kinds of things (like translations, load icons, etc.). 
There is usually no harm in merging them as it will all be overwritten during runtime. If you have changed nothing in the file you can just leave it out of your commits, but you can also keep them in. 
Whenever possible (not possible here I believe) one should just open the scripts and not the scenes.

**Comment by nickfla1** [comment]
Yeah, I've changed the layout a bit to add the new section and input. 
Thank you!

**Comment by Jowan-Spooner** [comment]
Fixed by #738

**Comment by hsandt** [comment]
I'm working with Dialogic 2, found this but the interface changed quite a lot. I don't see a Theme resource/settings anymore, has it been replaced by Styles? Then the Hide Name label option was apparently removed.

![image](https://github.com/dialogic-godot/dialogic/assets/1067772/df1f0608-e368-436f-afc3-9a4c2a9a07ec)

I do see a Hide When Empty flag on the NameLabel itself:

![image](https://github.com/dialogic-godot/dialogic/assets/1067772/c592e7f4-cf96-4d85-8f35-7f374e4debe6)

but I suspect it is different and requires to clear all character names, which is not convenient as there are still useful for other things like identifying characters and printing character name as variables in text.
