### ISSUE TITLE
Improved Previews

### ISSUE THREAD

**Issue by Aurora-Eluvia** [coppolaemilio/dialogic#678]
**Is your feature request related to a problem? Please describe.**
It's frustrating that I have to actually load the game and play dialogue to see how my choices buttons look

**Describe the solution you'd like**
Ability to preview other elements of the UI before using them.

I'd also like to see other elements, like character positions, and maybe the option to select a background to test it with.

**Comment by Jowan-Spooner** [comment]
This is unfortunately likely not going to change for 1.x and in 2.0 we do not plan to have a dedicated theme editor. This means the look/layout of all elements will be edited directly in the godot 2D editor, and as such this is irrelevant for 2.0
