### ISSUE TITLE
Add a warning to stray "End Branch" events. 

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#684]
![image](https://user-images.githubusercontent.com/2206700/146684912-0f1a6afa-1112-417b-b6ea-c75325bf9462.png)

A warning should be present but just to be safe we could also ignore them in the parser.

**Comment by muchitto** [comment]
Also, kinda related to this, it would be cool that you cannot delete the if/question statements only end branch as that produces a runtime error? Shot myself in the foot when trying out branches and questions.

**Comment by Jowan-Spooner** [comment]
@muchitto I've already created an issue that suggests that. #219

**Comment by muchitto** [comment]
Oh, nice. Yeah that issue is a bigger usability problem for beginners in my opinion (and why not advanced users also).
