### ISSUE TITLE
Directories are not being created on Android devices

### ISSUE THREAD

**Issue by josheb** [coppolaemilio/dialogic#688]
## The directory structure for dialogic and saves is not being created when running a godot application with dialogic on android.

**To Reproduce**
1. Call Dialogic.save('slot1')
2. Look for saves with Dialogic.get_slot_names()
3. Observe '[D] Error: failed to access working directory' from adb logcat output

**Expected behavior**
Saves should write just as they do on PC platforms

**System:**
 - OS: Android 11
 - Godot Version: 3.4.2
 - Dialogic Version: 1.3

## Solutions

**Possible fixes**

I edited Other/DialogicResources.gd functions get_saves_folders() and add_save_folder() to include the following:

>     if not directory.dir_exists(WORKING_DIR):
>         if not directory.make_dir(WORKING_DIR):
>             print("[D] Error: Failed to create working directory.")

After making this change the save slots work as expected.

**Comment by WolfgangSenff** [comment]
This should be fixed by #1801 and can be closed. (Thought that automatically happened with Github, not sure why it's not.)

**Comment by Jowan-Spooner** [comment]
I guess because this wasn't merged into main but the dialogic 1 branch. I will close it.
