### ISSUE TITLE
No option to disable darkening of non-speaking characters in latest dev version

### ISSUE THREAD

**Issue by VoxelTek** [coppolaemilio/dialogic#691]
## No option to disable darkening of non-speaking characters in latest dev version

**Describe the bug**
An option in version 1.3 of Dialogic was the ability to disable characters being darkened when they're not speaking. However, as of the latest dev build taken directly from the source code, this no longer seems to be possible.

**To Reproduce**
1. Download latest Dialogic development version from source code
2. Import into addons folder
3. Enable addon
4. Go to `Dialogic > Settings`
5. Notice the lack of an option to disable character darkening

**Expected behavior**
What I expected to be the case was for the option to disable non-speaking characters being dimmed. However, this option no longer is available, seemingly having been removed.

**Screenshots**
Version 1.3:
![image](https://user-images.githubusercontent.com/53562267/147412724-9739270a-6f50-4806-af91-dca280fa39ca.png)
![image](https://user-images.githubusercontent.com/53562267/147412727-0e5c436c-e71d-4aad-bfe7-ec7db4e59332.png)

Version 1.4 DEV:
![image](https://user-images.githubusercontent.com/53562267/147412733-63516958-be5f-44ad-8347-96e3e66b31ab.png)

**System:**
 - OS: Kubuntu 21.04 x86_64
 - Godot Version: 3.4.2
 - Dialogic Version: v1.4 - DEV (As of https://github.com/coppolaemilio/dialogic/commit/3fbf0f5e18abfbf58e82deead3b3088c58daa722)

## Solutions

**Workaround**

There's not much I can or would be able to do to solve this issue, however, I will note that I am using 1.4 for a reason, as 1.3 does not work correctly. An issue present in 1.3 was that putting a variable such as `[player]` in a line of dialogue did not appear to work, no matter what I tried. This has been solved as of 1.4, however, it seems that the option to disable characters being dimmed has been lost.

**Possible fixes**

The "issue" seems to simply be that either the feature was intentionally removed for whatever reason, or the feature was just forgotten or lost in some way. Whatever the case, I am asking that it be brought back.

**Comment by Jowan-Spooner** [comment]
Hi, this was on purpose. The option in the settings was removed in favor of an option in the theme. You can now set the dim_color which gives you more flexibility. I'm not quite sure where it is, but if you set it to white with no transparency it should be as if it was disabled.
