### ISSUE TITLE
Portrait [Definition] option does not work for Text Event and Character Join WHEN using Dialogic.set_variable

### ISSUE THREAD

**Issue by idchlife** [coppolaemilio/dialogic#693]
## The problem

**Describe the bug**
It seems that Dialogic.set_variable does not change the variable in the place that Text or Join nodes consume.
If I change variable in definition by hand - Text and Join react accordingly and portrait changed.

**To Reproduce**
1) Create dialogue with character that has 2 portraits. E.g.: Default, Female
2) In this dialogue create node Character Join and some texts just to observe.
3) Create definition variable called GENDER. Make it by default "Default".
3) In Character Join choose Portrait option - Definition. Choose GENDER
4) Start dialogue. See that Portrait is default.
5) Change GENDER definition to "Female"
6) Start dialogue. See that portrait is Female
7) Change GENDER definition to "" or "Default"
8) Create script that start and in _ready set Dialogic.set_variable("GENDER", "Female")
9) Start dialogue. See that portrait DID NOT change.

**Expected behavior**
Variable changed in code to affect portrait with "[Definition]" option.

**Screenshots**
---

**System (please complete the following information):**
 - OS: macOS
 - Godot Version: 3.4.2
 - Dialogic Version: 1.3
## Solutions

**Workaround**
Ugly but working workaround (USE BEFORE STARTING DIALOGUE):

```py
func dialogic_set_variable_for_sure(name: String, value):
  var defs = DialogicResources.get_default_definitions()
  var variables = defs["variables"]
  
  for v in variables:
    if v["name"] == name:
      v["value"] = value
      
  defs["variables"] = variables
  
  DialogicResources.save_default_definitions(defs)
```

**Possible fixes**

Fix something with set_variable and definitions loading. I made an ugly hack but has not time for now to figure out what's and where wrong in the source code :( Sorry

**Comment by Jowan-Spooner** [comment]
From what I can tell by looking at the code, the Definition thing just doesn't work for Text and Question events at all and only on the Join event. There seem to be no checks for definitions on the other events. I will investigate further and hopefully push a PR with a fix today.

**Comment by Jowan-Spooner** [comment]
This should be fixed with my PR. If not, please reopen!
