### ISSUE TITLE
Prevent Dialog Node from being removed at the end of the timeline

### ISSUE THREAD

**Issue by mechPenSketch** [coppolaemilio/dialogic#694]
**Is your feature request related to a problem? Please describe.**
I want my dialog node to stay even after it clear its last event.

**Describe the solution you'd like**
An option to clear the dialog node at the end of the timeline can be added to the Theme, specifically Dialog Text > Behavior.

**Describe alternatives you've considered**
* A new event could be added, or `Wait Seconds` could be toggled whether there should be time to be waited.
* I have previously coded the dialog node to not be removed, while it was under the singleton system (can't exactly remember how). I don't think the new node have the functions that lets me do it.

**Additional context**
This is a stylic choice for games where the dialog system to too well-integrated into the game space.
* I can think of the battle system in pre-gen V Pokémon mainline series as an example. 

I can pull a new request in myself. I just need to check whether this can already be done, or there is a better solution.

**Comment by Jowan-Spooner** [comment]
Afaik there isn't a way to do this yet.
