### ISSUE TITLE
Simplify left-hand panel UI to put data where it is relevant.

### ISSUE THREAD

**Issue by willnationsdev** [coppolaemilio/dialogic#7]
![conversation_editor](https://user-images.githubusercontent.com/16217563/95008998-02a54500-05e4-11eb-80db-faed911f742b.png)

In this original layout, you have many different parts of the UI present on the left-hand panel. But we've mixed together navigation, dialogue operations, and modifying the content of the dialogue all together in one place.

Here is a revised prototype of the UI:

![conversation_editor_new_ui](https://user-images.githubusercontent.com/16217563/95009334-e8209b00-05e6-11eb-83ab-8abdeeaa54bf.png)

In this case, the "events" stuff is all added to a sticky bottom "event" block that contains the buttons to add more blocks.

A toolbar is added to the top of the panel which would contain the script and folding ToolButtons.

Script: should show "add a script" icon when no script exists for the dialogue and the generic "script" icon (which it currently shows) to open the script in the ScriptEditor.

Folding: should be a toggleable ToolButton. If any 1 collapsable block is not collapsed, then the button displays a "fold" icon and clicking it will fold all blocks, after which, it displays the "unfold" icon. Clicking the button while in the "unfold" state will unfold all blocks and subsequently change it to the "fold" icon.

This paves the way for more making more fully-featured navigation options on the left, and creates more space for executing more dialogue-level operations in the above toolbar. I would reserve the higher toolbar for tabs, as you've done so. However, it might look better to give it more prominence with a full-fledged TabContainer or something. That way you can directly see the subsections of the dialogue editor laid out for you rather than the "tabs" looking like some sort of operations you can click on to execute. You could, in the long run, use it as a place to switch between minor editors for all kinds of pieces of data related to the story.

**Comment by coppolaemilio** [comment]
I really like this! At first I didn't have the list with scenes on the top left so I added the event buttons there, but after a while I tried imitating the script editing way of listing current files so I had to put it there. I really like the idea of moving the event buttons to the timeline, I'll play around with it and see what is the best way of doing it 👍

**Comment by coppolaemilio** [comment]
I tried a few things but I think that the second one is my fav. The other one got weird as soon as you had to scroll to see it. I want it to be always visible.
![test-1](https://user-images.githubusercontent.com/2206700/95249168-97908400-0818-11eb-9bc9-4c08fec47fe9.PNG)
![test-2](https://user-images.githubusercontent.com/2206700/95249175-99f2de00-0818-11eb-9f78-7da846cfdcbb.PNG)

I'm going to leave it like this for now and see how it feels after a while. I was also thinking since I don't really need so much horizontal space for the events that maybe splitting the view 50% 50% and leaving the left side for branches and the right side for events could be a good way to organize the entire thing. But I don't want to get ahead of myself now haha 

![test-3](https://user-images.githubusercontent.com/2206700/95249449-fa821b00-0818-11eb-86e1-75ba96a6513b.PNG)

**Comment by willnationsdev** [comment]
@coppolaemilio I see. Hmmm. I may try something myself.

1. Use a similar style "block", but with just a border and a transparent background, with a green + sign on the left. Keeps it in style with remaining blocks, but stands out as an "empty" one that needs filling.
1. Figure out how to trick the ScrollContainer (I'm assuming that's what it is) into thinking there is more scroll space than there actually is, that way you can scroll down *until* the last non-empty block is visible at the top.
1. Have the editor auto-scroll down to a configurable ratio to always keeps a portion (say, bottom 20%) of the window filled with whitespace, that way the content doesn't end up at the very bottom of the screen and people have to constantly scroll down manually.
1. Set up keyboard shortcuts (and display them visually somewhere(?) rather than just documenting them) so that people can avoid using the mouse for any of the work and can instead just use quick keyboard commands to snap out dialogue sequences.

Also, I really love the idea of being able to have a branching graph editor side-by-side with it as you've portrayed. The only thing I'd say is to be sure to make it something that you can easily toggle as being side-by-side vs. tabs, because users with a smaller screen will need to use tabs instead.

Another thing I would recommend is (in the backlog), creating an Issue for porting both of the editors to independent control nodes. Then, you can "undock" them by dragging their tab away and it becomes a Popup. Close the Popup for the tab to reappear. Click and drag the Popup back into place, and display a prompt to release and "dock" it, which would a) close the Popup, b) reinstate the tab, and c) give the tab focus (make it visible). This way, you can program dockable editors before the 4.0 release (at which point, your Popups will instantly be full Windows of their own rather than embedded within the Godot Editor window).

**Comment by willnationsdev** [comment]
Update: I found a working solution for 3, and *kinda* for 2 (although the bottom padding is currently a hardcoded value - need to make it a calculated one based on container's dimensions on the user's screen). Gonna see if I can figure out 1 after 2 and then try integrating it into the timeline editor for a partial PR on this issue.

**Comment by coppolaemilio** [comment]
you can check the branch 0.5 if you want to see the version I settled for
