### ISSUE TITLE
Question on variable management

### ISSUE THREAD

**Issue by bitbrain** [coppolaemilio/dialogic#708]
In the current version of Dialogic, each variable needs to be unique. This means in case I want to populate Dialogic state based on entities in the game world, I'd need to create a set of variables per entity. For example, let us assume I have 20 different NPCs, most of them have similar variables (items in inventory, health etc.) - currently, I'd need to manually create the same set of variables, 20 times but with custom names (e.g. npc1_health, npc2_health, npc3_item_ruby_count) which is not very straight-forward to manage on the long run.

Do folks have any suggestions how i can optimise this workflow? Maybe having something like a "struct" type might help? For example, instead of having a simple string variable, we could introduce a "complex variable type" where I can specify the individual values and names, and then I can just create complex variables of that type.

Any other suggestions welcome!

**Comment by coppolaemilio** [comment]
Not entirely sure if I know what your needs are but I would create "generic variables" in Dialogic and change them before spawning a timeline. For instance:

`example_timeline`
```
Hello there, my name is [npc_name] and my current hp is [npc_hp]
```

I would set those two variables to their specific value and show the dialog:

```
var name = "Emilio"
var hp = 10

var dia = Dialogic.start('timeline')
Dialogic.set_variable('npc_name', name)
Dialogic.set_variable('npc_hp', hp)
add_child(dia)
```

I haven't dealt with a game with too many variables and maybe [creating timelines from GDScript](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Documentation/Content/FAQ/create-timeline-using-gdscript.md) is something that might be interesting if you have a lot of "procedural content". Not sure if that helps, so feel free to keep asking 🙈

**Comment by bitbrain** [comment]
@coppolaemilio let me try to provide an example with what I mean exactly:

Let us say there is the concept of gold in my game and I want to track how much gold each NPC in the world owns. I can do that quite easily outside of Dialogic by giving each NPC an `int` variable that tracks that gold amount.

However, now I want to create dialogues based on the amount of gold a particular NPC owns. Let us say, there are two NPCs:

- Miguel has 500 gold
- Emilio has 1000 gold

Now, I want to trigger dialogue in case Miguel has at least 1500 gold (after Emilio has given away his gold, lol). As a result, I need to track these gold values in Dialogic as variables. Currently, I'd go and create two variables:

- `emilio_gold_amount`
- `miguel_gold_amount`

I can then connect my gold collecting signals so it updates these variables automatically, no problem. The problem is now that there is not just a single gold value but potentially hundreds of different values and hundreds of NPCs and this would mean I'd need to manually create over a thousand of different variables.

A solution to this problem could be to be able to define character-specific variables those get automatically set up for each character I create within Dialogic. I could define the `gold_amount` variable and I can set this variable then "per character". Let us say I have set up over 100 different characters in Dialogic, adding a new "character variable" would automatically provide it on each of these 100 characters.

**Comment by coppolaemilio** [comment]
Variables per character would be a great solution for this. I understand where you are coming from with the different variables that you need to trigger different conversations but I think the solution I provided would still work (even if it is a bit _meh_). `npc_gold_amount`, `player_gold_amount` inside dialogic and then get those values from where you store that information. Not ideal but yeah, the only sane solution I could think at the moment.

Adding variables per character would be a great way of dealing with things like this, but it would require some work to get it implemented. Super doable tho.

**Comment by bitbrain** [comment]
@coppolaemilio the problem then becomes that I'd need to populate the state whenever I create a new dialogue. I'll have to see how this impacts performance but this might be an okay trade-off compared to manually creating hundreds of variables, haha.
