### ISSUE TITLE
Add Character z-index property

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#712]
Portraits can overlap and there is no way to order them.
There should be a "z-index" property on the character join event and a "default" option on the character editor.

**Comment by thebardsrc** [comment]
just to add to it, currently it's swapping the draw order every other dialogue box, unless character is talking and "dim characters when they are not speaking" is enabled, then they hold properly. 

having Z-index setting on character join event lets you customize the order you want people drawn in, for say just everyone right-to-left  or left-to-right-, or say if you have characters on the side looking at someone in the center then draw in z orders 1,2,3,2,1 or 3,2,1,2,3 depending on how you want a particular scene

**Comment by Jowan-Spooner** [comment]
Any ideas on how to implement this? Control Nodes don't have a z-index property. We will just have to manually sort the children of the portrait node acording to the given "z-index" probably... Also to achieve #640 (which is related to this) we would have to put the portrait node below the text bubble node.
