### ISSUE TITLE
Crash on [img] BBCode

### ISSUE THREAD

**Issue by vlyahovich** [coppolaemilio/dialogic#714]
## The problem

**Describe the bug**
When I insert image inside a question, plugin is crashed

**To Reproduce**
1. Go to `Timelines`
2. Add a new timeline
3. Input question with text: `Question [img=10x10]res://assets/any_icon_asset.png[/img]?`
2. Start dialog and test, you should see an error

**Expected behavior**
Image is displayed inside the box

**Screenshots**
<img width="1192" alt="Screenshot" src="https://user-images.githubusercontent.com/2776343/148680909-da132e92-99d5-4dae-963b-b90919eb5ddb.png">

**System (please complete the following information):**
 - OS: Mac OS 12.0.1
 - Godot Version: 3.4.2
 - Dialogic Version: 1.3

## Solutions

**Possible fixes**

I edited plugin myself to check the boundaries of a string in text label, it may be that [img] code produces zero length character or something.
At `TextBubble.gd` after line `199`  I had to add boundary check `text_label.text.length() > text_label.visible_characters-1 and`

Please let me know if I am doing something wrong. If it is indeed a bug I can prepare pull-request

**Comment by Jowan-Spooner** [comment]
It does not seem to be happening anymore on 1.4 WIP, so I'm going to close this. If you want to try it out yourself, please use version control or make a backup version, as 1.4 is still WorkInProgress.

**Comment by Jowan-Spooner** [comment]
My bad. Moments after writing it happened again. Damn'it! I will investigate.
