### ISSUE TITLE
Timeline_start signal dose not work, and dialogic_signal at the start of a timeline

### ISSUE THREAD

**Issue by SevyChrist** [coppolaemilio/dialogic#717]
## Timeline_start signal dose not work. Also dialogic_signals at the start of a timeline.

**Describe the bug**
So dialogic_signal emiter seem to work, only if u put a timer 0.1 at the begining.

**System:**
 - OS: [Windows 10]
 - Godot Version: [3.4.2]
 - Dialogic Version: [1.3]

**Comment by Jowan-Spooner** [comment]
After lots of playing around with this, it is probably due to the canvas layer node connecting on ready but being further up in the tree than the Dialog Node an thus connecting a moment after the DialogNode ready function. I'm looking into a fix.

**Comment by coppolaemilio** [comment]
@SevyChrist Feel free to re-open if it still happening after the fix

**Comment by ceejjay** [comment]
Did this fix it for you @SevyChrist ?

I'm just getting into dialogic, having downloaded it a couple days ago, and I'm seeing this exact behavior.

timeline_start never seems to trigger. I get timeline_end just fine, and tons of event_start events. 
But timeline_start just doesn't happen for me.

**Comment by Jowan-Spooner** [comment]
Make sure you connect to the signal before you add the node to the tree.

**Comment by Jowan-Spooner** [comment]
@ceejjay make sure you connect the signal before you add the dialog.

**Comment by ceejjay** [comment]
Sorry to beat this horse. lol. 

By "before your add" you mean before add_child(<name>) right? I am definitely connecting the signal before adding it to the scene. 

Here is what I'm doing, and I'm not getting the TLStart function to trigger. If I change it to event_start it fires a bunch *shrug* 

func Interact(body):
	var new_dialog = Dialogic.start('timeline-01')
	new_dialog.connect("timeline_start", self, "_TLStart")
	new_dialog.connect("timeline_end", self, "_TLEnd")
	add_child(new_dialog)
	
func _TLStart(type, event) -> void:
	print_debug("TL_START")
	PauseInput(true)
	
func _TLEnd(timeline_name) -> void:
	print_debug("TL END")
	PauseInput(false)
