### ISSUE TITLE
Add option for portrait background image

### ISSUE THREAD

**Issue by Hatchet2k4** [coppolaemilio/dialogic#727]
I have a hopefully simple request regarding portraits that others may find useful as well. It would be handy to be able to have a configurable background image that can go behind a character portrait. This way, I could have a consistent frame that the portrait can appear in without necessarily having to manually apply it to every portrait, or to have the option of customizable frames. Could also be used if you wanted to have something like a different background behind the character for different areas, for example. 

Examples:
![portraitwindow](https://user-images.githubusercontent.com/5480348/149539296-5548f301-c720-4e8a-a00e-45167dd0f670.png)

![tabby](https://user-images.githubusercontent.com/5480348/149539210-e364f188-f228-4245-b799-f48acf60cea2.png)

For the final result of:

![tabportrait](https://user-images.githubusercontent.com/5480348/149539214-ec9da31d-c411-4cb7-81ea-85989a3182f5.png)

One thing to consider with this would be how to handle scale/offsets, but if the image sizes were always consistent you could have a global offset for backgrounds and a corresponding global offset for the portraits, maybe with the option to still have an override on a per portrait basis. 

Not an urgent request, but hopefully an idea that has some value! It's definitely a useful plugin. :)

**Comment by bitbrain** [comment]
This should be doable already by using custom portrait scenes.

**Comment by coppolaemilio** [comment]
With the new system in 2.0 you should be able to do this kind of layouts easily
