### ISSUE TITLE
Editor only error when creating a new Custom Event

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#731]
## The problem

**Describe the bug**
With the new Dialogic UI, the Custom Event Block no longer has the event_style variable. This causes an editor error when you try to create a new custom event. Everything still works and is generated, but clean up is nice too.

**To Reproduce**
1. Go to Settings
2. Click on Create New Event
3. Observe this error

![image](https://user-images.githubusercontent.com/7741797/149626283-4c560f37-2662-4f3d-98da-e0dff9a0ce34.png)

**Expected behavior**
No error appearing that may confuse newer users

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.2.4
 - Dialogic Version: 1.4-dev

## Solutions

**Workaround**
It can be safely ignored, but is also a pretty easy fix

**Possible fixes**
Remove Line 265 in the SettingsEditor.

**Comment by Jowan-Spooner** [comment]
Closed by #732
