### ISSUE TITLE
Test If A Timeline Exists

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#739]
I needed a way to test if a timeline with a specific name existed, for automated validation testing for my project. There is a function that almost does exactly waht I need, but it's internal. So I made up this quick external one:

static func timeline_exists(timeline: String):
	var timeline_file = _get_timeline_file_from_name(timeline)
	if timeline_file:
		return true
	else:
		return false

**Comment by thebardsrc** [comment]
as an addendum to this, the _get_timeline_file_from_name() function seems to fallback for searching the entire tree for a timeline, so it can't be used directly the way I have it for example. this also means that calling Dialogic.start() without an actual path could lead to calling the wrong node since it just goes for the first one it finds in the JSON order, rather than the sorted Dialogic order, which would seeem to be a bug:

Example timelines setup: 
<img width="111" alt="Capture" src="https://user-images.githubusercontent.com/2214793/151050418-3604a424-6792-42a0-b9ab-021fc9d987b2.PNG">

The absolute paths work for the most part, except for checking if one's in the root that one returns True even though there isnt one there. In this setup, the Test3/Sub/Auto timeline was created before Test2/Auto, so a call to Dialogic.start('Auto') ends up creating the subfolder timeline since its the first one found in creation order:

<img width="776" alt="Capture2" src="https://user-images.githubusercontent.com/2214793/151050605-8061794e-dbd0-41cf-b8ee-0ef677151eec.PNG">

if you were to call Dialogic.start('Test2/Auto'), it will call the proper timeline. also trying to call Dialogic.start('Test1/Auto') will give the  "No Timeline Speicified" error as expected, since that one doesn't exist.

**Comment by Jowan-Spooner** [comment]
Using the full path is the recommended way of doing it. Using just the timeline name (which doesn't always work as you pointed out) was only kept in to not break compatibility to older projects.

**Comment by thebardsrc** [comment]
yeah I agree, and it seems just fine on that account other than trying to address any timelines in the root folder
