### ISSUE TITLE
Folder paths do not work for get_variable/set_variable

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#746]
Problem: 
Folder paths are not working for the get/set variable functions.

With the following test variable layout, with each variable value set to the folder it is in:
<img width="89" alt="Capture" src="https://user-images.githubusercontent.com/2214793/151053246-9586948f-92b4-48d8-aa13-541d1e78cb8f.PNG">

The tests show that the folder paths are being completely ignored:
<img width="303" alt="Capture2" src="https://user-images.githubusercontent.com/2214793/151053707-7c97e76a-4568-488f-85b7-8261c3ed873c.PNG">

Also, as the same case with my addendum on #739 testing found with the timelines, it's also simply going by the order in the JSON, which means in this example screenshot it's actually pulling the value of Test2/TestValue, as that one was created first, rather than taking the root TestValue since that was created after it, which also can lead to unexpected behavior.

**Comment by thebardsrc** [comment]
From additional testing, I have found two additional problems:

First, it also doesn't get them parsing the text in a text node, either:
<img width="701" alt="Capture3" src="https://user-images.githubusercontent.com/2214793/151062149-b4267765-f394-4479-8429-3aa57c2f4055.PNG">

Second, something weird is happening when calling set_variable to the way Dialogic does logic calls. 

Take the following test timeline:
<img width="404" alt="Capture4" src="https://user-images.githubusercontent.com/2214793/151062486-18f05c82-3adb-4b48-9209-a49262b34b47.PNG">

While the If statement doesn't reflect the subfolders (which is not ideal, but fine since in the background it uses the event_id instead), each one of these If statements have been set separately: /TestValue has been set to 1, /Test2/TestValue has been set to 2, /Test3/sub/TestValue has been set to 3.  when running normally, since all three of them are set, they all execute correctly and show the text event assoicated to them. However, calling Dialogic.set_variable('TestValue', "updated value") in code before creating the dialogue isn't just updating the first found TestValue, as we were expecting from the previous test, but it seems to be updating _all_ of them because then _none_ of them are running. 

And if we print Dialogic.export() from before and after doing anything, we can indeed see that all three of them were changed, which isn't the behavior we want either:
<img width="619" alt="Capture5" src="https://user-images.githubusercontent.com/2214793/151063805-8d607df5-be05-40e0-8227-6690e24cbc23.PNG">

**Comment by Jowan-Spooner** [comment]
Thoughts/Info
- Not necessarily a bug, more a design problem/decision
- Yes text events do not consider the path of the definitions only the name and will pick the first one with a matching name (same with set and get functions)
- thus definitions where never supposed to have duplicate names. It would be good to change this probably, but that's a 2.0 thing imo.
- The definition picker does show the folders in 1.4 WIP

**Comment by thebardsrc** [comment]
on the third point, I would say it absolutely is something that should be changed going forward, because it is important for larger projects. for example, an RPG where you want to keep interaction flags for say an NPC remembering that they talked to you once already, you would need variables for every one of them

on the last point, what i mean is looking at it from the timeline. you can use the picker for the folders just fine in 1.3 too, but neither 1.3 nor 1.4 WIP actually show the label as being in subfolders after that
<img width="294" alt="Capture" src="https://user-images.githubusercontent.com/2214793/151069786-93e34742-45a0-4b90-8bec-05388422b219.PNG">
but since the actaul timeline file is testing them by their IDs, 1643141455-787, 1643141427-648, and 1643141480-146 in this case, the visual appearance isn't so important otehr than maybe looking back later to try and cross reference it

**Comment by thebardsrc** [comment]
so im trying to step through the code myself to try and figure it out to submit a PR. get_variable(), set_variable(), and the DialogNode all are calling the internal function _get_definitions(), which is just a dictionary of all the variables with four values: id, name, type, and value. it would seem to me that just adding one more item in that dictionary, the path from the folders definitions, would allow being able to extend the function to be able to both preserve the way it works currently, as well as be able to check it by a full path, i.e. makng get_variable('Variable') work as it does now, and get_variable('/Variable') return one from the root of the folder structure.

since I dont think there's a function to create new definitions at runtime, just set them, all it would need would be going through and adding the path in once at runtime, that's where I'm at right now.

**Comment by Jowan-Spooner** [comment]
This would have to be recalculated everytime you run the game, right? But yeah. That's certainly one way to achieve this.

**Comment by Jowan-Spooner** [comment]
This was fixed with PR #748
