### ISSUE TITLE
Animations for Choice Buttons and TextBubble

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#749]
from @kervesko on discord
**Is your feature request related to a problem? Please describe.**
Want's to have custom animations on the text bubble and choice buttons, like how they enter and leave and possibly what happens when you hover them. Last thing could be connected to #597 .

**Comment by Eversco** [comment]
Basically a similar customization ability like PowerPoint animations

**Comment by thebardsrc** [comment]
This is something that can be implemented in the actual scene for the Style itself in 2.0 so I'll mark this one as completed
