### ISSUE TITLE
Make a space between text command and = possible

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#756]
## The problem

**Describe the bug**
Currently if you write [signal = test] instead of [signal=test] it won't recognise the command. I feel like this isn't very user friendly.

**Comment by AnidemDex** [comment]
Discussed in https://github.com/coppolaemilio/dialogic/discussions/755

<div type='discussions-op-text'>

<sup>Originally posted by **fire7side** January 30, 2022</sup>
I'm trying to get a character to talk during the text rollout by sending a signal but it's ignored and printed as text.
[signal = test] Hello There.  I've tried using quotes and not.  The brackets aren't printed on screen for [br] so it seems to be ignoring it.  Any help would be appreciated.</div>
