### ISSUE TITLE
Enable More Positional Control of Dialog Box

### ISSUE THREAD

**Issue by AnomalyAces** [coppolaemilio/dialogic#761]
I would like to be able to set an offset on the entire dialog box, similar to the way we can set an offset to the next indicator

Thanks

**Comment by thebardsrc** [comment]
from discussion on the Discord, it seems this might be a bug with any of the positions in themes that are based on Center (the four cardinal centers, and middle), where it doesn't take into account the Box Margin in the positional.  Top and Bottom Center are ignoring the X, Left and Right Center are ignoring the Y, and Center is ignoring both

**Comment by AnomalyAces** [comment]
For more context, It also seems there is a soft cap of 100 for the choice button offsets as well but you can choose any negative number you want. So the current workaround is to position them in the bottom right and use negative numbers to position them. It also may make more sense to position the buttons relative to the dialog box if possible

In a similar vain if you position the dialog with without using one of the 5 "Center" positions you can use the margin to position those as a workaround

**Comment by zaknafean** [comment]
@lamsorsen PR is merged into main and handles this stuff very nicely. Much easier to do cool stuff now
