### ISSUE TITLE
Documentation update for 1.4

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#763]
Some things need to be updated before release:

- [x] event images
- [ ] settings editor
- [x] theme editor
- [x] new DialogicClass functions

are the ones I could think of so far

**Comment by zaknafean** [comment]
- [ ] Details for the History settings 
- [ ] Guide to customizing History Parts

**Comment by Jowan-Spooner** [comment]
I will close this as it has no priority whatsoever anymore.
