### ISSUE TITLE
Unnamed folder that cannot be deleted

### ISSUE THREAD

**Issue by Kamilayza** [coppolaemilio/dialogic#766]
_**Important**: Google Translator!_

**The event that led to this error** : Due to inattention, I forgot to specify a different folder name, I wanted to change it, but as a result, the Godot engine fails. Then I decided to delete it and it didn't work out either.

**Problem** : The unnamed folder is not deleted and causes other problems

**Describe the error**: If you accidentally do not fill in the folder name, then this folder cannot be deleted or renamed and Godot will fail.

**To Reproduce** :
1. Go to any section of the Dialog box (in the screenshots below there will be a folder with characters).
2. Create a folder.
3. Erase the folder name and leave it by pressing enter.
4. We are trying to delete\rename an unnamed folder.
5. Godot is closing.

![2022-02-04_00-01-20](https://user-images.githubusercontent.com/69761343/152428698-64d9133f-f6d9-45bd-9a2b-0257a9481f6e.png)

Also, if you insert a new folder into it, this will happen:
![2022-02-04_00-14-17](https://user-images.githubusercontent.com/69761343/152430584-91bfa45d-4ac9-4be0-a6b4-3580213b63ec.png)

Also, if you try to delete this folder too often, then as a result, the project that this unnamed folder was will stop opening at all.

**System:**
 - OS: Windows 10 64x
 - Godot Version: 3.4.2
 - Dialogic Version: 1.3

I do not know what is the cause of these strange errors, so I cannot offer a solution to this problem.

**Comment by AnidemDex** [comment]
Are there any error in the console shell or in the output tab? I think I know what is the issue, but want to confirm my theory

**Comment by Kamilayza** [comment]
The console in engine shows nothing
Immediately after deleting\changing folder, Godot automatically closes

**Comment by Jowan-Spooner** [comment]
@Kamilayza, thanks for the report! I'll try to fix this tomorrow. For a quick-fix you can open the folder_structure.json file in the res:/dialogic/ folder and look for the empty folder. It should look something like this:
![grafik](https://user-images.githubusercontent.com/42868150/152445460-7014c491-7ea0-416b-95bc-23e760bcab10.png)
If you delete the content of that folders dictionary so it looks like this:
![grafik](https://user-images.githubusercontent.com/42868150/152445558-cbfaa8a7-cf24-49b8-a846-25a802fed8da.png)
it should work again and the folder should be removed.
