### ISSUE TITLE
Adjustable name label

### ISSUE THREAD

**Issue by GammaGames** [coppolaemilio/dialogic#78]
It would be nice if you could resize the name label like you can the text.

![image](https://user-images.githubusercontent.com/7832163/111106508-d8ed3400-851a-11eb-83e3-3d603295fdce.png)

Color, shadow, background color, size, etc. 

I wanted to make a news popup via a theme, but had to edit the scene to do so. For now I've edited the `start` method to take an optional `dialog_scene_path` variable. I can make a PR if that sounds interesting, my custom scene is inherited from `Dialog.tscn` so there *shouldn't* be any compatibility issues.

Here's my result: 
![image](https://user-images.githubusercontent.com/7832163/111108413-77c75f80-851e-11eb-85e5-54008954eddc.png)

**Comment by arnaudvergnet** [comment]
@coppolaemilio this would be very useful because right now the name label can become hard to read depending on the scene background. I would work on it but I fear it would create too much conflicts with #107.

**Comment by coppolaemilio** [comment]
I can work on this one today 👍🏻

**Comment by coppolaemilio** [comment]
I pushed some changes to `main` with the theming options for the names. Tell me what you think! I will probably be changing more stuff soon because it is not 100% flexible, but at least it is something.

**Comment by arnaudvergnet** [comment]
Looks good! I would also add an option to add padding. Depending on the background you use, it might be useful. And we cannot preview character names inside the theme editor which makes it difficult to use. Other than that great job!

**Comment by coppolaemilio** [comment]
I forgot to push the last commit, but you can see it now. It will pick a random character and show it on the preview.
The padding on the names and the position of the name label is something that I need to add in a future update for sure
