### ISSUE TITLE
Improve compatibility with other assets (e.g Tiled Map Importer)

### ISSUE THREAD

**Issue by fabioamc** [coppolaemilio/dialogic#784]
**Is your feature request related to a problem? Please describe.**
Some other assets require importing json extenson files. This makes the current version of Dialog incompatible, since Godot will create ".import" files for every json file in the project, including those used by dialogic (Characters and timelines), making the program crash or not working properly.

**Describe the solution you'd like**
In version 1.3 of Dialogic, file DialogicResources.gd, replace line 118 with the following:
> if not dir.current_is_dir() and not file_name.begins_with(".") and not file_name.ends_with(".import"):

**Additional context**
Although this is not a problem with Dialogic itself, any asset which requires importing json files would not be compatible with Dialogic right now.

**Comment by coppolaemilio** [comment]
thank you for pointing this out! I'll try your change and push it if works :)

**Comment by AnidemDex** [comment]
The workaround works for plugins that uses json files as Resources, but can still be a problem with those plugins that uses the file directly. Maybe can consider telling the editor that files inside dialogic folder must be treated as is (plain files) instead of trying to import them as resources

**Comment by fabioamc** [comment]
True.
I am new to Godot assets, but I have been reading and added .gdignore file to dialogic folder, and it worked.
