### ISSUE TITLE
Changing History Screen Margin results in error

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#788]
## The problem

**Describe the bug**
It seems to me that if you change the history screen margin it gives an error as soon as the dialog is added.

Error:
![grafik](https://user-images.githubusercontent.com/42868150/154983990-ab2eecea-252f-4811-8694-fdec0fe8ed75.png)

**Comment by Jowan-Spooner** [comment]
Any idea why this could be @zaknafean?

**Comment by zaknafean** [comment]
Weird. Will dig into it today

**Comment by zaknafean** [comment]
The error originated in _on_HistoryPopup_item_rect_changed. This signal was neccesary when the HistoryPopup was an actual Popup type. Now that its a Panel, panel handles the rect changed and margins properly, and all the code in _on_HistoryPopup_item_rect_changed does is cause an infinite loop. 

The code actually works better and more consistently now without this signal connection, so its been removed.

**Comment by Jowan-Spooner** [comment]
Closed by #789.
