### ISSUE TITLE
Expose the animation for "focus in" and "focus out" characters

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#792]

**Comment by thebardsrc** [comment]
IIRC there were two bug/feature requests from before about changing the fade speed between portraits (particulrly for single portrait mode when you have all the portraits in the same spot) that had been fixed, but then the Anima update overhauled Portraits.gd and reintroduced it. but that update also simplified it, chaning it from four hard-coded speeds there before to just one on line 145, as it reaeds currently: 

`func tween_modulate(from_value, to_value, time = 0.5):`
