### ISSUE TITLE
With the new style, it doesn't look good at all when you don't have characters and you create a text event

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#814]
![image](https://user-images.githubusercontent.com/2206700/156451393-35562bb0-9eb7-4800-9936-4a6edcd90178.png)
It should go to the same line as the icon

**Comment by Sslaxx** [comment]
Or you could have it say "No character" or something like that?

**Comment by coppolaemilio** [comment]
This is no longer the case in 2.0
