### ISSUE TITLE
Dialog Box Not Appearing in the Correct Position

### ISSUE THREAD

**Issue by Shargon-Pendragon** [coppolaemilio/dialogic#82]
Attached the script below to a Godot Control Node.

![image](https://user-images.githubusercontent.com/29558236/111357932-c593b300-8657-11eb-99e6-7e8bbcf70910.png)

Yet the Dialog box is appearing to the left of the screen instead of the bottom. 

![image](https://user-images.githubusercontent.com/29558236/111358171-0d1a3f00-8658-11eb-9940-7cf599a0b696.png)

Is there any way to move the dialog box to the bottom of the screen?

**Comment by coppolaemilio** [comment]
Can you post a screenshot of your scene tree?

**Comment by Shargon-Pendragon** [comment]
Here you go.

![image](https://user-images.githubusercontent.com/29558236/111377403-989eca80-866e-11eb-93f6-66820ae87e19.png)

**Comment by coppolaemilio** [comment]
@Shargon-Pendragon can you try the latest version of `main` and see if the issue is fixed?

**Comment by Shargon-Pendragon** [comment]
The dialog is showing on the bottom of the screen now. Thanks for your help.
