### ISSUE TITLE
Define properties of custom portrait scenes

### ISSUE THREAD

**Issue by bitbrain** [coppolaemilio/dialogic#820]
**Is your feature request related to a problem? Please describe.**
It is possible in Dialogic to define a custom scene node for a character's portrait. However, that node cannot be modified but [it will be instantiated with its default exports instead](https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Nodes/Portrait.gd#L58). This becomes a problem if I want to define a "generic" custom portrait scene that has a configurable enum on it or other exports that I want to modify for specific portraits. In its current state, Dialogic is unable to support that.

**Describe the solution you'd like**
Have a property panel on the right side of the screen (like when selecting a node in the scene tree) where the user can modify the properties of a custom portrait scene. This panel should only be visible when "selecting" a custom scene portrait entry within the character screen.

Example:

![example](https://user-images.githubusercontent.com/822035/156882448-9c6a004f-45e6-4c54-bdd4-bbbe51865c8c.jpg)

**Comment by Jowan-Spooner** [comment]
This is being worked on and will probably be in the next dialogic alpha, if nothing breaks my implementation.

**Comment by bitbrain** [comment]
@Jowan-Spooner wow, that is amazing.

**Comment by bitbrain** [comment]
🍾
