### ISSUE TITLE
Working on HTML5 Export

### ISSUE THREAD

**Issue by linux-man** [coppolaemilio/dialogic#83]
Is it possible? I added "\*.json" on the Resources tab (also tried "dialogic/*") and copied dialogic folder next to html and js files.
The Dialog appears, but no timeline.

**Comment by linux-man** [comment]
Got it!
At line 43 and 452 of dialog_node.gd you're calling set_current_dialog and adding a '/' to dialog_path.
Later, get_path will add another '/'.
This will break file.open on HTML5.

**Comment by coppolaemilio** [comment]
Thanks! I'll fix that one 🙃

**Comment by coppolaemilio** [comment]
@linux-man I pushed the change! thank you for finding this one. I'll close it but feel free to comment again if it wasn't fixed

**Comment by arnaudvergnet** [comment]
@coppolaemilio I tried the HTML export and it failed to find my config files, so it didn't find the theme and definitions.

To fix the issue, I added `*.cfg` to the `Resources` tab in export. It might be worth updating the readme.

**Comment by coppolaemilio** [comment]
I'll fix the readme 👍🏻
