### ISSUE TITLE
No way to remove Choice hotkeys

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#830]
## The problem

**Describe the bug**
Since the [Default] option has been removed on the Default Action Key selector, and the choice hotkeys use the same function there is no way to use no choice hotkey again, after one was selected.

@zaknafean could be interesing for you.

**Comment by zaknafean** [comment]
I'll get right km this one

**Comment by Jowan-Spooner** [comment]
Also noticed the second hotkey selector says "click" instead of [default] for me by default

**Comment by zaknafean** [comment]
This is fixed in #878
