### ISSUE TITLE
Clicking on the "Themes" icons causes Godot to crash

### ISSUE THREAD

**Issue by lani-KKS** [coppolaemilio/dialogic#842]
## The problem

**Describe the bug**
Everytime I click on the "Themes" icon in the toolbar, the blue circle next to mouse icon appears on screen to indicate that theme editor is about to appear, then suddenly Godot exits. When I reopen Godot, in the master tree, under the Themes folder it shows that a theme has been created, but when I click on theme that has been  created in the master tree the same issue occurs; the blue circle appears next to the mouse then Godot exits. 

**To Reproduce**
1. Simply click on the Themes icon in the Dialogic Tab. 

**System (please complete the following information):**
 - OS: Windows 10 
 - Godot Version: 3.3.2
 - Dialogic Version: 1.4.1

## Solutions

**Workaround**

I reinstalled a previous version(version:1.2.5)of Dialogic.

**Comment by Jowan-Spooner** [comment]
This is very strange and I cannot manage to recreate this. Maybe try updating to godot 3.4.4 if there is no reason not to. 

You can also create resources by right clicking the folder and selecting 'Add Theme' but it sounds like your problem has more to do with the theme editor, then with the toolbar button.

**Comment by zaknafean** [comment]
Downloaded 1.4.1 with Godot 3.3.2, using windows 10. Can not recreate this issue at all. If you can give a log output of some kind, or try the latest main branch, and the problem maintains, we can look into this again.

**Comment by zaknafean** [comment]
Closing this issue as no developer can recreate it in the current main branch.
