### ISSUE TITLE
Choice button styles not saving

### ISSUE THREAD

**Issue by nookstray** [coppolaemilio/dialogic#845]
## The problem

**Describe the bug**
The choice button background textures and text color reset every time I open Godot. It seems to only be the choice buttons that get affected by this.

**To Reproduce**
1. Go to Choice Buttons and change them.
2. Close and open Godot.
3. They reset to their default state. (for me, at least)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.3.3
 - Dialogic Version: 1.4

**Comment by Jowan-Spooner** [comment]
Hi, thanks for the report. I cannot manage to recreate this. 
The only thing I can see that is different is that I used godot 3.4.4. Not sure if thats the cause or something else I missed. 
If you could test with godot 3.4 or try to test this again under different circumstances, it would be apreciated.

**Comment by sebsobb** [comment]
Hello! I updated Godot and the choice buttons broke even more. They don’t show the choice hover image through key inputs anymore and only do so through mouse inputs. This was not an issue before I updated. Also, the text color is only applying to one choice and not the other. Should I delete Dialogic and reinstall it again? It seems to be the only plausible solution to this problem.

**Comment by zaknafean** [comment]
Trying to recreate it on main branch with Godot 3.4.4 and unable too either. Button choice styles work as expected

**Comment by pjalsGit** [comment]
I also have this problem but with timelines, characters, themes, etc.
