### ISSUE TITLE
Clicking on android don't work

### ISSUE THREAD

**Issue by hicchanwan** [coppolaemilio/dialogic#848]
Hi!
I ported my game with Dialogic to my android device. I created an instant dialog appearance in the scene. Choose event works well, but text events don't respond. In theory, by clicking on the screen, the following text should appear, but instead - nothing. Maybe this problem has already been discussed here? If you can tell me how to solve it, I will be grateful. 
Thanks

Android: 12
Godot: 3.4.3 stable

**Comment by hicchanwan** [comment]
I solved this problem by adding a condition in the DialogNode file.tscn at the moment where the _input() function works. Where *if not Engine.is_editor_hints() and event.is_action_pressed(Dialogic.get_action_button()):* understands only mouse clicking on PC, but when importing to Android, mouse or click emulation does not work at all. I added a second condition for touchscreens *if not Engine.is_editor_hints() and InputEventScreenTouch:*. Everything is working well now. I hope this will help you fix similar problems

**Comment by Jowan-Spooner** [comment]
Hi. I can confirm that the dialog doesn't respond to touch input as one would expect and because I think it would be a good thing to suport out of the box I will reopen this issue.

**Comment by thebardsrc** [comment]
on my Android tablet, i found that its because the touchscreen isn't Device 0, which is what we have the default for mouse clicks set to. I had to change mine to All Devices Left Button insead of Device 0 Left Button

![image](https://user-images.githubusercontent.com/2214793/160294133-048d3de8-30da-4a2e-ac78-ee9089919672.png)

(this projects from before dialogic_default_action was created but that's where it would need to be updated)

**Comment by zaknafean** [comment]
Adding this line to DialogNode

```if not Engine.is_editor_hint() and (event.is_action_pressed(Dialogic.get_action_button()) or event is InputEventScreenTouch):```
![image](https://user-images.githubusercontent.com/7741797/165870167-2e6c1abe-c7d9-4748-be3c-a5aec562fd9b.png)

Also just makes dialogic advance with any touch. Some solution is definitely needed, and we have alot of options.
