### ISSUE TITLE
Theme resize doesn't trigger on different theme anchor

### ISSUE THREAD

**Issue by qskousen** [coppolaemilio/dialogic#856]
## The problem

When characters have special themes, the theme main_resize function in `DialogNode.gd` doesn't trigger if the box size is the same but the anchor is different.

**To Reproduce**
1. Create 2 themes that have the same size but different anchors.
2. Create 2 characters and assign one character the non-default theme.
3. Create a dialog between the 2 characters.
4. Play the dialog. The box will not move to the new anchor position on switching themes.

**Expected behavior**
The resize function should run when the new theme has a different anchor than the current theme.

**Screenshots**

**System:**
 - OS: Linux
 - Godot Version: 3.4.4
 - Dialogic Version: 1.4.1

## Solutions

This can be solved by comparing the anchor position as well as the size when determining if the main resize needs to be run.

https://github.com/coppolaemilio/dialogic/blob/239feb7d2b673ad99969c3e000070416f07178ae/addons/dialogic/Nodes/DialogNode.gd#L306

I have created a fix for this that I would be happy to submit but it might be a little hacky.

**Comment by coppolaemilio** [comment]
If your PR fixes this one feel free to close
