### ISSUE TITLE
MacOS: Dialog text does not appear

### ISSUE THREAD

**Issue by mcsantiago** [coppolaemilio/dialogic#859]
## The problem

**Describe the bug**
When a dialog node is added to the scene, the dialog text does not appear. However, the number of events remain the same. 

**To Reproduce**
1. Create a timeline
2. Add a Text event with any text and character
3. Play Timeline, or add dialog node to any scene
4. See only a gray rectangle at the bottom and a dark gray background

**Expected behavior**
When a dialog is added, the text from within the text event should be visible.

**Screenshots**

![Screen Shot 2022-04-03 at 9 59 49 PM](https://user-images.githubusercontent.com/8943898/161466841-1814061b-991c-470f-9eb9-40f80d13aad9.png)

**System (please complete the following information):**
 - OS: macOS Monterey Version 12.0.1
 - Godot Version: 3.4.1
 - Dialogic Version: 1.4.1

## Solutions

**Workaround**
No workaround found yet.

**Possible fixes**

**Comment by Jowan-Spooner** [comment]
Have you changed your window size?

**Comment by mcsantiago** [comment]
I just tried resizing the window. Still no effect :(

**Comment by Jowan-Spooner** [comment]
@mcsantiago I was asking because it looks a lot like the dialog is appearing but is HUGE, so you only see the bottom part of the panel. This happens if you set the window size of your project in the setting to something tiny like 300x150 or so (often for pixel-art games). You can fix that if you adjust the box and font size in the dialogic theme. Otherwise I don't know what could cause this.

**Comment by mcsantiago** [comment]
Oh I see. Yes this project was originally started as a pixel art game. Then I thought it would be better as a sort of 2.5D game. I forgot that I had the window size set to that 350x190 range. Project Settings > Display > Window to adjust the window size. I'm not really sure if this is a bug at this point rather than user error. You can close this if you want.

**Comment by zaknafean** [comment]
Per user, closing this.
