### ISSUE TITLE
Automatic export of *.cfg and *.json doesn't work

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#862]
I'm investigating why. It did work in 1.3, just tested it again there.

**Comment by zaknafean** [comment]
This still going to be an issue in 2.0?

**Comment by coppolaemilio** [comment]
No, we are not going to be using any custom file type that won't be added by Godot automatically

**Comment by zaknafean** [comment]
Can probably close this. The mechanism used to 'export' automatically in 1.3 is incompatible with android exports, I'd rather just have people do the export procedure properly.
