### ISSUE TITLE
Inconsistent naming convention

### ISSUE THREAD

**Issue by AnidemDex** [coppolaemilio/dialogic#864]
## The problem
Names in code are not the same as the ones show in the editor:

- [ ] `Dialogic.[set|get]_variable` is the same as dialogic **definition**s

I've created this issue as an issue tracker just in case there were more inconsistences between the code and the name used in editor.

**Comment by thebardsrc** [comment]
to further compliate this, it's an inconsistency not with the name _definitions_ but with _values_. Dialogic has Value and Glossary both as subtypes of the Definitions. the set/get_variable functions only operate on Values, they don't work with Glossaries

**Comment by Jowan-Spooner** [comment]
It seems very likely that this will not translate to dialogic 2.0. 
It will only use the words
- variables
- glossary entries
Thus I would close this issue
