### ISSUE TITLE
CustomEvent.svg needs updating to new style

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#867]
## The problem

**Describe the bug**
One of these things is not like the others
![image](https://user-images.githubusercontent.com/7741797/163821237-b62fca8a-228d-4af7-a13b-6769550e3331.png)

**System (please complete the following information):**
 - Dialogic Version: 1.4.1

## Solutions

**Possible fixes**

Emilio halp!

**Comment by coppolaemilio** [comment]
I'll merge a new one whenever I can 😅

**Comment by coppolaemilio** [comment]
pushed a new icon! feel free to re-open if needed
