### ISSUE TITLE
suport to godot 4.x and gdscript 2.0

### ISSUE THREAD

**Issue by Rodemarck** [coppolaemilio/dialogic#870]
the code of gdscript are not compatible with gdscript 2.0. Lots of changes in syntax and more. Since godot 4.x is still alpha, i suppose need to new branch to support the changes in alpha version.

**Comment by zaknafean** [comment]
The Dialogic 2.0 work is intended to work with Godot 4.0, so that branch should handle it. You can take a peak at that progress here: https://github.com/coppolaemilio/dialogic/branches

**Comment by coppolaemilio** [comment]
What @zaknafean said!
I'll close this one as it is not an issue per se, but as soon as Godot 4 beta is out we will start working on it :)

**Comment by Rodemarck** [comment]
thx, and sorry

**Comment by coppolaemilio** [comment]
No worries! Thanks for creating the issue, don't feel discouraged to create other issues whenever you need to 👍🏻

**Comment by AnidemDex** [comment]
As an additional note, Godot 4 is stills in alpha, Wich means that a lot of core things there can be broken or dropped without advice, discarding a lot of work that can be made to be compatible with that version.

Support for Godot 4 is planned, for beta version (to avoid losing time in the integration) as already mentioned
