### ISSUE TITLE
timeline_start and timeline_end doesn't work in the 1.4 version of dialogic

### ISSUE THREAD

**Issue by EXSPIRAVIT1104OFFICIAL** [coppolaemilio/dialogic#872]
## The problem

**Describe the bug**
The automated signal timeline_start and timeline_end dont work in the 1.4 version of dialogic.

**To Reproduce**
setup like this and use the start_dialog() to input any timeline, and do something like a print() to see if the function is being called automatically.
![微信图片_20220420171719](https://user-images.githubusercontent.com/80319225/164195289-5bdf2ef6-d235-4d7c-a016-6687f3295389.png)

**Expected behavior**
the connected functions of the signal should be called as the "How do I use signals with Dialogic?
" part of the FAQ in the Help document, but it didn't.

**Screenshots**
![微信图片_20220420171719](https://user-images.githubusercontent.com/80319225/164195289-5bdf2ef6-d235-4d7c-a016-6687f3295389.png)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.4.4
 - Dialogic Version: 1.4

## Solutions

**Workaround**

Couldn't, since I don't know anything about the script, but I did see the signal timeline_start or timeline_end in the Dialogic script.

**Possible fixes**

maybe it is because the 1.4 version had a new way of sending the signal, which caused this to stop working?

**Comment by zaknafean** [comment]
Can confirm that **timeline_start** signal is spotty at best. The other signals seem fine in main branch, so troubleshooting that for now.,

**Comment by zaknafean** [comment]
It appears that timeline_start occurs consistnetly if you connect the signals before you add to child. IE:
This is good:
![image](https://user-images.githubusercontent.com/7741797/166522866-817d6bbc-3213-4eb5-9f9b-25a62ab834aa.png)

But this is bad:
![image](https://user-images.githubusercontent.com/7741797/166522898-3917bc79-4f03-494f-baeb-b8c1a06c0a82.png)

We will leave this open until we update the docs and tutorials to reflect this.

**Comment by chao-mu** [comment]
I've run into the same (?) issuer with timeline_end seemingly never being emitted:

```gdscript
	
func show_dialog(timeline_name: String) -> void:
	pause()
	var dialog = Dialogic.start(timeline_name)
	dialog.pause_mode = Node.PAUSE_MODE_PROCESS
	dialog.connect('timeline_end', self, 'unpause')
	add_child(dialog)
	
func pause() -> void:
	get_tree().paused = true
	
func unpause() -> void:
	print("hi")
	get_tree().paused = false
```

"hi" never prints and the scene is not unpaused, despite the dialog ending. The timeline consists of just a text event and a "close dialog" event.

**Comment by chao-mu** [comment]
I figured it out when I actually checked the debugger for errros:

E 0:00:08.030   emit_signal: Error calling method from signal 'timeline_end': 'Node(Helpers.gd)::unpause': Method expected 0 arguments, but called with 1..
  <C++ Source>  core/object.cpp:1236 @ emit_signal()
  <Stack Trace> canvas_dialog_node.gd:70 @ _on_timeline_end()
                DialogNode.gd:549 @ on_timeline_end()
                DialogNode.gd:873 @ event_handler()

This seems to be the same issue @EXSPIRAVIT1104OFFICIAL is experiencing: the callbacks are expected to receive arguments that our function definitions don't have.

Here is my WORKING code

```gdscript
func show_dialog(timeline_name: String) -> void:
	pause()
	var dialog = Dialogic.start(timeline_name)
	dialog.pause_mode = Node.PAUSE_MODE_PROCESS
	dialog.connect('timeline_end', self, '_on_timeline_end')
	add_child(dialog)
	
func _on_timeline_end(_type):
	unpause()
	
func pause() -> void:
	get_tree().paused = true
	
func unpause() -> void:
	print("hi")
	get_tree().paused = false
```

**Comment by Jowan-Spooner** [comment]
Closing as this is user error. 
For anyone seeing this later:
- make sure to connect the signals BEFORE adding the dialog node to the scene
- make sure to add a argument to your method (even if you don't use if)
