### ISSUE TITLE
Features for dialogues with many characters. (for version 2.X)

### ISSUE THREAD

**Issue by EmmanuelHuazo** [coppolaemilio/dialogic#884]
In my game, I tend to have scenes with 3 or more characters, so sometimes they get behind other characters and it's tedious to add an "update node" just to get that character upfront before he talks.

Also, it would be great if we can change the position on the screen cause my characters are way in the middle even when I select the first and last position.

And also, it would be great if you can add a "Y offset value" in the "update character node" that let us move the player besides the predetermined position, in my case to hide a shy character behind other.

Can you also change the "Join character node" to add multiple characters at a time with only one node?

I have all the characters in different positions, but they look way pile up.

![image](https://user-images.githubusercontent.com/79464276/166158723-16311982-132f-4b51-afe9-d0241865c587.png)

![image](https://user-images.githubusercontent.com/79464276/166158696-706ea1f2-80b3-4676-86bc-6ea71883f068.png)

When "Dom" is talking he is still at the back...

![image](https://user-images.githubusercontent.com/79464276/166158808-18d5edeb-57bb-4d8f-bc49-cf4f85b04bf3.png)

AND FOR LAST PETITION: Can you change the way Dialogic show where a node is going to be put? It moves the other nodes and that makes me confused about where I wanted to place it since my screen is not high resolution and sometimes where I wanted to place it disappears from the screen if I have other nodes open. Other software, instead of creating a preview of where it will be placed, put bars or indicators of where it will be without moving the nodes down. 

How Dialogic works:

![image](https://user-images.githubusercontent.com/79464276/166158962-912c9fa5-6a1c-4eac-ba23-680691fd057d.png)

Reaper highlight with a blue bar where the channel is going to be moved.

![image](https://user-images.githubusercontent.com/79464276/166158952-11f6cc54-6406-4496-9e8d-fec8228bb182.png)

.

**Comment by AnidemDex** [comment]
https://github.com/coppolaemilio/dialogic/discussions/751 updated

**Comment by Jowan-Spooner** [comment]
Update on this: 
Positions can relatively easily be changed in 2.0. There is also a Position event that allows to move a position and the characters that are on it.
For the multiple characters to join with one event, I'm not sure how to do it, but we should simplify the event so it's smaller by default. It already is a bit smaller by default: 
![grafik](https://user-images.githubusercontent.com/42868150/196286982-dd8ece99-f26a-492e-93e2-38fa42dde5a4.png)

For the preview of moving events, maybe we can do that.
I might make this into multiple issues though, as this is quite much in one. Will probably do tomorrow.

**Comment by Jowan-Spooner** [comment]
I have created #1282, #1283 and #1284. I hope that is all of the requests from this that still need to be implemented for 2.x. 
Will close this now.
