### ISSUE TITLE
Name label disappears after question

### ISSUE THREAD

**Issue by pjalsGit** [coppolaemilio/dialogic#899]
## The problem

**Describe the bug**
For some reason, when I make a question to a character with a custom theme, the name label of the next character disappears.

**To Reproduce**
1. Make a question
2. Put a text event in the choice branch
3. Play timeline
4. See that name label disappears

**Expected behavior**
For the name label not to disappear.

**Screenshots**

https://user-images.githubusercontent.com/25231103/168756056-e5835b87-894f-4b98-99ea-0e9cf5fc0819.mp4

(yea i had some fun making the bug report)

Niko's custom theme has "Hide name labels" off.
Player's custom theme has "Hide name labels" on.

**System (please complete the following information):**
 - OS: Fedora Linux 35
 - Godot Version: 3.3.3.stable, tested also with 3.4.4.stable
 - Dialogic Version: [2efa1a0](https://github.com/coppolaemilio/dialogic/commit/2efa1a092143c10bff344539b904e84328f8cdc1)

## Solutions

**Workaround**

Disable name labels and act like it didn't happen.

**Possible fixes**

Not sure.

**Comment by Yotopihi-Dev** [comment]
It's fading cause you didnt add a character join event for the player **_lol_**

**Comment by zaknafean** [comment]
My hunch was right. It was the same root issue as #893. This is now fixed in the main branch.
