### ISSUE TITLE
Resources unavailable in HTML game

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#90]
* **Dialogic version**: rc_1.0
* **OS**: Ubuntu 20.04

## Summary

Resources such as images are not loaded Web game.

## The problem

**Steps to reproduce**

* Create a new game with this plugin
* Create a new character with a portrait
* Export the game as explained in the [readme](https://github.com/coppolaemilio/dialogic#-why-are-the-dialogs-are-not-working-when-exporting-my-project)
* Start the game on web, you will not see your character portait

**What is the current behavior?**

When exporting a game, characters portraits are not loaded. Did not try scenes but it might have the same problem.

**What is the expected correct behavior?**

Portraits should show like the rest of the game.

## Solutions

**Possible fixes**

According to the [documentation](https://docs.godotengine.org/en/stable/classes/class_file.html#class-file-method-file-exists), `file_exists` method should not be used to check for resources as their names are changed inside the packed resources. Instead, [`ResourceLoader.exists`](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-exists) should be used.

So to fix this issue, it should be enough to replace `file_exists` when checking for resources availability by `ResourceLoader.exists`.

**Comment by coppolaemilio** [comment]
Are you going to work on this one or should I?

**Comment by arnaudvergnet** [comment]
I can do it if it saves you some time
