### ISSUE TITLE
Allow for the changing of character portrait after dialogue has finished printing.

### ISSUE THREAD

**Issue by VoxelTek** [coppolaemilio/dialogic#906]
**Is your feature request related to a problem? Please describe.**
I'm trying to recreate an Ace Attorney type scene, and in Ace Attorney, the characters have an animation where their mouths move while the dialogue is being printed, but after it's printed, they return to a normal, non-talking animation. Dialogic has no way to change a character's portrait after the dialogue has finished printing, only after the dialogue is advanced. This would result in either characters not moving their mouths when dialogue is being printed (as the portrait would be set to the non-talking animation) or characters continue to move their mouths even after dialogue has completed printing.

**Describe the solution you'd like**
I would like some way to be able to change the character's portrait after dialogue has finished printing. This would allow me to change the portrait back to a normal, non-talking animation.

**Describe alternatives you've considered**
Alternatively, another possible solution would simply be allowing the emission of a custom signal when dialogue has finished printing.

**Additional context**
N/A.

**Comment by coppolaemilio** [comment]
This can probably be achieved with signals, but I'll keep the issue open to make sure it is easy to execute.

**Comment by Jowan-Spooner** [comment]
In 2.0 (WIP) we have a [portrait=portraitname] command for text events. Do you think that would be enough for you?
