### ISSUE TITLE
Choice Option menu blocks Glossary Hover

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#907]
## The problem

**Describe the bug**
From Winking in Discord.  "why does hovering over the words with definitions not work in a choice event. Is this just user error or some kind of setting?"

![image](https://user-images.githubusercontent.com/7741797/170607329-44e5b9b4-9d46-49b9-a078-ef16d92012c5.png)

The answer to their question is that the Mouse filter, when set to **Pass**, rather than **Ignore**, seems to block mouse hover. Easy fix, but the question is:

Was there a real reason it was set to Pass? Does setting it to ignore break anything else? Whats your opinions @Jowan-Spooner @coppolaemilio

**Comment by coppolaemilio** [comment]
Not sure if it is the same, but I remember we did a fix to an error like this before? My brain 🥲

**Comment by zaknafean** [comment]
Fixed with #909
