### ISSUE TITLE
Broken signals?

### ISSUE THREAD

**Issue by JWBWork** [coppolaemilio/dialogic#912]
**The Problem**
I seem to only be able to connect one signal to a dialogue instance - and then this signal is only emitted at the end of the conversation

Here's what I'm currently trying:

**To Reproduce**
```gdscript
func enter_dialogue():
	if dialogue_node == null:
		Dialogic.set_variable("woman_name", character.woman_name)
		dialogue_node = Dialogic.start(dialogue_script)
		character.add_child(dialogue_node)
		dialogue_node.connect('timeline_end', self, 'exit_dialogue')
		dialogue_node.connect('dialogic_signal', self, 'dialog_listener')
	elif is_instance_valid(dialogue_node) and not dialogue_node.is_inside_tree():
		character.add_child(dialogue_node)

	if is_instance_valid(dialogue_node):
		dialogue_node.get_child(0).show()

func dialog_listener(d_signal):
	print("processing dialogic signal ", d_signal)
	if has_method(d_signal):
		call(d_signal)
		# callable.get_object().callv(callable.get_method(), args)

func exit_dialogue(_info=null):
	print("exiting dialogue")
	dialogue_node.queue_free()
	.exit()
```

**Expected behavior**
In my timeline I emit `dialogic_signal` at the very start - I expect it to emit at that point in the dialogue, but it doesn't fire until the end. If I connect two signals, like I do below, then depending on the order only `dialogic_signal` emits, or `timeline_end` emits _twice_ - either way it's at the end of the dialogue's timeline

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.4.4
 - Dialogic Version: occured on both 1.4.1 and 1.4.2

**Comment by zaknafean** [comment]
Connect the signals before you add the child. The signals are firing off before you can react to them.

**Comment by JWBWork** [comment]
> Connect the signals before you add the child. The signals have fired off before you connected them.

🤦🏻‍♂️ ... yep - that did it
thanks!
