### ISSUE TITLE
Game don't open

### ISSUE THREAD

**Issue by kakurokan** [coppolaemilio/dialogic#913]
## The problem

**Describe the bug**
My game simply don open, and when I see in the with debug versions, i see this.

**
![image](https://user-images.githubusercontent.com/67524990/171496946-05d0aeea-6345-4162-91b9-878355780346.png)
**

**Comment by zaknafean** [comment]
Need more info. This an export? Windows? What version of dialogic?

**Comment by kakurokan** [comment]
An export, Windows 10 and version 1.4.1. Sorry for that.

**Comment by kakurokan** [comment]
Thank you, it's the problem of this comment. I will check

**Comment by zaknafean** [comment]
Duplicate of #898
