### ISSUE TITLE
Dialogue Box is not showing during timelines within itch.io export

### ISSUE THREAD

**Issue by locherunderscore** [coppolaemilio/dialogic#917]
# Dialogue Box is not showing during timelines within itch.io export

I am using version 1.4.2.
Whenever I display a timeline, images and delays are working as expected but all dialogboxes dont show up at all.

## How it should look like (when playing the Project within Godot)
![grafik](https://user-images.githubusercontent.com/45494626/172059736-7187b595-f9cb-44a3-9d70-a199d43c058c.png)

## How it currently looks like (after exporting it onto itch.io)
![grafik](https://user-images.githubusercontent.com/45494626/172059801-1b493ec9-cf99-4939-82af-471c8a4b11df.png)

# Assumptions
It's as if not all ressources are included in the export.
But even after exporting all resources and dependencies, it cannot be solved.
![grafik](https://user-images.githubusercontent.com/45494626/172059924-a65c9127-eb35-4178-a32a-aa45beeb457a.png)

# How my project implements the display of timelines
![grafik](https://user-images.githubusercontent.com/45494626/172060033-73c751f0-6b77-4a0c-87c7-ee653633641c.png)
Due to the fact that Timelines are triggered at all, there should be no problem with implementation.

It's as if either the dialog box is displayed behind everything or that the dialogbox with text is displayed with max transparency.
I've first been using Dialogic with the working version 0.3 dialogs and then upgrading it to 1.4.2 Dialogics but the problems are still the same. Maybe itch.io doesn't allow addons?

**Comment by locherunderscore** [comment]
# Workaround
After reading through #914 and duplicating the Default Theme, the dialogboxes are now visible.
I will close this issue although it would be nice if a future update could address this issue.

**Comment by zaknafean** [comment]
Dupcliate of #898
