### ISSUE TITLE
Error while installing - MasterTree

### ISSUE THREAD

**Issue by Aruurunnn** [coppolaemilio/dialogic#926]
I'm trying to follow along with [Emilio's "Getting started with Dialogic" video](https://www.youtube.com/watch?v=sYjgDIgD7AY) but I'm not able to progress into the "create a character" part because the button doesn't respond on click and I get this error code:

` core/object.cpp:1228 - Error calling method from signal 'pressed': 'Tree(MasterTree.gd)::new_character': Method not found..` 

I'm on windows 10 and have the latest version of godot and dialogic.

![image](https://user-images.githubusercontent.com/107468157/173554804-79a89950-5809-4fb5-8fe5-0df40fa70257.png)

**Comment by coppolaemilio** [comment]
You need to have at least Godot 3.4 to run Dialogic. From the screenshot I see that you are running version 3.2.1.
Let me know if that fixes your issue!

**Comment by coppolaemilio** [comment]
I'm closing, but feel free to re-open
