### ISSUE TITLE
Idle animations for characters

### ISSUE THREAD

**Issue by SJcoded** [coppolaemilio/dialogic#929]
**Is your feature request related to a problem? Please describe.**
Static characters are cool but a small 2-frame animation during the discussion would bring dialogic to life!

**Describe the solution you'd like**
A way to import a sprite sheet (we can limit it to 2-frames) and transition between frames on a loop with a custom duration.

**Describe alternatives you've considered**
Other alternatives involve excluding dialogic from the loop. Say adding a custom animated sprite next to the dialogue box and listening to dialogic's signals in order to swap the sprite out ~ using dialogic's portrait but with an option to import a sprite sheet would be a fantastic experience for devs and players.

**Comment by zaknafean** [comment]
So you can actually use any scene you want as a portrait, not just an image, already! With signals and hacking the Text Bubble class you can even get lip flaps working as letters type, though that's up to you to get right.

**Comment by SJcoded** [comment]
> 

Absolutely fantastic, had no idea this was implemented already! Anywhere I can find more info?
