### ISSUE TITLE
Definitions broken on HTML5?

### ISSUE THREAD

**Issue by linux-man** [coppolaemilio/dialogic#94]
I can't make it work, but there are no console errors!
![image](https://user-images.githubusercontent.com/1733538/111849363-52af6400-8905-11eb-9ebb-2a9444f70f23.png)
If later, at the same timeline, I try to use "a" with
![image](https://user-images.githubusercontent.com/1733538/111849457-90ac8800-8905-11eb-98e2-414287a1919b.png)
Nothing happens.

**Comment by coppolaemilio** [comment]
I tried to compile a dialogic project for HTML5 for the first time and I can confirm that this is not working. I'm not sure what the issue could be... I'll keep investigating and see if I find some information

**Comment by coppolaemilio** [comment]
It can be related to this issue: https://github.com/coppolaemilio/dialogic/issues/95

**Comment by linux-man** [comment]
You're probably right, if Definitions aren't stored in-memory during a timeline.
Also, I suspect that the advice "copy the dialogic folder to the same place where the executable of your game is" should be dropped. There are too many cases where that folder is read-only, or not accessible (like on HTML5).
