### ISSUE TITLE
An error occurred when trying to access the custom event folder. [linux]

### ISSUE THREAD

**Issue by theVoidZ** [coppolaemilio/dialogic#942]
## The problem
Simple project, i created a character, few timeline with few conversations. The Dialog box runs fine on the Editor, but when exported as Release, the game Crashes. 

**To Reproduce**
1. Create Timeline for test.
2. Invoke the Timeline in the GameLogic
```gd
	var d = Dialogic.start("boss_warning")
	add_child(d)
```
3. Export the Game ( linux ) Release.
4. Run from Console. 
5. When the Dialog box is about the pop. the Game Crashes.

Error. `[D] An error occurred when trying to access the custom event folder`

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 3.4.4 ( Just FYI. pre-compiled godot binaries with Godotsteam )
 - Dialogic Version: 1.4.1 and 1.4.2 - Dev

**Comment by coppolaemilio** [comment]
Have you tried some solutions already listed in other issues? Not sure what happened with the latest versions of Godot but it broke our 1.4 exports for some reason.

- https://github.com/coppolaemilio/dialogic/issues/928
- https://github.com/coppolaemilio/dialogic/issues/917
- https://github.com/coppolaemilio/dialogic/issues/898

Let me know if it was any of those help!

**Comment by theVoidZ** [comment]
Hi, 
So The Override default Theme Fixed it. it runs in production mode without extra steps of exporting.
1 - Create a new Theme.
2 - Set the newly created theme as Default in `Settings` at Dialogic Tab
