### ISSUE TITLE
Reimplement settings

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#963]
This is a list of settings that should be (re)-implemented for 2.0:

Remiplement:
- [x] Default theme name
- [x] Autofocus first choice button
- [x] Choice delay
- [x] Next Action (previously "Default Action Key")
      -> should be renamed because it's an action not a key
- [x] Choice hotkeys
- [ ] New lines -> extra message
- [x] Autocolor character names
- [x] Autosave (see #951)
- [x] Single -portrait mode (maybe a different name)
      -> no need to join characters, only portrait position 1 will be used

Add:
- [x] Default action for false choices (Hide/Disable)
- [x] Custom events folder path?
- [x] Default text speed
- [x] Allow skipping
- [x] Auto continuing (on/off + wait_time) (global [nw])

**Comment by coppolaemilio** [comment]
Do you feel good closing this one?
