### ISSUE TITLE
Create good default theme and multiple example dialog nodes

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#965]
I would suggest:
- one dialog node that tries to be as similar to the default dialog node and theme of 1.x as possible
- a dialog bubble like dialog node
- a dialog node with one/two portraits inside the dialog box

**Comment by pjalsGit** [comment]
Also it would be nice to have a RPG-style dialog box because making that in 1.x was such a nightmare.
