### ISSUE TITLE
Reimplement Text Commands

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#966]
- [x] speed
- [x] signal
- [x] pause
- [x] portrait (to change the characters portrait)
- [x] br
- [x] [word1,word2,word3] -> select a random word
     - [x] allow `\,`
- [ ] nw (would rename this tho, and make it a global setting)

- [ ] noskip # suggestion by @thebardsrc to not allow skipping on this event

**Comment by pjalsGit** [comment]
Regrading [x,y,z], maybe this: https://github.com/coppolaemilio/dialogic/issues/971 should also be added here.

**Comment by zaknafean** [comment]
A 2nd vote for 'noskip'. May honestly backport that to 1.4.3. I badly need a nw, noskip option for cutscenes.
