### ISSUE TITLE
Allow escaping "," in square brackets (Version 2.0)

### ISSUE THREAD

**Issue by pjalsGit** [coppolaemilio/dialogic#971]
**Is your feature request related to a problem? Please describe.**
So I have a character that strictly speaks in square brackets (how inconvenient!), and I want to use the character `","` in their sentences.
The problem here, is that `","` in square brackets will select a random string from that list.
This is also a problem in 1.x, but that version isn't accepting new features anymore.

**Describe the solution you'd like**
If I use `"\,"`, it should escape , and disable random string selection.

**Describe alternatives you've considered**
None.

**Additional context**
None.
(wait did I forget to flag it as feature or is there no automatic tag assignment system?)

**Comment by Jowan-Spooner** [comment]
Hi, how exactly does your character speak in "square brackets"? You mean you want the brackets to print in the dialog box?
We can implement the \, for sure. Maybe I can do it today.

**Comment by pjalsGit** [comment]
I mean like, instead of 
` Hello, this is example text!`
The character says:
`[Hello, this is example text!]

**Comment by Jowan-Spooner** [comment]
Hmmm... I think it would be better to then add `\[` as a way to say: this bracket does NOT start a special block. 
This should be fairly easy to implement as well.

**Comment by Jowan-Spooner** [comment]
Alright, the 2. PR is merged. 
In 2.0 you can now write:
```
\[This is text in brackets]
[This is randomly selected\, isn't it., This is something else.]
```
and get
```
[This is text in brackets]
This is randomly selected, isn't it.
```
I hope this is helpfull to you.
