### ISSUE TITLE
Change Speed/Settings of a Dialog During Timeline Execution

### ISSUE THREAD

**Issue by ellogwen** [coppolaemilio/dialogic#99]
I just fiddled around a bit with your amazing plugin, but stumpled on something I couldn't find out how to implement.
I have a dialog with default speed of 2. While the timeline is running, I want to change the speed of the text to 100 but just for one sentence. Is there a way to do this? I tried to use bbcode, but couldnt find the right vars. I want to accomplish something like that

```
This is strange, [speed=100]very strange[/speed]
```
If there is no bbcode tag available, is there a way to access the current dialogs settings with using the Set Var node? But this would only work for whole chat nodes and not for single sentences. I will try it with a custom RichtTextBox effect in the meantime.

Maybe you can add something like this `[dialogic speed=100]test[/dialogic]`

Edit: Okay, you cannot slow down / access the speed inside a RichTextEffect. Darn.

**Comment by ellogwen** [comment]
Ok, since you use a tween for determing the total length times the character count, changing the speed inbetween would not work aswell.

**Comment by arnaudvergnet** [comment]
You could create a new theme with a high text speed, then trigger a theme change just before the chat node you want sped up, then after this node switch back to previous theme. This will allow different speeds between nodes, but yeah I don't think it is possible mid-sentence

**Comment by coppolaemilio** [comment]
Like Arnaud said, the theme is the one dictating the speed not the bbcode, so it is not possible to change using any custom tag. I could explore adding more granular customization inside the text messages in the future, but for now you will have to make different themes for different messages.

**Comment by Crystalwarrior** [comment]
Why not ditch bbcode and do something like this instead?
`\t{100}\e{armscrossed}`That thief `\t{40}`you ran into `\t{100}\e{normal}\s`should be your `\f`real suspect, `\t{100}\e{smug}`wouldn't you say?

\t = time, ms per letter OR percentage of global theme speed like 0.5
\e = emote, aka change character portrait mid-text
\f = screen flash
\s = screen shake

**Comment by ellogwen** [comment]
@Crystalwarrior then problem ist not the syntax. furthermore, Godot has builtin functionality for bbcode and RichTextEffects per character to do shake and complex text effects. It would gain nothing to ditch this already done work in favor of a new syntax. 
The problem however, is not related to bbcode or any text rendering at all, it's how the animation is implemented within the plugin, using a Tween and calculating the length for the whole text box in advanced.
In order to achieve mid sentence speed changes you would need chain multiple tweens or find another solution how you playback the scrolling.

**Comment by Crystalwarrior** [comment]
> @Crystalwarrior then problem ist not the syntax. furthermore, Godot has builtin functionality for bbcode and RichTextEffects per character to do shake and complex text effects. It would gain nothing to ditch this already done work in favor of a new syntax. 
> The problem however, is not related to bbcode or any text rendering at all, it's how the animation is implemented within the plugin, using a Tween and calculating the length for the whole text box in advanced.
> In order to achieve mid sentence speed changes you would need to chain multiple tweens or find another solution how you playback the scrolling like manipulation the time scale of the tween mid running.

That's a good point. I guess a different syntax can simply be built on top after the internal bbcode one, and even then it doesn't have to be the plugin responsibility.

Regarding the tween - I agree! I suggest replacing it with a looping timer instead.

**Comment by coppolaemilio** [comment]
A looping timer could be an interesting solution to the problem. I'll look into it 👍🏻

**Comment by coppolaemilio** [comment]
I replaced the tween with a timer, now I'll see the best way to implement the mid-text tags

**Comment by Nemesis-AS** [comment]
Maybe look for the number of tags and their positions in the text before displaying it, and calculating the amount of loops needed and their duration in an array?
Eg, Text- `Hello \t{100}World!`
Array - `[50, 100]` where the first element is the default from the theme

**Comment by coppolaemilio** [comment]
A tag `[speed=2]` (or whatever number you want) has been added to text events. It will change the speed for that particular event and then go back to the theme default speed.

Still not able to change it mid sentence, but this is much better than making a new theme to change the speed.

**Comment by coppolaemilio** [comment]
I will close this one and reopen again if someone needs the tag happening mid sentence.

**Comment by stephanbogner** [comment]
Would love to see this feature happen to emphasize certain words in the dialog / express hesitance in the character talking.
I could also contribute if pointed into the right direction … or has it already been implemented? (Haven‘t checked the latest version yet)

**Comment by Jowan-Spooner** [comment]
@stephanbogner In 2.x (still in alpha) the speed effect works mid-sentence. So you can do
```
Do you know that [speed=2]a slow word[speed=1] feels emphasized but a [speed=0]instant reveal[speed=1] might feel rushed?
```
Note that the speed effect is a multiplier that affects both the letter-speed (can be set directly with the [lspeed=x] effect) as well as pauses [pause=x]. That's why speed=1 returns to the default speed, speed= 0 is instant and speed=2 is half as quickly.

**Comment by stephanbogner** [comment]
@Jowan-Spooner That sounds awesome! Thanks for clarifying and explaining. Will try it out!
