### ISSUE TITLE
Error calling method from signal 'timeline_end'

### ISSUE THREAD

**Issue by FoggyFella** [coppolaemilio/dialogic#990]
Error calling method from signal 'timeline_end'

I tried to implement Dialogic into my game using [this](https://www.youtube.com/watch?v=gZ3h09B7Utc&ab_channel=Emi) tutorial and I keep getting an error

```
func unpause():
	get_tree().paused = false
	active = false

func _input(event):
	if get_node_or_null('DialogNode') == null:
		if event.is_action_pressed("ui_accept") and active:
			get_tree().paused = true
			var dialog = Dialogic.start(timeline_name)
			dialog.pause_mode = Node.PAUSE_MODE_PROCESS
			add_child(dialog)
			dialog.connect('timeline_end',dialog,'unpause')
```

To Reproduce:
I did everything like in the tutorial.

System:
 - OS: Windows 10
 - Godot Version: [e.g. 3.2.3]
 - Dialogic Version:

**Comment by Jowan-Spooner** [comment]
You have to add an argument to the unpause() function (as emilio has in the tutorial):

```
func unpause(unused_argument):
    get_tree().paused = false
    active = false
```
