### ISSUE TITLE
Stopping Audio Not Working

### ISSUE THREAD

**Issue by exelia-antonov** [coppolaemilio/dialogic#996]
The audio event has a default value of nothing, and should stop audio playback like that. But currently it does not, it will do nothing. It can play audio files just fine, just does not stop any currently playing if it's left blank

**Comment by Jowan-Spooner** [comment]
Can you specify if this is for the 1.x or 2.x branch? Sorry these are confusing times.

**Comment by zaknafean** [comment]
This is 1.4.x. I'll be taking a peak later on it.

**Comment by Jowan-Spooner** [comment]
@zaknafean is this still relevant?

**Comment by zaknafean** [comment]
Not sure when it was fixed, but it is definitely working properly as of now.
