### ISSUE TITLE
Buttons on dialog box

### ISSUE THREAD

**Issue by M7mdKady14** [coppolaemilio/dialogic#997]
is there any way to make the buttons part of the dialog box at the bottom?

like there is the text in the box and below that are the buttons?

something like this
![An-example-of-the-exploratory-choice-taken-from-the-computer-roleplaying-game-Planescape](https://user-images.githubusercontent.com/104588917/178202258-80c62e73-0e92-4798-997d-01d984735ab7.png)

**Comment by M7mdKady14** [comment]
This is one 1.4 btw, but I am also curious about how to use 2.0 since there is no mention of how to install it

**Comment by Yotopihi-Dev** [comment]
2.0 Is in its alpha phase. It's estimated to be fully released by 2023. So I'd recommend leaving it aside as there are going to be a lot more bugs and errors going on in there if you start using it now. Although, you can find it by going into dialogics branches and selecting the 2.0 branch, I'll link it here too just so it's easier to find:

https://github.com/coppolaemilio/dialogic/tree/version-2.0

**Comment by Yotopihi-Dev** [comment]
> is there any way to make the buttons part of the dialog box at the bottom?
> 
> like there is the text in the box and below that are the buttons?
> 
> something like this ![An-example-of-the-exploratory-choice-taken-from-the-computer-roleplaying-game-Planescape](https://user-images.githubusercontent.com/104588917/178202258-80c62e73-0e92-4798-997d-01d984735ab7.png)

I'm not sure as I havent tried this before, but it shouldnt be too hard. But I believe if you go to **Theme>Choice Buttons>Placement**, You'll find an option called "Offset x/y" So from there, you can tinker with it until it reaches your desired spot

**Comment by zaknafean** [comment]
It's not really going to be inline like you want however. It's planned but no eta. If that's a deal breaker, there are other Godot plugins for dialog that may help today tho

**Comment by Yotopihi-Dev** [comment]
I’d recommend trying the **Dialogue Manager** Plug-in. It automatically has the choice buttons on the bottom. Although, you have to type your timelines rather than drag events to make a timeline

https://github.com/nathanhoad/godot_dialogue_manager

**Comment by M7mdKady14** [comment]
> I’d recommend trying the Dialogue Manager

yeah thanks, it does what I want in my project.
dialogic is still cool though, loved it!
